// Bible quiz question bank — 329 questions, English source.
//
// Authored as a TS const, not JSON: tsconfig extends expo/tsconfig.base with no
// `resolveJsonModule`, and every JSON require in this repo is a Lottie file.
//
// ⚠️ NOT uniformly 4-option. 269 questions have 4 options; 60 are True/False and
// have exactly 2. Renderers must map over `options`, never assume a length.
//
// `answerIndex` is the ONLY source of truth for correctness. The upstream export
// also carried an `answer` string; it is dropped here because a second
// representation of the same fact is a second thing that can disagree.
//
// ⚠️ BUMP QUIZ_BANK_VERSION on ANY edit to this array (add / remove / reorder /
// reword). An in-flight session stores question ids; a silent bank change would
// have it grading answers against questions the user never saw.

export interface QuizQuestion {
  /** Stable id from the source export. Never reuse or renumber. */
  id: number;
  question: string;
  /** 2 or 4 entries. Order is meaningful — answerIndex points into it. */
  options: readonly string[];
  answerIndex: number;
}

export const QUIZ_BANK_VERSION = 1;

export const QUIZ_BANK: readonly QuizQuestion[] = [
  { id: 1, question: 'Which of these is NOT a son of Adam and Eve?', options: ['Enoch', 'Cain', 'Abel', 'Seth'], answerIndex: 0 },
  { id: 2, question: 'Noah sent these two birds out of the ark to search for land:', options: ['raven and hawk', 'hawk and jay', 'raven and dove', 'dove and hawk'], answerIndex: 2 },
  { id: 3, question: 'Jacob had 12 sons.  Which of his wives/maids bore the most babies?', options: ['Zilpah', 'Leah', 'Rachel', 'Bilhah'], answerIndex: 1 },
  { id: 4, question: 'Which of these animals did the Israelites worship while Moses was on the mountain?', options: ['bull', 'calf', 'duck', 'ram'], answerIndex: 1 },
  { id: 5, question: 'Many of King Solomons wise sayings are recorded in Book 10 of Proverbs.  Which of these is NOT found there?', options: ['When you see trouble coming, dont be stupid and walk right into it--be smart and hide.', 'Good people are remembered long after they are gone, but the wicked are soon forgotten.', 'Children with good sense make their parents happy, but foolish children make them sad.', 'You will say the wrong thing if you talk too much--so be sensible and watch what you say.'], answerIndex: 0 },
  { id: 6, question: 'Mary was visited by this angel.', options: ['Uriel', 'Raphael', 'Gabriel', 'Michael'], answerIndex: 2 },
  { id: 7, question: 'Jesus was fond of using parables to give his messages.  Which of these was NOT one he used?', options: ['The Parable of the Mustard Seed', 'The Parable of the Old Men and the Young', 'The Parable of the Prodigal Son', 'The Parable of the Ten Servants'], answerIndex: 1 },
  { id: 8, question: 'Complete the following quote from Matthew 5:3: Blessed are the poor in spirit, for ________', options: ['they shall be comforted.', 'shall be called children of God.', 'they shall see Heaven.', 'theirs is the Kindgom of Heaven.'], answerIndex: 3 },
  { id: 9, question: 'Who wrote the first five books of the Bible?', options: ['Adam', 'Joseph', 'Moses', 'Abraham'], answerIndex: 2 },
  { id: 10, question: 'In the Bible, how many wives and concubines did Solomon have?', options: ['2000', '500', '1000', '100'], answerIndex: 2 },
  { id: 11, question: 'Who wrote most of the books in the New Testament?', options: ['David', 'John', 'Peter', 'Paul'], answerIndex: 3 },
  { id: 12, question: 'Who wrote the Book of Revelation while in exile?', options: ['Paul', 'Peter', 'James', 'John'], answerIndex: 3 },
  { id: 13, question: 'According to the accepted theory, how old was Jesus when He was crucified?', options: ['33', '27', '40', '30'], answerIndex: 0 },
  { id: 14, question: 'How old was Jesus when He performed His first miracle (Biblical, not Apocriphal)?', options: ['40', '33', '27', '30'], answerIndex: 3 },
  { id: 15, question: 'David, the famous ancient King of Israel, was the oldest child in the family.', options: ['True', 'False'], answerIndex: 1 },
  { id: 16, question: 'It is stated in the Bible that God told Moses to build the Temple in Jerusalem.', options: ['True', 'False'], answerIndex: 1 },
  { id: 17, question: 'According to the New Testament, who obtained permission to take Jesus Christs body down from the cross and place it in the tomb?', options: ['Joseph of Arimathea', 'Joseph of Antioch', 'Mary Magdalene', 'Apostle Peter'], answerIndex: 0 },
  { id: 18, question: 'Apostle Paul was a kind, friendly and peace-loving man who always helped Christians even before his conversion to Christianity.', options: ['False', 'True'], answerIndex: 0 },
  { id: 19, question: 'Seven people went on the ark with Noah according to the Bible, Genesis, chapters 6 to 9.', options: ['True', 'False'], answerIndex: 0 },
  { id: 20, question: 'What was the profession of Luke the Apostle according to the New Testament?', options: ['Tax collector', 'Carpenter', 'Physician', 'Boat builder'], answerIndex: 2 },
  { id: 21, question: 'Who committed the first murder in the Bible?', options: ['Cain', 'Solomon', 'Adam', 'Abel'], answerIndex: 0 },
  { id: 22, question: 'Who was Gods son according to the Bible?', options: ['John', 'Peter', 'Solomon', 'Jesus'], answerIndex: 3 },
  { id: 23, question: 'What is the name of the angel that God sent to tell Mary she was to conceive Jesus?', options: ['Abraham', 'Gabriel', 'Michael', 'Peter'], answerIndex: 1 },
  { id: 24, question: 'Who was Jesus earthly father according to the Bible?', options: ['Solomon', 'Joseph', 'no one', 'David'], answerIndex: 1 },
  { id: 25, question: 'According to Matthew and Luke, in what city was Jesus born?', options: ['Jerusalem', 'Bethlehem', 'Babylon', 'Nazareth'], answerIndex: 1 },
  { id: 26, question: 'Jesus Christ is considered to be an exorcist. One of the legends tells of Jesus casting out multiple demons from a madman. The spirits then entered the bodies of some animals. What kind of animals were they?', options: ['Vultures', 'Pigs', 'Crows', 'Cows'], answerIndex: 1 },
  { id: 27, question: 'Jesus Christ gave the power to exorcise demons to his disciples.', options: ['True', 'False'], answerIndex: 0 },
  { id: 28, question: 'Adam was the first human made by God according to the Bible texts.', options: ['True', 'False'], answerIndex: 0 },
  { id: 29, question: 'The Ten Commandments can be found in the book of Exodus, New Testament.', options: ['True', 'False'], answerIndex: 1 },
  { id: 30, question: 'According to the Bible, Gods laws were given to Moses on Mount Rushmore.', options: ['True', 'False'], answerIndex: 1 },
  { id: 31, question: 'Moses talked to God on the mountain and received the Ten Commandments in 40 days.', options: ['False', 'True'], answerIndex: 1 },
  { id: 32, question: 'Moses broke the tablets on which the Ten Commandments were written when he slipped on the rocky mountainside.', options: ['True', 'False'], answerIndex: 1 },
  { id: 33, question: 'According to the Bible texts, Jesus earthly father Joseph was sheep herder.', options: ['False', 'True'], answerIndex: 0 },
  { id: 34, question: 'In the Bible texts, “Am I my brother’s keeper?” was a question asked by Cain to God.', options: ['True', 'False'], answerIndex: 0 },
  { id: 35, question: 'This line from the Bible is from an address by God to Noah: “And the bow shall be in the cloud and I will look upon it that I may remember the everlasting covenant between God and every living creature of all flesh that is upon the earth.”', options: ['False', 'True'], answerIndex: 1 },
  { id: 36, question: 'According to the Bible, Judas Iscariot was paid 30 pieces of gold to betray Jesus.', options: ['True', 'False'], answerIndex: 1 },
  { id: 37, question: 'In Genesis, we can read that Joseph was sold into slavery by his brothers.', options: ['False', 'True'], answerIndex: 1 },
  { id: 38, question: 'This is one of the most widely used religious symbols. It is generally used for protection. Even though it is often associated with witchcraft, it was also used in Christianity, symbolizing the five wounds of Christ.', options: ['Hazel', 'Sword', 'Pentagram', 'Chalice'], answerIndex: 2 },
  { id: 39, question: 'This part of the Catholic mass, in which the priest asks God to change the bread and wine into Jesus body and blood, is called what?', options: ['invocation', 'consecration', 'offertory', 'communion'], answerIndex: 1 },
  { id: 40, question: 'The Hail Mary is a biblical prayer.', options: ['True', 'False'], answerIndex: 0 },
  { id: 41, question: 'What is the Catholic term for a person who, after death, goes to heaven?', options: ['saint', 'cherub', 'seraph', 'angel'], answerIndex: 0 },
  { id: 42, question: 'What does the Catholic church teach about Mary, Jesus mother?', options: ['She was a virgin when Jesus was born, but not necessarily after.', 'Joseph divorced her quietly after Jesus was born.', 'She was a virgin when Jesus was conceived, but not necessarily after.', 'She was a virgin until her death.'], answerIndex: 3 },
  { id: 43, question: 'According to the Bible, Sarah and Abraham have a common relative by blood.', options: ['False', 'True'], answerIndex: 1 },
  { id: 44, question: 'Who begged for the body of Jesus to give it a proper burial?', options: ['Joseph of Arimathaea', 'Peter', 'Mark', 'Matthew'], answerIndex: 0 },
  { id: 45, question: 'What scripture of the King James Bible is most noted for the story of the birth of Jesus?', options: ['Luke, Chapter 1', 'Luke, Chapter 3', 'Luke, Chapter 2', 'Matthew, Chapter 2'], answerIndex: 2 },
  { id: 46, question: 'According to the biblical texts, whom do these words belong to: Thou shalt have no other gods before me!?', options: ['Moses', 'Aaron', 'Miriam', 'God'], answerIndex: 3 },
  { id: 47, question: 'According to the Bible, Ruth was the great grandmother of David.', options: ['False', 'True'], answerIndex: 1 },
  { id: 48, question: 'Who wrote Epistle to the Romans, included in the New Testament canon of the Christian Bible?', options: ['Peter', 'Paul', 'Mark', 'Luke'], answerIndex: 1 },
  { id: 49, question: 'According to the Bibles interpretation of Moses life, who ran along the bank to make sure that Moses was alright in his basket after he was set adrift on the Nile river?', options: ['His brother', 'His mother', 'His sister', 'His father'], answerIndex: 2 },
  { id: 50, question: 'According to the Bible, did the Pharaoh’s wife find little Moses who was drifting along the Nile in a basket.', options: ['No', 'Yes'], answerIndex: 0 },
  { id: 51, question: 'What does the name Moses mean according to the Biblical texts?', options: ['Found', 'Child of the river', 'Conceived by a Hebrew', 'Drawn out'], answerIndex: 3 },
  { id: 52, question: 'What was the name of Mosess brother according to the Bible?', options: ['Clive', 'Aaron', 'Peter', 'John'], answerIndex: 1 },
  { id: 53, question: 'According to Exodus, what was the ninth plague that God inflicted on Egypt in order to convince Pharaoh to let the Israelite slaves leave?', options: ['Death of First Born Child', 'Lice', 'Darkness', 'Frogs'], answerIndex: 2 },
  { id: 54, question: 'Why did Moses have to flee out of Egypt and settle on the Sinai Peninsula according to the Bible?', options: ['He killed an Egyptian', 'He was banned for disrespectable behaviour towards the Pharaoh.', 'None of these', 'He killed the Pharaoh'], answerIndex: 0 },
  { id: 55, question: 'According to the last chapters of Exodus, what was the Tabernacle, which was built after the Israelites passed safely the Red Sea with Gods help?', options: ['A vehicle with a prayer altar', 'A portable prayer altar', 'A portable place of worship', 'A portable irrigating system'], answerIndex: 2 },
  { id: 56, question: 'Who is the second oldest living man according to the Bible?', options: ['Enoch', 'Mahalalel', 'Jared', 'Methuselah'], answerIndex: 2 },
  { id: 57, question: 'What is the name of the only Archangel mentioned in the Bible?', options: ['Lucifer', 'Jesus', 'Michael', 'Gabriel'], answerIndex: 2 },
  { id: 58, question: 'Who was emperor of Rome at the time of Jesus death?', options: ['Augustus', 'Tiberius', 'Caligula', 'Claudius'], answerIndex: 1 },
  { id: 59, question: 'King Solomon had 300 wives and 700 concubines.', options: ['False', 'True'], answerIndex: 0 },
  { id: 60, question: 'At Passover, Jews eat a special meal done in a special order.  What is that meal called?', options: ['A festavus for the rest of us', 'A seder', 'A Shidduch', 'A circumcision'], answerIndex: 1 },
  { id: 61, question: 'We consider there to be three Patriarchs in Judaism. Who were they?', options: ['Moses, David, Abraham', 'Abraham, David, Moses', 'Abraham, Issac, Jacob', 'David, Joshua, Solomon'], answerIndex: 2 },
  { id: 62, question: 'In Judaism, who was Joshuas father?', options: ['Abraham', 'Solomon', 'Nun', 'Moses'], answerIndex: 2 },
  { id: 63, question: 'Who was the Baal Shem Tov ?', options: ['The founder of the Bnai Brith', 'The first Premier of  Israel', 'The founder of Chassidism', 'The first President of Israel'], answerIndex: 2 },
  { id: 64, question: 'According to the second half of the Acts of the Apostles, what was Pauls name before God changed it?', options: ['Peter', 'Luke', 'Saul', 'John'], answerIndex: 2 },
  { id: 65, question: 'The second chapter of the Gospel of Luke, Luke 2, tells us the story of Christs birth.', options: ['True', 'False'], answerIndex: 0 },
  { id: 66, question: 'In the Old Testament, a man is said to have lived to be 969 years old.', options: ['False', 'True'], answerIndex: 1 },
  { id: 67, question: 'There is a man in the Bible named Rehoboam who had 88 children.', options: ['False', 'True'], answerIndex: 1 },
  { id: 68, question: 'There was an army mentioned in the Old Testament that consisted of men who were all left-handed and numbered 700.', options: ['False', 'True'], answerIndex: 1 },
  { id: 69, question: 'Does the Bible ever speak of the sun moving backwards?', options: ['No', 'Yes'], answerIndex: 1 },
  { id: 70, question: 'Which line gives the correct order of the first 5 books of the Old Testament?', options: ['Genesis, Leviticus, Numbers, Deuteronomy, Exodus', 'Genesis, Exodus, Numbers, Deuteronomy, Leviticus', 'Genesis, Exodus, Leviticus, Deuteronomy, Numbers', 'Genesis, Exodus, Leviticus, Numbers, Deuteronomy'], answerIndex: 3 },
  { id: 71, question: 'What tribe of Israel was Moses born into?', options: ['Reubon', 'Benjamin', 'Jacob', 'Levite'], answerIndex: 3 },
  { id: 72, question: 'On which Holy Day do Jews feast on unleavened bread?', options: ['Rosh Hashannah', 'Channukah', 'Passover', 'Yom Kippur'], answerIndex: 2 },
  { id: 73, question: 'In what business did John M. Brunswick and his two half brothers, David and Emmanuel, make their fortune?', options: ['Entertaining industry', 'Aircraft industry', 'Billiard table business', 'Cell phone business'], answerIndex: 2 },
  { id: 74, question: 'Why was Rabbi David Einhorn, a German rabbi and later leader of the Jewish reform movement in the United States, forced to leave Baltimore in 1861, during the Civil War?', options: ['He expressed too radical views', 'He insulted the Governor of Maryland,Thomas Hicks', 'He insulted the Mayor of Baltimore, George Williams', 'He preached against slavery'], answerIndex: 3 },
  { id: 75, question: 'A famous and talented composer was almost bankrupt when he wrote one of his best-known works, Judas Maccabaeus - an oratorio based on a Jewish theme. Who was this classical composer?', options: ['Hayden', 'Handel', 'Chopin', 'Mozart'], answerIndex: 1 },
  { id: 76, question: 'Who is known as the patron of India?', options: ['Francis Xavier', 'John the Divine', 'Giles', 'Catherine'], answerIndex: 0 },
  { id: 77, question: 'Which saint is referred to as the patron of fishermen?', options: ['Andrew the Apostle', 'Raphael the Archangel', 'Jerome', 'Sebastian'], answerIndex: 0 },
  { id: 78, question: 'To which saint does one pray for healthy eyes?', options: ['St. Mary of Naples', 'St. Lucy, Virgin', 'St. Frances of the Holy Redeemer', 'St. Anne'], answerIndex: 1 },
  { id: 79, question: 'According to the Book of Esther, Esther replaced this disobedient Biblical queen.', options: ['Queen Ruth', 'Queen Vashti', 'Queen Mary', 'Queen of Sheba'], answerIndex: 1 },
  { id: 80, question: 'This brave Biblical woman led the Israelites to victory in the battle against Sisera.', options: ['Rebecah', 'Leah', 'Sarah', 'Deborah'], answerIndex: 3 },
  { id: 81, question: 'According to the Bible, King David saw this beautiful woman bathing, and immediately desired her, but she was married.', options: ['Ahinoam', 'Abigail', 'Michal', 'Bathsheba'], answerIndex: 3 },
  { id: 82, question: 'According to the New Testament, this woman had a son called John the Baptist.', options: ['Martha', 'Elizabeth', 'Maacah', 'Mary'], answerIndex: 1 },
  { id: 83, question: 'According to the Book of Exodus, this brave mother hid her young baby son, Moses, in a basket along the Nile River, so that no one could kill him.', options: ['Jochebed', 'Miriam', 'Martha', 'Zipporah'], answerIndex: 0 },
  { id: 84, question: 'This biblical heroine hid two Israelite spies in her house under stalks of flax.', options: ['Leah', 'Rehab', 'Naomi', 'Rachel'], answerIndex: 1 },
  { id: 85, question: 'In the Bible, this woman gave birth to male twins and as she was in labor the twins jostled each other, one babys hand grasping the heel of the other infants foot.', options: ['Rachel', 'Rebekah', 'Leah', 'Hagar'], answerIndex: 1 },
  { id: 86, question: 'This Biblical woman poured perfume on Jesus feet and wiped them with her hair.', options: ['Mary', 'Keturah', 'Samaritan woman', 'Sarah'], answerIndex: 0 },
  { id: 87, question: 'According to the Bible, this woman became a widow and decided to live with her mother-in-law instead of going home to her family. She then married Boaz.', options: ['Ruth', 'Naomi', 'Oprah', 'Esther'], answerIndex: 0 },
  { id: 88, question: 'The Temple of Vespasian was begun by Titus after whose death?', options: ['his brother-in-law, Jesus', 'his father, Vespasian', 'his brother, Domitian', 'his best friend, Tiberius'], answerIndex: 1 },
  { id: 89, question: 'When Michelangelo was still an apprentice, he made an imitation of a famous Roman statue that was sold in Rome as an ancient Roman original. What was the name of the original statue?', options: ['Cherubini', 'Bacchus', 'Il Putto Dormiente', 'Moses'], answerIndex: 2 },
  { id: 90, question: 'On front of the home of every Jew, there is a special decoration or religious symbol. It is also found inside the home at very doorpost and every gate. In each one, there are three sections of the (Old) Testament.  What do we call these religious objects?', options: ['Moshiach', 'Mohels', 'Mezzuzas', 'Torahs'], answerIndex: 2 },
  { id: 91, question: 'On Columbus first trip to the new world, many Jews were employed by Columbus. What was the highest job held by a Jew?', options: ['Weatherman', 'Translator', 'Treasurer', 'Supply commander'], answerIndex: 1 },
  { id: 92, question: 'What religious article must every unmarried Jewish woman wear?', options: ['Red String', 'Star of David', 'None', 'Fringes'], answerIndex: 2 },
  { id: 93, question: 'According to the Bible, God forbade Adam and Eve to eat the fruit of the apple tree.', options: ['False', 'True'], answerIndex: 0 },
  { id: 94, question: 'Who is the first human who murdered a human according to the Bible?', options: ['Eve', 'Cain', 'Adam', 'Abel'], answerIndex: 1 },
  { id: 95, question: 'According to the Book of Revelation, there are angels of the Devil.', options: ['True', 'False'], answerIndex: 0 },
  { id: 96, question: 'It is written in the Bible, that false Christs and prophets will arise and will show great signs and wonders.', options: ['False', 'True'], answerIndex: 1 },
  { id: 97, question: 'According to Christian theology, Jesus Christ is a person with an entirely human nature.', options: ['False', 'True'], answerIndex: 0 },
  { id: 98, question: 'What Biblical figure built an ark on top of a mountain?', options: ['Moses', 'Jacob', 'Noah', 'Joseph'], answerIndex: 2 },
  { id: 99, question: 'What Biblical hero split the sea so that he and his people could go across?', options: ['Noah', 'Joseph', 'Jacob', 'Moses'], answerIndex: 3 },
  { id: 100, question: 'What does the name Moses mean according to the Bible?', options: ['Prince of Egypt', 'taken from the water', 'beautiful', 'sour'], answerIndex: 1 },
  { id: 101, question: 'How many books are there in the Bible?', options: ['64', '65', '59', '66'], answerIndex: 3 },
  { id: 102, question: 'It is considered that the Jewish Golden Age occurred in this country.', options: ['Spain', 'France', 'Israel', 'India'], answerIndex: 0 },
  { id: 103, question: 'Judaism divides The Old Testament into three parts, called this in English.', options: ['Torah, Pentatuch, Prophets', 'Torah, Histories, Pentatuch', 'Torah, Prophets, Wisdom Literature', 'Torah, Chronicles, Major Prophets'], answerIndex: 2 },
  { id: 104, question: 'In what book of The New Testament was John the Baptist beheaded?', options: ['John', 'Luke', 'Mark', 'Matthew'], answerIndex: 3 },
  { id: 105, question: 'In The New Testament, Romans was written by the apostle Paul.', options: ['True', 'False'], answerIndex: 0 },
  { id: 106, question: 'How many books are in the New Testament?', options: ['25', '27', '20', '31'], answerIndex: 1 },
  { id: 107, question: 'It is believed by many that the Gospel of Luke is the most beautiful book ever written.', options: ['False', 'True'], answerIndex: 1 },
  { id: 108, question: 'Which of the laws in  the Ten Commandments of the New Testament is conceived to be the greatest one?', options: ['Honor your father and your mother', 'You shall not steal', 'Love the Lord with all your heart, soul and mind', 'Love your neighbor as yourself'], answerIndex: 2 },
  { id: 109, question: 'In the New Testament, Acts is the next book after Romans.', options: ['False', 'True'], answerIndex: 0 },
  { id: 110, question: 'What is the third book of the New Testament?', options: ['Mark', 'Matthew', 'Jonh', 'Luke'], answerIndex: 3 },
  { id: 111, question: 'What did Jesus do to the man with leprosy, according to The New Testament?', options: ['ignored him', 'gave him medicine', 'prayed for him', 'touched him and cured him'], answerIndex: 3 },
  { id: 112, question: 'Paul is acknowledged as the author of  First Epistle to the Corinthians book in The New Testament.', options: ['True', 'False'], answerIndex: 0 },
  { id: 113, question: 'In which book of The New Testament is the following passage found Ask and it will be given to you;seek and you will find;knock and the door will be opened to you?', options: ['Psalms', 'Matthew', 'Acts', 'Luke'], answerIndex: 1 },
  { id: 114, question: 'What was the name of Abrahams wife according to the book of Genesis?', options: ['Rebekah', 'Rachel', 'Leah', 'Sarah'], answerIndex: 3 },
  { id: 115, question: 'In the book of Genesis, how old was Abraham when Isaac was born?', options: ['101 years old', '95 years old', '100 years old', '99 years old'], answerIndex: 2 },
  { id: 116, question: 'Isaac was Abrahams first son according to the Torah.', options: ['False', 'True'], answerIndex: 0 },
  { id: 117, question: 'What was the name of Isaacs wife according to the book of Genesis?', options: ['Leah', 'Rachel', 'Sarah', 'Rebekah'], answerIndex: 3 },
  { id: 118, question: 'The book of Genesis tells that when Esau and Jacob were born, Jacob grabbed hold of what?', options: ['Esaus hand', 'Esaus hair', 'Esaus heel', 'Esaus food'], answerIndex: 2 },
  { id: 119, question: 'According to the Torah, what did Esau trade his birthright with Jacob for?', options: ['Bread and wild game', 'Bread and vegetables', 'Bread and lentil stew', 'Manna'], answerIndex: 2 },
  { id: 120, question: 'Who was Jacobs first wife in the book of Genesis?', options: ['Leah', 'Sarah', 'Rebekah', 'Rachel'], answerIndex: 0 },
  { id: 121, question: 'How many years did Jacob have to work for each of his wives according to the Torah?', options: ['3 years each', '7 years each', '1 year each', '14 years each'], answerIndex: 1 },
  { id: 122, question: 'This actor, who made it big as a high school gang member, delivering paint and flying airplanes, is one of the most famous Scientologists.', options: ['Hayward Nelson', 'John Travolta', 'Christian Slater', 'Brad Pitt'], answerIndex: 1 },
  { id: 123, question: 'Which Scientologist played the wife of “The King of Queens?', options: ['Juliette Lewis', 'Mimi Rogers', 'Ann Archer', 'Leah Remini'], answerIndex: 3 },
  { id: 124, question: 'What Scientologist started the EST movement?', options: ['David Miscavige', 'Werner Erhard', 'Greta  Van Susteren', 'Sonny Bono'], answerIndex: 1 },
  { id: 125, question: 'The title of what book in the Bible means departure?', options: ['Lamentations', 'Exodus', 'Genesis', 'Deuteronomy'], answerIndex: 1 },
  { id: 126, question: 'Deuteronomy, the title of the fifth book of the Hebrew Bible, means second law.', options: ['True', 'False'], answerIndex: 0 },
  { id: 127, question: 'What is the meaning of the book title Genesis?', options: ['God', 'man', 'beginning', 'creation'], answerIndex: 2 },
  { id: 128, question: 'Does The Book of Numbers from the Old Testament begin with the numbering of the people in Sinai?', options: ['No', 'Yes'], answerIndex: 1 },
  { id: 129, question: 'What book in the Bible was named after the successor of Moses?', options: ['Isaiah', 'Ezekiel', 'Joshua', 'Jeremiah'], answerIndex: 2 },
  { id: 130, question: 'Where can you find the story of Adam and Eve?', options: ['Book of Jeremiah', 'Book of Genesis', 'Book of Lamentations', 'Book of Exodus'], answerIndex: 1 },
  { id: 131, question: 'The story of Moses birth can be found in the Book of Deuteronomy.', options: ['True', 'False'], answerIndex: 1 },
  { id: 132, question: 'Was Moses still alive in the Book of Numbers?', options: ['Yes', 'No'], answerIndex: 0 },
  { id: 133, question: 'What was the age of Joshua (Moses successor) when he died?', options: ['120 years old', '105 years old', '110 years old', '115 years old'], answerIndex: 2 },
  { id: 134, question: 'What is the name of the collection of stories, legends, and allegorical interpretations of the Hebrew Bible Tanach?', options: ['Gemara', 'Midrash', 'Kislev', 'Mishnah'], answerIndex: 1 },
  { id: 135, question: 'When did the Six Day War between Israel and the Arab states of Egypt, Jordan, and Syria begin?', options: ['June 5, 1971', 'June 5, 1967', 'June 5, 1963', 'June 5, 1969'], answerIndex: 1 },
  { id: 136, question: 'In 1825, Jewish American diplomat and journalist Mordecai Manuel Noah tried to found what Jewish institution in the United States?', options: ['A Jewish rebellion organization in the United States', 'A Jewish homeland in the United States', 'A Jewish government in the United States', 'A Jewish independent church in the United States'], answerIndex: 1 },
  { id: 137, question: 'Which of these terms is used by Jews to refer to the Old Testament?', options: ['Torah', 'Tehillim', 'Tanakh', 'Schmuel'], answerIndex: 2 },
  { id: 138, question: 'This is the holiest city in Judaism and the spiritual center of the Jewish people. It also plays an important role in Christianity and Islam.', options: ['Constantinople', 'Jerusalem', 'Medina', 'Mecca'], answerIndex: 1 },
  { id: 139, question: 'The Temple Mount, the Church of Holy Sepulchre and the Western Wall are landmarks found in this city.', options: ['Baghdad', 'Ohrid', 'Jerusalem', 'Constantinople'], answerIndex: 2 },
  { id: 140, question: 'Who built the Temple of Jerusalem also known as the Holy Temple?', options: ['Constantine I Emperor', 'King Ferdinand', 'Justinian Emperor', 'King Solomon'], answerIndex: 3 },
  { id: 141, question: 'When was Jerusalem conquered by the Islamic Caliphate?', options: ['In 1500', 'In 340', 'In 1040', 'In 638'], answerIndex: 3 },
  { id: 142, question: 'After the Arabic-Israeli War (1948-1949) Jerusalem was divided between Israel (West part) and Jordan (East part).', options: ['False', 'True'], answerIndex: 1 },
  { id: 143, question: 'What is Jesus birthplace according to the Bible?', options: ['Bethlehem', 'Jerusalem', 'Constantinople', 'Nazareth'], answerIndex: 0 },
  { id: 144, question: 'Where is The Milk Grotto Church of Virgin Mary located?', options: ['Bethlehem', 'Jerusalem', 'Nazareth', 'Baghdad'], answerIndex: 0 },
  { id: 145, question: 'In Bethlehem, Christmas ceremonies are held on three different dates.', options: ['False', 'True'], answerIndex: 1 },
  { id: 146, question: 'According to New Testament, the home of Joseph and Mary was in Jerusalem.', options: ['False', 'True'], answerIndex: 0 },
  { id: 147, question: 'The Church of the Annunciation was built in Nazareth.', options: ['True', 'False'], answerIndex: 0 },
  { id: 148, question: 'According to the Book of Matthew, Jacob was the father of Issac.', options: ['True', 'False'], answerIndex: 1 },
  { id: 149, question: 'Who was king when Jesus was born?', options: ['King Solomon', 'King David', 'King Herod', 'None of these'], answerIndex: 2 },
  { id: 150, question: 'Jesus was baptized by John the Baptist.', options: ['False', 'True'], answerIndex: 1 },
  { id: 151, question: 'In the Book of Matthew, what did Jesus say to the man with leprosy when he touched him?', options: ['Be cured!', 'Be Clean!', 'Be Healed!', 'None of these'], answerIndex: 1 },
  { id: 152, question: 'Whose mother-in-law was lying in bed with a fever in the Book of Matthew?', options: ['Peter', 'James', 'John', 'Mark'], answerIndex: 0 },
  { id: 153, question: 'According to the Book of Matthew, how many disciples did Jesus give authority to heal the sick and drive out evil spirits?', options: ['10', '7', '12', '5'], answerIndex: 2 },
  { id: 154, question: 'Which of the apostles betrayed Jesus?', options: ['Simon the Zealot', 'Philip', 'Matthew', 'Judas Iscariot'], answerIndex: 3 },
  { id: 155, question: 'Where did Ruth live when she met her first husband according to the Book of Ruth?', options: ['Bethlehem', 'Moab', 'Jerusalem', 'Judah'], answerIndex: 1 },
  { id: 156, question: 'In the Book of Ruth, who was Ruths mother-in-law that she would not abandon?', options: ['Naomi', 'Mary', 'Orpah', 'Rahab'], answerIndex: 0 },
  { id: 157, question: 'Who was Ruths sister-in-law according to the Book of Ruth?', options: ['Oprah', 'Rahab', 'Orpah', 'Naomi'], answerIndex: 2 },
  { id: 158, question: 'In the Book of Ruth, after the deaths of Naomis husband and her two sons, Naomi wanted to leave Moab. Where did she go?', options: ['Bethlehem', 'Joppa', 'Jerusalem', 'Ninevah'], answerIndex: 0 },
  { id: 159, question: 'In the Book of Ruth, what did Ruth do to indicate that she wanted to be redeemed?', options: ['Bow down to Boaz', 'Wash Boaz feet.', 'Sing to Boaz', 'Sleep at Boaz feet.'], answerIndex: 3 },
  { id: 160, question: 'In the Book of Ruth, Boaz was the closest relative thats why he came forward as the kinsman-redeemer.', options: ['True', 'False'], answerIndex: 1 },
  { id: 161, question: 'According to the Book of Ruth, what did the kinsman-redeemer give to Boaz to indicate that Boaz would be the redeemer of Ruth?', options: ['A signed piece of paper', '500 shekels', 'His cloak', 'His sandal'], answerIndex: 3 },
  { id: 162, question: 'What was the name of Ruth and Boazs son in the Book of Ruth?', options: ['Jesse', 'David', 'Salmon', 'Obed'], answerIndex: 3 },
  { id: 163, question: 'The Book of Ruth comes after this book.', options: ['Joshua', 'Esther', 'Daniel', 'Judges'], answerIndex: 3 },
  { id: 164, question: 'How many books are there in the Old Testament of the Bible?', options: ['39', '43', '20', '35'], answerIndex: 0 },
  { id: 165, question: 'Finish the title of this book of the Old Testament: The Song of _____', options: ['Solomon', 'Job', 'Ruth', 'Joel'], answerIndex: 0 },
  { id: 166, question: 'Which book of the Old Testament of the Bible has the least number of chapters?', options: ['Obadiah', 'Haggai', 'Zephaniah', 'Habakkuk'], answerIndex: 0 },
  { id: 167, question: 'Which book of the Old Testament has the most chapters?', options: ['Psalms', 'Genesis', 'Isaiah', 'Jeremiah'], answerIndex: 0 },
  { id: 168, question: 'The first two books in the Old Testament are Genesis and Exodus. What is the name of the third book?', options: ['Deuteronomy', 'Numbers', 'Joshua', 'Leviticus'], answerIndex: 3 },
  { id: 169, question: 'What is the title of the last book of the Old Testament?', options: ['Job', 'Malachi', 'Zechariah', 'Haggai'], answerIndex: 1 },
  { id: 170, question: 'Which of these books doesnt belong with the others?', options: ['Ezekiel', 'Lamentations', 'Jude', 'Genesis'], answerIndex: 2 },
  { id: 171, question: 'Amos is the first book of the Old Testament alphabetically.', options: ['True', 'False'], answerIndex: 0 },
  { id: 172, question: 'Which of these books of the Old Testament is not divided into parts I and II?', options: ['Kings', 'Numbers', 'Samuel', 'Chronicles'], answerIndex: 1 },
  { id: 173, question: 'There are 32 chapters in the Book of Proverbs.', options: ['True', 'False'], answerIndex: 1 },
  { id: 174, question: 'Who was the first US President whose name appeared on the charter of a synagogue?', options: ['Millard Fillmore', 'George Washington', 'Franklin Pierce', 'John F. Kennedy'], answerIndex: 2 },
  { id: 175, question: 'Who was the  first Jew to serve as a  diplomat for the USA?', options: ['Harvey Lembeck', 'Mordechai Noah', 'Judah Benjamin', 'Noah Hershey'], answerIndex: 1 },
  { id: 176, question: 'Who was the  first Jew to serve as US Minister to The Hague?', options: ['Judah Benjamin', 'August Belmont', 'John Hays', 'Henry Androwsky'], answerIndex: 1 },
  { id: 177, question: 'How many years did Golda Meir serve as President of Israel?', options: ['0', '3', '4', '6'], answerIndex: 0 },
  { id: 178, question: 'Who was the first President of Israel?', options: ['David ben -Gurion', 'Chaim Weizmann', 'Golda Meir', 'Mosahe Dayan'], answerIndex: 1 },
  { id: 179, question: 'Who was famous for saying We will fight the War [WWII] as if there were no White Paper and the White paper as if there were no war.?', options: ['Menachem Begin', 'Moshe Dayan', 'Golda Meir', 'David Ben-Gurion'], answerIndex: 3 },
  { id: 180, question: 'This great American Army officer helped form the Israeli Army. He was responsible for organizing the army along modern lines and for leading the effort  to save Jerusalem in the 1948 war.', options: ['Moshe Dayan', 'Modechai Manual', 'Eddie Jacobson', 'Mickey Marcus'], answerIndex: 3 },
  { id: 181, question: 'What king of Babylon took over Jerusalem in the first chapter of the Book of Daniel?', options: ['Nebuchadnezzar', 'Jehoiakim', 'Darius', 'Belshazzar'], answerIndex: 0 },
  { id: 182, question: 'According to the Book of Daniel, upon his arrival in Babylon, what was Daniels name changed to?', options: ['Meshach', 'Belshazzar', 'Belteshazzar', 'Shadrach'], answerIndex: 2 },
  { id: 183, question: 'What were the Hebrew names of Shadrach, Meshach and Abednego according to the Book of Daniel?', options: ['Hananiah, Michael and Amos', 'Hananiah, Mark and Amos', 'Hananiah, Michael and Abraham', 'Hananiah, Mishael and Azariah'], answerIndex: 3 },
  { id: 184, question: 'In the second chapter of the Book of Daniel, what did King Nebuchadnezzar have a dream about?', options: ['A tree', 'A goat', 'A temple', 'A statue'], answerIndex: 3 },
  { id: 185, question: 'In King Nebuchadnezzars dream from the second chapter of the Book of Daniel, what kingdom does the head of gold represent?', options: ['Roman Empire', 'Babylonian Empire', 'Medo-Persia Empire', 'Greek Empire'], answerIndex: 1 },
  { id: 186, question: 'What kingdom do the legs of iron represent in King Nebuchadnezzars dream in the second chapter of the Book of Daniel?', options: ['Roman Empire', 'Medo-Persian Empire', 'Greek Empire', 'Babylonian Empire'], answerIndex: 0 },
  { id: 187, question: 'In the Book of Daniel, in King Nebuchadnezzars dream, the Greek Empire was represented by the chest and arms of silver.', options: ['True', 'False'], answerIndex: 1 },
  { id: 188, question: 'In the Book of Daniel, what would Shadrach, Meshach and Abednego not bow down to?', options: ['An image of gold', 'An image of silver', 'King Nebuchadnezzar', 'King Xerxes'], answerIndex: 0 },
  { id: 189, question: 'Since they did not bow down, as King Nebuchadnezzar commanded, what happened to Shadrach, Meshach and Abednego in the Book of Daniel?', options: ['They were sent to the gallows.', 'They were thrown into a den of lions.', 'They were thrown into a fiery furnace.', 'They were stoned with rocks.'], answerIndex: 2 },
  { id: 190, question: 'Who was king of Babylon when Darius the Mede took over?', options: ['Nebuchadnezzar', 'Belshazzar', 'Belteshazzar', 'Xerxes'], answerIndex: 1 },
  { id: 191, question: 'In the Book of Daniel, what did King Darius decree would happen if anyone prayed to any god or person, except for him for a period of 30 days?', options: ['They would be beheaded.', 'They would be thrown into the lions den.', 'They would be stoned.', 'They would be thrown into a fiery furnace.'], answerIndex: 1 },
  { id: 192, question: 'Who led the Jewish revolt against the Roman Empire in the period from 132 to 135?', options: ['The Savoraim', 'Judas Maccabee and his family', 'Bar Kochba and Rabbi Akiva', 'Eliezer Ben Ephraim'], answerIndex: 2 },
  { id: 193, question: 'What does the number 613 refer to in Judaism?', options: ['The number of Israelites who went into Egypt to survive while famine plagued the Holy  Land', 'The number of commandments in the Torah', 'The number of Israelites who left Egypt with Moses', 'The days in a Jewish lunar year'], answerIndex: 1 },
  { id: 194, question: 'What distinction does Moses Alexander hold?', options: ['He was the first Jewish governor in the USA.', 'He was the first Jew to get an M.D. degree in the USA.', 'He was the first Jewish candidate for the American Presidency.', 'He was the first Jewish US Senator.'], answerIndex: 0 },
  { id: 195, question: 'What is Victor David Brenner remembered for?', options: ['He was the first Jewish mayor in the USA.', 'He painted the painting Washington Crossing the Delaware.', 'He was the first Jewish general in the US Army.', 'He made the portrait of Lincoln found on the US penny.'], answerIndex: 3 },
  { id: 196, question: 'Which settlement is famous as the location of one of the most spectacular craters in Israel?', options: ['Kfar Yaackov', 'Mitzpeh Ramon', 'Kiryat Shemona', 'Acre'], answerIndex: 1 },
  { id: 197, question: 'Which Israeli city is a sister city of New York City?', options: ['Haifa', 'Netanya', 'Tel Aviv', 'Jerusalem'], answerIndex: 2 },
  { id: 198, question: 'What is strange about the edible vegetable Salicornia, which Israel exports to Europe?', options: ['It can only be eaten cooked.', 'The plant is 100% edible.', 'It is completely salt-free.', 'The vegetable is also used in glass-making.'], answerIndex: 3 },
  { id: 199, question: 'This Israeli city, which features many beautiful beaches and beautiful seashore views, is also the site of the first IKEA in Israel.', options: ['Jaffa', 'Netanya', 'Hadera', 'Kiryat Shemona'], answerIndex: 1 },
  { id: 200, question: 'This great proponent for peace and understanding, who was Mayor of Jerusalem for 28 years, died in January , 2007.', options: ['Moshe Tellek', 'Teddy  Kollek', 'Ariel Sharon', 'Illiyon Golan'], answerIndex: 1 },
  { id: 201, question: 'Which of these holidays does not have a fast associated with it?', options: ['Sukkot', 'Tisha BAv', 'Purim', 'Passover'], answerIndex: 0 },
  { id: 202, question: 'Who was Ilon Ramon?', options: ['The first Israeli astronaut', 'The first Israeli to win the Nobel Prize in Literature', 'The first Israeli tomplay in the NBA.', 'The first Israeli Ambassador to Egypt since Moses'], answerIndex: 0 },
  { id: 203, question: 'In Jewish traditions, what is the ceremony for the naming of a female baby on the evening of her fifth day?', options: ['Sarahs Ceremony', 'The Confirmation', 'Pinyin Ha-ben', 'The Eve of the Sixth'], answerIndex: 3 },
  { id: 204, question: 'Which line contains the correct names of the three Pilgrimage Festivals in Judaism?', options: ['Passover, Channukah, and Shavuot', 'Rosh Hashannah, Yom Kippur, and Channukah', 'Rosh Hashannah, Yom Kippur, and Sukkot', 'Sukkot, Passover, and Shavuot'], answerIndex: 3 },
  { id: 205, question: 'Which line represents the correct beginning of the Shema prayer?', options: ['Hear, O Israel! Bless the Lord who gave us the Torah!', 'Hear, O Israel! The Lord is our God! The Lord is One!', 'Blessed be the name of the glory of His kingdom!', 'Blessed be the name of the Lord who made our bread!'], answerIndex: 1 },
  { id: 206, question: 'Which of these people do Jews consider to be their historical religious Patriarchs?', options: ['Abraham, Moses, and David', 'Abraham, Issac, and Jacob', 'Abraham, Moses, and Solomon', 'Moses, David, and Solomon'], answerIndex: 1 },
  { id: 207, question: 'According to the Bible, God commanded this prophet to anoint David as king.', options: ['Abiathar', 'Samuel', 'Ahimelech', 'Saul'], answerIndex: 1 },
  { id: 208, question: 'According to the Bible, David played this instrument to Israels first king, Saul.', options: ['Bongos', 'Harp', 'Flute', 'Guitar'], answerIndex: 1 },
  { id: 209, question: 'Who was Davids father according to the Bible?', options: ['Jesse', 'Samuel', 'Solomon', 'Eliab'], answerIndex: 0 },
  { id: 210, question: 'In the Bible, David fought the giant Goliath of Gath with a staff in his hand, a sling, and a shepherds bag which contained this number of stones.', options: ['6', '4', '5', '3'], answerIndex: 2 },
  { id: 211, question: 'According to the Bible, David was very close friends with this son of King Saul.', options: ['Shammah', 'Jonathan', 'Joshua', 'Abner'], answerIndex: 1 },
  { id: 212, question: 'The Biblical king Saul became jealous of David because he was victorious in battle and was loved by all Israel. One day when David was playing the harp for him, Saul did which of the following in an attempt to kill him?', options: ['Hurled a spear', 'Threw a heavy rock', 'Tried to choke him', 'Tried to poison him'], answerIndex: 0 },
  { id: 213, question: 'According to the Bible, David married this daughter of Saul.', options: ['Michal', 'Merab', 'Serah', 'Ruth'], answerIndex: 0 },
  { id: 214, question: 'In the Bible, David once killed a lion and a bear.', options: ['False', 'True'], answerIndex: 1 },
  { id: 215, question: 'What Jewish tribe did David belong to?', options: ['Judah', 'Naphtali', 'Benjamin', 'Simon'], answerIndex: 0 },
  { id: 216, question: 'How many years did David reign as king of Israel?', options: ['25', '45', '35', '40'], answerIndex: 3 },
  { id: 217, question: 'How long has Tel Aviv been the capital of Israel?', options: ['Since 1967', 'Since 1948', 'None of these', 'Since 1984'], answerIndex: 2 },
  { id: 218, question: 'Who named Tel Aviv?', options: ['David Ben Gurion', 'Nahum Sokolow', 'Chaim Nachman Bialik', 'Joshua'], answerIndex: 1 },
  { id: 219, question: 'What was the approximate population of Tel Aviv according to the Israel Central Bureau of Statistics as of June 2006?', options: ['570,600', '475,500', '1,125,000', '380,600'], answerIndex: 3 },
  { id: 220, question: 'What type of stone was used to build the Western or Wailing Wall in Jerusalem?', options: ['Safedstone', 'Gnesis', 'Limestone', 'Granite'], answerIndex: 2 },
  { id: 221, question: 'Who was the first mayor of Tel Aviv?', options: ['Israel Rokach', 'David Bloch', 'Meir Dizengoff', 'Chaim Levanon'], answerIndex: 2 },
  { id: 222, question: 'What term is used to describe a persons return to live in Israel?', options: ['midinayah', 'aliyah', 'shiddoch', 'gaboniah'], answerIndex: 1 },
  { id: 223, question: 'What is the name of the organization that promotes a return to Israel?', options: ['The Gush Etzion', 'The Vaad Harabbonim', 'The Karaite', 'The Jewish Agency'], answerIndex: 3 },
  { id: 224, question: 'Which part of Israel is famous fro producing wine?', options: ['The Negev', 'Lod', 'Golan Heights', 'Eilat'], answerIndex: 2 },
  { id: 225, question: 'Who is given credit  for reviving the Hebrew language?', options: ['Eliezer Ben Yehuda', 'Hannah Senesh', 'Joseph Trumpeldor', 'David Ben Gurion'], answerIndex: 0 },
  { id: 226, question: 'What poem written by Chaim Nachman Bialik inspired many people to immigrate to Israel?', options: ['The New Colossus', 'Rabbi BenEzra', 'Babi Yar', 'The City of the Killings'], answerIndex: 3 },
  { id: 227, question: 'Arthur Loomis Harmon, who helped design the Empire State Building, designed what building in Jerusalem?', options: ['The King David Hotel', 'The Kinnesset', 'The YMCA', 'The Water Clock Tower Hotel'], answerIndex: 2 },
  { id: 228, question: 'Where in Israel was the Mishna written?', options: ['The Galilee', 'Qumran', 'Jerusalem', 'The Negev'], answerIndex: 0 },
  { id: 229, question: 'Who wrote Psalm 23?', options: ['Moses', 'David', 'Solomon', 'Ethan'], answerIndex: 1 },
  { id: 230, question: 'What are Psalms 120 to 134 referred to as?', options: ['Psalms of David', 'Psalms of God', 'Psalms of Ascent', 'Hymns'], answerIndex: 2 },
  { id: 231, question: 'Who was the earliest author of a psalm?', options: ['David', 'Moses', 'Ezra', 'Asaph'], answerIndex: 1 },
  { id: 232, question: 'In Psalm 23, the Lord is referred to as what?', options: ['My Provider', 'My Shepherd', 'My God', 'My Hope'], answerIndex: 1 },
  { id: 233, question: 'The following lines are from which psalm?', options: ['Psalm 23', 'Psalm 139', 'Psalm 150', 'Psalm 119'], answerIndex: 1 },
  { id: 234, question: 'The Book of Psalms is classified as what type of book in the Bible?', options: ['Poetic', 'Historical', 'Apocalyptic', 'Prophetic'], answerIndex: 0 },
  { id: 235, question: 'During her testimony at her trial, Joan of Arc stated she preferred which of the following to the sword?', options: ['Knitting', 'Praying', 'Banner', 'Bible'], answerIndex: 2 },
  { id: 236, question: 'What is the name of the famous sci-fi author that created Scientology?', options: ['Isaac Asimov', 'L. Ron Hubbard', 'Robert A. Heinlein', 'Arthur C. Clarke'], answerIndex: 1 },
  { id: 237, question: 'What is the name of the book, that states points of the scientologic doctrine for the first time?', options: ['The Study of Scientology', 'The Scientology Bible', 'Final Blackout', 'Dianetics: The Modern Science of Mental Health'], answerIndex: 3 },
  { id: 238, question: 'Which of these celebrities is not a scientologist?', options: ['Jack Nicholson', 'John Travolta', 'Juliette Lewis', 'Tom Cruise'], answerIndex: 0 },
  { id: 239, question: 'What is Yom Sheni shel Galuyot?', options: ['The extra day of observance of  some holidays in the Diaspora', 'The special prayer shawl worn by men every day', 'The last day of Passover', 'The second Torah read in synagogues on Saturday'], answerIndex: 0 },
  { id: 240, question: 'What is Yichuss?', options: ['Special honor you get from family members', 'The special prayer shawl worn by women', 'A fast day celebrated on the day before Passover', 'The first book of the Kabbalah'], answerIndex: 0 },
  { id: 241, question: 'What does Yom Yerusalyim celebrate?', options: ['The building of the Second Temple in Jerusalem', 'The peace treaty between Egypt and Israel at Camp David', 'The building of the First Temple by Solomon', 'The unification of the City of Jerusalem after the Six Days War'], answerIndex: 3 },
  { id: 242, question: 'What are Dam, Tzefardea, Kinim?', options: ['The names of the three major holidays Jews celebrate in September and October', 'The first three plagues G-D put upon the Egyptians', 'The three books of the Torah', 'The national anthem of Israel'], answerIndex: 1 },
  { id: 243, question: 'The Hebrew term for the Old Testament is Tanach. How many books are in the Tanach?', options: ['26', '65', '39', '24'], answerIndex: 3 },
  { id: 244, question: 'Who wrote Joseph dArimathie, the first literary work to link the Holy Grail with the Last Supper of Jesus and Joseph of Arimathea?', options: ['Geoffrey of Monmouth', 'Chrétien de Troyes', 'Thomas Malory', 'Robert de Boron'], answerIndex: 3 },
  { id: 245, question: 'The book ‘Holy Blood, Holy Grail’ by Michael Baigent, Richard Leigh, and Henry Lincoln proposes the hypothesis that Jesus and Mary Magdalene were actually married and upon Jesus’ death she fled to France, carrying his child.', options: ['True', 'False'], answerIndex: 0 },
  { id: 246, question: 'The Holy Grail was a popular theme in many literary works from the 19th century such as the Arthurian cycle The Idylls of the King. Who was its author?', options: ['Dante Gabriel Rossetti', 'Jane Austin', 'Walter Scott', 'Alfred, Lord Tennyson'], answerIndex: 3 },
  { id: 247, question: 'At Christmas, Christians celebrates the Nativity or birth of Jesus Christ in which city?', options: ['None of these', 'Bethlehem', 'Nazareth', 'Jerusalem'], answerIndex: 1 },
  { id: 248, question: 'Which Christian saint, regarded as the first martyr of Christianity, is commemorated on December 27 or 26?', options: ['Saint Matthew', 'Saint Andrew', 'Saint Paul', 'Saint Stephen'], answerIndex: 3 },
  { id: 249, question: 'On September 8 or September 21, Eastern Orthodox Christians celebrate the birth of this important biblical figure to parents Joachim and Anna.', options: ['King Solomon', 'John the Baptist', 'Virgin Mary', 'King David'], answerIndex: 2 },
  { id: 250, question: 'Which event is regarded as the greatest feast in the Christian calendar?', options: ['Resurrection of Jesus', 'Ascension of Christ', 'Epiphany', 'Nativity of Christ'], answerIndex: 0 },
  { id: 251, question: 'He is considered to be the first Jew  to set foot on land that would become part of the USA.', options: ['Asser Lev', 'Joachim Gaunse', 'Luis de Torres', 'Solomon Franco'], answerIndex: 1 },
  { id: 252, question: 'In 1649 he was warned out of trying to settle in Boston.', options: ['Joachim Gaunse', 'Solomon Franco', 'Asser Lev', 'Luis de Torres'], answerIndex: 1 },
  { id: 253, question: 'He is considered the first Jew on American land to get the right  to serve in a militia.', options: ['Asser Lev', 'Solomon Franco', 'Myer Myers', 'Asser Levy'], answerIndex: 3 },
  { id: 254, question: 'In 1665, Abraham de Lucena was arrested and fined for selling goods at retail prices.', options: ['False', 'True'], answerIndex: 1 },
  { id: 255, question: 'This famous pirate, who was a marrano, played a significant role in American history.', options: ['Jean Lafitte', 'Alexander Hamilton', 'Lafayette', 'John Jay'], answerIndex: 0 },
  { id: 256, question: 'He was the first Jewish Commodore in the US Navy. He ended the practice of flogging which used to be an accepted form of punishment in the US Navy.', options: ['Uriah Phillip Levy', 'Abraham Moise Silver', 'Myer Myers', 'Asser Lev'], answerIndex: 0 },
  { id: 257, question: 'He was the first American-born Rabbi to lead a Chassidic group.', options: ['Rabbi Abba Hillel Silver', 'Rabbi Chaim Nathan Silver', 'Rabbi Jacob ben Yakov Halevy', 'Rabbi Levi Yitzach Halevi Horowitz'], answerIndex: 3 },
  { id: 258, question: 'Which of the following may save sinners according to the King James version of the Bible?', options: ['membership in a certain religion', 'personal relationship with God through His Son Jesus Christ', 'good works like almsgiving and fasting', 'baptism'], answerIndex: 1 },
  { id: 259, question: 'What is the punishment for human sins as it is written according to the Bible?', options: ['excommunication from the religion', 'longer life', 'physical death', 'second or spiritual death'], answerIndex: 3 },
  { id: 260, question: 'According to the Bible, is there anything that humans can do to be saved from Hell, the bottomless pit where worms dieth not?', options: ['Yes', 'No'], answerIndex: 0 },
  { id: 261, question: 'At Nazareth, this Biblical figure grew and waxed in spirit. His name means the anointed one.', options: ['Isaac', 'Jesus Christ', 'Paul', 'Moses'], answerIndex: 1 },
  { id: 262, question: 'According to the Bible, people are reconciled with God because of His Sons death at the cross in Mount Golgotha.', options: ['False', 'True'], answerIndex: 1 },
  { id: 263, question: 'According to the Bible, Jesus turned water to wine in this wedding feast that He had attended in Cana. Which of His miracles was this?', options: ['last miracle', 'second miracle', 'least miracle', 'first miracle'], answerIndex: 3 },
  { id: 264, question: 'According to the Bible, who should believers use as mediator between them and God when they pray?', options: ['Mary', 'Joseph', 'Jesus Christ', 'John, the Baptist'], answerIndex: 2 },
  { id: 265, question: 'Which epistle states that there is one mediator between God and men?', options: ['Ephesians', 'Philemon', 'Romans', 'Timothy'], answerIndex: 3 },
  { id: 266, question: 'According to the King James Version of the Bible, what did God command people to do always, day and night?', options: ['rejoicing', 'drinking wine', 'sinning', 'praying'], answerIndex: 3 },
  { id: 267, question: 'In the Bible, are there any verses that strictly mention “trinity” as a term?', options: ['Yes', 'No'], answerIndex: 1 },
  { id: 268, question: 'Nicknamed Black Angel, he was a prominent commander in the Chechen separatist movement against Russia.', options: ['Magomed Khanbiyev', 'Ruslan Gelayev', 'Mukhtar Suleimanov', 'Abdulkhalik Kurbanov'], answerIndex: 1 },
  { id: 269, question: 'James, one of the Twelve Apostles of Jesus, was known by which of these names?', options: ['All of these', 'James, son of Alphaeus', 'James the Greater', 'James the Less'], answerIndex: 0 },
  { id: 270, question: 'He was a Supreme Pontiff of the Roman Catholic Church and Sovereign of Vatican City from 1978 until his death in 2005.', options: ['John Paul I', 'Pope John Paul II', 'Benedict XVI', 'Paul VI'], answerIndex: 1 },
  { id: 271, question: 'This Spanish knight founded the Society of Jesus in 1534.', options: ['Martin Luther', 'Ignatius of Loyola', 'Pope Paul V', 'John Calvin'], answerIndex: 1 },
  { id: 272, question: 'He wrote the third Gospel and the Acts of the Apostles.', options: ['Luke the Evangelist', 'John the Evangelist', 'Matthew the Evangelist', 'Mark the Evangelist'], answerIndex: 0 },
  { id: 273, question: 'He was a Christian saint from Egypt and a prominent leader among the Desert Fathers.', options: ['Saint Menas', 'Anthony the Great', 'Saint Varus', 'Saint Rais'], answerIndex: 1 },
  { id: 274, question: 'Mary Faustina Kowalska was a Russian nun and mystic, venerated by the Roman Catholic Church as a saint.', options: ['True', 'False'], answerIndex: 1 },
  { id: 275, question: 'According to Christian tradition, this saint attached a silver hand to the icon of Theotokos, which has since then been known as Three-handed?', options: ['Ignatius of Antioch', 'Cosmas of Maiuma', 'John of Damascus', 'Abraham the Writer'], answerIndex: 2 },
  { id: 276, question: 'Megiddo church, one of the oldest church buildings discovered by archaeologists, is located in Israel.', options: ['True', 'False'], answerIndex: 0 },
  { id: 277, question: 'This Coptic Orthodox monastery is located in an oasis in the Eastern Desert of Egypt.', options: ['St. George Monastery', 'St. Anthony Monastery', 'St. Bishoy Monastery', 'St. Mina Monastery'], answerIndex: 1 },
  { id: 278, question: 'The Church of Our Lady Mary of Zion is an Ethiopian Orthodox Church.', options: ['False', 'True'], answerIndex: 1 },
  { id: 279, question: 'Which of these churches was designed by Isidore of Miletus and Anthemius of Tralles, who were professors of geometry at the University of Constantinople?', options: ['Saint Catherine’s Monastery', 'None of these', 'The Church of Our Lady Mary of Zion', 'Hagia Sophia'], answerIndex: 3 },
  { id: 280, question: 'Which monastery lies at the foot of Mount Sinai, where, according to the Hebrew Bible, Moses received the Ten Commandments from God?', options: ['St. Anthony Monastery', 'St. Simeon Monastery', 'St. Paul Monastery', 'Saint Catherine’s Monastery'], answerIndex: 3 },
  { id: 281, question: 'What church was built over the cave that tradition marks as the birthplace of Jesus of Nazareth?', options: ['Church of the Nativity, Raleigh', 'All of these', 'Church of the Nativity, Bethlehem', 'Church of the Nativity, Arbanassi'], answerIndex: 2 },
  { id: 282, question: 'What did Emanuel Swedenborg claim?', options: ['all of these', 'that the presence of the spiritual sense makes the Word Divine', 'that the Second Coming of Jesus Christ had occurred', 'that the Last Judgement had already occurred'], answerIndex: 0 },
  { id: 283, question: 'The first five books of the Old Testament are referred to as what?', options: ['The Torah', 'The Sacred Writings of Abraham', 'The Code', 'The Bible'], answerIndex: 0 },
  { id: 284, question: 'In Judaism, who is considered to be the first Jew ?', options: ['Abraham', 'Moses', 'Noah', 'Adam'], answerIndex: 0 },
  { id: 285, question: 'Why is the city of Hebron so important to Judaism ?', options: ['It is where the first Capital of Israel stood', 'It is believed that Abraham, Sarah, Issac, Rebekkah, Leah and Jacob are buried there', 'It was a stop on the way out of Egypt', 'It is where Jeremiah was born'], answerIndex: 1 },
  { id: 286, question: 'In the context of Judaism, who was Abrahams wife ?', options: ['Leah', 'Rachel', 'Sarah', 'Rebekkah'], answerIndex: 2 },
  { id: 287, question: 'How many laws are in the first five books of the Old Testament?', options: ['2150', '1000', '613', '100'], answerIndex: 2 },
  { id: 288, question: 'The witch hunts started as a result of the superstitions of some Catholic Monks. This Dominican monk is considered to be the initiator of the witch hunts as he prepared a detailed manual of deviltry for the Church.  It did not take long before women in Southern France were sent to the stake, condemned for cohabitation with the devil.', options: ['Thomas Aquinas', 'John XXII', 'Gregory', 'Hugo de Boniols'], answerIndex: 0 },
  { id: 289, question: 'Witch hunts still exist today. In 1981 a woman was killed by the mob, throwing stones at her as they believed she was a witch. This was the reason for stoning her to death.', options: ['Her sorcery incited the attack upon Pope John Paul II', 'Her spells were the reason for the ozone hole', 'Her magic killed the child of a neighbour', 'Her sorcery caused a tsunami in Mexico'], answerIndex: 0 },
  { id: 290, question: 'According to the Old Testament, the prophet Hosea was instructed by God to marry a prostitute.', options: ['False', 'True'], answerIndex: 1 },
  { id: 291, question: 'Psalm 119 is the longest psalm in the Bible. How many verses does it contain?', options: ['176', '150', '200', '138'], answerIndex: 0 },
  { id: 292, question: 'According to the Old Testament, Moses was 105 years old when he died.', options: ['True', 'False'], answerIndex: 1 },
  { id: 293, question: 'It is stated in the Old Testament that Jeremiah, Hosea, Jonah, and Job were prophets.', options: ['False', 'True'], answerIndex: 0 },
  { id: 294, question: 'According to The Old Testament, the prophet Jonah was sent to which city to warn its inhabitants of the coming judgment on them?', options: ['Ninevah', 'Joppa', 'Ai', 'Tarshish'], answerIndex: 0 },
  { id: 295, question: 'According to the Book of Genesis, what did G-D  create last, on the sixth day, as almost an afterthought?', options: ['Eve', 'Adam', 'The fishes of the waters', 'The birds of prey'], answerIndex: 1 },
  { id: 296, question: 'What was the name of Abrahams first wife?', options: ['Sarah', 'Haggar', 'Haggai', 'Ruth'], answerIndex: 0 },
  { id: 297, question: 'Who was Issacs wife according to Genesis?', options: ['Leah', 'Rebecca', 'Rachel', 'Ruth'], answerIndex: 1 },
  { id: 298, question: 'Judaism has three  Patriarchs -Abraham, Issac, and Jacob. Who are the four Matriarchs?', options: ['Sarah, Rebecca, Ruth, Naomi', 'Sarah , Rebecca , Rachel, Ruth', 'Sarah, Rebecca, Leah, Rachel', 'Sarah , Rebecca , Leah, Ruth'], answerIndex: 2 },
  { id: 299, question: 'What is the name of Jacobs only daughter according to Genesis?', options: ['Dina', 'Leah', 'Laban', 'Mileah'], answerIndex: 0 },
  { id: 300, question: 'The  Book of Genesis contains the first Biblical reference to someone being put into prison. Who was  put into prison?', options: ['Cain', 'Potiphar', 'Judah', 'Joseph'], answerIndex: 3 },
  { id: 301, question: 'Who was the third son of Adam and Eve, sometimes described as the quiet one?', options: ['Seth', 'Eli', 'Abel', 'Nahor'], answerIndex: 0 },
  { id: 302, question: 'The Hebrew people lived in the first ghetto when they were in Egypt. Where was this place?', options: ['Cannan', 'Barnes-Kaddesh', 'Nubia', 'Goshen'], answerIndex: 3 },
  { id: 303, question: 'According to the genealogy of Jesus, who was the father of Jesse?', options: ['David', 'Obed', 'Boaz', 'Samson'], answerIndex: 1 },
  { id: 304, question: 'In which of the following lands did Job live when he was first mentioned in the book of Job?', options: ['Judea', 'Uz', 'Galilee', 'Nazareth'], answerIndex: 1 },
  { id: 305, question: 'Who was king of Judaea during the birth of Jesus?', options: ['King David', 'King Solomon', 'King Herod', 'King Darius'], answerIndex: 2 },
  { id: 306, question: 'According to the Bible, how old was Joseph when he was put in charge of the whole land of Egypt, as Pharaoh had ordered.', options: ['40 years old', '30 years old', '22 years old', '35 years old'], answerIndex: 1 },
  { id: 307, question: 'According to the Bible after Sarahs death, Abraham married another woman. What was her name?', options: ['Keturah', 'Jessica', 'Naomi', 'Sheba'], answerIndex: 0 },
  { id: 308, question: 'From what tribe of Israel was Samson according to the Bible?', options: ['Benjamin', 'Gad', 'Dan', 'Levi'], answerIndex: 2 },
  { id: 309, question: 'This Biblical character is Jacobs father-in-law as well as father of Rachel and Leah.', options: ['Laban', 'Terah', 'Noah', 'Aram-balam'], answerIndex: 0 },
  { id: 310, question: 'Which is the sixth book of the New Testament?', options: ['Mark', 'Romans', 'Galatians', 'Luke'], answerIndex: 1 },
  { id: 311, question: 'According to the Bible, when Naomi told her two daughters-in-law to leave her and go to their homes, which daughter-in-law decided to stay?', options: ['Rebbecca', 'Judy', 'Beth', 'Ruth'], answerIndex: 3 },
  { id: 312, question: 'Which of the following did Jesus call first to be his disciple?', options: ['Philip', 'James', 'Simon', 'Judas'], answerIndex: 2 },
  { id: 313, question: 'What kind of person may you call Judas?', options: ['Someone who follows you', 'A thief', 'A friend who betrayed you', 'A person who committed suicide'], answerIndex: 2 },
  { id: 314, question: 'Which use of Goliath is correct?', options: ['Switzerland is the Goliath of international politics.', 'The FIFA 2006 World Cup final between France and Italy was like David against Goliath.', 'The local grocery successfully competed against the nearby Goliath supermaket', 'Fiesta is a real Goliath among Fords models.'], answerIndex: 2 },
  { id: 315, question: 'Which of the following can be described as a prodigal son?', options: ['The youngest son in the family', 'A young man who wastes his parents money on parties', 'A son that is very obedient and does dutifully everything his parents tell him', 'The firstborn son'], answerIndex: 1 },
  { id: 316, question: 'What does the sentence Ann was the apple of Marks eye tell us about the relation between those two?', options: ['Mark hates Ann.', 'Mark is deeply in love with Ann.', 'Ann is deeply in love with Mark.', 'Ann hates Mark.'], answerIndex: 1 },
  { id: 317, question: 'What characteristic is commonly attributed to King Solomon?', options: ['Wealth', 'Lust', 'Hunger', 'Wisdom'], answerIndex: 3 },
  { id: 318, question: 'What message am I conveying, if I say I dont know him from Adam?', options: ['I know very little about the person.', 'In spite of the negative form, the idiom means that you know someone very well.', 'The person is completely unknown to me.', 'I dont know his true character.'], answerIndex: 2 },
  { id: 319, question: 'If John knows Mary in the biblical sense, what can we say about the pair?', options: ['Mary is Johns sister.', 'They have had sex.', 'Their parents decided about their marriage.', 'They are in a Platonic relationship (ie. love, but no sex).'], answerIndex: 1 },
  { id: 320, question: 'What Biblical character said the following?', options: ['Esther', 'Martha', 'Ruth', 'Deborah'], answerIndex: 0 },
  { id: 321, question: 'The following words belong to this biblical figure:', options: ['Jesus', 'John the Baptist', 'Abraham', 'Job'], answerIndex: 3 },
  { id: 322, question: 'What Biblical hero delivered these words?', options: ['Samson', 'Solomon', 'David', 'Samuel'], answerIndex: 0 },
  { id: 323, question: 'What Biblical character asked the following question?', options: ['Peter', 'Jude', 'Jesus', 'Paul'], answerIndex: 2 },
  { id: 324, question: 'What character from the Bible said the following? Get rid of that slave woman and her son, for that slave womans son will never share in the inheritance with my son Isaac.', options: ['Ruth', 'Sarah', 'Leah', 'Rebeccah'], answerIndex: 1 },
  { id: 325, question: 'Who said the following: It is not the healthy who need a doctor, but the sick. But go and learn what this means: I desire mercy, not sacrifice. For I have not come to call the righteous, but sinners.', options: ['John', 'Jesus', 'Joseph', 'Matthew'], answerIndex: 1 },
  { id: 326, question: 'What Biblical figure said this?', options: ['Jacob', 'Esau', 'Adam', 'Issac'], answerIndex: 3 },
  { id: 327, question: 'Name the Biblical character who delivered these words: Pick me up and throw me into the sea, and it will become calm, I know that is is my fault that this great storm has come upon you.', options: ['Obadiah', 'Micah', 'Haggai', 'Jonah'], answerIndex: 3 },
  { id: 328, question: 'What character from the Bible said this?', options: ['Queen Vashti', 'Martha', 'Mary', 'Queen Sheba'], answerIndex: 1 },
  { id: 329, question: 'Who delivered these words: Suppose I go to the Israelites and say to them, The God of your fathers has sent me to you, and they ask me, ‘What is his name? Then what shall I tell them?', options: ['Joseph', 'Jonah', 'Moses', 'Aaron'], answerIndex: 2 },
];
