// AUTO-GENERATED by scripts/gen_bundled_verses.mjs from
// "120 verse 7 languages" (3-day fallback, 7 languages × 6 verses).
// Do not edit by hand — re-run the generator if the upstream JSON changes.

import type { LanguageCode } from '../state/TranslationsContext';

export interface DailyVerse {
  day: number;
  segment: 'morning' | 'evening';
  reference: {
    book: string;
    chapter: number;
    verse: string;
    full_reference: string;
  };
  modernVersion: string;
  modernText: string;
  meditation: string;
  actionStep: string;
  prayer: string;
}

export const BUNDLED_DAILY_VERSES: Record<LanguageCode, DailyVerse[]> =
  {
  "en": [
    {
      "day": 1,
      "segment": "morning",
      "reference": {
        "book": "John",
        "chapter": 1,
        "verse": "9",
        "full_reference": "John 1:9"
      },
      "modernVersion": "NIV",
      "modernText": "The true light that gives light to everyone was coming into the world.",
      "meditation": "What does it mean to live in darkness? For some, it's the gray of depression—that fog where nothing seems meaningful or hopeful. For others, it's confusion—searching for meaning, purpose, truth. For some, darkness is the weight of loss, loneliness, or failure. But John says there is a true light. Not many lights, each illuminating the way you prefer. Not relative truth, each person finding their own way.\n\nOne true light. Jesus. And He came—into this world, to illuminate 「everyone.」 Without exception. Not just the smartest, the most virtuous, the most worthy. Every person born into this world. This includes you—in your darkest moments, in your confusion and failure. This true light isn't distant or untouchable.\n\nIt came into the world. It comes into your darkness. Light dispels darkness. Not through force or struggle, but simply by existing. You don't have to earn this light. You don't have to prove yourself worthy of it. You simply turn toward it.",
      "actionStep": "Today, if you're in darkness—even a little—turn toward the true light. Seek Jesus in your dark places and invite His light into your life.",
      "prayer": "Lord Jesus, you are the True Light that gives light to everyone—without exception, without barrier. Your light breaks through every darkness and reaches every corner of the world. Thank you that this light is available to all, shining equally on rich and poor, near and far. Amen."
    },
    {
      "day": 1,
      "segment": "evening",
      "reference": {
        "book": "John",
        "chapter": 14,
        "verse": "1",
        "full_reference": "John 14:1"
      },
      "modernVersion": "NIV",
      "modernText": "Do not let your hearts be troubled. You believe in God; believe also in me.",
      "meditation": "Is your heart troubled right now? Maybe it's a breakup. Maybe it's a lost job. Maybe it's bad news about your health. Maybe it's just nighttime anxiety, when your mind turns to everything that could go wrong. Whatever the reason, you're here. Troubled. Anxious. Afraid.\n\nJesus says this to His disciples at the most difficult moment. They are about to watch Him be arrested. They will watch Him die on a cross. Their world is about to collapse. They have every reason to be afraid. And Jesus looks at them and says: 「Do not let your hearts be troubled.」 Not because everything will be fine—He doesn't even promise that. But because they can trust Him. \"You believe in God; believe also in me.\" What does that mean? It means trust God's character—His goodness, His power, His faithfulness—and believe those same qualities exist in Jesus. It means even in the worst case, you are not alone.\n\nHe is with you. He knows. He cares. He is able. So right now, in your troubles, Jesus says the same words to you. Do not let your heart be troubled. Turn toward faith. Turn toward Jesus. He once entered the deepest darkness to save you. He will not leave you in your everyday anxiety.",
      "actionStep": "Bring to mind the thing your heart fears most. Now, every time that fear rises, say it aloud: 「I will not let my heart be troubled. I believe in God, and I believe in Jesus.」 This isn't denying the fear. It's responding to it with faith instead.",
      "prayer": "Thank you, Jesus, for your peace—a peace that surpasses all understanding. You are the antidote to anxiety, the anchor in every storm. Your peace is not the absence of trouble, but your presence in the midst of it. Help us trust you completely. Amen."
    },
    {
      "day": 2,
      "segment": "morning",
      "reference": {
        "book": "Jeremiah",
        "chapter": 29,
        "verse": "11",
        "full_reference": "Jeremiah 29:11"
      },
      "modernVersion": "NIV",
      "modernText": "\"For I know the plans I have for you,\" declares the Lord, \"plans to prosper you and not to harm you, plans to give you hope and a future.\"",
      "meditation": "When Jeremiah wrote these words, the nation of Judah was drowning in despair. They had been dragged into exile in Babylon, separated from their homeland, uncertain what lay ahead. Many thought: \"Has God abandoned us? Is this really the end for us?\"\n\nBut in the deepest darkness, the Lord speaks through the prophet with a stunning message: \"I know.\" Not \"I observe,\" not \"I know what is happening\"—but \"I know the plans I have for you.\" God speaks about His thoughts toward them, His purposes, His designs. This changes everything.\n\nWhen you feel abandoned, forgotten, overlooked—God says: \"I remember you. My thoughts are full of plans for you.\" And these plans? They are not meant to harm you. They are not disaster. They are shalom—peace, wholeness, restoration.\n\nThey are a future. Sister, no matter your current circumstances, no matter what mistakes you have made, no matter how many times you have fallen—God's plans for you have not changed. He is not watching you fail and regretting that He created you. His eyes are fixed on your future, on the hope and restoration He wants to give you. Believe this. Let this promise sink into your bones.",
      "actionStep": "Write this in your journal or phone notes: \"God has plans of peace for me, not disaster.\" Every time doubt creeps in, read those words. If possible, read them every morning and evening, letting this truth gradually reshape how you see your future.",
      "prayer": "Lord, thank you for your promise that your plans for us are for our good — filled with hope and a flourishing future. You hold our days in your hands. Your purposes are not to harm us but to establish us in hope. Your plans do not fail — not one of them. History is your story, and you write it with hope as the final word. What a good Father you are, one who plans our flourishing before we can even imagine it. Amen."
    },
    {
      "day": 2,
      "segment": "evening",
      "reference": {
        "book": "John",
        "chapter": 14,
        "verse": "16",
        "full_reference": "John 14:16"
      },
      "modernVersion": "NIV",
      "modernText": "And I will ask the Father, and he will give you another advocate to help you and be with you forever—",
      "meditation": "Have you ever experienced that moment when someone important suddenly leaves, and despair floods in? Maybe it was a move to a new city, the end of a relationship, or the death of someone you loved. In that moment, all your sense of security disappeared. The disciples felt this despair too. When Jesus told them he was leaving, terror seized them.\n\nBut in that darkest hour, Jesus made a promise: \"And I will ask the Father, and he will give you another advocate to help you and be with you forever.\" Notice the word—\"another.\" Not a replacement, but another presence. Jesus left, but the Holy Spirit came. This isn't a downgrade but a deeper intimacy—not just being with Jesus, but having Jesus's Spirit living inside your heart. This is why the disciples' sorrow eventually transformed into joy. This is why they moved from hiding to bold witness.\n\nThe Advocate doesn't visit occasionally; he lives with you forever—in your loneliest midnight, in your most confusing moment, in the decision where you need guidance most. He is there. He knows your heart, he understands your thoughts, he even prays for you. You are truly not alone. You will never be alone.",
      "actionStep": "Today, stop and ask yourself: Am I feeling lonely right now? Do I need comfort? Do I need guidance? Whatever the answer, turn inward and invite the Spirit's presence: \"Holy Spirit, thank you for being with me forever. I invite you into this moment. Please help me, guide me, comfort me.\" Sit in that invitation, breathe, and feel his gentle presence. He is there.",
      "prayer": "Jesus, thank you for promising another Advocate—the Holy Spirit—to be with us forever. We are never alone, never without help. In every darkness, your Spirit intercedes for us, guides us, strengthens us. Thank you for this permanent presence. You promised an Advocate who would never leave. The Holy Spirit is this promise made permanent — not visiting, but dwelling in us forever. We are never truly alone. Thank you. Amen."
    },
    {
      "day": 3,
      "segment": "morning",
      "reference": {
        "book": "Matthew",
        "chapter": 28,
        "verse": "19",
        "full_reference": "Matthew 28:19"
      },
      "modernVersion": "NIV",
      "modernText": "Therefore go and make disciples of all nations, baptizing them in the name of the Father and of the Son and of the Holy Spirit,",
      "meditation": "Go and make disciples of all nations. When you read those words, maybe doubt creeps in. Maybe you think you're not qualified, not knowledgeable enough, not spiritually mature enough. But hear what Jesus said just before: \"All authority in heaven and on earth has been given to me.\" This isn't saying you need to have all the answers.\n\nIt's saying: I have all the authority, and I'm going with you. Sharing faith doesn't require a divinity degree. It requires a real story. Maybe your friend is struggling at work, and you tell them how prayer helped you. Maybe someone is grieving, and your honesty about your own pain opens a conversation about hope.\n\nMaybe you're simply living differently—with more peace, more forgiveness, more joy—and someone asks why. Your voice matters. Your small witness, your genuine faith, your willingness to share what Jesus has done for you—that changes lives. You don't have to be an expert. You just have to be authentic.",
      "actionStep": "Think of one person in your life who seems spiritually open or searching. This week, initiate a genuine conversation with them. Don't force theology—just share one way your faith has helped you practically. Listen more than you talk. Plant a seed.",
      "prayer": "Lord Jesus, you commissioned us to go to all nations, baptizing in the name of the Father, Son, and Holy Spirit. What an awesome calling! Thank you for entrusting us with your mission and making us your witnesses to the world. You go before us and behind us, opening the way for your gospel to reach every corner of this earth. May our lives reflect the glory of your name — Father, Son, and Holy Spirit. Amen."
    },
    {
      "day": 3,
      "segment": "evening",
      "reference": {
        "book": "Genesis",
        "chapter": 1,
        "verse": "2",
        "full_reference": "Genesis 1:2"
      },
      "modernVersion": "NIV",
      "modernText": "Now the earth was formless and empty, darkness was over the surface of the deep, and the Spirit of God was hovering over the waters.",
      "meditation": "Chaos. Formlessness. Void. Emptiness. Darkness. These are the starting conditions—not the ending conditions of God's creative work. When Genesis opens, the earth is 「formless and empty,」 and darkness covers everything. And in that very emptiness, the Spirit of God is present, hovering. Not distant.\n\nNot waiting. Hovering—present, active, intentional. This is a profound promise for those of us going through formless seasons. Seasons where nothing feels solid, where your plans have dissolved, where you can't see the shape of your future. Seasons of loss, of waiting, of not knowing. The hovering Spirit is there. God is not absent in your chaos. He is not overwhelmed by your emptiness. He is present.\n\nHe is moving. The hovering suggests gentleness—not violent intrusion but tender presence. Like a mother hovering over her child. Like hands cupped protectively around something precious. In your darkness, in your formlessness, God is hovering. He is working. He is moving toward creation, toward order, toward life. Your chaos is not the end of the story. It is the beginning of transformation.",
      "actionStep": "In whatever area of your life feels formless right now, pause and acknowledge: \"God is hovering here. He is present. He is working.\" Invite His presence into your chaos.",
      "prayer": "Lord, thank you—even in formlessness and darkness, your Spirit hovers, present and active. Life feels chaotic, unclear, beyond our control. Yet your Spirit moves over the deep, bringing order from chaos. Thank you for your constant care even in our confusion. The Spirit of God hovering over chaos — this is what you do. You move close, you breathe life into emptiness. You were present at the first creation and you are present in every new beginning. Amen."
    }
  ],
  "zh-Hans": [
    {
      "day": 1,
      "segment": "morning",
      "reference": {
        "book": "John",
        "chapter": 1,
        "verse": "9",
        "full_reference": "John 1:9"
      },
      "modernVersion": "CCB",
      "modernText": "真光来了，它照亮所有进入世界的人。",
      "meditation": "在黑暗中生活意味着什么？对某些人来说，这意味着抑郁症——那种让所有东西看起来都没有意义和无望的灰色，绝望的雾霾。对其他人来说，这意味着困惑——想知道生活的意义、你的目的、什么是真实的。对某些人来说，黑暗是损失、孤独或失败的重担。但约翰说有一个真光。不是许多光，照着每个人喜欢的方式。\n\n不是相对的，每个人找到他们自己的真理。一个真光。耶稣。他来了，照亮「所有人」——没有例外。不仅仅是最聪明的人，最好的人，最值得的人。每一个走进这个世界的人。这包括你——在你的黑暗时刻，在你的困惑和失败中。\n\n这个真光不是远离的，高高在上。它来到世界里。它来到你的黑暗。光驱散黑暗。不是通过力量或冲突，而是简单地存在。你不必赚取这个光。你只需要转向它。",
      "actionStep": "今天，如果你处于黑暗中，即使只是一点点——转向真光。在你的黑暗中寻求耶稣，并邀请他的光来到你的生活中。",
      "prayer": "主啊，你是那真光，照亮每一个人。你的光不分国籍、肤色、贫富，照亮世界上的每个人。感谢你，这盏灯如此明亮，如此普世，如此充满怜悯。愿这真光今天照亮我们的心。阿们。"
    },
    {
      "day": 1,
      "segment": "evening",
      "reference": {
        "book": "John",
        "chapter": 14,
        "verse": "1",
        "full_reference": "John 14:1"
      },
      "modernVersion": "CCB",
      "modernText": "你们的心不要不安。你们信神，也要信我。",
      "meditation": "你的心现在被扰乱吗？这可能是一次分手。也可能是一份失去的工作。也可能是一个关于健康的坏消息。也可能只是夜间的焦虑，当你的思想转向所有可能出错的事情时。无论是什么原因，你在这里。被扰乱。被烦恼。被恐惧。耶稣在最困难的时刻对门徒说这句话。\n\n他们将看到他被逮捕。他们将看到他死在十字架上。他们的世界即将崩溃。他们有充分的理由感到害怕。而耶稣看着他们，说：「你们心里不要忧愁。」不是因为一切都会好的——祂甚至没有承诺这一点。而是因为他们可以信任祂。「你们信神，也当信我。」这是什么意思？这意味着信任神的品格——祂的善良、祂的力量、祂的忠诚——并相信这些相同的品质也存在于耶稣身上。\n\n这意味着即使在最糟糕的情况下，你也不是孤单的。祂与你同在。祂知道。祂关心。祂有能力。所以，现在，在你的扰乱中，耶稣对你说同样的话。不要让你的心被扰乱。转向信仰。转向耶稣。祂曾经进入最深的黑暗来救你。祂不会在你的日常焦虑中离开你。",
      "actionStep": "让你的心所害怕的事情进入你的脑海。现在，每次恐惧浮现时，说出来：「我不会让我的心被扰乱。我信神，也信耶稣。」这不是否认恐惧。这是用信仰而不是恐惧来回应。",
      "prayer": "主耶稣啊，感谢你的话语——不要让我们的心忧愁，因为你就是我们的平安。你的平安超越一切理解，超越我们的恐惧。我们因信靠你而得着稳定。求你在我们的焦虑中赐予平安。阿们。"
    },
    {
      "day": 2,
      "segment": "morning",
      "reference": {
        "book": "Jeremiah",
        "chapter": 29,
        "verse": "11",
        "full_reference": "Jeremiah 29:11"
      },
      "modernVersion": "CCB",
      "modernText": "耶和华说：「我知道我对你们所有的计划，都是为了祝福你们，而不是伤害你们，要给你们一个美好的未来和希望。」",
      "meditation": "耶利米写这些话的时候，犹大民族已经陷入绝望。他们被掳到巴比伦，远离家园，不知道会如何。许多人心想：「神放弃我们了吗？这就是我们的结局吗？」\n\n就在这种深深的黑暗中，耶和华通过先知传来了一个惊人的信息：「我知道。」不是「我观看」，不是「我知道发生了什么」——而是「我知道我向你们所怀的意念」。\n\n神说的是祂对他们的想法、祂对他们的计划、祂对他们的目的。这改变一切。当你感到被遗弃、被遗忘时，神说：「我想起你了。我的思想满了关乎你的计划。」这些计划不是为了伤害你，而是为了祝福你。不是灾祸，而是和平。\n\n不是死亡，而是未来。姐妹，无论你现在的处境如何，无论你犯过什么错误，无论你多次跌倒，神关于你的计划没有改变。祂不是在观看你失败而后悔创造了你。祂的眼目始终看向你的未来，看向祂想要给你的希望和恢复。相信这个。让这个承诺进入你的骨髓。",
      "actionStep": "在你的日记或手机备忘录中写下：「关于我，神有和平的计划，不是灾祸的计划。」每当怀疑来临时，读这句话。如果可能，每天早晨和晚上都读一遍，让这个真理逐渐改变你对未来的看法。",
      "prayer": "主啊，感谢你这样应许我们——你的计划一直为了我们的美好，为了给我们希望和未来。你不是要破坏我们的梦想，而是要用你的恩典实现比我们所求所想更大的事。我们的未来在你的手中，充满希望。 你的计划不会失败——一个都不会。历史是你的故事，你用盼望作为最后的词来书写它。你是何等好的父亲，一位在我们甚至无法想象之前就为我们的繁盛筹划的神。 阿们。"
    },
    {
      "day": 2,
      "segment": "evening",
      "reference": {
        "book": "John",
        "chapter": 14,
        "verse": "16",
        "full_reference": "John 14:16"
      },
      "modernVersion": "CCB",
      "modernText": "我会向父祈求，父会赐给你们另一位保惠师，他要永远与你们同在。",
      "meditation": "你是否有过那样的经历——某个重要的人突然要离开你，而你感到被抛弃的绝望？也许是一次搬迁、一段关系的结束、或者某个爱你的人去世了。在那一刻，所有的安全感都消失了。耶稣的门徒也经历过这种绝望。他们听到耶稣说他要离开，就被恐惧吞没了。\n\n但在那最黑暗的时刻，耶稣做了一个承诺：「我要求父，父就另外赐给你们一位保惠师，叫他永远与你们同在。」注意这个词——「另外」。不是一个替代品，而是另一位。耶稣离开了，但保惠圣灵来了。这不是一个劣质的交易，而是一个更深层次的亲密——不只是与耶稣同在，而是让耶稣的灵住在你心里。这就是为什么门徒们的忧伤最终转变成了喜乐。\n\n这就是为什么他们可以从隐藏转向大胆传道。保惠师不是偶尔来访，而是永远与你同在——在你最孤独的午夜，在你最困惑的时刻，在你最需要引导的决定关头。他在那里。他知道你的心，他明白你的想法，他甚至为你祷告。你真的不是一个人。你从来都不会是一个人。",
      "actionStep": "今天，停下来，问问自己：我现在感到孤独吗？我现在需要安慰吗？我现在需要引导吗？不管答案是什么，转向内心，邀请圣灵的同在：「圣灵啊，感谢你永远与我同在。我邀请你进入这个时刻。请帮助我、引导我、安慰我。」坐在这个邀请中，呼吸，感受他的温柔同在。他就在那里。",
      "prayer": "耶稣啊，感谢你——你应许赐给我们另一位保惠师，在我们身旁永远与我们同在。圣灵是我们永远的倡导者、永远的帮助者。我们永远不孤单，永远不没有帮助。即使在最黑暗的时刻，你的灵仍在我们心中呼唤，引领，保护。感谢你永远的陪伴。 你应许了一位永不离开的保惠师。圣灵是这个应许的永久实现——不是探访，而是永远住在我们里面。我们从未真正孤单。感谢你。 阿们。"
    },
    {
      "day": 3,
      "segment": "morning",
      "reference": {
        "book": "Matthew",
        "chapter": 28,
        "verse": "19",
        "full_reference": "Matthew 28:19"
      },
      "modernVersion": "CCB 当代译本",
      "modernText": "所以，你们要去，使所有民族都成为我的门徒，奉父、子、圣灵的名给他们施洗，",
      "meditation": "\"去使万民作我的门徒\"——当你读到这句话时，也许你的心里闪过一些自我怀疑。也许你想：\"我够资格吗？我懂得够多吗？我的见证足够强大吗？\"\n\n但注意耶稣在这句话之前说了什么：\"天上地下所有的权柄都赐给我了。\"这不是说\"你需要有所有的答案\"，而是说\"我有所有的权柄，而我就在你身边\"。\n\n分享信仰不一定意味着成为传教士或牧师。它意味着让别人看到基督改变你的生活。也许是通过你的诚实、你的同情、你的原谅，或你在困难中的勇气。也许是通过你愿意倾听朋友的痛苦，并说：\"我知道有一个人可以帮助你。\"\n\n你不需要有完美的神学。你只需要有一个真实的故事——一个关于耶稣如何改变你的故事。那本身就有力量。",
      "actionStep": "想想你认识的一个人，他们似乎在属灵上寻求什么。不要计划一个长长的宗教讨论。只需邀请他们喝咖啡，并分享一个小故事——关于你的信仰如何帮助你度过困难。听听他们怎么说。",
      "prayer": "主耶稣，你赐给我们大使命，差遣我们去到万民中，为圣父、圣子、圣灵的名施洗。这是多么伟大的呼召，多么荣耀的委托。感谢你信任我们成为你的见证人。 你在我们前后同行，让你的福音抵达大地的每一个角落。愿我们的生命荣耀你的圣名——父、子、圣灵。 阿们。"
    },
    {
      "day": 3,
      "segment": "evening",
      "reference": {
        "book": "Genesis",
        "chapter": 1,
        "verse": "2",
        "full_reference": "Genesis 1:2"
      },
      "modernVersion": "CCB",
      "modernText": "大地一片混乱空洞，黑暗笼罩着深洋；神的灵在水面上运行。",
      "meditation": "想象一下：一切都是混沌的。没有形状、没有光、没有秩序。这不是诗意的描述，这是真实的——这是世界在形成之前的样子。它是空虚的，它是黑暗的，它是无形的。这就是你可能现在感受到的——你的生活、你的梦想、你的未来都像是一片混沌。但在这个混沌之中，有一个细节改变了一切：「神的灵运行在水面上」。这不是神站在远处，指挥和评判。这是神的灵「运行」——像母鹰在嵌套上盘旋，温柔而专注地悬停。这是神在混沌中的存在。\n\n这是神在黑暗中的活动。他没有逃避这个混沌；他进入了它，用他的灵触摸了它。然后，第三天、第四天、第五天、第六天……秩序开始浮现。光从黑暗中分离出来。陆地从水中浮现。生命从死的原料中诞生。但所有这一切都始于同一件事：神的灵在那里，运行，工作，创造。没有任何东西表明最终会发生什么；只有一个承诺：神在这里，他在工作。亲爱的，如果你现在正在混沌中，如果你的生活感到空虚、黑暗、无形，请听这个古老而真实的话：神的灵正在你上面运行。\n\n他没有逃离你的混沌；他进入了它。他不仅仅是观看；他正在工作。即使你看不到他在做什么，即使你不知道这将导向何处，他也在那里。他在创造。秩序即将来临。光即将出现。生命即将在你的荒野中绽放。但首先，在混沌中，在黑暗中，他就在那里。这就是足够的。这，对于现在，已经足够了。",
      "actionStep": "如果你正在一个「混沌」的季节——一个你不知道会发生什么、事情看起来没有形状或目的的季节——花一些时间想象神的灵在你上面运行。不是在远处看，而是温柔地、专注地悬停在你的混沌之上。写下你生活中正在「混沌」中的一个领域，以及你认为可能会从中浮现出什么。不是一个计划，而是一个相信——即使在黑暗中，神也在工作。",
      "prayer": "主啊，感谢你——即使在混沌和黑暗中，你的灵也在运行。我们的生活有时看似无形、不清楚、失控。但你的灵运行在其中，塑造一切，带来秩序。感谢你，即使在我们的混乱、困惑和不确定中，你仍在看顾，仍在行动。 神的灵运行在混沌之上——这就是你所做的。你走近，你将生命吹入空虚中。你在第一次创造时同在，你在每一个新的开始时同在。 阿们。"
    }
  ],
  "zh-Hant": [
    {
      "day": 1,
      "segment": "morning",
      "reference": {
        "book": "John",
        "chapter": 1,
        "verse": "9",
        "full_reference": "John 1:9"
      },
      "modernVersion": "CCB",
      "modernText": "真光来了，它照亮所有进入世界的人。",
      "meditation": "在黑暗中生活意味着什麼？對某些人來說，這意味着抑郁症——那種讓所有東西看起來都沒有意義和无望的灰色，绝望的雾霾。對其他人來說，這意味着困惑——想知道生活的意義、你的目的、什麼是真實的。對某些人來說，黑暗是損失、孤獨或失败的重擔。但約翰說有一個真光。不是许多光，照着每個人喜欢的方式。\n\n不是相對的，每個人找到他們自己的真理。一個真光。耶稣。他來了，照亮「所有人」——沒有例外。不仅仅是最聰明的人，最好的人，最值得的人。每一個走進這個世界的人。這包括你——在你的黑暗時刻，在你的困惑和失败中。\n\n這個真光不是遠离的，高高在上。它來到世界裡。它來到你的黑暗。光驱散黑暗。不是通過力量或冲突，而是簡單地存在。你不必赚取這個光。你只需要转向它。",
      "actionStep": "今天，如果你处于黑暗中，即使只是一點點——转向真光。在你的黑暗中寻求耶稣，並邀請他的光來到你的生活中。",
      "prayer": "主啊，你是那真光，照亮每一個人。你的光不分国籍、肤色、贫富，照亮世界上的每個人。感谢你，這盏燈如此明亮，如此普世，如此充滿怜悯。願這真光今天照亮我們的心。阿們。"
    },
    {
      "day": 1,
      "segment": "evening",
      "reference": {
        "book": "John",
        "chapter": 14,
        "verse": "1",
        "full_reference": "John 14:1"
      },
      "modernVersion": "CCB",
      "modernText": "你们的心不要不安。你们信神，也要信我。",
      "meditation": "你的心現在被擾乱吗？這可能是一次分手。也可能是一份失去的工作。也可能是一個關于健康的壞消息。也可能只是夜間的焦慮，當你的思想转向所有可能出錯的事情時。无論是什麼原因，你在這裡。被擾乱。被烦惱。被恐惧。耶稣在最困難的時刻對門徒說這句話。\n\n他們將看到他被逮捕。他們將看到他死在十字架上。他們的世界即將崩溃。他們有充分的理由感到害怕。而耶稣看着他們，說：「你們心裡不要忧愁。」不是因為一切都會好的——祂甚至沒有承諾這一點。而是因為他們可以信任祂。「你們信神，也當信我。」這是什麼意思？這意味着信任神的品格——祂的善良、祂的力量、祂的忠誠——並相信這些相同的品质也存在于耶稣身上。\n\n這意味着即使在最糟糕的情况下，你也不是孤單的。祂与你同在。祂知道。祂關心。祂有能力。所以，現在，在你的擾乱中，耶稣對你說同樣的話。不要讓你的心被擾乱。转向信仰。转向耶稣。祂曾經進入最深的黑暗來救你。祂不會在你的日常焦慮中离開你。",
      "actionStep": "讓你的心所害怕的事情進入你的腦海。現在，每次恐惧浮現時，說出來：「我不會讓我的心被擾乱。我信神，也信耶稣。」這不是否認恐惧。這是用信仰而不是恐惧來回應。",
      "prayer": "主耶稣啊，感谢你的話语——不要讓我們的心忧愁，因為你就是我們的平安。你的平安超越一切理解，超越我們的恐惧。我們因信靠你而得着稳定。求你在我們的焦慮中赐予平安。阿們。"
    },
    {
      "day": 2,
      "segment": "morning",
      "reference": {
        "book": "Jeremiah",
        "chapter": 29,
        "verse": "11",
        "full_reference": "Jeremiah 29:11"
      },
      "modernVersion": "CCB",
      "modernText": "耶和华说：「我知道我对你们所有的计划，都是为了祝福你们，而不是伤害你们，要给你们一个美好的未来和希望。」",
      "meditation": "耶利米寫這些話的時候，犹大民族已經陷入绝望。他們被擄到巴比伦，遠离家园，不知道會如何。许多人心想：「神放弃我們了吗？這就是我們的結局吗？」\n\n就在這種深深的黑暗中，耶和華通過先知传來了一個驚人的信息：「我知道。」不是「我观看」，不是「我知道發生了什麼」——而是「我知道我向你們所怀的意念」。\n\n神說的是祂對他們的想法、祂對他們的计划、祂對他們的目的。這改變一切。當你感到被遗弃、被遗忘時，神說：「我想起你了。我的思想滿了關乎你的计划。」這些计划不是為了傷害你，而是為了祝福你。不是災禍，而是和平。\n\n不是死亡，而是未來。姐妹，无論你現在的处境如何，无論你犯過什麼錯误，无論你多次跌倒，神關于你的计划沒有改變。祂不是在观看你失败而后悔创造了你。祂的眼目始终看向你的未來，看向祂想要給你的希望和恢複。相信這個。讓這個承諾進入你的骨髓。",
      "actionStep": "在你的日记或手機备忘錄中寫下：「關于我，神有和平的计划，不是災禍的计划。」每當怀疑來临時，读這句話。如果可能，每天早晨和晚上都读一遍，讓這個真理逐渐改變你對未來的看法。",
      "prayer": "主啊，感谢你這樣應许我們——你的计划一直為了我們的美好，為了給我們希望和未來。你不是要破壞我們的夢想，而是要用你的恩典實現比我們所求所想更大的事。我們的未來在你的手中，充滿希望。 你的计划不會失败——一個都不會。歷史是你的故事，你用盼望作為最后的詞來書寫它。你是何等好的父親，一位在我們甚至无法想象之前就為我們的繁盛筹划的神。 阿們。"
    },
    {
      "day": 2,
      "segment": "evening",
      "reference": {
        "book": "John",
        "chapter": 14,
        "verse": "16",
        "full_reference": "John 14:16"
      },
      "modernVersion": "CCB",
      "modernText": "我会向父祈求，父会赐给你们另一位保惠师，他要永远与你们同在。",
      "meditation": "你是否有過那樣的經歷——某個重要的人突然要离開你，而你感到被抛弃的绝望？也许是一次搬迁、一段關系的結束、或者某個愛你的人去世了。在那一刻，所有的安全感都消失了。耶稣的門徒也經歷過這種绝望。他們听到耶稣說他要离開，就被恐惧吞沒了。\n\n但在那最黑暗的時刻，耶稣做了一個承諾：「我要求父，父就另外赐給你們一位保惠師，叫他永遠与你們同在。」注意這個詞——「另外」。不是一個替代品，而是另一位。耶稣离開了，但保惠聖靈來了。這不是一個劣质的交易，而是一個更深層次的親密——不只是与耶稣同在，而是讓耶稣的靈住在你心裡。這就是為什麼門徒們的忧傷最终转變成了喜樂。\n\n這就是為什麼他們可以從隐藏转向大胆传道。保惠師不是偶爾來访，而是永遠与你同在——在你最孤獨的午夜，在你最困惑的時刻，在你最需要引導的决定關头。他在那裡。他知道你的心，他明白你的想法，他甚至為你祷告。你真的不是一個人。你從來都不會是一個人。",
      "actionStep": "今天，停下來，問問自己：我現在感到孤獨吗？我現在需要安慰吗？我現在需要引導吗？不管答案是什麼，转向内心，邀請聖靈的同在：「聖靈啊，感谢你永遠与我同在。我邀請你進入這個時刻。請帮助我、引導我、安慰我。」坐在這個邀請中，呼吸，感受他的溫柔同在。他就在那裡。",
      "prayer": "耶稣啊，感谢你——你應许赐給我們另一位保惠師，在我們身旁永遠与我們同在。聖靈是我們永遠的倡導者、永遠的帮助者。我們永遠不孤單，永遠不沒有帮助。即使在最黑暗的時刻，你的靈仍在我們心中呼唤，引領，保护。感谢你永遠的陪伴。 你應许了一位永不离開的保惠師。聖靈是這個應许的永久實現——不是探访，而是永遠住在我們裡面。我們從未真正孤單。感谢你。 阿們。"
    },
    {
      "day": 3,
      "segment": "morning",
      "reference": {
        "book": "Matthew",
        "chapter": 28,
        "verse": "19",
        "full_reference": "Matthew 28:19"
      },
      "modernVersion": "CCB 当代译本",
      "modernText": "所以，你们要去，使所有民族都成为我的门徒，奉父、子、圣灵的名给他们施洗，",
      "meditation": "\"去使萬民作我的門徒\"——當你读到這句話時，也许你的心裡闪過一些自我怀疑。也许你想：\"我够资格吗？我懂得够多吗？我的見證足够強大吗？\"\n\n但注意耶稣在這句話之前說了什麼：\"天上地下所有的權柄都赐給我了。\"這不是說\"你需要有所有的答案\"，而是說\"我有所有的權柄，而我就在你身邊\"。\n\n分享信仰不一定意味着成為传教士或牧師。它意味着讓別人看到基督改變你的生活。也许是通過你的誠實、你的同情、你的原諒，或你在困難中的勇氣。也许是通過你願意傾听朋友的痛苦，並說：\"我知道有一個人可以帮助你。\"\n\n你不需要有完美的神學。你只需要有一個真實的故事——一個關于耶稣如何改變你的故事。那本身就有力量。",
      "actionStep": "想想你認識的一個人，他們似乎在属靈上寻求什麼。不要计划一個長長的宗教討論。只需邀請他們喝咖啡，並分享一個小故事——關于你的信仰如何帮助你度過困難。听听他們怎麼說。",
      "prayer": "主耶稣，你赐給我們大使命，差遣我們去到萬民中，為聖父、聖子、聖靈的名施洗。這是多麼伟大的呼召，多麼荣耀的委托。感谢你信任我們成為你的見證人。 你在我們前后同行，讓你的福音抵達大地的每一個角落。願我們的生命荣耀你的聖名——父、子、聖靈。 阿們。"
    },
    {
      "day": 3,
      "segment": "evening",
      "reference": {
        "book": "Genesis",
        "chapter": 1,
        "verse": "2",
        "full_reference": "Genesis 1:2"
      },
      "modernVersion": "CCB",
      "modernText": "大地一片混乱空洞，黑暗笼罩着深洋；神的灵在水面上运行。",
      "meditation": "想象一下：一切都是混沌的。沒有形状、沒有光、沒有秩序。這不是詩意的描述，這是真實的——這是世界在形成之前的樣子。它是空虛的，它是黑暗的，它是无形的。這就是你可能現在感受到的——你的生活、你的夢想、你的未來都像是一片混沌。但在這個混沌之中，有一個细節改變了一切：「神的靈運行在水面上」。這不是神站在遠处，指挥和評判。這是神的靈「運行」——像母鹰在嵌套上盤旋，溫柔而專注地悬停。這是神在混沌中的存在。\n\n這是神在黑暗中的活動。他沒有逃避這個混沌；他進入了它，用他的靈触摸了它。然后，第三天、第四天、第五天、第六天……秩序開始浮現。光從黑暗中分离出來。陸地從水中浮現。生命從死的原料中誕生。但所有這一切都始于同一件事：神的靈在那裡，運行，工作，创造。沒有任何東西表明最终會發生什麼；只有一個承諾：神在這裡，他在工作。親愛的，如果你現在正在混沌中，如果你的生活感到空虛、黑暗、无形，請听這個古老而真實的話：神的靈正在你上面運行。\n\n他沒有逃离你的混沌；他進入了它。他不仅仅是观看；他正在工作。即使你看不到他在做什麼，即使你不知道這將導向何处，他也在那裡。他在创造。秩序即將來临。光即將出現。生命即將在你的荒野中绽放。但首先，在混沌中，在黑暗中，他就在那裡。這就是足够的。這，對于現在，已經足够了。",
      "actionStep": "如果你正在一個「混沌」的季節——一個你不知道會發生什麼、事情看起來沒有形状或目的的季節——花一些時間想象神的靈在你上面運行。不是在遠处看，而是溫柔地、專注地悬停在你的混沌之上。寫下你生活中正在「混沌」中的一個領域，以及你認為可能會從中浮現出什麼。不是一個计划，而是一個相信——即使在黑暗中，神也在工作。",
      "prayer": "主啊，感谢你——即使在混沌和黑暗中，你的靈也在運行。我們的生活有時看似无形、不清楚、失控。但你的靈運行在其中，塑造一切，帶來秩序。感谢你，即使在我們的混乱、困惑和不确定中，你仍在看顾，仍在行動。 神的靈運行在混沌之上——這就是你所做的。你走近，你將生命吹入空虛中。你在第一次创造時同在，你在每一個新的開始時同在。 阿們。"
    }
  ],
  "de": [
    {
      "day": 1,
      "segment": "morning",
      "reference": {
        "book": "John",
        "chapter": 1,
        "verse": "9",
        "full_reference": "John 1:9"
      },
      "modernVersion": "Lutherbibel 2017",
      "modernText": "Das wahre Licht, das jeden Menschen erleuchtet, kam in die Welt.",
      "meditation": "Was bedeutet es, in Finsternis zu leben? Für manche ist es die Grauheit der Depression—jener Nebel, wo nichts bedeutsam oder hoffnungsvoll erscheint. Für andere ist es Verwirrung—die Suche nach Sinn, Zweck, Wahrheit. Für manche ist Finsternis das Gewicht von Verlust, Einsamkeit oder Versagen. Aber Johannes sagt, dass es ein wahres Licht gibt.\n\nNicht viele Lichter, jedes illuminiert den Weg, den du bevorzugst. Nicht relative Wahrheit, jede Person findet ihren eigenen Weg. Ein wahres Licht. Jesus. Und Er kam—in die Welt, um alle」zu erleuchten. Ohne Ausnahme.\n\nNicht nur die intelligentesten, die tugendhaftesten, die würdigsten. Jede Person, die in diese Welt geboren wird. Das schließt dich ein—in deinen dunkelsten Momenten, in deiner Verwirrung und deinem Versagen. Dieses wahre Licht ist nicht fern oder unerreichbar. Es kam in die Welt. Es kommt in deine Finsternis.",
      "actionStep": "Heute, wenn du in Finsternis bist—auch nur ein bisschen—wende dich dem wahren Licht zu. Suche Jesus in deinen dunklen Orten und lade sein Licht in dein Leben ein.",
      "prayer": "Herr Jesus, du bist das Wahre Licht, das jeden Menschen erleuchtet—ohne Ausnahme, ohne Barriere. Dein Licht durchbricht alle Finsternis und erreicht jeden Winkel der Welt. Danke, dass dieses Licht allen zugänglich ist und gleichermaßen auf Reiche und Arme, Nah und Fern scheint. Amen."
    },
    {
      "day": 1,
      "segment": "evening",
      "reference": {
        "book": "John",
        "chapter": 14,
        "verse": "1",
        "full_reference": "John 14:1"
      },
      "modernVersion": "Lutherbibel 2017",
      "modernText": "Euer Herz erschrecke nicht! Glaubt an Gott und glaubt an mich.",
      "meditation": "Wird dein Herz jetzt beunruhigt? Vielleicht ist es ein Bruch. Vielleicht ist es ein verlorener Job. Vielleicht ist es eine schlechte Nachricht über deine Gesundheit. Vielleicht ist es nur nächtliche Angst, wenn sich dein Geist allem zuwendet, das schiefgehen könnte. Was auch immer der Grund ist, du bist hier. Beunruhigt.\n\nÄngstlich. Verängstigt. Jesus sagt dies zu Seinen Jüngern im schwierigsten Moment. Sie werden sehen, wie Er verhaftet wird. Sie werden sehen, dass Er am Kreuz stirbt. Ihre Welt wird zusammenbrechen. Sie haben jeden Grund, verängstigt zu sein.\n\nUnd Jesus schaut sie an und sagt: 「Euer Herz erschrecke nicht.」 Nicht weil alles gut wird—Er verspricht das nicht einmal. Aber weil sie Ihm vertrauen können. \"Glaubt an Gott und glaubt an mich.\" Was bedeutet das? Das bedeutet, Gottes Charakter zu vertrauen—Seine Güte, Seine Kraft, Seine Treue—und zu glauben, dass diese gleichen Qualitäten auch in Jesus existieren. Es bedeutet, dass du auch im schlimmsten Fall nicht allein bist. Er ist bei dir. Also jetzt, in deinen Beunruhigungen, sagt Jesus dir die gleichen Worte.",
      "actionStep": "Bring das in den Sinn, das dein Herz am meisten fürchtet. Sage jedes Mal, wenn diese Angst aufsteigt, laut: 「Ich werde nicht zulassen, dass mein Herz beunruhigt wird. Ich glaube an Gott, und ich glaube an Jesus.」",
      "prayer": "Danke, Jesus, für deinen Frieden—einen Frieden, der alles Verständnis übersteigt. Du bist das Gegenmittel gegen Angst, der Anker in jedem Sturm. Dein Frieden ist nicht die Abwesenheit von Problemen, sondern deine Gegenwart inmitten von ihnen. Hilf uns, dir völlig zu vertrauen. Amen."
    },
    {
      "day": 2,
      "segment": "morning",
      "reference": {
        "book": "Jeremiah",
        "chapter": 29,
        "verse": "11",
        "full_reference": "Jeremiah 29:11"
      },
      "modernVersion": "Lutherbibel 2017",
      "modernText": "Denn ich weiß wohl, welche Gedanken ich von euch habe, spricht der Herr, Gedanken des Friedens und nicht des Unheils, um euch Zukunft und Hoffnung zu geben.",
      "meditation": "Als Jeremia diese Worte schrieb, erstickte die Nation Juda in Verzweiflung. Sie waren ins Exil nach Babylon verschleppt worden, von ihrer Heimat getrennt, unsicher über das, was vor ihnen lag. Viele dachten: \"Hat uns Gott verlassen?\n\nIst dies wirklich unser Ende?\"\n\nAber in der tiefsten Finsternis spricht der Herr durch den Propheten mit einer erstaunlichen Botschaft: \"Ich weiß.\" Nicht \"Ich beobachte\", nicht \"Ich weiß, was passiert\"—sondern \"Ich weiß die Gedanken, die ich von euch habe.\" Gott spricht über Seine Gedanken gegenüber ihnen. Das ändert alles. Wenn du dich verlassen, vergessen fühlst—sagt Gott: \"Ich erinnere mich an dich. Meine Gedanken sind voller Pläne für dich.\" Und diese Pläne?\n\nSie sind nicht, um dir zu schaden. Sie sind keine Katastrophen. Sie sind Frieden, Wohlstand, Wiederherstellung. Schwester, unabhängig von deinen gegenwärtigen Umständen, unabhängig davon, welche Fehler du gemacht hast, unabhängig davon, wie oft du gefallen bist—Gottes Pläne für dich haben sich nicht geändert.",
      "actionStep": "Schreiben Sie in Ihr Tagebuch oder in Ihre Telefonnotizen: \"Gott hat Pläne des Friedens für mich, nicht der Katastrophe.\" Jedes Mal, wenn der Zweifel auftaucht, lesen Sie diese Worte. Wenn möglich, lesen Sie sie jeden Morgen und jeden Abend.",
      "prayer": "Lieber himmlischer Vater, ich danke dir, dass du weißt. Danke, dass du nicht ein gleichgültiger Gott bist, sondern ein Gott voller Liebe mit absichtlichen Plänen für mich. Ich gestehe ein, dass ich manchmal Schwierigkeiten habe, das zu glauben. Meine Geschichte, meine Fehler, die Dinge, die mich unwürdig fühlen lassen, lassen mich zweifeln. Aber du sagst, deine Pläne sind Pläne des Friedens, nicht der Katastrophe. Hilf mir, diese Verheißung anzunehmen. Während ich darauf warte, deine Pläne sich entfalten zu sehen, gib mir Frieden in meinem Herzen. Lass mich dir jeden Tag mehr vertrauen. Im Namen Jesu, amen."
    },
    {
      "day": 2,
      "segment": "evening",
      "reference": {
        "book": "John",
        "chapter": 14,
        "verse": "16",
        "full_reference": "John 14:16"
      },
      "modernVersion": "Lutherbibel 2017",
      "modernText": "Und ich werde den Vater bitten, und er wird euch einen anderen Beistand geben, dass er bei euch bleibt auf ewig—",
      "meditation": "Hast du jemals diesen Moment erlebt, in dem jemand Wichtiges plötzlich geht und Verzweiflung dich überschwemmt? Vielleicht war es ein Umzug in eine neue Stadt, das Ende einer Beziehung oder der Tod von jemandem, den du geliebt hast. In diesem Moment verschwand all dein Sicherheitsgefühl. Die Jünger empfanden diese Verzweiflung auch. Als Jesus ihnen sagte, dass er ging, ergriff sie Terror.\n\nAber in dieser dunkelsten Stunde machte Jesus ein Versprechen: \"Und ich werde den Vater bitten, und er wird euch einen anderen Beistand geben, dass er bei euch bleibt auf ewig.\" Beachte das Wort—\"einen anderen.\" Kein Ersatz, sondern eine weitere Präsenz. Jesus ging, aber der Heilige Geist kam. Dies ist kein Rückschritt, sondern eine tiefere Intimität—nicht nur bei Jesus sein, sondern Jesu Geist in deinem Herzen haben, der lebt. Deshalb verwandelte sich die Trauer der Jünger schließlich in Freude. Deshalb bewegten sie sich vom Verstecken zum kühnen Zeugnis.\n\nDer Tröster besucht nicht gelegentlich; er lebt für immer bei dir—in deiner einsamsten Mitternacht, in deinem verwirrtesten Moment, in der Entscheidung, in der du die meiste Führung brauchst. Er ist dort. Er kennt dein Herz, er versteht deine Gedanken, er betet sogar für dich. Du bist wirklich nicht allein. Du wirst niemals allein sein.",
      "actionStep": "Heute, halte inne und frag dich selbst: Fühle ich mich jetzt einsam? Brauche ich Trost? Brauche ich Führung? Egal wie die Antwort lautet, wende dich nach innen und lade die Gegenwart des Geistes ein: \"Heiliger Geist, danke dass du für immer bei mir bist. Ich lade dich in diesen Moment ein. Bitte hilf mir, leite mich, tröste mich.\" Sitz in dieser Einladung, atme und spüre seine sanfte Gegenwart. Er ist dort.",
      "prayer": "Jesus, danke, dass du einen anderen Anwalt versprochen hast—den Heiligen Geist—der für immer bei uns sein wird. Wir sind nie allein, nie ohne Hilfe. In aller Finsternis tritt dein Geist für uns ein, leitet uns, stärkt uns. Danke für diese ständige Gegenwart. Du versprach einen Fürsprecher, der für immer in uns wohnt. Wir sind nie allein. Amen."
    },
    {
      "day": 3,
      "segment": "morning",
      "reference": {
        "book": "Matthew",
        "chapter": 28,
        "verse": "19",
        "full_reference": "Matthew 28:19"
      },
      "modernVersion": "Lutherbibel 2017",
      "modernText": "Darum gehet hin und machet zu Jüngern alle Völker, und täufet sie auf den Namen des Vaters und des Sohnes und des heiligen Geistes,",
      "meditation": "Geh und mache Jünger aller Völker. Wenn du diese Worte liest, vielleicht schleicht sich Zweifel ein. Aber höre, was Jesus davor sagte: \"Mir ist alle Gewalt gegeben.\" Das sagt nicht, dass du alle Antworten haben musst.\n\nEs sagt: Ich habe alle Gewalt, und ich gehe mit dir. Glauben zu teilen erfordert keinen Theologiedoktor. Es erfordert eine echte Geschichte. Vielleicht kämpft deine Freundin bei der Arbeit, und du erzählst, wie Gebet dir geholfen hat.\n\nVielleicht jemand trauert, und deine Ehrlichkeit über deinen eigenen Schmerz öffnet ein Gespräch über Hoffnung. Vielleicht lebst du einfach anders—mit mehr Frieden, mehr Vergebung, mehr Freude—und jemand fragt warum. Deine Stimme zählt. Dein kleines Zeugnis, dein echter Glaube, deine Bereitschaft, zu teilen, was Jesus für dich getan hat—das ändert Leben.",
      "actionStep": "Denke an eine Person, die spirituell offen oder auf der Suche zu sein scheint. Diese Woche führe ein echtes Gespräch mit ihr. Erzwinge keine Theologie—teile einfach eine Weise, wie dein Glaube dir geholfen hat. Höre mehr zu, als du sprichst.",
      "prayer": "Herr Jesus, du hast uns den Missionsauftrag anvertraut, zu allen Völkern zu gehen und im Namen des Vaters, des Sohnes und des Heiligen Geistes zu taufen. Welch wunderbar Ruf! Danke, dass du uns vertraust und uns zu deinen Zeugen machst. Du ebnest den Weg für das Evangelium. Mögen unsere Leben deinen Namen verherrlichen. Amen."
    },
    {
      "day": 3,
      "segment": "evening",
      "reference": {
        "book": "Genesis",
        "chapter": 1,
        "verse": "2",
        "full_reference": "Genesis 1:2"
      },
      "modernVersion": "Lutherbibel 2017",
      "modernText": "Und die Erde war wüst und leer, und Finsternis lag auf der Urflut, und der Geist Gottes schwebte über dem Wasser.",
      "meditation": "Chaos. Gestaltlos. Leer. Finsternis. Dies sind die Anfangsbedingungen—nicht die Endbedingungen von Gottes schöpferischem Werk. Wenn Genesis sich öffnet, ist die Erde 「gestaltlos und leer,」 und Finsternis bedeckt alles. Und in diesem sehr Leeren ist der Geist Gottes präsent, schwebend. Nicht fern.\n\nNicht wartend. Schwebend—präsent, aktiv, absichtsvoll. Dies ist ein tiefes Versprechen für diejenigen von uns, die durch gestaltlose Jahreszeiten gehen. Jahreszeiten, in denen sich nichts fest anfühlt, in denen deine Pläne aufgelöst haben, in denen du die Form deiner Zukunft nicht sehen kannst. Jahreszeiten des Verlusts, des Wartens, des Nicht-Wissens. Der schwebende Geist ist da. Gott ist nicht abwesend in deinem Chaos. Er ist nicht von deiner Leere überwältigt.\n\nEr ist präsent. Er bewegt sich. Das Schweben deutet auf Sanftheit hin—nicht gewaltsame Eindringlichkeit, sondern zärtliche Gegenwart. Wie eine Mutter, die über ihrem Kind schwebt. Wie Hände, die schützend um etwas Kostbares gewickelt sind. In deiner Finsternis, in deinem Gestaltlosen, schwebt Gott. Er arbeitet. Er bewegt sich in Richtung Schöpfung, Ordnung, Leben.",
      "actionStep": "In einem beliebigen Bereich deines Lebens, der sich jetzt gestaltlos anfühlt, halte inne und erkenne an: \"Gott schwebt hier. Er ist präsent. Er arbeitet.\" Laden Sie Seine Gegenwart in Ihr Chaos ein.",
      "prayer": "Herr, danke—auch in der Gestaltlosigkeit und Finsternis schwebt dein Geist, gegenwärtig und aktiv. Das Leben fühlt sich chaotisch, unklar und außer Kontrolle an. Dennoch bewegt sich dein Geist über der Tiefe und bringt Ordnung aus dem Chaos. Danke für deine ständige Fürsorge auch in unserer Verwirrung. Der Geist Gottes über dem Chaos — du rückst nah und hauchst Leben. Gegenwärtig bei jedem neuen Anfang. Amen."
    }
  ],
  "fr": [
    {
      "day": 1,
      "segment": "morning",
      "reference": {
        "book": "John",
        "chapter": 1,
        "verse": "9",
        "full_reference": "John 1:9"
      },
      "modernVersion": "PDV",
      "modernText": "Cette lumière était la véritable lumière, celle qui éclaire tout être humain.",
      "meditation": "Qu'est-ce que cela signifie de vivre dans l'obscurité? Pour certains, c'est le gris de la dépression—ce brouillard où rien ne semble significatif ou plein d'espoir. Pour d'autres, c'est la confusion—chercher un sens, un but, la vérité. Pour certains, l'obscurité est le poids de la perte, de la solitude ou de l'échec. Mais Jean dit qu'il y a une véritable lumière.\n\nPas beaucoup de lumières, chacune illuminant le chemin que vous préférez. Pas la vérité relative, chaque personne trouvant son propre chemin. Une véritable lumière. Jésus. Et Il est venu—dans le monde, pour éclairer 「tous.」 Sans exception.\n\nNon seulement les plus intelligents, les plus vertueux, les plus dignes. Chaque personne née dans ce monde. Cela vous inclut—dans vos moments les plus sombres, dans votre confusion et votre échec. Cette vraie lumière n'est pas lointaine ou inaccessible. Elle est venue au monde. Elle vient à votre obscurité.",
      "actionStep": "Aujourd'hui, si vous êtes dans l'obscurité—même un peu—tournez-vous vers la vraie lumière. Cherchez Jésus dans vos lieux sombres et invitez sa lumière dans votre vie.",
      "prayer": "Seigneur Jésus, tu es la Vraie Lumière qui éclaire tout le monde—sans exception, sans barrière. Ta lumière perce toute obscurité et atteint chaque coin du monde. Merci que cette lumière est accessible à tous, brillant équitablement sur les riches et les pauvres, près et loin. Amen."
    },
    {
      "day": 1,
      "segment": "evening",
      "reference": {
        "book": "John",
        "chapter": 14,
        "verse": "1",
        "full_reference": "John 14:1"
      },
      "modernVersion": "PDV",
      "modernText": "Que votre cœur ne soit pas troublé. Croyez en Dieu, et croyez aussi en moi.",
      "meditation": "Votre cœur se trouble-t-il maintenant? C'est peut-être une rupture. C'est peut-être un emploi perdu. C'est peut-être une mauvaise nouvelle sur votre santé. C'est peut-être juste de l'anxiété nocturne, quand votre esprit se tourne vers tout ce qui pourrait mal tourner. Quelle que soit la raison, vous êtes là. Troublé.\n\nAnxieux. Effrayé. Jésus dit cela à Ses disciples au moment le plus difficile. Ils vont le voir être arrêté. Ils verront qu'il meurt sur une croix. Leur monde est sur le point de s'effondrer. Ils ont toutes les raisons d'avoir peur. Et Jésus les regarde et dit: 「Que votre cœur ne soit pas troublé.」 Non parce que tout ira bien—Il ne promet même pas cela.\n\nMais parce qu'ils peuvent lui faire confiance. \"Croyez en Dieu, et croyez aussi en moi.\" Qu'est-ce que cela signifie? Cela signifie faire confiance au caractère de Dieu—Sa bonté, Son pouvoir, Sa fidélité—et croire que ces mêmes qualités existent en Jésus. Cela signifie que même dans le pire des cas, vous n'êtes pas seul. Il est avec vous. Alors maintenant, dans vos troubles, Jésus vous dit les mêmes paroles. Ne laissez pas votre cœur être troublé. Tournez-vous vers la foi.",
      "actionStep": "Amenez à l'esprit la chose que votre cœur craint le plus. Maintenant, chaque fois que cette peur surgit, dites à haute voix: 「Je ne laisserai pas mon cœur être troublé. Je crois en Dieu, et je crois en Jésus.」",
      "prayer": "Merci, Jésus, pour votre paix—une paix qui dépasse tout entendement. Vous êtes l'antidote à l'anxiété, l'ancre dans toute tempête. Votre paix n'est pas l'absence de problèmes, mais votre présence au milieu d'eux. Aidez-nous à vous faire confiance complètement. Amen."
    },
    {
      "day": 2,
      "segment": "morning",
      "reference": {
        "book": "Jeremiah",
        "chapter": 29,
        "verse": "11",
        "full_reference": "Jeremiah 29:11"
      },
      "modernVersion": "PDV",
      "modernText": "\"Je connais bien les projets que j'ai pour vous, déclare l'Éternel, des projets de paix et non de malheur, pour vous donner un avenir et de l'espérance.\"",
      "meditation": "Quand Jérémie a écrit ces paroles, la nation de Juda se noyait dans le désespoir. Ils avaient été traînés en exil à Babylone, séparés de leur terre, incertains de ce qui les attendait. Beaucoup pensaient: \"Dieu nous a-t-il abandonnés?\n\nEst-ce vraiment notre fin?\"\n\nMais dans l'obscurité la plus profonde, le Seigneur parle à travers le prophète avec un message stupéfiant: \"Je sais.\" Pas \"Je regarde\", pas \"Je sais ce qui se passe\"—mais \"Je connais les projets que j'ai pour vous.\" Dieu parle de Ses pensées envers eux. Cela change tout. Quand vous vous sentez abandonnée, oubliée—Dieu dit: \"Je me souviens de vous. Mes pensées sont pleines de plans pour vous.\" Et ces plans?\n\nIls ne sont pas pour vous faire du mal. Ce ne sont pas des désastres. C'est la paix, la prospérité, la restauration. Sœur, peu importe vos circonstances actuelles, peu importe les erreurs que vous avez commises, peu importe combien de fois vous êtes tombée—les plans de Dieu pour vous n'ont pas changé.",
      "actionStep": "Écrivez dans votre journal ou vos notes téléphone: \"Dieu a des plans de paix pour moi, pas de calamité.\" Chaque fois que le doute s'installe, lisez ces paroles. Si possible, lisez-les chaque matin et chaque soir.",
      "prayer": "Seigneur, merci pour ta promesse que tes plans pour nous sont pour le bien — remplis d'espoir et d'un avenir prospère. Tu tiens nos jours dans tes mains. Tes desseins ne nous blessent pas mais nous établissent dans l'espoir. Tes plans ne faillissent jamais. Tu écris l'histoire avec espoir. Quel bon Père tu es. Amen."
    },
    {
      "day": 2,
      "segment": "evening",
      "reference": {
        "book": "John",
        "chapter": 14,
        "verse": "16",
        "full_reference": "John 14:16"
      },
      "modernVersion": "PDV",
      "modernText": "Et moi, je vais demander au Père, et il vous donnera un autre Défenseur pour être avec vous à jamais.",
      "meditation": "As-tu jamais vécu ce moment où quelqu'un d'important s'en va soudainement et le désespoir t'envahit ? Peut-être c'était un déménagement dans une nouvelle ville, la fin d'une relation, ou la mort de quelqu'un que tu aimais. À ce moment, tout ton sentiment de sécurité a disparu. Les disciples ont aussi ressenti ce désespoir. Quand Jésus leur a dit qu'il s'en allait, la terreur les a saisis.\n\nMais dans cette heure la plus sombre, Jésus a fait une promesse : \"Et moi, je vais demander au Père, et il vous donnera un autre Défenseur pour être avec vous à jamais.\" Note le mot—\"un autre.\" Pas un remplacement, mais une autre présence. Jésus est parti, mais le Saint-Esprit est venu. Ce n'est pas une régression mais une intimité plus profonde—non seulement être avec Jésus, mais avoir l'Esprit de Jésus vivant dans ton cœur. C'est pourquoi la tristesse des disciples s'est finalement transformée en joie. C'est pourquoi ils ont passé de se cacher à un témoignage audacieux.\n\nLe Défenseur ne visite pas occasionnellement; il vit avec toi pour toujours—dans ta minuit la plus solitaire, dans ton moment le plus confus, dans la décision où tu as le plus besoin de guidance. Il est là. Il connaît ton cœur, il comprend tes pensées, il prie même pour toi. Tu n'es vraiment pas seule. Tu ne seras jamais seule.",
      "actionStep": "Aujourd'hui, arrête-toi et demande-toi : Est-ce que je me sens seule en ce moment ? Ai-je besoin de réconfort ? Ai-je besoin de guidance ? Quelle que soit la réponse, tourne-toi vers l'intérieur et invite la présence de l'Esprit : \"Saint-Esprit, merci d'être avec moi à jamais. Je t'invite à ce moment. S'il te plaît, aide-moi, guide-moi, réconforte-moi.\" Assieds-toi dans cette invitation, respire, et sens sa présence douce. Il est là.",
      "prayer": "Jésus, merci d'avoir promis un autre Avocat—le Saint-Esprit—qui sera avec nous à jamais. Nous ne sommes jamais seuls, jamais sans aide. Dans toute obscurité, ton Esprit intercède pour nous, nous guide, nous fortifie. Merci pour cette présence permanente. Tu as promis un Défenseur qui demeure en nous pour toujours. Nous ne sommes jamais seuls. Amen."
    },
    {
      "day": 3,
      "segment": "morning",
      "reference": {
        "book": "Matthew",
        "chapter": 28,
        "verse": "19",
        "full_reference": "Matthew 28:19"
      },
      "modernVersion": "PDV",
      "modernText": "Allez donc, faites de toutes les nations des disciples. Baptisez-les au nom du Père, du Fils et du Saint-Esprit.",
      "meditation": "Va et fais de toutes les nations des disciples. Quand tu lis ces paroles, peut-être que le doute apparaît. Mais écoute ce que Jésus a dit avant: \"Toute autorité m'a été donnée.\" Cela ne dit pas que tu dois avoir toutes les réponses.\n\nCela dit: j'ai toute l'autorité, et je vais avec toi. Partager la foi n'exige pas un doctorat en théologie. Cela exige une vraie histoire. Peut-être que ton amie lutte au travail, et tu lui racontes comment la prière t'a aidée.\n\nPeut-être que quelqu'un est en deuil, et ton honnêteté sur ta propre douleur ouvre une conversation sur l'espoir. Peut-être que tu vis simplement différemment—avec plus de paix, plus de pardon, plus de joie—et quelqu'un demande pourquoi. Ta voix compte. Ton petit témoignage, ta foi authentique, ta volonté de partager ce que Jésus a fait pour toi—cela change des vies.",
      "actionStep": "Pense à une personne qui semble spirituellement ouverte ou en quête. Cette semaine, engage une conversation authentique avec elle. Ne force pas la théologie—partage simplement une façon dont ta foi t'a aidée. Écoute plus que tu ne parles.",
      "prayer": "Seigneur Jésus, tu nous as confié d'aller vers toutes les nations et de baptiser au nom du Père, du Fils et du Saint-Esprit. Quel appel magnifique! Merci de nous avoir confié ta mission et de nous rendre tes témoins. Tu ouvres le chemin pour l'évangile. Que nos vies glorifient ton nom. Amen."
    },
    {
      "day": 3,
      "segment": "evening",
      "reference": {
        "book": "Genesis",
        "chapter": 1,
        "verse": "2",
        "full_reference": "Genesis 1:2"
      },
      "modernVersion": "PDV",
      "modernText": "La terre était en désordre total, les ténèbres couvraient l'abîme, et l'Esprit de Dieu se mouvait sur les eaux.",
      "meditation": "Chaos. Informe. Vide. Obscurité. Ce sont les conditions initiales—pas les finales du travail créatif de Dieu. Quand la Genèse s'ouvre, la terre est 「informe et vide,」 et l'obscurité couvre tout. Et dans ce même vide, l'Esprit de Dieu est présent, planant. Pas distante.\n\nPas attendant. Planant—présent, actif, intentionnel. C'est une promesse profonde pour ceux d'entre nous qui traversons des saisons informes. Des saisons où rien ne semble solide, où vos plans se sont dissous, où vous ne pouvez pas voir la forme de votre avenir. Des saisons de perte, d'attente, de ne pas savoir. L'Esprit planant est là. Dieu n'est pas absent dans votre chaos. Il n'est pas accablé par votre vide.\n\nIl est présent. Il se meut. Le survol suggère la douceur—pas une intrusion violente mais une présence tendre. Comme une mère planant sur son enfant. Comme des mains creusées de manière protectrice autour de quelque chose de précieux. Dans votre obscurité, dans votre informe, Dieu plane. Il travaille. Il se meut vers la création, vers l'ordre, vers la vie.",
      "actionStep": "Dans n'importe quel domaine de votre vie qui semble informe maintenant, faites une pause et reconnaissez: \"Dieu plane ici. Il est présent. Il travaille.\" Invitez Sa présence à votre chaos.",
      "prayer": "Seigneur, merci—même dans l'informe et l'obscurité, ton Esprit plane, présent et actif. La vie semble chaotique, peu claire, au-delà de notre contrôle. Pourtant, ton Esprit se meut sur les profondeurs, apportant l'ordre du chaos. Merci pour ton soin constant même dans notre confusion. L'Esprit de Dieu sur le chaos — tu t'approches et donnes la vie. Présent à chaque nouveau commencement. Amen."
    }
  ],
  "es": [
    {
      "day": 1,
      "segment": "morning",
      "reference": {
        "book": "John",
        "chapter": 1,
        "verse": "9",
        "full_reference": "John 1:9"
      },
      "modernVersion": "NVI",
      "modernText": "Esa luz verdadera que ilumina a todos viene al mundo.",
      "meditation": "¿Qué significa vivir en la oscuridad? Para algunos, es la depresión—esa niebla donde nada parece significativo o esperanzador. Para otros, es la confusión—buscando significado, propósito, verdad. Para algunos, la oscuridad es el peso de la pérdida, la soledad o el fracaso. Pero Juan dice que hay una verdadera luz. No muchas luces, cada una iluminando el camino que prefieres.\n\nNo verdad relativa, cada persona encontrando su propio camino. Una verdadera luz. Jesús. Y vino—al mundo, para iluminar a 「todos.」 Sin excepción. No solo los más inteligentes, los más virtuosos, los más dignos. Cada persona nacida en este mundo. Esto te incluye a ti—en tus momentos más oscuros, en tu confusión y fracaso.\n\nEsta verdadera luz no está distante o inalcanzable. Vino al mundo. Viene a tu oscuridad. La luz disipa la oscuridad. No por la fuerza o la lucha, sino simplemente por existir. No tienes que ganarte esta luz. Simplemente te vuelves hacia ella.",
      "actionStep": "Hoy, si estás en la oscuridad—aunque sea un poco—gírate hacia la verdadera luz. Busca a Jesús en tus lugares oscuros e invita su luz a tu vida.",
      "prayer": "Señor Jesús, eres la Verdadera Luz que ilumina a todo el mundo—sin excepción, sin barrera. Tu luz rompe toda oscuridad y llega a cada rincón del mundo. Gracias porque esta luz está disponible para todos, brillando igualmente sobre ricos y pobres, cercanos y lejanos. Amén."
    },
    {
      "day": 1,
      "segment": "evening",
      "reference": {
        "book": "John",
        "chapter": 14,
        "verse": "1",
        "full_reference": "John 14:1"
      },
      "modernVersion": "NVI",
      "modernText": "No dejen que se turbe su corazón. Crean en Dios, y crean también en mí.",
      "meditation": "¿Se turba tu corazón ahora? Tal vez sea un rompimiento. Tal vez sea un trabajo perdido. Tal vez sea una mala noticia sobre tu salud. Tal vez sea solo ansiedad nocturna, cuando tu mente se vuelve a todo lo que podría salir mal. Sea cual sea la razón, estás aquí. Perturbado. Ansioso.\n\nAsustado. Jesús dice esto a Sus discípulos en el momento más difícil. Están a punto de verlo ser arrestado. Verán que muere en una cruz. Su mundo está a punto de colapsar. Tienen todas las razones para tener miedo. Y Jesús los mira y dice: 「No se turbe su corazón.」 No porque todo estará bien—ni siquiera lo promete. Sino porque pueden confiar en Él.\n\n\"Crean en Dios, y crean también en mí.\" ¿Qué significa eso? Significa confiar en el carácter de Dios—Su bondad, Su poder, Su fidelidad—y creer que esas mismas cualidades existen en Jesús. Significa que incluso en el peor de los casos, no estás solo. Él está contigo. Así que ahora, en tus problemas, Jesús te dice las mismas palabras. No dejes que tu corazón se turbe. Gírate hacia la fe. Gírate hacia Jesús.",
      "actionStep": "Trae a tu mente la cosa que más teme tu corazón. Ahora, cada vez que surja ese miedo, dilo en voz alta: 「No dejaré que mi corazón se turbe. Creo en Dios, y creo en Jesús.」",
      "prayer": "Gracias, Jesús, por tu paz—una paz que sobrepasa todo entendimiento. Eres el antídoto para la ansiedad, el ancla en toda tormenta. Tu paz no es la ausencia de problemas, sino tu presencia en medio de ellos. Ayúdanos a confiar completamente en ti. Amén."
    },
    {
      "day": 2,
      "segment": "morning",
      "reference": {
        "book": "Jeremiah",
        "chapter": 29,
        "verse": "11",
        "full_reference": "Jeremiah 29:11"
      },
      "modernVersion": "NVI",
      "modernText": "\"Porque sé los planes que tengo para ustedes —afirma el Señor—, planes de bienestar y no de calamidad, a fin de darles un futuro y una esperanza.\"",
      "meditation": "Cuando Jeremías escribió estas palabras, la nación de Judá se estaba ahogando en la desesperación. Habían sido arrastrados al exilio en Babilonia, separados de su tierra, inciertos sobre lo que les esperaba. Muchos pensaban: \"¿Nos ha abandonado Dios? ¿Es este realmente nuestro fin?\"\n\nPero en la más profunda oscuridad, el Señor habla a través del profeta con un mensaje asombroso: \"Yo sé.\" No \"Yo observo\", no \"Yo sé qué está sucediendo\"—sino \"Yo sé los planes que tengo para ustedes.\" Dios habla sobre Sus pensamientos hacia ellos, Sus propósitos.\n\nEsto lo cambia todo. Cuando te sientes abandonada, olvidada—Dios dice: \"Te recuerdo. Mis pensamientos están llenos de planes para ti.\" ¿Y estos planes? No son para dañarte. No son desastres.\n\nSon paz, bienestar, restauración. Son un futuro. Hermana, sin importar tus circunstancias actuales, sin importar qué errores hayas cometido, sin importar cuántas veces hayas caído—los planes de Dios para ti no han cambiado. No te está observando fallar y lamentando haberte creado. Sus ojos están fijos en tu futuro.",
      "actionStep": "Escribe en tu diario o notas del teléfono: \"Dios tiene planes de paz para mí, no de calamidad.\" Cada vez que la duda se cuele, lee esas palabras. Si es posible, léelas cada mañana y cada noche.",
      "prayer": "Señor, gracias por tu promesa de que tus planes para nosotros son para bien — llenos de esperanza y un futuro próspero. Sostienes nuestros días en tus manos. Tus propósitos no son para dañarnos sino para establecernos en esperanza. Tus planes nunca fallan. Escribes la historia con esperanza. Qué buen Padre eres. Amén."
    },
    {
      "day": 2,
      "segment": "evening",
      "reference": {
        "book": "John",
        "chapter": 14,
        "verse": "16",
        "full_reference": "John 14:16"
      },
      "modernVersion": "NVI",
      "modernText": "Y yo le pediré al Padre, y él les dará otro Consolador para que los acompañe siempre.",
      "meditation": "¿Has experimentado alguna vez ese momento cuando alguien importante de repente se va y la desesperación te inunda? Quizás fue una mudanza a una nueva ciudad, el final de una relación, o la muerte de alguien que amabas. En ese momento, toda tu sensación de seguridad desapareció. Los discípulos también sintieron esta desesperación. Cuando Jesús les dijo que se iba, el terror los apresó.\n\nPero en esa hora más oscura, Jesús hizo una promesa: \"Y yo le pediré al Padre, y él les dará otro Consolador para que los acompañe siempre.\" Nota la palabra—\"otro.\" No una sustitución, sino otra presencia. Jesús se fue, pero el Espíritu Santo vino. Esto no es una rebaja sino una intimidad más profunda—no solo estar con Jesús, sino tener el Espíritu de Jesús viviendo dentro de tu corazón. Esto es por qué la tristeza de los discípulos finalmente se transformó en alegría. Esto es por qué se movieron de esconderse a un testimonio audaz.\n\nEl Consolador no visita ocasionalmente; vive contigo para siempre—en tu medianoche más solitaria, en tu momento más confuso, en la decisión donde más necesitas orientación. Él está allí. Conoce tu corazón, entiende tus pensamientos, incluso ora por ti. Realmente no estás sola. Nunca estarás sola.",
      "actionStep": "Hoy, detente y pregúntate: ¿Me siento solo en este momento? ¿Necesito consuelo? ¿Necesito orientación? Sea cual sea la respuesta, gírate hacia adentro e invita la presencia del Espíritu: \"Espíritu Santo, gracias por estar conmigo siempre. Te invito a este momento. Por favor, ayúdame, guíame, consuélame.\" Siéntate en esa invitación, respira, y siente su presencia suave. Él está allí.",
      "prayer": "Jesús, gracias por prometer otro Abogado—el Espíritu Santo—que estará con nosotros para siempre. Nunca estamos solos, nunca sin ayuda. En toda oscuridad, tu Espíritu intercede por nosotros, nos guía, nos fortalece. Gracias por esta presencia permanente. Prometiste un Defensor que mora en nosotros para siempre. Nunca estamos solos. Amén."
    },
    {
      "day": 3,
      "segment": "morning",
      "reference": {
        "book": "Matthew",
        "chapter": 28,
        "verse": "19",
        "full_reference": "Matthew 28:19"
      },
      "modernVersion": "NVI",
      "modernText": "Por lo tanto, vayan y hagan discípulos de todas las naciones, bautizándolos en el nombre del Padre y del Hijo y del Espíritu Santo,",
      "meditation": "Ve y haz discípulos de todas las naciones. Cuando lees esas palabras, tal vez la duda se cuela. Pero escucha lo que Jesús dijo antes: \"Toda potestad me es dada.\" Esto no dice que necesites todas las respuestas.\n\nDice: tengo toda la autoridad, y voy contigo. Compartir fe no requiere un doctorado en teología. Requiere una historia real. Tal vez tu amiga está luchando en el trabajo, y tú le cuentas cómo la oración te ayudó.\n\nTal vez alguien está de luto, y tu honestidad sobre tu propio dolor abre una conversación sobre esperanza. Tal vez simplemente estás viviendo diferente—con más paz, más perdón, más alegría—y alguien pregunta por qué. Tu voz importa. Tu pequeño testimonio, tu fe genuina, tu disposición a compartir lo que Jesús ha hecho por ti—eso cambia vidas.",
      "actionStep": "Piensa en una persona que parece espiritualmente abierta. Esta semana, inicia una conversación genuina con ella. No fuerces la teología—solo comparte una forma en que tu fe te ha ayudado. Escucha más de lo que hablas.",
      "prayer": "Señor Jesús, nos encomendaste ir a todas las naciones y bautizar en el nombre del Padre, del Hijo y del Espíritu Santo. ¡Qué llamado extraordinario! Gracias por confiarnos tu misión y hacernos tus testigos ante el mundo. Abres el camino para el evangelio. Que nuestras vidas glorifiquen tu nombre. Amén."
    },
    {
      "day": 3,
      "segment": "evening",
      "reference": {
        "book": "Genesis",
        "chapter": 1,
        "verse": "2",
        "full_reference": "Genesis 1:2"
      },
      "modernVersion": "NVI",
      "modernText": "La tierra era un caos total, las tinieblas cubrían el abismo, y el Espíritu de Dios se movía sobre la superficie de las aguas.",
      "meditation": "Caos. Informe. Vacío. Oscuridad. Estas son las condiciones iniciales—no las finales del trabajo creativo de Dios. Cuando Génesis abre, la tierra es 「informe y vacía,」 y la oscuridad cubre todo. Y en ese mismo vacío, el Espíritu de Dios está presente, merodeando. No distante.\n\nNo esperando. Merodeando—presente, activo, intencional. Esta es una promesa profunda para aquellos de nosotros que pasamos por temporadas informes. Temporadas donde nada se siente sólido, donde sus planes se han disuelto, donde no puede ver la forma de su futuro. Temporadas de pérdida, de espera, de no saber. El Espíritu merodeador está allí. Dios no está ausente en su caos. No está abrumado por su vacío.\n\nEstá presente. Se está moviendo. El merodeo sugiere gentileza—no intrusión violenta sino presencia tierna. Como una madre merodeando sobre su hijo. Como manos ahuecadas protectoramente alrededor de algo precioso. En su oscuridad, en su informe, Dios está merodeando. Está trabajando. Se está moviendo hacia la creación, hacia el orden, hacia la vida.",
      "actionStep": "En cualquier área de su vida que se sienta informe ahora, haga una pausa y reconozca: \"Dios está merodeando aquí. Está presente. Está trabajando.\" Invite Su presencia a su caos.",
      "prayer": "Señor, gracias—incluso en la informalidad y la oscuridad, tu Espíritu se cierne, presente y activo. La vida se siente caótica, poco clara, más allá de nuestro control. Sin embargo, tu Espíritu se mueve sobre lo profundo, trayendo orden del caos. Gracias por tu cuidado constante incluso en nuestra confusión. El Espíritu de Dios sobre el caos — acercas y das vida. Presente en cada nuevo comienzo. Amén."
    }
  ],
  "pt": [
    {
      "day": 1,
      "segment": "morning",
      "reference": {
        "book": "John",
        "chapter": 1,
        "verse": "9",
        "full_reference": "John 1:9"
      },
      "modernVersion": "NVI-PT",
      "modernText": "A verdadeira luz que ilumina todos vinha chegando ao mundo.",
      "meditation": "O que significa viver na escuridão? Para alguns, é o cinzento da depressão—aquele nevoeiro onde nada parece significativo ou esperançoso. Para outros, é a confusão—procurando significado, propósito, verdade. Para alguns, a escuridão é o peso da perda, da solidão ou do fracasso. Mas João diz que há uma verdadeira luz. Não muitas luzes, cada uma iluminando o caminho que você prefere.\n\nNão verdade relativa, cada pessoa encontrando seu próprio caminho. Uma verdadeira luz. Jesus. E Ele veio—ao mundo, para iluminar 「todos.」 Sem exceção. Não apenas os mais inteligentes, os mais virtuosos, os mais dignos. Cada pessoa nascida neste mundo. Isso o inclui a você—em seus momentos mais escuros, em sua confusão e fracasso.\n\nEsta verdadeira luz não está distante ou intocável. Vem ao mundo. Vem à sua escuridão. A luz dissipa a escuridão. Não através da força ou da luta, mas simplesmente por existir. Você não precisa ganhar esta luz. Você simplesmente se vira para ela.",
      "actionStep": "Hoje, se você está na escuridão—ainda que um pouco—vire-se para a verdadeira luz. Procure Jesus em seus lugares escuros e convide sua luz para sua vida.",
      "prayer": "Senhor Jesus, tu és a Verdadeira Luz que ilumina a todos—sem exceção, sem barreira. Tua luz rompe toda escuridão e chega a cada canto do mundo. Obrigado porque esta luz está disponível para todos, brilhando igualmente sobre ricos e pobres, perto e longe. Amém."
    },
    {
      "day": 1,
      "segment": "evening",
      "reference": {
        "book": "John",
        "chapter": 14,
        "verse": "1",
        "full_reference": "John 14:1"
      },
      "modernVersion": "NVI-PT",
      "modernText": "Não deixem que seus corações se perturbem. Creiam em Deus; creiam também em mim.",
      "meditation": "Seu coração se turba agora? Talvez seja um rompimento. Talvez seja um emprego perdido. Talvez seja uma má notícia sobre sua saúde. Talvez seja apenas ansiedade noturna, quando sua mente se volta para tudo que poderia dar errado. Seja qual for a razão, você está aqui. Perturbado. Ansioso.\n\nAssustado. Jesus diz isto a Seus discípulos no momento mais difícil. Eles estão prestes a vê-lo ser preso. Verão que ele morre na cruz. Seu mundo está prestes a desabar. Eles têm todas as razões para ter medo. E Jesus os olha e diz: 「Não deixem que seus corações se perturbem.」 Não porque tudo ficará bem—nem promete isso. Mas porque podem confiar nEle.\n\n\"Creiam em Deus; creiam também em mim.\" O que isso significa? Significa confiar no caráter de Deus—Sua bondade, Seu poder, Sua fidelidade—e acreditar que essas mesmas qualidades existem em Jesus. Significa que mesmo no pior caso, você não está sozinho. Ele está com você. Então agora, em suas perturbações, Jesus diz as mesmas palavras para você. Não deixe que seu coração se perturbe. Vire-se para a fé. Vire-se para Jesus.",
      "actionStep": "Traga à mente a coisa que seu coração mais teme. Agora, toda vez que esse medo surgir, diga em voz alta: 「Não deixarei que meu coração se perturbe. Acredito em Deus, e acredito em Jesus.」",
      "prayer": "Obrigado, Jesus, por sua paz—uma paz que transcende todo entendimento. Você é o antídoto para a ansiedade, a âncora em toda tempestade. Sua paz não é a ausência de problemas, mas sua presença em meio a eles. Ajude-nos a confiar completamente em você. Amém."
    },
    {
      "day": 2,
      "segment": "morning",
      "reference": {
        "book": "Jeremiah",
        "chapter": 29,
        "verse": "11",
        "full_reference": "Jeremiah 29:11"
      },
      "modernVersion": "NVI-PT",
      "modernText": "\"Porque eu bem sei os planos que tenho para vocês\", declara o Senhor, \"planos de bem-estar e não de calamidade, para lhes dar um futuro cheio de esperança.\"",
      "meditation": "Quando Jeremias escreveu essas palavras, a nação de Judá estava se afogando no desespero. Tinham sido arrastrados para o exílio na Babilônia, separados de sua terra, incertos sobre o que lay ahead. Muitos pensavam: \"Deus nos abandonou? Este é realmente nosso fim?\"\n\nMas na mais profunda escuridão, o Senhor fala através do profeta com uma mensagem espantosa: \"Eu sei.\" Não \"Eu observo\", não \"Eu sei o que está acontecendo\"—mas \"Eu sei os planos que tenho para vocês.\" Deus fala sobre Seus pensamentos em relação a eles.\n\nIsso muda tudo. Quando você se sente abandonada, esquecida—Deus diz: \"Eu me lembro de você. Meus pensamentos estão cheios de planos para você.\" E esses planos? Não são para machucá-lo.\n\nNão são desastres. Eles são paz, bem-estar, restauração. Irmã, não importa suas circunstâncias atuais, não importa quais erros você cometeu, não importa quantas vezes você caiu—os planos de Deus para você não mudaram. Seus olhos estão fixos em seu futuro.",
      "actionStep": "Escreva em seu diário ou notas do telefone: \"Deus tem planos de paz para mim, não de calamidade.\" Sempre que a dúvida surgir, leia essas palavras. Se possível, leia-as cada manhã e cada noite.",
      "prayer": "Senhor, obrigado por sua promessa de que seus planos para nós são para bem — cheios de esperança e um futuro próspero. Você sustenta nossos dias em suas mãos. Seus propósitos não são para nos prejudicar mas para nos estabelecer em esperança. Os teus planos nunca falham. Escreves a história com esperança. Que bom Pai és. Amém."
    },
    {
      "day": 2,
      "segment": "evening",
      "reference": {
        "book": "John",
        "chapter": 14,
        "verse": "16",
        "full_reference": "John 14:16"
      },
      "modernVersion": "NVI-PT",
      "modernText": "Vou pedir ao Pai, e ele lhes dará outro Consolador para estar com vocês para sempre—",
      "meditation": "Você já experimentou aquele momento em que alguém importante de repente se vai e a desesperação a inunda? Talvez tenha sido uma mudança para uma nova cidade, o fim de um relacionamento, ou a morte de alguém que você amava. Naquele momento, todo o seu sentimento de segurança desapareceu. Os discípulos também sentiram essa desesperação. Quando Jesus lhes disse que estava indo embora, o terror os apoderou.\n\nMas naquela hora mais escura, Jesus fez uma promessa: \"Vou pedir ao Pai, e ele lhes dará outro Consolador para estar com vocês para sempre.\" Note a palavra—\"outro.\" Não uma substituição, mas outra presença. Jesus se foi, mas o Espírito Santo veio. Isso não é um retrocesso, mas uma intimidade mais profunda—não apenas estar com Jesus, mas ter o Espírito de Jesus vivendo dentro do seu coração. É por isso que a tristeza dos discípulos finalmente se transformou em alegria. É por isso que se moveram de se esconder para um testemunho ousado.\n\nO Consolador não visita ocasionalmente; ele vive com você para sempre—em sua meia-noite mais solitária, em seu momento mais confuso, na decisão onde você mais precisa de orientação. Ele está lá. Ele conhece seu coração, ele entende seus pensamentos, ele até ora por você. Você realmente não está sozinha. Você nunca estará sozinha.",
      "actionStep": "Hoje, pare e perguntea si mesma: Estou me sentindo sozinha agora? Preciso de conforto? Preciso de orientação? Qualquer que seja a resposta, vire-se para dentro e convide a presença do Espírito: \"Espírito Santo, obrigada por estar comigo para sempre. Convido você para este momento. Por favor, ajude-me, guie-me, conforte-me.\" Sente-se nesse convite, respire, e sinta sua presença suave. Ele está lá.",
      "prayer": "Jesus, obrigado por prometer outro Advogado—o Espírito Santo—que estará conosco para sempre. Nunca estamos sozinhos, nunca sem ajuda. Em toda escuridão, teu Espírito intercede por nós, nos guia, nos fortalece. Obrigado por esta presença permanente. Prometeste um Advogado que mora em nós para sempre. Nunca estamos sós. Amém."
    },
    {
      "day": 3,
      "segment": "morning",
      "reference": {
        "book": "Matthew",
        "chapter": 28,
        "verse": "19",
        "full_reference": "Matthew 28:19"
      },
      "modernVersion": "NVI-PT",
      "modernText": "Portanto, vão e façam discípulos de todas as nações, batizando-os em nome do Pai e do Filho e do Espírito Santo,",
      "meditation": "Vá e faça discípulos de todas as nações. Quando você lê essas palavras, talvez a dúvida apareça. Mas ouça o que Jesus disse antes: \"Toda a autoridade me foi dada.\" Isso não diz que você precisa de todas as respostas.\n\nDiz: tenho toda a autoridade, e vou com você. Compartilhar fé não exige um doutorado em teologia. Exige uma história real. Talvez sua amiga esteja lutando no trabalho, e você conta como a oração a ajudou.\n\nTalvez alguém esteja de luto, e sua honestidade sobre sua própria dor abre uma conversa sobre esperança. Talvez você esteja simplesmente vivendo diferente—com mais paz, mais perdão, mais alegria—e alguém pergunta por quê. Sua voz importa. Seu pequeno testemunho, sua fé genuína, sua disposição em compartilhar o que Jesus fez por você—isso muda vidas.",
      "actionStep": "Pense em uma pessoa que parece espiritualmente aberta ou buscando. Esta semana, inicie uma conversa genuína com ela. Não force teologia—apenas compartilhe uma forma como sua fé a ajudou. Ouça mais do que fale.",
      "prayer": "Senhor Jesus, você nos confiou o Grande Mandato para ir a todas as nações e batizar em nome do Pai, do Filho e do Espírito Santo. Que chamado extraordinário! Obrigado por confiar em nós e fazer-nos teus testemunhas. Abres o caminho para o evangelho. Que nossas vidas glorifiquem o teu nome. Amém."
    },
    {
      "day": 3,
      "segment": "evening",
      "reference": {
        "book": "Genesis",
        "chapter": 1,
        "verse": "2",
        "full_reference": "Genesis 1:2"
      },
      "modernVersion": "NVI-PT",
      "modernText": "A terra era um caos total, as trevas cobriam o abismo, e o Espírito de Deus se movia sobre as águas.",
      "meditation": "Caos. Informe. Vazio. Escuridão. Estas são as condições iniciais—não as finais do trabalho criativo de Deus. Quando Gênesis abre, a terra é 「informe e vazia,」 e a escuridão cobre tudo. E naquele mesmo vazio, o Espírito de Deus está presente, pairando. Não distante.\n\nNão esperando. Pairando—presente, ativo, intencional. Esta é uma promessa profunda para aqueles de nós que passamos por estações informes. Estações onde nada se sente sólido, onde seus planos se dissolveram, onde você não consegue ver a forma de seu futuro. Estações de perda, de espera, de não saber. O Espírito pairando está lá. Deus não está ausente em seu caos. Ele não está sobrecarregado por seu vazio.\n\nEle está presente. Ele está se movendo. O pairar sugere gentileza—não intrusão violenta, mas presença morna. Como uma mãe pairando sobre seu filho. Como mãos em concha protetoramente ao redor de algo precioso. Em sua escuridão, em seu informe, Deus está pairando. Ele está trabalhando. Ele está se movendo em direção à criação, à ordem, à vida.",
      "actionStep": "Em qualquer área de sua vida que se sinta informe agora, faça uma pausa e reconheça: \"Deus está pairando aqui. Ele está presente. Ele está trabalhando.\" Convide Sua presença ao seu caos.",
      "prayer": "Senhor, obrigado—mesmo na informalidade e na escuridão, teu Espírito paira, presente e ativo. A vida parece caótica, pouco clara, além do nosso controle. No entanto, teu Espírito se move sobre o abismo, trazendo ordem do caos. Obrigado por teu cuidado constante mesmo em nossa confusão. O Espírito de Deus sobre o caos — aproximas e dás vida. Presente em cada novo começo. Amém."
    }
  ]
} as const;

export const BUNDLED_COVERAGE_DAYS = 3;
