// AUTO-GENERATED by scripts/gen_dailyverse_audio_manifest.mjs — do not edit by hand.
//
// Maps each verseId (m_001 / e_001) to the four exact mp3 filenames of its
// narration steps. The middle slug in each filename is unpredictable
// (sometimes the verse ref, sometimes a topic), so the app can't build the
// names itself — it reads this baked-in map. Bundled (not CDN-fetched)
// because it's tiny + static; only the audio bytes are pulled on demand.
//
// Regenerate after re-recording / re-uploading audio:
//   node scripts/gen_dailyverse_audio_manifest.mjs <local-audio-en-folder>
//
// Until this is populated (verses = {}), the listen button stays disabled.
import type { DailyVerseAudioManifest } from './dailyVerseAudioCdn';

export const DAILY_VERSE_AUDIO_MANIFEST: DailyVerseAudioManifest = {
  version: 1,
  base_url: 'https://audio.everlandapps.com/dailyverse_4steps_audio_7languages/en',
  step_order: ['scripture', 'reflection', 'simple-step', 'prayer'],
  verses: {},
};
