// Daily-verse "listen / 导读" narration audio. Google-TTS reads of the
// four prayer-flow steps (scripture → reflection → simple-step → prayer)
// for each of the 120 verses. Served PUBLICLY from the same R2 bucket as
// the Bible audio (audio.everlandapps.com → herbible-audio-7languages),
// under `dailyverse_4steps_audio/`. No gating — it's free narration of
// already-free content, same posture as the bg music + Bible audio.
//
// **English only for now.** TTS was generated for `en`; the listen button
// is hidden for other UI languages until those are recorded.
//
// Filenames carry an unpredictable middle slug, so the app can't build
// them directly — it fetches a manifest that maps each verseId to its
// four exact filenames. Manifest is generated by
// scripts/gen_dailyverse_audio_manifest.mjs and uploaded next to the audio.

export const DAILY_VERSE_AUDIO_BASE =
  'https://audio.everlandapps.com/dailyverse_4steps_audio';

export const DAILY_VERSE_AUDIO_MANIFEST_URL =
  `${DAILY_VERSE_AUDIO_BASE}/manifest.json`;

// The only language with recorded narration today. Gate the listen button
// on this so non-English readers don't get an English-only control.
export const DAILY_VERSE_AUDIO_LANG = 'en';

// Step keys in PRAYER-FLOW PAGE ORDER (page 0..3). Mirrors PrayerFlow's
// SECTIONS = ['verse','meditation','action','prayer'] one-to-one:
//   page 0 verse      → scripture
//   page 1 meditation → reflection
//   page 2 action     → simple-step
//   page 3 prayer     → prayer
export const DAILY_VERSE_AUDIO_STEPS = ['scripture', 'reflection', 'simple-step', 'prayer'] as const;
export type DailyVerseAudioStep = typeof DAILY_VERSE_AUDIO_STEPS[number];

export interface DailyVerseAudioManifest {
  version: number;
  base_url: string;
  step_order: string[];
  // verseId (m_001 / e_001) → { scripture, reflection, simple-step, prayer }
  verses: Record<string, Partial<Record<DailyVerseAudioStep, string>>>;
}

export function dailyVerseAudioUrl(filename: string): string {
  return `${DAILY_VERSE_AUDIO_BASE}/${filename}`;
}
