// AUTO-GENERATED by scripts/gen_dailyverse_audio_manifest.mjs — do not edit by hand.
//
// Maps each verseId (m_001 / e_001) to the four exact mp3 filenames of its
// narration steps. Bundled (not CDN-fetched) — tiny + static; only the
// audio bytes are pulled on demand.
//
// Regenerate after re-recording / re-uploading audio:
//   node scripts/gen_dailyverse_audio_manifest.mjs <local-audio-en-folder>
import type { DailyVerseAudioManifest } from './dailyVerseAudioCdn';

export const DAILY_VERSE_AUDIO_MANIFEST: DailyVerseAudioManifest = {
  "version": 1,
  "base_url": "https://audio.everlandapps.com/dailyverse_4steps_audio_7languages/en",
  "step_order": [
    "scripture",
    "reflection",
    "simple-step",
    "prayer"
  ],
  "verses": {
    "e_001": {
      "scripture": "e_001_evening_john-14-1_01_scripture.mp3",
      "reflection": "e_001_evening_john-14-1_02_reflection.mp3",
      "simple-step": "e_001_evening_john-14-1_03_simple-step.mp3",
      "prayer": "e_001_evening_john-14-1_04_prayer.mp3"
    },
    "e_002": {
      "scripture": "e_002_evening_promises-and-comfort_01_scripture.mp3",
      "reflection": "e_002_evening_promises-and-comfort_02_reflection.mp3",
      "simple-step": "e_002_evening_promises-and-comfort_03_simple-step.mp3",
      "prayer": "e_002_evening_promises-and-comfort_04_prayer.mp3"
    },
    "e_003": {
      "scripture": "e_003_evening_promises-and-comfort_01_scripture.mp3",
      "reflection": "e_003_evening_promises-and-comfort_02_reflection.mp3",
      "simple-step": "e_003_evening_promises-and-comfort_03_simple-step.mp3",
      "prayer": "e_003_evening_promises-and-comfort_04_prayer.mp3"
    },
    "e_004": {
      "scripture": "e_004_evening_core-faith-and-redemption_01_scripture.mp3",
      "reflection": "e_004_evening_core-faith-and-redemption_02_reflection.mp3",
      "simple-step": "e_004_evening_core-faith-and-redemption_03_simple-step.mp3",
      "prayer": "e_004_evening_core-faith-and-redemption_04_prayer.mp3"
    },
    "e_005": {
      "scripture": "e_005_evening_john-1-14_01_scripture.mp3",
      "reflection": "e_005_evening_john-1-14_02_reflection.mp3",
      "simple-step": "e_005_evening_john-1-14_03_simple-step.mp3",
      "prayer": "e_005_evening_john-1-14_04_prayer.mp3"
    },
    "e_006": {
      "scripture": "e_006_evening_promises-and-comfort_01_scripture.mp3",
      "reflection": "e_006_evening_promises-and-comfort_02_reflection.mp3",
      "simple-step": "e_006_evening_promises-and-comfort_03_simple-step.mp3",
      "prayer": "e_006_evening_promises-and-comfort_04_prayer.mp3"
    },
    "e_007": {
      "scripture": "e_007_evening_romans-3-23_01_scripture.mp3",
      "reflection": "e_007_evening_romans-3-23_02_reflection.mp3",
      "simple-step": "e_007_evening_romans-3-23_03_simple-step.mp3",
      "prayer": "e_007_evening_romans-3-23_04_prayer.mp3"
    },
    "e_008": {
      "scripture": "e_008_evening_ephesians-2-8_01_scripture.mp3",
      "reflection": "e_008_evening_ephesians-2-8_02_reflection.mp3",
      "simple-step": "e_008_evening_ephesians-2-8_03_simple-step.mp3",
      "prayer": "e_008_evening_ephesians-2-8_04_prayer.mp3"
    },
    "e_009": {
      "scripture": "e_009_evening_romans-5-8_01_scripture.mp3",
      "reflection": "e_009_evening_romans-5-8_02_reflection.mp3",
      "simple-step": "e_009_evening_romans-5-8_03_simple-step.mp3",
      "prayer": "e_009_evening_romans-5-8_04_prayer.mp3"
    },
    "e_010": {
      "scripture": "e_010_evening_encouragement-and-action_01_scripture.mp3",
      "reflection": "e_010_evening_encouragement-and-action_02_reflection.mp3",
      "simple-step": "e_010_evening_encouragement-and-action_03_simple-step.mp3",
      "prayer": "e_010_evening_encouragement-and-action_04_prayer.mp3"
    },
    "e_011": {
      "scripture": "e_011_evening_promise-and-comfort_01_scripture.mp3",
      "reflection": "e_011_evening_promise-and-comfort_02_reflection.mp3",
      "simple-step": "e_011_evening_promise-and-comfort_03_simple-step.mp3",
      "prayer": "e_011_evening_promise-and-comfort_04_prayer.mp3"
    },
    "e_012": {
      "scripture": "e_012_evening_john-10-10_01_scripture.mp3",
      "reflection": "e_012_evening_john-10-10_02_reflection.mp3",
      "simple-step": "e_012_evening_john-10-10_03_simple-step.mp3",
      "prayer": "e_012_evening_john-10-10_04_prayer.mp3"
    },
    "e_013": {
      "scripture": "e_013_evening_core-doctrine-and-salvation_01_scripture.mp3",
      "reflection": "e_013_evening_core-doctrine-and-salvation_02_reflection.mp3",
      "simple-step": "e_013_evening_core-doctrine-and-salvation_03_simple-step.mp3",
      "prayer": "e_013_evening_core-doctrine-and-salvation_04_prayer.mp3"
    },
    "e_014": {
      "scripture": "e_014_evening_core-faith-and-redemption_01_scripture.mp3",
      "reflection": "e_014_evening_core-faith-and-redemption_02_reflection.mp3",
      "simple-step": "e_014_evening_core-faith-and-redemption_03_simple-step.mp3",
      "prayer": "e_014_evening_core-faith-and-redemption_04_prayer.mp3"
    },
    "e_015": {
      "scripture": "e_015_evening_promises-and-comfort_01_scripture.mp3",
      "reflection": "e_015_evening_promises-and-comfort_02_reflection.mp3",
      "simple-step": "e_015_evening_promises-and-comfort_03_simple-step.mp3",
      "prayer": "e_015_evening_promises-and-comfort_04_prayer.mp3"
    },
    "e_016": {
      "scripture": "e_016_evening_matthew-28-18_01_scripture.mp3",
      "reflection": "e_016_evening_matthew-28-18_02_reflection.mp3",
      "simple-step": "e_016_evening_matthew-28-18_03_simple-step.mp3",
      "prayer": "e_016_evening_matthew-28-18_04_prayer.mp3"
    },
    "e_017": {
      "scripture": "e_017_evening_john-3-16_01_scripture.mp3",
      "reflection": "e_017_evening_john-3-16_02_reflection.mp3",
      "simple-step": "e_017_evening_john-3-16_03_simple-step.mp3",
      "prayer": "e_017_evening_john-3-16_04_prayer.mp3"
    },
    "e_018": {
      "scripture": "e_018_evening_john-4-1_01_scripture.mp3",
      "reflection": "e_018_evening_john-4-1_02_reflection.mp3",
      "simple-step": "e_018_evening_john-4-1_03_simple-step.mp3",
      "prayer": "e_018_evening_john-4-1_04_prayer.mp3"
    },
    "e_019": {
      "scripture": "e_019_evening_promises-and-comfort_01_scripture.mp3",
      "reflection": "e_019_evening_promises-and-comfort_02_reflection.mp3",
      "simple-step": "e_019_evening_promises-and-comfort_03_simple-step.mp3",
      "prayer": "e_019_evening_promises-and-comfort_04_prayer.mp3"
    },
    "e_020": {
      "scripture": "e_020_evening_salvation-and-core-faith_01_scripture.mp3",
      "reflection": "e_020_evening_salvation-and-core-faith_02_reflection.mp3",
      "simple-step": "e_020_evening_salvation-and-core-faith_03_simple-step.mp3",
      "prayer": "e_020_evening_salvation-and-core-faith_04_prayer.mp3"
    },
    "e_021": {
      "scripture": "e_021_evening_wisdom-and-proverbs_01_scripture.mp3",
      "reflection": "e_021_evening_wisdom-and-proverbs_02_reflection.mp3",
      "simple-step": "e_021_evening_wisdom-and-proverbs_03_simple-step.mp3",
      "prayer": "e_021_evening_wisdom-and-proverbs_04_prayer.mp3"
    },
    "e_022": {
      "scripture": "e_022_evening_romans-5-12_01_scripture.mp3",
      "reflection": "e_022_evening_romans-5-12_02_reflection.mp3",
      "simple-step": "e_022_evening_romans-5-12_03_simple-step.mp3",
      "prayer": "e_022_evening_romans-5-12_04_prayer.mp3"
    },
    "e_023": {
      "scripture": "e_023_evening_titus-3-5_01_scripture.mp3",
      "reflection": "e_023_evening_titus-3-5_02_reflection.mp3",
      "simple-step": "e_023_evening_titus-3-5_03_simple-step.mp3",
      "prayer": "e_023_evening_titus-3-5_04_prayer.mp3"
    },
    "e_024": {
      "scripture": "e_024_evening_galatians-5-22_01_scripture.mp3",
      "reflection": "e_024_evening_galatians-5-22_02_reflection.mp3",
      "simple-step": "e_024_evening_galatians-5-22_03_simple-step.mp3",
      "prayer": "e_024_evening_galatians-5-22_04_prayer.mp3"
    },
    "e_025": {
      "scripture": "e_025_evening_exhortation-and-action_01_scripture.mp3",
      "reflection": "e_025_evening_exhortation-and-action_02_reflection.mp3",
      "simple-step": "e_025_evening_exhortation-and-action_03_simple-step.mp3",
      "prayer": "e_025_evening_exhortation-and-action_04_prayer.mp3"
    },
    "e_026": {
      "scripture": "e_026_evening_john-3-1_01_scripture.mp3",
      "reflection": "e_026_evening_john-3-1_02_reflection.mp3",
      "simple-step": "e_026_evening_john-3-1_03_simple-step.mp3",
      "prayer": "e_026_evening_john-3-1_04_prayer.mp3"
    },
    "e_027": {
      "scripture": "e_027_evening_christian-living-and-relationships_01_scripture.mp3",
      "reflection": "e_027_evening_christian-living-and-relationships_02_reflection.mp3",
      "simple-step": "e_027_evening_christian-living-and-relationships_03_simple-step.mp3",
      "prayer": "e_027_evening_christian-living-and-relationships_04_prayer.mp3"
    },
    "e_028": {
      "scripture": "e_028_evening_church-and-community_01_scripture.mp3",
      "reflection": "e_028_evening_church-and-community_02_reflection.mp3",
      "simple-step": "e_028_evening_church-and-community_03_simple-step.mp3",
      "prayer": "e_028_evening_church-and-community_04_prayer.mp3"
    },
    "e_029": {
      "scripture": "e_029_evening_christology-and-the-fulfillment-of-old-testament_01_scripture.mp3",
      "reflection": "e_029_evening_christology-and-the-fulfillment-of-old-testament_02_reflection.mp3",
      "simple-step": "e_029_evening_christology-and-the-fulfillment-of-old-testament_03_simple-step.mp3",
      "prayer": "e_029_evening_christology-and-the-fulfillment-of-old-testament_04_prayer.mp3"
    },
    "e_030": {
      "scripture": "e_030_evening_pastoral-leadership_01_scripture.mp3",
      "reflection": "e_030_evening_pastoral-leadership_02_reflection.mp3",
      "simple-step": "e_030_evening_pastoral-leadership_03_simple-step.mp3",
      "prayer": "e_030_evening_pastoral-leadership_04_prayer.mp3"
    },
    "e_031": {
      "scripture": "e_031_evening_spiritual-warfare_01_scripture.mp3",
      "reflection": "e_031_evening_spiritual-warfare_02_reflection.mp3",
      "simple-step": "e_031_evening_spiritual-warfare_03_simple-step.mp3",
      "prayer": "e_031_evening_spiritual-warfare_04_prayer.mp3"
    },
    "e_032": {
      "scripture": "e_032_evening_righteous-judgment_01_scripture.mp3",
      "reflection": "e_032_evening_righteous-judgment_02_reflection.mp3",
      "simple-step": "e_032_evening_righteous-judgment_03_simple-step.mp3",
      "prayer": "e_032_evening_righteous-judgment_04_prayer.mp3"
    },
    "e_033": {
      "scripture": "e_033_evening_universal-sinfulness_01_scripture.mp3",
      "reflection": "e_033_evening_universal-sinfulness_02_reflection.mp3",
      "simple-step": "e_033_evening_universal-sinfulness_03_simple-step.mp3",
      "prayer": "e_033_evening_universal-sinfulness_04_prayer.mp3"
    },
    "e_034": {
      "scripture": "e_034_evening_eternal-life_01_scripture.mp3",
      "reflection": "e_034_evening_eternal-life_02_reflection.mp3",
      "simple-step": "e_034_evening_eternal-life_03_simple-step.mp3",
      "prayer": "e_034_evening_eternal-life_04_prayer.mp3"
    },
    "e_035": {
      "scripture": "e_035_evening_cross-cultural-encounter_01_scripture.mp3",
      "reflection": "e_035_evening_cross-cultural-encounter_02_reflection.mp3",
      "simple-step": "e_035_evening_cross-cultural-encounter_03_simple-step.mp3",
      "prayer": "e_035_evening_cross-cultural-encounter_04_prayer.mp3"
    },
    "e_036": {
      "scripture": "e_036_evening_sexual-ethics_01_scripture.mp3",
      "reflection": "e_036_evening_sexual-ethics_02_reflection.mp3",
      "simple-step": "e_036_evening_sexual-ethics_03_simple-step.mp3",
      "prayer": "e_036_evening_sexual-ethics_04_prayer.mp3"
    },
    "e_037": {
      "scripture": "e_037_evening_eternal-truth_01_scripture.mp3",
      "reflection": "e_037_evening_eternal-truth_02_reflection.mp3",
      "simple-step": "e_037_evening_eternal-truth_03_simple-step.mp3",
      "prayer": "e_037_evening_eternal-truth_04_prayer.mp3"
    },
    "e_038": {
      "scripture": "e_038_evening_discipleship-and-commitment_01_scripture.mp3",
      "reflection": "e_038_evening_discipleship-and-commitment_02_reflection.mp3",
      "simple-step": "e_038_evening_discipleship-and-commitment_03_simple-step.mp3",
      "prayer": "e_038_evening_discipleship-and-commitment_04_prayer.mp3"
    },
    "e_039": {
      "scripture": "e_039_evening_john-2-1_01_scripture.mp3",
      "reflection": "e_039_evening_john-2-1_02_reflection.mp3",
      "simple-step": "e_039_evening_john-2-1_03_simple-step.mp3",
      "prayer": "e_039_evening_john-2-1_04_prayer.mp3"
    },
    "e_040": {
      "scripture": "e_040_evening_rebirth-and-regeneration_01_scripture.mp3",
      "reflection": "e_040_evening_rebirth-and-regeneration_02_reflection.mp3",
      "simple-step": "e_040_evening_rebirth-and-regeneration_03_simple-step.mp3",
      "prayer": "e_040_evening_rebirth-and-regeneration_04_prayer.mp3"
    },
    "e_041": {
      "scripture": "e_041_evening_identity-in-christ_01_scripture.mp3",
      "reflection": "e_041_evening_identity-in-christ_02_reflection.mp3",
      "simple-step": "e_041_evening_identity-in-christ_03_simple-step.mp3",
      "prayer": "e_041_evening_identity-in-christ_04_prayer.mp3"
    },
    "e_042": {
      "scripture": "e_042_evening_christology-divinity_01_scripture.mp3",
      "reflection": "e_042_evening_christology-divinity_02_reflection.mp3",
      "simple-step": "e_042_evening_christology-divinity_03_simple-step.mp3",
      "prayer": "e_042_evening_christology-divinity_04_prayer.mp3"
    },
    "e_043": {
      "scripture": "e_043_evening_greatest-commandment_01_scripture.mp3",
      "reflection": "e_043_evening_greatest-commandment_02_reflection.mp3",
      "simple-step": "e_043_evening_greatest-commandment_03_simple-step.mp3",
      "prayer": "e_043_evening_greatest-commandment_04_prayer.mp3"
    },
    "e_044": {
      "scripture": "e_044_evening_christology-and-redemption_01_scripture.mp3",
      "reflection": "e_044_evening_christology-and-redemption_02_reflection.mp3",
      "simple-step": "e_044_evening_christology-and-redemption_03_simple-step.mp3",
      "prayer": "e_044_evening_christology-and-redemption_04_prayer.mp3"
    },
    "e_045": {
      "scripture": "e_045_evening_holy-spirits-role_01_scripture.mp3",
      "reflection": "e_045_evening_holy-spirits-role_02_reflection.mp3",
      "simple-step": "e_045_evening_holy-spirits-role_03_simple-step.mp3",
      "prayer": "e_045_evening_holy-spirits-role_04_prayer.mp3"
    },
    "e_046": {
      "scripture": "e_046_evening_promise-and-comfort_01_scripture.mp3",
      "reflection": "e_046_evening_promise-and-comfort_02_reflection.mp3",
      "simple-step": "e_046_evening_promise-and-comfort_03_simple-step.mp3",
      "prayer": "e_046_evening_promise-and-comfort_04_prayer.mp3"
    },
    "e_047": {
      "scripture": "e_047_evening_christs-divinity_01_scripture.mp3",
      "reflection": "e_047_evening_christs-divinity_02_reflection.mp3",
      "simple-step": "e_047_evening_christs-divinity_03_simple-step.mp3",
      "prayer": "e_047_evening_christs-divinity_04_prayer.mp3"
    },
    "e_048": {
      "scripture": "e_048_evening_faith-and-discernment_01_scripture.mp3",
      "reflection": "e_048_evening_faith-and-discernment_02_reflection.mp3",
      "simple-step": "e_048_evening_faith-and-discernment_03_simple-step.mp3",
      "prayer": "e_048_evening_faith-and-discernment_04_prayer.mp3"
    },
    "e_049": {
      "scripture": "e_049_evening_gods-justice-and-holiness_01_scripture.mp3",
      "reflection": "e_049_evening_gods-justice-and-holiness_02_reflection.mp3",
      "simple-step": "e_049_evening_gods-justice-and-holiness_03_simple-step.mp3",
      "prayer": "e_049_evening_gods-justice-and-holiness_04_prayer.mp3"
    },
    "e_050": {
      "scripture": "e_050_evening_ethical-and-moral-imperative_01_scripture.mp3",
      "reflection": "e_050_evening_ethical-and-moral-imperative_02_reflection.mp3",
      "simple-step": "e_050_evening_ethical-and-moral-imperative_03_simple-step.mp3",
      "prayer": "e_050_evening_ethical-and-moral-imperative_04_prayer.mp3"
    },
    "e_051": {
      "scripture": "e_051_evening_anxiety-management-and-trust_01_scripture.mp3",
      "reflection": "e_051_evening_anxiety-management-and-trust_02_reflection.mp3",
      "simple-step": "e_051_evening_anxiety-management-and-trust_03_simple-step.mp3",
      "prayer": "e_051_evening_anxiety-management-and-trust_04_prayer.mp3"
    },
    "e_052": {
      "scripture": "e_052_evening_kingdom-priority_01_scripture.mp3",
      "reflection": "e_052_evening_kingdom-priority_02_reflection.mp3",
      "simple-step": "e_052_evening_kingdom-priority_03_simple-step.mp3",
      "prayer": "e_052_evening_kingdom-priority_04_prayer.mp3"
    },
    "e_053": {
      "scripture": "e_053_evening_spiritual-transformation_01_scripture.mp3",
      "reflection": "e_053_evening_spiritual-transformation_02_reflection.mp3",
      "simple-step": "e_053_evening_spiritual-transformation_03_simple-step.mp3",
      "prayer": "e_053_evening_spiritual-transformation_04_prayer.mp3"
    },
    "e_054": {
      "scripture": "e_054_evening_eternal-life-definition_01_scripture.mp3",
      "reflection": "e_054_evening_eternal-life-definition_02_reflection.mp3",
      "simple-step": "e_054_evening_eternal-life-definition_03_simple-step.mp3",
      "prayer": "e_054_evening_eternal-life-definition_04_prayer.mp3"
    },
    "e_055": {
      "scripture": "e_055_evening_eschatology-and-final-judgment_01_scripture.mp3",
      "reflection": "e_055_evening_eschatology-and-final-judgment_02_reflection.mp3",
      "simple-step": "e_055_evening_eschatology-and-final-judgment_03_simple-step.mp3",
      "prayer": "e_055_evening_eschatology-and-final-judgment_04_prayer.mp3"
    },
    "e_056": {
      "scripture": "e_056_evening_messianic-promise_01_scripture.mp3",
      "reflection": "e_056_evening_messianic-promise_02_reflection.mp3",
      "simple-step": "e_056_evening_messianic-promise_03_simple-step.mp3",
      "prayer": "e_056_evening_messianic-promise_04_prayer.mp3"
    },
    "e_057": {
      "scripture": "e_057_evening_perseverance-trials_01_scripture.mp3",
      "reflection": "e_057_evening_perseverance-trials_02_reflection.mp3",
      "simple-step": "e_057_evening_perseverance-trials_03_simple-step.mp3",
      "prayer": "e_057_evening_perseverance-trials_04_prayer.mp3"
    },
    "e_058": {
      "scripture": "e_058_evening_early-church-practice_01_scripture.mp3",
      "reflection": "e_058_evening_early-church-practice_02_reflection.mp3",
      "simple-step": "e_058_evening_early-church-practice_03_simple-step.mp3",
      "prayer": "e_058_evening_early-church-practice_04_prayer.mp3"
    },
    "e_059": {
      "scripture": "e_059_evening_gods-grace_01_scripture.mp3",
      "reflection": "e_059_evening_gods-grace_02_reflection.mp3",
      "simple-step": "e_059_evening_gods-grace_03_simple-step.mp3",
      "prayer": "e_059_evening_gods-grace_04_prayer.mp3"
    },
    "e_060": {
      "scripture": "e_060_evening_core-doctrine-and-salvation_01_scripture.mp3",
      "reflection": "e_060_evening_core-doctrine-and-salvation_02_reflection.mp3",
      "simple-step": "e_060_evening_core-doctrine-and-salvation_03_simple-step.mp3",
      "prayer": "e_060_evening_core-doctrine-and-salvation_04_prayer.mp3"
    },
    "m_001": {
      "scripture": "m_001_morning_core-doctrine-and-salvation_01_scripture.mp3",
      "reflection": "m_001_morning_core-doctrine-and-salvation_02_reflection.mp3",
      "simple-step": "m_001_morning_core-doctrine-and-salvation_03_simple-step.mp3",
      "prayer": "m_001_morning_core-doctrine-and-salvation_04_prayer.mp3"
    },
    "m_002": {
      "scripture": "m_002_morning_jeremiah-29-11_01_scripture.mp3",
      "reflection": "m_002_morning_jeremiah-29-11_02_reflection.mp3",
      "simple-step": "m_002_morning_jeremiah-29-11_03_simple-step.mp3",
      "prayer": "m_002_morning_jeremiah-29-11_04_prayer.mp3"
    },
    "m_003": {
      "scripture": "m_003_morning_matthew-28-19_01_scripture.mp3",
      "reflection": "m_003_morning_matthew-28-19_02_reflection.mp3",
      "simple-step": "m_003_morning_matthew-28-19_03_simple-step.mp3",
      "prayer": "m_003_morning_matthew-28-19_04_prayer.mp3"
    },
    "m_004": {
      "scripture": "m_004_morning_exhortation-and-mission_01_scripture.mp3",
      "reflection": "m_004_morning_exhortation-and-mission_02_reflection.mp3",
      "simple-step": "m_004_morning_exhortation-and-mission_03_simple-step.mp3",
      "prayer": "m_004_morning_exhortation-and-mission_04_prayer.mp3"
    },
    "m_005": {
      "scripture": "m_005_morning_wisdom-and-maxim_01_scripture.mp3",
      "reflection": "m_005_morning_wisdom-and-maxim_02_reflection.mp3",
      "simple-step": "m_005_morning_wisdom-and-maxim_03_simple-step.mp3",
      "prayer": "m_005_morning_wisdom-and-maxim_04_prayer.mp3"
    },
    "m_006": {
      "scripture": "m_006_morning_exhortation-and-action_01_scripture.mp3",
      "reflection": "m_006_morning_exhortation-and-action_02_reflection.mp3",
      "simple-step": "m_006_morning_exhortation-and-action_03_simple-step.mp3",
      "prayer": "m_006_morning_exhortation-and-action_04_prayer.mp3"
    },
    "m_007": {
      "scripture": "m_007_morning_john-1-1_01_scripture.mp3",
      "reflection": "m_007_morning_john-1-1_02_reflection.mp3",
      "simple-step": "m_007_morning_john-1-1_03_simple-step.mp3",
      "prayer": "m_007_morning_john-1-1_04_prayer.mp3"
    },
    "m_008": {
      "scripture": "m_008_morning_genesis-1-1_01_scripture.mp3",
      "reflection": "m_008_morning_genesis-1-1_02_reflection.mp3",
      "simple-step": "m_008_morning_genesis-1-1_03_simple-step.mp3",
      "prayer": "m_008_morning_genesis-1-1_04_prayer.mp3"
    },
    "m_009": {
      "scripture": "m_009_morning_ephesians-4-11_01_scripture.mp3",
      "reflection": "m_009_morning_ephesians-4-11_02_reflection.mp3",
      "simple-step": "m_009_morning_ephesians-4-11_03_simple-step.mp3",
      "prayer": "m_009_morning_ephesians-4-11_04_prayer.mp3"
    },
    "m_010": {
      "scripture": "m_010_morning_church-growth-and-conversion_01_scripture.mp3",
      "reflection": "m_010_morning_church-growth-and-conversion_02_reflection.mp3",
      "simple-step": "m_010_morning_church-growth-and-conversion_03_simple-step.mp3",
      "prayer": "m_010_morning_church-growth-and-conversion_04_prayer.mp3"
    },
    "m_011": {
      "scripture": "m_011_morning_holy-spirit-outpouring_01_scripture.mp3",
      "reflection": "m_011_morning_holy-spirit-outpouring_02_reflection.mp3",
      "simple-step": "m_011_morning_holy-spirit-outpouring_03_simple-step.mp3",
      "prayer": "m_011_morning_holy-spirit-outpouring_04_prayer.mp3"
    },
    "m_012": {
      "scripture": "m_012_morning_perseverance-and-endurance_01_scripture.mp3",
      "reflection": "m_012_morning_perseverance-and-endurance_02_reflection.mp3",
      "simple-step": "m_012_morning_perseverance-and-endurance_03_simple-step.mp3",
      "prayer": "m_012_morning_perseverance-and-endurance_04_prayer.mp3"
    },
    "m_013": {
      "scripture": "m_013_morning_spiritual-strength_01_scripture.mp3",
      "reflection": "m_013_morning_spiritual-strength_02_reflection.mp3",
      "simple-step": "m_013_morning_spiritual-strength_03_simple-step.mp3",
      "prayer": "m_013_morning_spiritual-strength_04_prayer.mp3"
    },
    "m_014": {
      "scripture": "m_014_morning_mark-16-15_01_scripture.mp3",
      "reflection": "m_014_morning_mark-16-15_02_reflection.mp3",
      "simple-step": "m_014_morning_mark-16-15_03_simple-step.mp3",
      "prayer": "m_014_morning_mark-16-15_04_prayer.mp3"
    },
    "m_015": {
      "scripture": "m_015_morning_acts-4-12_01_scripture.mp3",
      "reflection": "m_015_morning_acts-4-12_02_reflection.mp3",
      "simple-step": "m_015_morning_acts-4-12_03_simple-step.mp3",
      "prayer": "m_015_morning_acts-4-12_04_prayer.mp3"
    },
    "m_016": {
      "scripture": "m_016_morning_proverbs-3-5_01_scripture.mp3",
      "reflection": "m_016_morning_proverbs-3-5_02_reflection.mp3",
      "simple-step": "m_016_morning_proverbs-3-5_03_simple-step.mp3",
      "prayer": "m_016_morning_proverbs-3-5_04_prayer.mp3"
    },
    "m_017": {
      "scripture": "m_017_morning_core-doctrine-and-salvation_01_scripture.mp3",
      "reflection": "m_017_morning_core-doctrine-and-salvation_02_reflection.mp3",
      "simple-step": "m_017_morning_core-doctrine-and-salvation_03_simple-step.mp3",
      "prayer": "m_017_morning_core-doctrine-and-salvation_04_prayer.mp3"
    },
    "m_018": {
      "scripture": "m_018_morning_john-3-3_01_scripture.mp3",
      "reflection": "m_018_morning_john-3-3_02_reflection.mp3",
      "simple-step": "m_018_morning_john-3-3_03_simple-step.mp3",
      "prayer": "m_018_morning_john-3-3_04_prayer.mp3"
    },
    "m_019": {
      "scripture": "m_019_morning_genesis-1-26_01_scripture.mp3",
      "reflection": "m_019_morning_genesis-1-26_02_reflection.mp3",
      "simple-step": "m_019_morning_genesis-1-26_03_simple-step.mp3",
      "prayer": "m_019_morning_genesis-1-26_04_prayer.mp3"
    },
    "m_020": {
      "scripture": "m_020_morning_romans-12-1_01_scripture.mp3",
      "reflection": "m_020_morning_romans-12-1_02_reflection.mp3",
      "simple-step": "m_020_morning_romans-12-1_03_simple-step.mp3",
      "prayer": "m_020_morning_romans-12-1_04_prayer.mp3"
    },
    "m_021": {
      "scripture": "m_021_morning_promises-and-comfort_01_scripture.mp3",
      "reflection": "m_021_morning_promises-and-comfort_02_reflection.mp3",
      "simple-step": "m_021_morning_promises-and-comfort_03_simple-step.mp3",
      "prayer": "m_021_morning_promises-and-comfort_04_prayer.mp3"
    },
    "m_022": {
      "scripture": "m_022_morning_john-14-6_01_scripture.mp3",
      "reflection": "m_022_morning_john-14-6_02_reflection.mp3",
      "simple-step": "m_022_morning_john-14-6_03_simple-step.mp3",
      "prayer": "m_022_morning_john-14-6_04_prayer.mp3"
    },
    "m_023": {
      "scripture": "m_023_morning_exhortation-and-action_01_scripture.mp3",
      "reflection": "m_023_morning_exhortation-and-action_02_reflection.mp3",
      "simple-step": "m_023_morning_exhortation-and-action_03_simple-step.mp3",
      "prayer": "m_023_morning_exhortation-and-action_04_prayer.mp3"
    },
    "m_024": {
      "scripture": "m_024_morning_salvation-through-faith_01_scripture.mp3",
      "reflection": "m_024_morning_salvation-through-faith_02_reflection.mp3",
      "simple-step": "m_024_morning_salvation-through-faith_03_simple-step.mp3",
      "prayer": "m_024_morning_salvation-through-faith_04_prayer.mp3"
    },
    "m_025": {
      "scripture": "m_025_morning_faith_01_scripture.mp3",
      "reflection": "m_025_morning_faith_02_reflection.mp3",
      "simple-step": "m_025_morning_faith_03_simple-step.mp3",
      "prayer": "m_025_morning_faith_04_prayer.mp3"
    },
    "m_026": {
      "scripture": "m_026_morning_gods-revelation_01_scripture.mp3",
      "reflection": "m_026_morning_gods-revelation_02_reflection.mp3",
      "simple-step": "m_026_morning_gods-revelation_03_simple-step.mp3",
      "prayer": "m_026_morning_gods-revelation_04_prayer.mp3"
    },
    "m_027": {
      "scripture": "m_027_morning_faith-and-salvation_01_scripture.mp3",
      "reflection": "m_027_morning_faith-and-salvation_02_reflection.mp3",
      "simple-step": "m_027_morning_faith-and-salvation_03_simple-step.mp3",
      "prayer": "m_027_morning_faith-and-salvation_04_prayer.mp3"
    },
    "m_028": {
      "scripture": "m_028_morning_promises-and-comfort_01_scripture.mp3",
      "reflection": "m_028_morning_promises-and-comfort_02_reflection.mp3",
      "simple-step": "m_028_morning_promises-and-comfort_03_simple-step.mp3",
      "prayer": "m_028_morning_promises-and-comfort_04_prayer.mp3"
    },
    "m_029": {
      "scripture": "m_029_morning_love-and-ethics_01_scripture.mp3",
      "reflection": "m_029_morning_love-and-ethics_02_reflection.mp3",
      "simple-step": "m_029_morning_love-and-ethics_03_simple-step.mp3",
      "prayer": "m_029_morning_love-and-ethics_04_prayer.mp3"
    },
    "m_030": {
      "scripture": "m_030_morning_holy-spirit_01_scripture.mp3",
      "reflection": "m_030_morning_holy-spirit_02_reflection.mp3",
      "simple-step": "m_030_morning_holy-spirit_03_simple-step.mp3",
      "prayer": "m_030_morning_holy-spirit_04_prayer.mp3"
    },
    "m_031": {
      "scripture": "m_031_morning_eschatology-hope_01_scripture.mp3",
      "reflection": "m_031_morning_eschatology-hope_02_reflection.mp3",
      "simple-step": "m_031_morning_eschatology-hope_03_simple-step.mp3",
      "prayer": "m_031_morning_eschatology-hope_04_prayer.mp3"
    },
    "m_032": {
      "scripture": "m_032_morning_mental-discipline-and-renewal_01_scripture.mp3",
      "reflection": "m_032_morning_mental-discipline-and-renewal_02_reflection.mp3",
      "simple-step": "m_032_morning_mental-discipline-and-renewal_03_simple-step.mp3",
      "prayer": "m_032_morning_mental-discipline-and-renewal_04_prayer.mp3"
    },
    "m_033": {
      "scripture": "m_033_morning_salvation-and-faith_01_scripture.mp3",
      "reflection": "m_033_morning_salvation-and-faith_02_reflection.mp3",
      "simple-step": "m_033_morning_salvation-and-faith_03_simple-step.mp3",
      "prayer": "m_033_morning_salvation-and-faith_04_prayer.mp3"
    },
    "m_034": {
      "scripture": "m_034_morning_jesuss-divinity-and-eternity_01_scripture.mp3",
      "reflection": "m_034_morning_jesuss-divinity-and-eternity_02_reflection.mp3",
      "simple-step": "m_034_morning_jesuss-divinity-and-eternity_03_simple-step.mp3",
      "prayer": "m_034_morning_jesuss-divinity-and-eternity_04_prayer.mp3"
    },
    "m_035": {
      "scripture": "m_035_morning_abiding-in-christ-and-fruitfulness_01_scripture.mp3",
      "reflection": "m_035_morning_abiding-in-christ-and-fruitfulness_02_reflection.mp3",
      "simple-step": "m_035_morning_abiding-in-christ-and-fruitfulness_03_simple-step.mp3",
      "prayer": "m_035_morning_abiding-in-christ-and-fruitfulness_04_prayer.mp3"
    },
    "m_036": {
      "scripture": "m_036_morning_parenting-and-child-rearing_01_scripture.mp3",
      "reflection": "m_036_morning_parenting-and-child-rearing_02_reflection.mp3",
      "simple-step": "m_036_morning_parenting-and-child-rearing_03_simple-step.mp3",
      "prayer": "m_036_morning_parenting-and-child-rearing_04_prayer.mp3"
    },
    "m_037": {
      "scripture": "m_037_morning_wealth-and-spiritual-blindness_01_scripture.mp3",
      "reflection": "m_037_morning_wealth-and-spiritual-blindness_02_reflection.mp3",
      "simple-step": "m_037_morning_wealth-and-spiritual-blindness_03_simple-step.mp3",
      "prayer": "m_037_morning_wealth-and-spiritual-blindness_04_prayer.mp3"
    },
    "m_038": {
      "scripture": "m_038_morning_help-and-deliverance_01_scripture.mp3",
      "reflection": "m_038_morning_help-and-deliverance_02_reflection.mp3",
      "simple-step": "m_038_morning_help-and-deliverance_03_simple-step.mp3",
      "prayer": "m_038_morning_help-and-deliverance_04_prayer.mp3"
    },
    "m_039": {
      "scripture": "m_039_morning_assurance-and-certainty_01_scripture.mp3",
      "reflection": "m_039_morning_assurance-and-certainty_02_reflection.mp3",
      "simple-step": "m_039_morning_assurance-and-certainty_03_simple-step.mp3",
      "prayer": "m_039_morning_assurance-and-certainty_04_prayer.mp3"
    },
    "m_040": {
      "scripture": "m_040_morning_invitation-and-fellowship_01_scripture.mp3",
      "reflection": "m_040_morning_invitation-and-fellowship_02_reflection.mp3",
      "simple-step": "m_040_morning_invitation-and-fellowship_03_simple-step.mp3",
      "prayer": "m_040_morning_invitation-and-fellowship_04_prayer.mp3"
    },
    "m_041": {
      "scripture": "m_041_morning_witness-and-faith_01_scripture.mp3",
      "reflection": "m_041_morning_witness-and-faith_02_reflection.mp3",
      "simple-step": "m_041_morning_witness-and-faith_03_simple-step.mp3",
      "prayer": "m_041_morning_witness-and-faith_04_prayer.mp3"
    },
    "m_042": {
      "scripture": "m_042_morning_faith-and-the-role-of-gods-word_01_scripture.mp3",
      "reflection": "m_042_morning_faith-and-the-role-of-gods-word_02_reflection.mp3",
      "simple-step": "m_042_morning_faith-and-the-role-of-gods-word_03_simple-step.mp3",
      "prayer": "m_042_morning_faith-and-the-role-of-gods-word_04_prayer.mp3"
    },
    "m_043": {
      "scripture": "m_043_morning_messianic-mission_01_scripture.mp3",
      "reflection": "m_043_morning_messianic-mission_02_reflection.mp3",
      "simple-step": "m_043_morning_messianic-mission_03_simple-step.mp3",
      "prayer": "m_043_morning_messianic-mission_04_prayer.mp3"
    },
    "m_044": {
      "scripture": "m_044_morning_civic-responsibility_01_scripture.mp3",
      "reflection": "m_044_morning_civic-responsibility_02_reflection.mp3",
      "simple-step": "m_044_morning_civic-responsibility_03_simple-step.mp3",
      "prayer": "m_044_morning_civic-responsibility_04_prayer.mp3"
    },
    "m_045": {
      "scripture": "m_045_morning_temptation-and-deception_01_scripture.mp3",
      "reflection": "m_045_morning_temptation-and-deception_02_reflection.mp3",
      "simple-step": "m_045_morning_temptation-and-deception_03_simple-step.mp3",
      "prayer": "m_045_morning_temptation-and-deception_04_prayer.mp3"
    },
    "m_046": {
      "scripture": "m_046_morning_practical-christian-living_01_scripture.mp3",
      "reflection": "m_046_morning_practical-christian-living_02_reflection.mp3",
      "simple-step": "m_046_morning_practical-christian-living_03_simple-step.mp3",
      "prayer": "m_046_morning_practical-christian-living_04_prayer.mp3"
    },
    "m_047": {
      "scripture": "m_047_morning_experience-and-goodness_01_scripture.mp3",
      "reflection": "m_047_morning_experience-and-goodness_02_reflection.mp3",
      "simple-step": "m_047_morning_experience-and-goodness_03_simple-step.mp3",
      "prayer": "m_047_morning_experience-and-goodness_04_prayer.mp3"
    },
    "m_048": {
      "scripture": "m_048_morning_promises-and-comfort_01_scripture.mp3",
      "reflection": "m_048_morning_promises-and-comfort_02_reflection.mp3",
      "simple-step": "m_048_morning_promises-and-comfort_03_simple-step.mp3",
      "prayer": "m_048_morning_promises-and-comfort_04_prayer.mp3"
    },
    "m_049": {
      "scripture": "m_049_morning_resurrection-and-eternal-life_01_scripture.mp3",
      "reflection": "m_049_morning_resurrection-and-eternal-life_02_reflection.mp3",
      "simple-step": "m_049_morning_resurrection-and-eternal-life_03_simple-step.mp3",
      "prayer": "m_049_morning_resurrection-and-eternal-life_04_prayer.mp3"
    },
    "m_050": {
      "scripture": "m_050_morning_creation-mandate_01_scripture.mp3",
      "reflection": "m_050_morning_creation-mandate_02_reflection.mp3",
      "simple-step": "m_050_morning_creation-mandate_03_simple-step.mp3",
      "prayer": "m_050_morning_creation-mandate_04_prayer.mp3"
    },
    "m_051": {
      "scripture": "m_051_morning_wisdom_01_scripture.mp3",
      "reflection": "m_051_morning_wisdom_02_reflection.mp3",
      "simple-step": "m_051_morning_wisdom_03_simple-step.mp3",
      "prayer": "m_051_morning_wisdom_04_prayer.mp3"
    },
    "m_052": {
      "scripture": "m_052_morning_core-faith-and-redemption_01_scripture.mp3",
      "reflection": "m_052_morning_core-faith-and-redemption_02_reflection.mp3",
      "simple-step": "m_052_morning_core-faith-and-redemption_03_simple-step.mp3",
      "prayer": "m_052_morning_core-faith-and-redemption_04_prayer.mp3"
    },
    "m_053": {
      "scripture": "m_053_morning_love-and-ethics_01_scripture.mp3",
      "reflection": "m_053_morning_love-and-ethics_02_reflection.mp3",
      "simple-step": "m_053_morning_love-and-ethics_03_simple-step.mp3",
      "prayer": "m_053_morning_love-and-ethics_04_prayer.mp3"
    },
    "m_054": {
      "scripture": "m_054_morning_ascension-of-jesus_01_scripture.mp3",
      "reflection": "m_054_morning_ascension-of-jesus_02_reflection.mp3",
      "simple-step": "m_054_morning_ascension-of-jesus_03_simple-step.mp3",
      "prayer": "m_054_morning_ascension-of-jesus_04_prayer.mp3"
    },
    "m_055": {
      "scripture": "m_055_morning_holy-spirit-power_01_scripture.mp3",
      "reflection": "m_055_morning_holy-spirit-power_02_reflection.mp3",
      "simple-step": "m_055_morning_holy-spirit-power_03_simple-step.mp3",
      "prayer": "m_055_morning_holy-spirit-power_04_prayer.mp3"
    },
    "m_056": {
      "scripture": "m_056_morning_romans-12-2_01_scripture.mp3",
      "reflection": "m_056_morning_romans-12-2_02_reflection.mp3",
      "simple-step": "m_056_morning_romans-12-2_03_simple-step.mp3",
      "prayer": "m_056_morning_romans-12-2_04_prayer.mp3"
    },
    "m_057": {
      "scripture": "m_057_morning_promises-and-comfort_01_scripture.mp3",
      "reflection": "m_057_morning_promises-and-comfort_02_reflection.mp3",
      "simple-step": "m_057_morning_promises-and-comfort_03_simple-step.mp3",
      "prayer": "m_057_morning_promises-and-comfort_04_prayer.mp3"
    },
    "m_058": {
      "scripture": "m_058_morning_core-doctrine-and-salvation_01_scripture.mp3",
      "reflection": "m_058_morning_core-doctrine-and-salvation_02_reflection.mp3",
      "simple-step": "m_058_morning_core-doctrine-and-salvation_03_simple-step.mp3",
      "prayer": "m_058_morning_core-doctrine-and-salvation_04_prayer.mp3"
    },
    "m_059": {
      "scripture": "m_059_morning_core-faith-and-redemption_01_scripture.mp3",
      "reflection": "m_059_morning_core-faith-and-redemption_02_reflection.mp3",
      "simple-step": "m_059_morning_core-faith-and-redemption_03_simple-step.mp3",
      "prayer": "m_059_morning_core-faith-and-redemption_04_prayer.mp3"
    },
    "m_060": {
      "scripture": "m_060_morning_acts-2-42_01_scripture.mp3",
      "reflection": "m_060_morning_acts-2-42_02_reflection.mp3",
      "simple-step": "m_060_morning_acts-2-42_03_simple-step.mp3",
      "prayer": "m_060_morning_acts-2-42_04_prayer.mp3"
    }
  }
};
