// AUTO-GENERATED by scripts/gen_bundled_verses.mjs — do not edit by hand.
// Slim, offline-first daily-verse bundle shipped inside the APK/IPA.
// Only the first 3 day(s) are bundled; the full 60-day set lives on
// the CDN (pd-text-corpus) and supersedes this the moment the first
// DailyVersesContext fetch completes. Regenerate with:
//   node scripts/gen_bundled_verses.mjs ./_incoming_verses 3
import type { LanguageCode } from '../state/TranslationsContext';

export interface DailyVerse {
  day: number;
  segment: 'morning' | 'evening';
  reference: {
    book: string;
    chapter: number;
    verse: string;
    full_reference: string;
  };
  modernVersion: string;
  modernText: string;
  meditation: string;
  actionStep: string;
  prayer: string;
}

// Bundled coverage in days. The CDN file covers 60; this fallback covers
// only the first 3 so the prayer card is never blank before the pull.
export const BUNDLED_COVERAGE_DAYS = 3;

export const BUNDLED_DAILY_VERSES: Record<LanguageCode, DailyVerse[]> =
{
  "en": [
    {
      "day": 1,
      "segment": "morning",
      "reference": {
        "book": "John",
        "chapter": 1,
        "verse": "9",
        "full_reference": "John 1:9"
      },
      "modernVersion": "NIV",
      "modernText": "The true light that gives light to everyone was coming into the world.",
      "meditation": "If you woke up today feeling as if the light is far away, this verse meets you with a gentle promise. Darkness is not always dramatic. Sometimes it is a quiet heaviness, a confused search for what is true, or the ache of loss and failure. John does not tell us to escape that darkness by becoming stronger or more worthy. He points us to Jesus, the true Light who has already come into the world.\n\nThis Light is not reserved for people who have life under control. He gives light to everyone, including you when faith feels small, your heart feels tired, or the next step is unclear. Jesus does not stand far away waiting for you to reach Him. He enters your darkness with His presence.\n\nToday, turning toward Christ means letting His truth become the first light in your heart. You do not have to create the light or earn it. You only need to turn toward the One who has come near.",
      "actionStep": "Name one place in your life that feels dark or unclear. Invite Jesus, the true Light, to meet you there today.",
      "prayer": "Dear Heavenly Father, I thank You for sending Jesus, the true Light who gives light to everyone without exception. I praise You that His light enters our darkness and leads us into Your truth and grace. I do not want to agree with this only in words and then return unchanged. Meet me in the hidden places where fear, habit, or self-protection still rule me. Teach me to open those places to Your love, and let my response to You become honest, steady, and whole. In Jesus' name, amen."
    },
    {
      "day": 1,
      "segment": "evening",
      "reference": {
        "book": "John",
        "chapter": 14,
        "verse": "1",
        "full_reference": "John 14:1"
      },
      "modernVersion": "NIV",
      "modernText": "Do not let your hearts be troubled. You believe in God; believe also in me.",
      "meditation": "When anxiety settles in, it rarely asks permission. It may come through a breakup, a lost job, frightening health news, or the quiet hours of night when every possible fear grows louder. You may not even know how to name what you feel. You only know your heart is unsettled, tired, and afraid.\n\nJesus spoke to His disciples in a moment like that, not when life was calm. He knew they were about to see Him arrested. He knew the cross would shake everything they thought they understood. Their world was not about to become easier, yet He still told them not to let their hearts be troubled. His comfort was not built on pleasant circumstances, but on trust: if they believed in God, they could also believe in Him.\n\nThat kind of faith does not deny trouble. It turns the heart toward the One whose goodness, power, and faithfulness hold steady when life does not. Jesus entered the deepest darkness to save you; He will not abandon you in ordinary fear. Today, your anxiety is not the final voice. His presence is nearer than the trouble pressing on your heart.",
      "actionStep": "Write down the fear or trouble that is speaking loudest in your heart today. Bring it to Jesus without polishing it, then write one sentence of trust beside it: “Lord, I choose to place this in Your hands.” Return to that sentence whenever the fear rises.",
      "prayer": "Dear Heavenly Father, I thank You that in Christ my heart does not have to be ruled by fear. When trouble feels louder than Your promise, teach me to bring my anxious thoughts honestly to You. Steady me with Your presence, and help me take the next step with a heart that trusts You. I do not want to agree with this only in words and then return unchanged. Meet me in the hidden places where fear, habit, or self-protection still rule me. Teach me to open those places to Your love, and let my response to You become honest, steady, and whole. In Jesus' name, amen."
    },
    {
      "day": 2,
      "segment": "morning",
      "reference": {
        "book": "Jeremiah",
        "chapter": 29,
        "verse": "11",
        "full_reference": "Jeremiah 29:11"
      },
      "modernVersion": "NIV",
      "modernText": "\"For I know the plans I have for you,\" declares the Lord, \"plans to prosper you and not to harm you, plans to give you hope and a future.\"",
      "meditation": "Jeremiah wrote these words to people living in exile, not to people whose lives felt easy or settled. They had lost home, security, and a clear future. Into that uncertainty, God says, 'I know the plans I have for you.' He is not merely watching their pain; He is still holding a purpose for them.\n\nThis promise does not deny the hardship. It reveals God's heart within it. His plans are not meant to destroy His people, but to lead them toward peace, restoration, and hope. When your future feels interrupted, or when your past mistakes seem to have the final word, this verse reminds you that God has not stopped thinking mercifully toward you. Your circumstances may still be unfinished, but His intention remains faithful.\n\nSo do not rush to call your present chapter the end of the story. Exile felt like an ending to Judah, but God was already speaking about a future. Your waiting, grief, or uncertainty may be real, but it is not stronger than God's faithful love. Let this promise steady you without forcing you to pretend: God can hold both your present pain and your future hope.",
      "actionStep": "Write this in your journal or phone notes: “God has plans of peace for me, not disaster.” When doubt comes up, read it again. If you can, read it in the morning and evening, and let it slowly shape the way you see your future.",
      "prayer": "Dear Heavenly Father, I praise You for Your promise that Your plans for us are for our good — filled with hope and a flourishing future. You hold our days in Your hands. Your purposes are not to harm us but to establish us in hope. Your plans do not fail — not one of them. History is Your story, and You write it with hope as the final word. What a good Father You are, one who plans our flourishing before we can even imagine it. I bring You the tired parts of my heart that know the right words but struggle to believe them. Sit with me there, Father, and make Your truth warmer than my shame and stronger than my fear. Help me pray not from distance, but from the trust that I am already held by You. In Jesus' name, amen."
    },
    {
      "day": 2,
      "segment": "evening",
      "reference": {
        "book": "John",
        "chapter": 14,
        "verse": "16",
        "full_reference": "John 14:16"
      },
      "modernVersion": "NIV",
      "modernText": "And I will ask the Father, and he will give you another advocate to help you and be with you forever—",
      "meditation": "When someone important leaves, the absence can feel bigger than the room itself. A move, a breakup, a death, or a sudden goodbye can make your whole sense of safety collapse. The disciples knew that fear. When Jesus told them He was leaving, they did not feel brave; they felt exposed and afraid.\n\nInto that fear, Jesus promised another Advocate who would remain with them forever. This was not a colder replacement for His presence. It was a deeper nearness. Jesus would no longer simply walk beside them; by the Spirit, God would dwell within them. The sorrow of separation would become the beginning of an intimacy they did not yet understand.\n\nThe Holy Spirit does not come and go like a visitor. He stays in the lonely midnight, the confusing decision, the grief you cannot explain, and the moment you need courage but cannot find it in yourself. He knows your heart, understands what you cannot put into words, and helps you pray when your own prayers feel weak. You are not left to survive by memory alone. God is with you now, and He will not leave.",
      "actionStep": "Pause and ask yourself: Where do I feel most alone today, and what do I need from God there? Pray simply, “Holy Spirit, remind me that I am not abandoned.” Then stay quiet for a moment and notice any comfort, wisdom, or strength He gives.",
      "prayer": "Dear Heavenly Father, I praise You for giving Your Spirit to remain with us. When absence, change, or loneliness makes me feel unprotected, remind me that I am not left to face life by myself. Help me listen for the Spirit's comfort and follow His quiet guidance today. I bring You the tired parts of my heart that know the right words but struggle to believe them. Sit with me there, Father, and make Your truth warmer than my shame and stronger than my fear. Help me pray not from distance, but from the trust that I am already held by You. In Jesus' name, amen."
    },
    {
      "day": 3,
      "segment": "morning",
      "reference": {
        "book": "Matthew",
        "chapter": 28,
        "verse": "19",
        "full_reference": "Matthew 28:19"
      },
      "modernVersion": "NIV",
      "modernText": "Therefore go and make disciples of all nations, baptizing them in the name of the Father and of the Son and of the Holy Spirit,",
      "meditation": "Jesus' command to make disciples begins with Jesus' power and authority, not our ability. Before He says, 'Go,' He declares that all authority in heaven and on earth belongs to Him. That means what we share does not rest on perfect words, complete confidence, or having every answer. It rests on the risen Christ who sends us and goes with us. Many of us hesitate because we feel unqualified. But Jesus is not asking you to act like a religious expert; He is inviting you to share what you have received from Him. Your changed life, your honest story, and your quiet faithfulness in ordinary places can become a doorway for someone else to meet Him.\n\nGod often uses willing people more than impressive people. This means small obedience matters. A quiet conversation, a patient answer, a prayer offered with someone, or a moment when you refuse to hide what Jesus means to you can become part of His mission. The nations may feel far away, but helping someone follow Jesus often begins with the person in front of you. You are called to be faithful with the person before you.",
      "actionStep": "Think of one person in your life who seems open or searching. This week, start a natural conversation with them. Do not force a religious discussion; simply share one practical way your faith has helped you, and listen well.",
      "prayer": "Dear Heavenly Father, I receive this grace: You have entrusted the mission of making disciples to those who follow Jesus. Give us courage to witness faithfully and humility to always point others to Christ. Where I still try to control outcomes, loosen my grip and quiet my anxious heart. I admit that I often want certainty more than surrender. Draw me back to You until obedience feels less like losing myself and more like coming home to the One who loves me best. In Jesus' name, amen."
    },
    {
      "day": 3,
      "segment": "evening",
      "reference": {
        "book": "Genesis",
        "chapter": 1,
        "verse": "2",
        "full_reference": "Genesis 1:2"
      },
      "modernVersion": "NIV",
      "modernText": "Now the earth was formless and empty, darkness was over the surface of the deep, and the Spirit of God was hovering over the waters.",
      "meditation": "Some seasons do not feel like a life being built; they feel formless. Plans dissolve, familiar ground disappears, and the future has no clear shape. Darkness can make you assume nothing good is happening, but the beginning of Scripture shows us something different: emptiness is not too empty for God.\n\nBefore there was order, beauty, or visible fruit, the Spirit of God was already present, hovering over the deep. He was not distant, delayed, or confused by the chaos. His presence came before the transformation could be seen. That is a quiet promise for every season where your life feels unfinished and hard to read.\n\nThe Spirit's hovering suggests tenderness as much as power. God does not need to force His way into your darkness; He is already near, guarding what looks fragile, preparing what is not yet formed. Your confusion is not beyond Him. Your waiting is not wasted. The same God who brings creation out of emptiness can move over the unshaped places of your life and begin again with order, light, and life.",
      "actionStep": "Name one area of life that feels unfinished, confused, or without clear shape. Invite God’s Spirit into that place, not with a forced plan, but with trust. Ask Him to show one small step toward order, light, or patient faith today.",
      "prayer": "Dear Heavenly Father, I receive this grace: Your Spirit is present even when life feels unfinished and without shape. Come near to the places in me that feel confused, dark, or empty. Breathe order, patience, and hope into what I cannot yet understand, and help me trust Your work before I can see its form. Where I keep trying to control outcomes, soften my hands and quiet my heart. I confess that I often want certainty more than I want surrender. Draw me back to You until obedience feels less like losing myself and more like coming home to the One who loves me best. In Jesus' name, amen."
    }
  ],
  "zh-Hans": [
    {
      "day": 1,
      "segment": "morning",
      "reference": {
        "book": "John",
        "chapter": 1,
        "verse": "9",
        "full_reference": "John 1:9"
      },
      "modernVersion": "CCB",
      "modernText": "真光来了，它照亮所有进入世界的人。",
      "meditation": "如果今天你一醒来，就觉得光离自己很远，这节经文带着温柔的应许来靠近你。黑暗不一定总是惊天动地的。很多时候，它只是心里说不清的沉重，是对真理和方向的困惑，也是失去或失败之后留下的阴影。约翰没有叫我们先变得更坚强、更明白、更配得；他把我们的眼光带向那已经来到世界的真光——耶稣。\n\n这光不是只照给生命整齐、信心稳定的人。经文说，祂照亮一切生在世上的人，也包括你：在你信心微弱、心里疲惫、看不清下一步的时候。耶稣不是远远等你走出黑暗；祂亲自进入你的黑暗，用祂的同在驱散惧怕和谎言。\n\n今天转向基督，就是让祂的真理成为你心里的第一道光。你不需要制造这光，也不需要证明自己配得。你只需要转向那位已经靠近你的主。",
      "actionStep": "今天，具体说出一个让你感到沉重或混乱的地方，并邀请耶稣这位真光照进那里。",
      "prayer": "亲爱的天父，感谢祢赐下主耶稣这真光，照亮每一个人，没有例外，也没有阻隔。赞美祢使祂的光进入我们的黑暗，引导我们进入祢的真理和恩典。我不愿只是在话语上同意这真理，然后仍旧原样离开。求祢在我里面那些被惧怕、习惯或自我保护掌管的隐秘之处遇见我。教我把这些地方向祢的爱打开，使我对祢的回应变得诚实、稳定，也更完整。奉主耶稣的名祷告，阿们。"
    },
    {
      "day": 1,
      "segment": "evening",
      "reference": {
        "book": "John",
        "chapter": 14,
        "verse": "1",
        "full_reference": "John 14:1"
      },
      "modernVersion": "CCB",
      "modernText": "你们的心不要不安。你们信神，也要信我。",
      "meditation": "焦虑来的时候，常常不会先给你准备。它可能来自一段关系的破裂，一份工作的失去，一个关于健康的坏消息，也可能只是夜深时，脑子里不断浮现各种可能出错的事。你也许说不清自己到底怎么了，只知道心里不安、疲惫，也害怕。\n\n耶稣对门徒说安慰的话时，并不是在一个平静的时刻。祂知道他们很快要看见祂被捉拿，也要看见十字架震动他们所有的理解。他们的处境不会马上变轻松，但耶稣仍然呼召他们信靠：既信神，也当信祂。祂不是用“事情都会顺利”来安慰他们，而是把他们的心带回祂自己，带回祂可靠的同在。\n\n这样的信心不是否认困难，而是把心转向那位在一切摇动中仍然良善、信实、有能力的主。耶稣曾进入最深的黑暗，为要拯救你；祂也不会在你今天的焦虑里撇下你。此刻，惧怕不是最后的声音。祂知道你的处境，也能扶持你的心。祂的同在比压在你心上的忧虑更近。你可以在不安还没有完全消失时，就先把心交给祂。",
      "actionStep": "写下今天在你心里声音最大的那个惧怕或忧虑，不用修饰，也不用先让自己坚强。把它诚实带到耶稣面前，并在旁边写一句信靠的话：“主啊，我把这件事交在你手中。”当惧怕再次浮上来，就回到这句话里。",
      "prayer": "亲爱的天父，感谢祢在基督里使我的心不必被惧怕支配。当困难的声音大过祢的应许，求祢教我诚实把焦虑带到祢面前。用祢的同在稳住我，使我今天能带着信靠走下一步。我不愿只是在话语上同意这真理，然后仍旧原样离开。求祢在我里面那些被惧怕、习惯或自我保护掌管的隐秘之处遇见我。教我把这些地方向祢的爱打开，使我对祢的回应变得诚实、稳定，也更完整。奉主耶稣的名祷告，阿们。"
    },
    {
      "day": 2,
      "segment": "morning",
      "reference": {
        "book": "Jeremiah",
        "chapter": 29,
        "verse": "11",
        "full_reference": "Jeremiah 29:11"
      },
      "modernVersion": "CCB",
      "modernText": "耶和华说：「我知道我对你们所有的计划，都是为了祝福你们，而不是伤害你们，要给你们一个美好的未来和希望。」",
      "meditation": "耶利米写下这句话时，听见的人不是生活顺利安稳的人，而是被掳、失落、看不见未来的百姓。他们失去家园、安全感和清晰的前路。就在这样的不确定中，神说：我知道我向你们所怀的意念。祂不是只看见他们的痛苦，祂仍然为他们持守一个目的。\n\n这个应许没有否认艰难，却显明神在艰难中的心。祂的计划不是要毁坏祂的百姓，而是要带他们进入平安、恢复和盼望。当你的未来被打断，或过去的错误好像已经决定结局时，这节经文提醒你：神仍以怜悯记念你。你的处境可能还没有完成，但祂向你的心意仍然信实。\n\n所以，不要太快把现在这一章称为结局。对犹大人来说，被掳像是故事结束了，但神已经在谈论未来。你的等待、伤痛和不确定都是真实的，却不比神守约的信实更大。让这个应许稳住你，而不是逼你假装没事：神能同时托住你今天的痛，也托住你将来的盼望。",
      "actionStep": "在日记或手机备忘录里写下：「关于我，神有平安的计划，不是灾祸的计划。」每当怀疑出现，就再读一遍。如果可以，早上和晚上都读一次，让这个真理慢慢改变你看未来的方式。",
      "prayer": "亲爱的天父，赞美祢应许我们，祢的计划是为了赐下平安、盼望和未来。我们的日子在祢手中，祢的心意不是伤害我们，而是建立我们、扶持我们走向盼望。祢的计划不会落空。求祢让这应许稳住我们的心，使我们在等待中仍然信靠祢的良善。我把心里那些疲惫的地方带到祢面前：它们知道正确的话，却仍然很难真正相信。父啊，求祢在那里陪伴我，使祢的真理比我的羞耻更温暖，比我的惧怕更有力量。帮助我不是远远地祷告，而是在已经被祢扶持的信靠中祷告。奉主耶稣的名祷告，阿们。"
    },
    {
      "day": 2,
      "segment": "evening",
      "reference": {
        "book": "John",
        "chapter": 14,
        "verse": "16",
        "full_reference": "John 14:16"
      },
      "modernVersion": "CCB",
      "modernText": "我会向父祈求，父会赐给你们另一位保惠师，他要永远与你们同在。",
      "meditation": "当一个重要的人离开时，空缺有时会大到占满整个房间。搬到陌生城市、一段关系结束、所爱之人离世，或突然的告别，都可能让安全感一下子崩塌。门徒也经历过这种惧怕。当耶稣告诉他们祂要离开时，他们并不勇敢，而是慌乱、无助。\n\n就在这样的黑暗时刻，耶稣应许赐下另一位保惠师，永远与他们同在。这不是把祂的同在降级为一个替代品，而是一种更深的亲近。耶稣不只是走在他们身边；借着圣灵，神要住在他们里面。门徒起初只感到失去，后来却明白，圣灵的同在使他们不再只是回忆耶稣，而是天天被祂带领、安慰和坚固。\n\n圣灵不是偶尔来探访的客人。祂在孤单的深夜、困惑的决定、无法解释的悲伤里同在，也在你没有力量祷告时帮助你。祂知道你的心，明白你说不出的叹息，甚至在你软弱时扶持你转向神。你不是靠回忆撑下去。神现在与你同在，也永远不会离开你。这同在是真实的。",
      "actionStep": "停下来问问自己：我今天在哪个地方最觉得孤单？在那里，我最需要神给我什么？简单祷告：“圣灵啊，提醒我，我没有被遗弃。”然后安静片刻，留意祂怎样赐下安慰、智慧或力量。",
      "prayer": "亲爱的天父，我领受这个恩典：祢赐下圣灵与我们同住。当离别、改变或孤单让我觉得无依无靠，求祢提醒我，我不是独自面对生活。帮助我听见圣灵温柔的安慰，也顺服祂今天细微的引导。我把心里那些疲惫的地方带到祢面前：它们知道正确的话，却仍然很难真正相信。父啊，求祢在那里陪伴我，使祢的真理比我的羞耻更温暖，比我的惧怕更有力量。帮助我不是远远地祷告，而是在已经被祢扶持的信靠中祷告。奉主耶稣的名祷告，阿们。"
    },
    {
      "day": 3,
      "segment": "morning",
      "reference": {
        "book": "Matthew",
        "chapter": 28,
        "verse": "19",
        "full_reference": "Matthew 28:19"
      },
      "modernVersion": "CCB 当代译本",
      "modernText": "所以，你们要去，使所有民族都成为我的门徒，奉父、子、圣灵的名给他们施洗，",
      "meditation": "耶稣使人作门徒的命令，从祂的权柄开始，而不是从我们的能力开始。祂先宣告：天上地下所有的权柄都赐给我了，然后才说：你们要去。因此，我们的分享信仰不是建立在完美表达、完全自信或拥有所有答案上，而是建立在差遣我们、也与我们同行的复活基督身上。很多时候我们犹豫，是因为觉得自己不够资格。但耶稣不是要你装作宗教专家，祂邀请你见证自己真实领受的恩典。\n\n你被改变的生命、诚实的故事、在日常中的忠心，都可能成为别人遇见祂的一扇门。神常使用愿意的人，多过使用看起来厉害的人。这使微小的顺服也很重要。一次安静的谈话，一个耐心的回答，和别人一起做的一个祷告，或一次不再隐藏耶稣对你意义的时刻，都可能成为祂使命的一部分。万民听起来很远，但门徒训练常常从你眼前的那个人开始。",
      "actionStep": "想一想你身边一个似乎愿意了解信仰、或正在寻找答案的人。这一周，和他/她自然地聊一次。不要硬把话题变成宗教讨论，只分享一个你的信仰怎样实际帮助过你的例子，并好好聆听。",
      "prayer": "亲爱的天父，我领受祢的恩典：祢借着主耶稣把使万民作门徒的使命交托给祂的门徒。求祢赐我们勇气忠心见证，也赐我们谦卑，使我们始终把人指向基督。在我仍想掌控结果的地方，求祢松开我紧握的手，安静我不安的心。我承认，我常常想要确定感，胜过想要降服。求祢把我重新拉回祢面前，直到顺服不再像失去自己，而像回到最爱我的那一位家中。奉主耶稣的名祷告，阿们。"
    },
    {
      "day": 3,
      "segment": "evening",
      "reference": {
        "book": "Genesis",
        "chapter": 1,
        "verse": "2",
        "full_reference": "Genesis 1:2"
      },
      "modernVersion": "CCB",
      "modernText": "大地一片混乱空洞，黑暗笼罩着深洋；神的灵在水面上运行。",
      "meditation": "有些季节不像生命正在被建造，反而像一切都没有形状。计划散开，熟悉的地面消失，未来也看不见轮廓。你可能经历失去、等待、停滞，或一种说不清的混乱。黑暗会让人以为什么好事都没有发生，但神创造的起头告诉我们：再空旷的虚空，也不超出神的工作。\n\n在秩序、美丽和果效出现以前，神的灵已经在那里运行。祂不是远远观看，也不是迟迟未到，更不是被混乱难住。祂的同在先于我们能看见的改变。这对每一个感到人生未成形的人，都是安静的应许。你看不见结构时，神仍然知道祂正在塑造什么；你看不见结果时，祂仍然没有停止工作。黑暗不是祂缺席的证据，空白也不是祂放弃的记号。\n\n圣灵的运行显出能力，也显出温柔。神不需要粗暴闯入你的黑暗；祂已经靠近，守护那些看似脆弱的地方，预备尚未成形的生命。就像母亲俯身看顾孩子，又像双手护住珍贵之物，祂的同在不是冷漠的观察，而是带着目的的守护。你的困惑没有大到祂不能进入，你的等待也没有白费。那位从空虚中创造生命的神，也能在你混乱之处重新带来光、秩序和生命。今天你也许只能看见水面上的黑暗，但神的灵已经在那里运行。所以，不要急着用眼前的混乱定义整个故事。神常常先在看不见的地方运行，然后才让我们慢慢看见光怎样出现、道路怎样展开。",
      "actionStep": "写下你生命中一个还没有形状、让你困惑或看不清方向的领域。邀请神的灵进入那里，不是急着做完整计划，而是带着信靠求祂带领。今天只求一个小小的下一步，走向秩序、光或更深的信心。",
      "prayer": "亲爱的天父，求祢让我看见这个恩典：祢在生命还混乱、没有形状的时候仍然同在。求祢临近我里面困惑、黑暗、空荡的地方。把秩序、忍耐和盼望吹进我还看不明白的处境里，使我在看见结果以前就学习信靠祢。在我仍想掌控结果的地方，求祢松开我紧握的手，安静我不安的心。我承认，我常常想要确定感，胜过想要降服。求祢把我重新拉回祢面前，直到顺服不再像失去自己，而像回到最爱我的那一位家中。奉主耶稣的名祷告，阿们。"
    }
  ],
  "zh-Hant": [
    {
      "day": 1,
      "segment": "morning",
      "reference": {
        "book": "John",
        "chapter": 1,
        "verse": "9",
        "full_reference": "John 1:9"
      },
      "modernVersion": "CCB",
      "modernText": "真光來了，它照亮所有進入世界的人。",
      "meditation": "如果今天你一醒来，就覺得光离自己很遠，這节經文带著温柔的應許来靠近你。黑暗不一定总是惊天動地的。很多時候，它只是心裡說不清的沉重，是對真理和方向的困惑，也是失去或失敗之後留下的阴影。约翰没有叫我們先變得更堅強、更明白、更配得；他把我們的眼光带向那已經来到世界的真光——耶穌。\n\n這光不是只照給生命整齐、信心稳定的人。經文說，祂照亮一切生在世上的人，也包括你：在你信心微弱、心裡疲惫、看不清下一步的時候。耶穌不是遠遠等你走出黑暗；祂親自进入你的黑暗，用祂的同在驱散惧怕和谎言。\n\n今天轉向基督，就是讓祂的真理成為你心裡的第一道光。你不需要制造這光，也不需要證明自己配得。你只需要轉向那位已經靠近你的主。",
      "actionStep": "今天，具體說出一個讓你感到沉重或混乱的地方，並邀請耶穌這位真光照进那裡。",
      "prayer": "親愛的天父，感謝祢赐下主耶穌這真光，照亮每一個人，没有例外，也没有阻隔。讚美祢使祂的光进入我們的黑暗，引导我們进入祢的真理和恩典。我不愿只是在話語上同意這真理，然後仍舊原样离開。求祢在我裡面那些被惧怕、習惯或自我保護掌管的隐秘之處遇見我。教我把這些地方向祢的愛打開，使我對祢的回應變得诚實、稳定，也更完整。奉主耶穌的名禱告，阿們。"
    },
    {
      "day": 1,
      "segment": "evening",
      "reference": {
        "book": "John",
        "chapter": 14,
        "verse": "1",
        "full_reference": "John 14:1"
      },
      "modernVersion": "CCB",
      "modernText": "你們的心不要不安。你們信神，也要信我。",
      "meditation": "焦慮来的時候，常常不會先給你准備。它可能来自一段關係的破裂，一份工作的失去，一個關于健康的坏消息，也可能只是夜深時，脑子裡不斷浮現各種可能出错的事。你也许說不清自己到底怎麼了，只知道心裡不安、疲惫，也害怕。\n\n耶穌對門徒說安慰的話時，並不是在一個平静的時刻。祂知道他們很快要看見祂被捉拿，也要看見十字架震動他們所有的理解。他們的處境不會马上變輕松，但耶穌仍然呼召他們信靠：既信神，也當信祂。祂不是用“事情都會順利”来安慰他們，而是把他們的心带回祂自己，带回祂可靠的同在。\n\n這样的信心不是否認困難，而是把心轉向那位在一切摇動中仍然良善、信實、有能力的主。耶穌曾进入最深的黑暗，為要拯救你；祂也不會在你今天的焦慮裡撇下你。此刻，惧怕不是最後的声音。祂知道你的處境，也能扶持你的心。祂的同在比壓在你心上的憂慮更近。你可以在不安還没有完全消失時，就先把心交給祂。",
      "actionStep": "寫下今天在你心裡声音最大的那個惧怕或憂慮，不用修饰，也不用先讓自己堅強。把它诚實帶到耶穌面前，並在旁邊寫一句信靠的話：“主啊，我把這件事交在你手中。”當惧怕再次浮上来，就回到這句話裡。",
      "prayer": "親愛的天父，感謝祢在基督裡使我的心不必被惧怕支配。當困難的声音大過祢的應許，求祢教我诚實把焦慮帶到祢面前。用祢的同在稳住我，使我今天能带著信靠走下一步。我不愿只是在話語上同意這真理，然後仍舊原样离開。求祢在我裡面那些被惧怕、習惯或自我保護掌管的隐秘之處遇見我。教我把這些地方向祢的愛打開，使我對祢的回應變得诚實、稳定，也更完整。奉主耶穌的名禱告，阿們。"
    },
    {
      "day": 2,
      "segment": "morning",
      "reference": {
        "book": "Jeremiah",
        "chapter": 29,
        "verse": "11",
        "full_reference": "Jeremiah 29:11"
      },
      "modernVersion": "CCB",
      "modernText": "耶和華說：「我知道我對你們所有的計劃，都是為了祝福你們，而不是傷害你們，要給你們一個美好的未來和希望。」",
      "meditation": "耶利米寫下這句話時，聽見的人不是生活順利安稳的人，而是被掳、失落、看不見未来的百姓。他們失去家园、安全感和清晰的前路。就在這样的不确定中，神說：我知道我向你們所懷的意念。祂不是只看見他們的痛苦，祂仍然為他們持守一個目的。\n\n這個應許没有否認艰難，却显明神在艰難中的心。祂的計劃不是要毁坏祂的百姓，而是要带他們进入平安、恢復和盼望。當你的未来被打斷，或過去的错误好像已經决定結局時，這节經文提醒你：神仍以憐憫記念你。你的處境可能還没有完成，但祂向你的心意仍然信實。\n\n所以，不要太快把現在這一章称為結局。對犹大人来說，被掳像是故事結束了，但神已經在谈论未来。你的等待、伤痛和不确定都是真實的，却不比神守约的信實更大。讓這個應許稳住你，而不是逼你假装没事：神能同時托住你今天的痛，也托住你将来的盼望。",
      "actionStep": "在日記或手机備忘录裡寫下：「關于我，神有平安的計劃，不是灾祸的計劃。」每當懷疑出現，就再讀一遍。如果可以，早上和晚上都讀一次，讓這個真理慢慢改變你看未来的方式。",
      "prayer": "親愛的天父，讚美祢應許我們，祢的計劃是為了赐下平安、盼望和未来。我們的日子在祢手中，祢的心意不是傷害我們，而是建立我們、扶持我們走向盼望。祢的計劃不會落空。求祢讓這應許稳住我們的心，使我們在等待中仍然信靠祢的良善。我把心裡那些疲惫的地方帶到祢面前：它們知道正确的話，却仍然很難真正相信。父啊，求祢在那裡陪伴我，使祢的真理比我的羞耻更温暖，比我的惧怕更有力量。幫助我不是遠遠地禱告，而是在已經被祢扶持的信靠中禱告。奉主耶穌的名禱告，阿們。"
    },
    {
      "day": 2,
      "segment": "evening",
      "reference": {
        "book": "John",
        "chapter": 14,
        "verse": "16",
        "full_reference": "John 14:16"
      },
      "modernVersion": "CCB",
      "modernText": "我會向父祈求，父會賜給你們另一位保惠師，他要永遠與你們同在。",
      "meditation": "當一個重要的人离開時，空缺有時會大到占滿整個房間。搬到陌生城市、一段關係結束、所愛之人离世，或突然的告别，都可能讓安全感一下子崩塌。門徒也經歷過這種惧怕。當耶穌告訴他們祂要离開時，他們並不勇敢，而是慌乱、無助。\n\n就在這样的黑暗時刻，耶穌應許赐下另一位保惠師，永遠與他們同在。這不是把祂的同在降級為一個替代品，而是一種更深的親近。耶穌不只是走在他們身邊；藉著聖靈，神要住在他們裡面。門徒起初只感到失去，後来却明白，聖靈的同在使他們不再只是回忆耶穌，而是天天被祂带领、安慰和堅固。\n\n聖靈不是偶尔来探访的客人。祂在孤单的深夜、困惑的决定、無法解释的悲伤裡同在，也在你没有力量禱告時幫助你。祂知道你的心，明白你說不出的叹息，甚至在你軟弱時扶持你轉向神。你不是靠回忆撑下去。神現在與你同在，也永遠不會离開你。這同在是真實的。",
      "actionStep": "停下来问问自己：我今天在哪個地方最覺得孤单？在那裡，我最需要神給我什麼？简单禱告：“聖靈啊，提醒我，我没有被遗弃。”然後安静片刻，留意祂怎样赐下安慰、智慧或力量。",
      "prayer": "親愛的天父，我领受這個恩典：祢赐下聖靈與我們同住。當离别、改變或孤单讓我覺得無依無靠，求祢提醒我，我不是独自面對生活。幫助我聽見聖靈温柔的安慰，也順服祂今天细微的引导。我把心裡那些疲惫的地方帶到祢面前：它們知道正确的話，却仍然很難真正相信。父啊，求祢在那裡陪伴我，使祢的真理比我的羞耻更温暖，比我的惧怕更有力量。幫助我不是遠遠地禱告，而是在已經被祢扶持的信靠中禱告。奉主耶穌的名禱告，阿們。"
    },
    {
      "day": 3,
      "segment": "morning",
      "reference": {
        "book": "Matthew",
        "chapter": 28,
        "verse": "19",
        "full_reference": "Matthew 28:19"
      },
      "modernVersion": "CCB 當代譯本",
      "modernText": "所以，你們要去，使所有民族都成為我的門徒，奉父、子、聖靈的名給他們施洗，",
      "meditation": "耶穌使人作門徒的命令，從祂的權柄開始，而不是從我們的能力開始。祂先宣告：天上地下所有的權柄都赐給我了，然後才說：你們要去。因此，我們的分享信仰不是建立在完美表达、完全自信或擁有所有答案上，而是建立在差遣我們、也與我們同行的復活基督身上。很多時候我們犹豫，是因為覺得自己不夠资格。但耶穌不是要你装作宗教专家，祂邀請你見證自己真實领受的恩典。\n\n你被改變的生命、诚實的故事、在日常中的忠心，都可能成為别人遇見祂的一扇門。神常使用愿意的人，多過使用看起来厉害的人。這使微小的順服也很重要。一次安静的谈話，一個耐心的回答，和别人一起做的一個禱告，或一次不再隐藏耶穌對你意義的時刻，都可能成為祂使命的一部分。萬民聽起来很遠，但門徒训练常常從你眼前的那個人開始。",
      "actionStep": "想一想你身邊一個似乎愿意了解信仰、或正在尋找答案的人。這一周，和他/她自然地聊一次。不要硬把話題變成宗教讨论，只分享一個你的信仰怎样實际幫助過你的例子，並好好聆聽。",
      "prayer": "親愛的天父，我领受祢的恩典：祢藉著主耶穌把使萬民作門徒的使命交托給祂的門徒。求祢赐我們勇氣忠心見證，也赐我們谦卑，使我們始终把人指向基督。在我仍想掌控結果的地方，求祢松開我緊握的手，安静我不安的心。我承認，我常常想要确定感，胜過想要降服。求祢把我重新拉回祢面前，直到順服不再像失去自己，而像回到最愛我的那一位家中。奉主耶穌的名禱告，阿們。"
    },
    {
      "day": 3,
      "segment": "evening",
      "reference": {
        "book": "Genesis",
        "chapter": 1,
        "verse": "2",
        "full_reference": "Genesis 1:2"
      },
      "modernVersion": "CCB",
      "modernText": "大地一片混亂空洞，黑暗籠罩著深洋；神的靈在水面上運行。",
      "meditation": "有些季节不像生命正在被建造，反而像一切都没有形状。計劃散開，熟悉的地面消失，未来也看不見轮廓。你可能經歷失去、等待、停滞，或一種說不清的混乱。黑暗會讓人以為什麼好事都没有發生，但神創造的起頭告訴我們：再空旷的虛空，也不超出神的工作。\n\n在秩序、美丽和果效出現以前，神的靈已經在那裡运行。祂不是遠遠观看，也不是迟迟未到，更不是被混乱難住。祂的同在先于我們能看見的改變。這對每一個感到人生未成形的人，都是安静的應許。你看不見結构時，神仍然知道祂正在塑造什麼；你看不見結果時，祂仍然没有停止工作。黑暗不是祂缺席的證据，空白也不是祂放弃的記号。\n\n聖靈的运行显出能力，也显出温柔。神不需要粗暴闯入你的黑暗；祂已經靠近，守護那些看似脆弱的地方，預備尚未成形的生命。就像母親俯身看顧孩子，又像雙手護住珍贵之物，祂的同在不是冷漠的观察，而是带著目的的守護。你的困惑没有大到祂不能进入，你的等待也没有白费。那位從空虛中創造生命的神，也能在你混乱之處重新带来光、秩序和生命。今天你也许只能看見水面上的黑暗，但神的靈已經在那裡运行。所以，不要急著用眼前的混乱定義整個故事。神常常先在看不見的地方运行，然後才讓我們慢慢看見光怎样出現、道路怎样展開。",
      "actionStep": "寫下你生命中一個還没有形状、讓你困惑或看不清方向的领域。邀請神的靈进入那裡，不是急著做完整計劃，而是带著信靠求祂带领。今天只求一個小小的下一步，走向秩序、光或更深的信心。",
      "prayer": "親愛的天父，求祢讓我看見這個恩典：祢在生命還混乱、没有形状的時候仍然同在。求祢临近我裡面困惑、黑暗、空荡的地方。把秩序、忍耐和盼望吹进我還看不明白的處境裡，使我在看見結果以前就學習信靠祢。在我仍想掌控結果的地方，求祢松開我緊握的手，安静我不安的心。我承認，我常常想要确定感，胜過想要降服。求祢把我重新拉回祢面前，直到順服不再像失去自己，而像回到最愛我的那一位家中。奉主耶穌的名禱告，阿們。"
    }
  ],
  "de": [
    {
      "day": 1,
      "segment": "morning",
      "reference": {
        "book": "John",
        "chapter": 1,
        "verse": "9",
        "full_reference": "John 1:9"
      },
      "modernVersion": "Lutherbibel 2017",
      "modernText": "Das wahre Licht, das jeden Menschen erleuchtet, kam in die Welt.",
      "meditation": "Wenn du heute aufgewacht bist und es sich anfühlt, als wäre das Licht weit weg, begegnet dir dieser Vers mit einer sanften Verheißung. Dunkelheit ist nicht immer dramatisch. Manchmal ist sie eine stille Schwere, eine verwirrte Suche nach Wahrheit oder der Schmerz von Verlust und Versagen. Johannes sagt nicht, dass wir dieser Dunkelheit entkommen, indem wir stärker oder würdiger werden. Er weist uns auf Jesus hin, das wahre Licht, das bereits in die Welt gekommen ist.\n\nDieses Licht ist nicht nur für Menschen, die ihr Leben im Griff haben. Es erleuchtet jeden Menschen, auch dich, wenn dein Glaube klein ist, dein Herz müde wird oder du den nächsten Schritt nicht siehst. Jesus wartet nicht aus der Ferne, bis du ihn erreichst. Er kommt mit seiner Gegenwart in deine Dunkelheit.\n\nSich heute Christus zuzuwenden heißt, seine Wahrheit zum ersten Licht im Herzen werden zu lassen. Du musst das Licht nicht erzeugen oder verdienen. Du darfst dich dem öffnen, der dir nahe gekommen ist.",
      "actionStep": "Benenne einen Bereich, der dunkel oder unklar wirkt. Lade Jesus, das wahre Licht, ein, dir dort heute zu begegnen.",
      "prayer": "Lieber himmlischer Vater, ich danke dir, dass du Jesus gesandt hast, das wahre Licht, das jeden Menschen erleuchtet. Ich preise dich, weil sein Licht in unsere Dunkelheit kommt und uns in deine Wahrheit und Gnade führt. Ich möchte dem nicht nur mit Worten zustimmen und dann unverändert weitergehen. Begegne mir an den verborgenen Orten, wo Angst, Gewohnheit oder Selbstschutz mich noch beherrschen. Lehre mich, diese Orte deiner Liebe zu öffnen, und lass meine Antwort an dich ehrlich, beständig und ganz werden. In Jesu Namen. Amen."
    },
    {
      "day": 1,
      "segment": "evening",
      "reference": {
        "book": "John",
        "chapter": 14,
        "verse": "1",
        "full_reference": "John 14:1"
      },
      "modernVersion": "Lutherbibel 2017",
      "modernText": "Euer Herz erschrecke nicht! Glaubt an Gott und glaubt an mich.",
      "meditation": "Wenn Angst sich in dein Herz setzt, fragt sie selten um Erlaubnis. Sie kann durch eine Trennung kommen, durch den Verlust der Arbeit, durch schlechte Nachrichten über die Gesundheit oder nachts, wenn alle möglichen Sorgen lauter werden. Vielleicht kannst du nicht einmal genau sagen, was du fühlst. Du weißt nur: dein Herz ist unruhig und müde.\n\nJesus sprach solche Worte nicht in einer ruhigen Stunde, sondern kurz bevor Seine Jünger Ihn leiden sehen würden. Ihre Welt sollte erschüttert werden. Trotzdem rief Er sie zum Vertrauen: Wer Gott glaubt, darf auch Ihm glauben.\n\nDieser Glaube leugnet die Not nicht. Er richtet das Herz auf den, dessen Güte und Treue halten, wenn nichts anderes hält. Jesus ist durch tiefste Dunkelheit gegangen, um dich zu retten; Er verlässt dich nicht in deiner heutigen Angst.",
      "actionStep": "Schreibe die Angst oder Sorge auf, die heute am lautesten in deinem Herzen spricht. Bring sie ungefiltert zu Jesus und schreibe daneben einen Satz des Vertrauens: „Herr, ich lege das in deine Hände.“ Kehre zu diesem Satz zurück, wenn die Angst wieder aufsteigt.",
      "prayer": "Lieber himmlischer Vater, ich danke dir, dass mein Herz in Christus nicht von Angst beherrscht werden muss. Wenn Sorgen lauter werden als deine Verheißung, lehre mich, sie ehrlich vor dich zu bringen. Stärke mich durch deine Nähe und hilf mir, heute den nächsten Schritt im Vertrauen zu gehen. Ich möchte dem nicht nur mit Worten zustimmen und dann unverändert weitergehen. Begegne mir an den verborgenen Orten, wo Angst, Gewohnheit oder Selbstschutz mich noch beherrschen. Lehre mich, diese Orte deiner Liebe zu öffnen, und lass meine Antwort an dich ehrlich, beständig und ganz werden. In Jesu Namen. Amen."
    },
    {
      "day": 2,
      "segment": "morning",
      "reference": {
        "book": "Jeremiah",
        "chapter": 29,
        "verse": "11",
        "full_reference": "Jeremiah 29:11"
      },
      "modernVersion": "Lutherbibel 2017",
      "modernText": "Denn ich weiß wohl, welche Gedanken ich von euch habe, spricht der Herr, Gedanken des Friedens und nicht des Unheils, um euch Zukunft und Hoffnung zu geben.",
      "meditation": "Jeremia schrieb diese Worte an Menschen im Exil, nicht an Menschen, deren Leben leicht oder geordnet wirkte. Sie hatten Heimat, Sicherheit und eine klare Zukunft verloren. In diese Ungewissheit hinein sagt Gott: 'Ich weiß, welche Pläne ich für euch habe.' Er sieht ihren Schmerz nicht nur; er hält weiterhin eine Absicht für sie fest. Diese Verheißung leugnet die Not nicht. Sie offenbart Gottes Herz mitten darin. Seine Pläne sollen sein Volk nicht zerstören, sondern zu Frieden, Wiederherstellung und Hoffnung führen.\n\nWenn deine Zukunft unterbrochen wirkt oder vergangene Fehler das letzte Wort zu haben scheinen, erinnert dich dieser Vers: Gott denkt weiterhin barmherzig an dich. Deine Umstände mögen noch offen sein, aber seine Absicht bleibt treu. Nenne dein gegenwärtiges Kapitel also nicht zu schnell das Ende der Geschichte. Für Juda fühlte sich das Exil wie ein Ende an, doch Gott sprach bereits von Zukunft. Dein Warten, deine Trauer oder deine Unsicherheit mögen real sein, aber sie sind nicht stärker als Gottes Bundestreue.",
      "actionStep": "Schreibe in dein Tagebuch oder in deine Notizen: „Gott hat Pläne des Friedens für mich, nicht des Unheils.“ Wenn Zweifel kommen, lies diesen Satz wieder. Wenn möglich, lies ihn morgens und abends, damit diese Wahrheit langsam deinen Blick auf die Zukunft prägt.",
      "prayer": "Lieber himmlischer Vater, ich preise dich, weil du weißt. Ich preise dich, weil du nicht ein gleichgültiger Gott bist, sondern ein Gott voller Liebe mit absichtlichen Plänen für mich. Ich gestehe ein, dass ich manchmal Schwierigkeiten habe, das zu glauben. Meine Geschichte, meine Fehler, die Dinge, die mich unwürdig fühlen lassen, lassen mich zweifeln. Aber du sagst, deine Pläne sind Pläne des Friedens, nicht der Katastrophe. Hilf mir, diese Verheißung anzunehmen. Während ich darauf warte, deine Pläne sich entfalten zu sehen, gib mir Frieden in meinem Herzen. Lass mich dir jeden Tag mehr vertrauen. Ich bringe dir die müden Teile meines Herzens, die die richtigen Worte kennen und sie doch kaum glauben können. Bleib dort bei mir, Vater, und mach deine Wahrheit wärmer als meine Scham und stärker als meine Angst. Hilf mir, nicht aus Distanz zu beten, sondern aus dem Vertrauen, dass du mich bereits hältst. In Jesu Namen. Amen."
    },
    {
      "day": 2,
      "segment": "evening",
      "reference": {
        "book": "John",
        "chapter": 14,
        "verse": "16",
        "full_reference": "John 14:16"
      },
      "modernVersion": "Lutherbibel 2017",
      "modernText": "Und ich werde den Vater bitten, und er wird euch einen anderen Beistand geben, dass er bei euch bleibt auf ewig—",
      "meditation": "Wenn ein wichtiger Mensch geht, kann die Leere größer wirken als alles andere. Ein Umzug, eine Trennung, ein Todesfall oder ein plötzliches Abschiednehmen kann jedes Gefühl von Sicherheit erschüttern. Die Jünger kannten diese Angst. Als Jesus ihnen sagte, dass Er gehen würde, waren sie nicht stark und gefasst, sondern verwirrt, erschrocken und hilflos.\n\nGerade in diese dunkle Stunde hinein versprach Jesus den anderen Beistand, der für immer bei ihnen bleiben würde. Das war kein schwächerer Ersatz für Seine Nähe, sondern eine tiefere Form der Gemeinschaft. Jesus würde nicht nur neben ihnen gehen; durch den Heiligen Geist wollte Gott in ihnen wohnen. Was zuerst wie Verlust aussah, wurde später zur Quelle von Trost, Leitung, Mut und innerer Kraft.\n\nDer Heilige Geist ist kein gelegentlicher Besucher. Er ist da in einsamen Nächten, in schweren Entscheidungen, in Trauer, die du kaum erklären kannst, und auch dann, wenn dir die Worte zum Beten fehlen. Er kennt dein Herz und versteht dein unausgesprochenes Seufzen. Du musst nicht nur von vergangenen Erfahrungen leben. Gott ist jetzt bei dir, und Er wird dich nicht verlassen. Gerade deshalb darf auch deine heutige Einsamkeit vor Ihm ausgesprochen werden.",
      "actionStep": "Halte inne und frage dich: Wo fühle ich mich heute am einsamsten, und was brauche ich dort von Gott? Bete schlicht: „Heiliger Geist, erinnere mich daran, dass ich nicht verlassen bin.“ Bleib einen Moment still und achte auf Trost, Weisheit oder Kraft, die Er schenkt.",
      "prayer": "Lieber himmlischer Vater, ich preise dich, weil du deinen Geist gibst, um bei uns zu bleiben. Wenn Abschied, Veränderung oder Einsamkeit mich schutzlos fühlen lassen, erinnere mich daran, dass ich das Leben nicht allein tragen muss. Hilf mir, den Trost des Geistes zu empfangen und seiner leisen Führung heute zu folgen. Ich bringe dir die müden Teile meines Herzens, die die richtigen Worte kennen und sie doch kaum glauben können. Bleib dort bei mir, Vater, und mach deine Wahrheit wärmer als meine Scham und stärker als meine Angst. Hilf mir, nicht aus Distanz zu beten, sondern aus dem Vertrauen, dass du mich bereits hältst. In Jesu Namen. Amen."
    },
    {
      "day": 3,
      "segment": "morning",
      "reference": {
        "book": "Matthew",
        "chapter": 28,
        "verse": "19",
        "full_reference": "Matthew 28:19"
      },
      "modernVersion": "Lutherbibel 2017",
      "modernText": "Darum gehet hin und machet zu Jüngern alle Völker, und täufet sie auf den Namen des Vaters und des Sohnes und des heiligen Geistes,",
      "meditation": "Der Missionsauftrag beginnt mit der Autorität Jesu, nicht mit unserer Fähigkeit. Bevor er sagt: 'Geht', erklärt er, dass ihm alle Macht im Himmel und auf Erden gegeben ist. Darum ruht unser Zeugnis nicht auf perfekten Worten, vollständigem Selbstvertrauen oder darauf, jede Antwort zu haben. Es ruht auf dem auferstandenen Christus, der uns sendet und mit uns geht. Viele von uns zögern, weil wir uns ungeeignet fühlen.\n\nDoch Jesus bittet dich nicht, eine religiöse Rolle zu spielen; er lädt dich ein, von dem zu zeugen, was du empfangen hast. Dein verändertes Leben, deine ehrliche Geschichte und deine stille Treue an gewöhnlichen Orten können für einen anderen Menschen eine Tür zu ihm werden. Gott gebraucht oft eher bereite als beeindruckende Menschen. Das verleiht kleinem Gehorsam Würde.",
      "actionStep": "Denke an eine Person in deinem Leben, die offen oder suchend wirkt. Beginne diese Woche ein natürliches Gespräch mit ihr. Erzwinge kein religiöses Thema; erzähle einfach, wie dein Glaube dir praktisch geholfen hat, und höre gut zu.",
      "prayer": "Lieber himmlischer Vater, ich empfange diese Gnade: Jesus seinen Jüngern den Auftrag gegeben hat, alle Völker zu Jüngern zu machen. Gib uns Mut, treu Zeugnis zu geben, und Demut, andere auf Christus hinzuweisen. Wo ich Ergebnisse kontrollieren will, öffne meine Hände und beruhige mein Herz. Ich bekenne, dass ich oft mehr nach Sicherheit verlange als nach Hingabe. Zieh mich zu dir zurück, bis Gehorsam sich weniger wie ein Verlust anfühlt und mehr wie Heimkehr zu dem, der mich am besten liebt. In Jesu Namen. Amen."
    },
    {
      "day": 3,
      "segment": "evening",
      "reference": {
        "book": "Genesis",
        "chapter": 1,
        "verse": "2",
        "full_reference": "Genesis 1:2"
      },
      "modernVersion": "Lutherbibel 2017",
      "modernText": "Und die Erde war wüst und leer, und Finsternis lag auf der Urflut, und der Geist Gottes schwebte über dem Wasser.",
      "meditation": "Manche Zeiten fühlen sich nicht wie Aufbau an, sondern formlos. Pläne lösen sich auf, vertrauter Boden verschwindet, und die Zukunft hat keine klare Gestalt. Dunkelheit kann dich glauben lassen, dass nichts Gutes geschieht. Doch Gottes Schöpfungsgeschichte zeigt: Selbst Leere und Chaos liegen nicht außerhalb Seines Wirkens.\n\nBevor Ordnung, Schönheit und Frucht sichtbar wurden, war Gottes Geist schon gegenwärtig. Er schaute nicht nur aus der Ferne zu, kam nicht zu spät und war von der Unordnung nicht überfordert. Seine Nähe beginnt oft, bevor wir Veränderung erkennen. Wenn du keine Struktur siehst, weiß Gott dennoch, was Er formt; wenn du kein Ergebnis siehst, arbeitet Er weiter.\n\nSein Wirken ist kraftvoll und zugleich behutsam. Gott kann in deine Dunkelheit kommen, ohne dich zu zerbrechen. Er bewahrt, was schwach aussieht, und bereitet Leben vor, das noch keine Gestalt hat. Auch der Anfang, der dir ungeordnet erscheint, kann in Seinen Händen ein Anfang von Leben sein.",
      "actionStep": "Nenne einen Bereich deines Lebens, der unfertig, verworren oder ohne klare Gestalt wirkt. Lade Gottes Geist dorthin ein, nicht mit einem erzwungenen Plan, sondern mit Vertrauen. Bitte Ihn um einen kleinen Schritt zu Ordnung, Licht oder geduldiger Hoffnung.",
      "prayer": "Lieber himmlischer Vater, ich empfange diese Gnade: dein Geist gegenwärtig ist, auch wenn mein Leben ungeordnet und unfertig wirkt. Komm den verwirrten, dunklen und leeren Stellen in mir nahe. Atme Ordnung, Geduld und Hoffnung in das, was ich noch nicht verstehe, und lehre mich, deinem Wirken zu vertrauen. Wo ich Ergebnisse kontrollieren will, öffne meine Hände und beruhige mein Herz. Ich bekenne, dass ich oft mehr nach Sicherheit verlange als nach Hingabe. Zieh mich zu dir zurück, bis Gehorsam sich weniger wie ein Verlust anfühlt und mehr wie Heimkehr zu dem, der mich am besten liebt. In Jesu Namen. Amen."
    }
  ],
  "fr": [
    {
      "day": 1,
      "segment": "morning",
      "reference": {
        "book": "John",
        "chapter": 1,
        "verse": "9",
        "full_reference": "John 1:9"
      },
      "modernVersion": "PDV",
      "modernText": "Cette lumière était la véritable lumière, celle qui éclaire tout être humain.",
      "meditation": "Si tu t'es réveillée aujourd'hui avec l'impression que la lumière est loin, ce verset vient à ta rencontre avec une douce promesse. L’obscurité n’a pas toujours quelque chose de spectaculaire. Parfois, elle est une lourdeur silencieuse, une recherche confuse de la vérité, ou la douleur d’une perte ou d’un échec. Jean ne nous dit pas d’en sortir en devenant plus forts ou plus dignes. Il nous montre Jésus, la vraie Lumière déjà venue dans le monde.\n\nCette Lumière n’est pas réservée à ceux qui semblent avoir leur vie en ordre. Elle éclaire chacun, y compris toi lorsque ta foi paraît faible, lorsque ton cœur est fatigué ou lorsque tu ne vois pas le prochain pas. Jésus n’attend pas au loin que tu l’atteignes. Il entre dans ton obscurité par sa présence.\n\nAujourd’hui, te tourner vers Christ, c’est laisser sa vérité devenir la première lumière de ton cœur. Tu n’as pas à produire cette lumière ni à la mériter. Tu peux simplement t’ouvrir à Celui qui s’est approché.",
      "actionStep": "Nomme un domaine de ta vie qui semble sombre ou confus. Invite Jésus, la vraie Lumière, à t’y rencontrer aujourd’hui.",
      "prayer": "Cher Père céleste, je te remercie d’avoir envoyé Jésus, la vraie Lumière qui éclaire tout être humain. Je te loue parce que sa lumière entre dans nos ténèbres et nous conduit dans ta vérité et ta grâce. Je ne veux pas être d’accord seulement avec des mots puis repartir inchangée. Rejoins-moi dans les lieux cachés où la peur, l’habitude ou l’autoprotection me gouvernent encore. Apprends-moi à ouvrir ces lieux à ton amour, et que ma réponse à toi devienne honnête, stable et entière. Au nom de Jésus, amen."
    },
    {
      "day": 1,
      "segment": "evening",
      "reference": {
        "book": "John",
        "chapter": 14,
        "verse": "1",
        "full_reference": "John 14:1"
      },
      "modernVersion": "PDV",
      "modernText": "Que votre cœur ne soit pas troublé. Croyez en Dieu, et croyez aussi en moi.",
      "meditation": "Quand l'anxiété s'installe, elle demande rarement la permission. Elle peut venir par une rupture, la perte d'un travail, une mauvaise nouvelle médicale, ou ces heures de nuit où chaque peur devient plus bruyante. Tu ne sais peut-être même pas nommer ce que tu ressens; tu sais seulement que ton cœur est agité, fatigué et effrayé.\n\nJésus a parlé de consolation à ses disciples dans un moment qui n'avait rien de paisible. Il savait qu'ils Le verraient bientôt arrêté et que la croix bouleverserait tout ce qu'ils comprenaient. Leur situation ne deviendrait pas facile tout de suite, mais Jésus les appelait à faire confiance: croire en Dieu et croire aussi en Lui. Il ne les rassurait pas en disant que tout se passerait comme prévu; Il ramenait leur cœur vers Lui-même.\n\nCette foi ne nie pas la difficulté. Elle tourne le cœur vers le Seigneur qui reste bon, fidèle et puissant quand tout vacille. C'est pourquoi, même si ton émotion ne change pas immédiatement, tu peux respirer devant Lui et laisser Sa présence porter ce que ta force ne peut plus porter.",
      "actionStep": "Écris la peur ou l’inquiétude qui parle le plus fort dans ton cœur aujourd’hui. Apporte-la à Jésus sans la polir, puis écris à côté une phrase de confiance : « Seigneur, je remets cela entre Tes mains. » Reviens à cette phrase chaque fois que la peur remonte.",
      "prayer": "Cher Père céleste, je te loue parce qu'en Christ mon cœur n'a pas à être gouverné par la peur. Quand les soucis parlent plus fort que ta promesse, apprends-moi à les déposer honnêtement devant toi. Affermis-moi par ta présence et aide-moi à avancer aujourd'hui dans la confiance. Je ne veux pas être d’accord seulement avec des mots puis repartir inchangée. Rejoins-moi dans les lieux cachés où la peur, l’habitude ou l’autoprotection me gouvernent encore. Apprends-moi à ouvrir ces lieux à ton amour, et que ma réponse à toi devienne honnête, stable et entière. Au nom de Jésus, amen."
    },
    {
      "day": 2,
      "segment": "morning",
      "reference": {
        "book": "Jeremiah",
        "chapter": 29,
        "verse": "11",
        "full_reference": "Jeremiah 29:11"
      },
      "modernVersion": "PDV",
      "modernText": "\"Je connais bien les projets que j'ai pour vous, déclare l'Éternel, des projets de paix et non de malheur, pour vous donner un avenir et de l'espérance.\"",
      "meditation": "Jérémie a écrit ces paroles à des personnes en exil, non à des personnes dont la vie semblait facile ou bien rangée. Elles avaient perdu leur maison, leur sécurité et une vision claire de l’avenir. Au cœur de cette incertitude, Dieu dit : 'Je connais les projets que j’ai formés pour vous.' Il ne fait pas qu’observer leur douleur; il porte encore un dessein pour elles. Cette promesse ne nie pas l’épreuve. Elle révèle le cœur de Dieu au milieu d’elle. Ses projets ne visent pas à détruire son peuple, mais à le conduire vers la paix, la restauration et l’espérance.\n\nQuand ton avenir semble interrompu, ou que tes erreurs passées paraissent avoir le dernier mot, ce verset rappelle que Dieu continue de penser à toi avec miséricorde. Tes circonstances peuvent rester inachevées, mais son intention demeure fidèle. Ne te hâte donc pas d’appeler ton chapitre présent la fin de l’histoire. Pour Juda, l’exil ressemblait à une fin, mais Dieu parlait déjà d’avenir. Ton attente, ta peine ou ton incertitude peuvent être réelles, mais elles ne sont pas plus fortes que la fidélité de l’alliance de Dieu.",
      "actionStep": "Écris dans ton journal ou dans les notes de ton téléphone : « Dieu a des projets de paix pour moi, non de malheur. » Quand le doute revient, relis cette phrase. Si tu peux, relis-la matin et soir, et laisse cette vérité changer peu à peu ta manière de regarder l’avenir.",
      "prayer": "Cher Père céleste, je te loue pour ta promesse que tes plans pour nous sont pour le bien — remplis d'espoir et d'un avenir prospère. Tu tiens nos jours dans tes mains. Tes desseins ne nous blessent pas mais nous établissent dans l'espoir. Tes plans ne faillissent jamais. Tu écris l'histoire avec espoir. Quel bon Père tu es. Je t’apporte les parties fatiguées de mon cœur qui connaissent les bons mots mais peinent à les croire. Reste avec moi là, Père, et rends ta vérité plus chaude que ma honte et plus forte que ma peur. Aide-moi à prier non depuis la distance, mais depuis la confiance que je suis déjà portée par toi. Au nom de Jésus, amen."
    },
    {
      "day": 2,
      "segment": "evening",
      "reference": {
        "book": "John",
        "chapter": 14,
        "verse": "16",
        "full_reference": "John 14:16"
      },
      "modernVersion": "PDV",
      "modernText": "Et moi, je vais demander au Père, et il vous donnera un autre Défenseur pour être avec vous à jamais.",
      "meditation": "Quand une personne importante s'en va, l'absence peut sembler remplir toute la pièce. Un déménagement, une rupture, un décès ou un départ soudain peut faire disparaître tout sentiment de sécurité. Les disciples ont connu cette peur. Lorsque Jésus leur a dit qu'Il allait partir, ils n'étaient pas courageux et calmes; ils étaient troublés, désorientés et remplis de tristesse.\n\nC'est précisément dans cette heure sombre que Jésus a promis un autre Consolateur, présent avec eux pour toujours. Ce n'était pas une présence moins forte, mais une proximité plus profonde. Jésus ne marcherait pas seulement à côté d'eux; par le Saint-Esprit, Dieu habiterait en eux. Ce qui ressemblait d'abord à une perte deviendrait une source de consolation, de direction, de courage et de force intérieure.\n\nLe Saint-Esprit n'est pas un visiteur occasionnel. Il est là dans les nuits solitaires, les décisions confuses, les peines impossibles à expliquer, et même lorsque tu n'as plus de mots pour prier. Il connaît ton cœur et comprend tes soupirs. Tu ne vis pas seulement de souvenirs. Dieu est avec toi maintenant, et Il ne t'abandonnera pas. C'est pourquoi ta solitude d'aujourd'hui peut aussi être nommée devant Dieu. Tu n'as pas seulement des souvenirs à garder; tu peux recevoir une présence vivante.",
      "actionStep": "Arrête-toi et demande-toi : où est-ce que je me sens le plus seule aujourd’hui, et de quoi ai-je besoin de la part de Dieu à cet endroit ? Prie simplement : « Saint-Esprit, rappelle-moi que je ne suis pas abandonnée. » Reste en silence un instant et remarque la consolation, la sagesse ou la force qu’Il donne.",
      "prayer": "Cher Père céleste, je te loue de nous donner ton Esprit pour demeurer avec nous. Quand l'absence, le changement ou la solitude me font me sentir sans appui, rappelle-moi que je n'affronte pas la vie seule. Aide-moi à recevoir la consolation de l'Esprit et à suivre aujourd'hui sa direction discrète. Je t’apporte les parties fatiguées de mon cœur qui connaissent les bons mots mais peinent à les croire. Reste avec moi là, Père, et rends ta vérité plus chaude que ma honte et plus forte que ma peur. Aide-moi à prier non depuis la distance, mais depuis la confiance que je suis déjà portée par toi. Au nom de Jésus, amen."
    },
    {
      "day": 3,
      "segment": "morning",
      "reference": {
        "book": "Matthew",
        "chapter": 28,
        "verse": "19",
        "full_reference": "Matthew 28:19"
      },
      "modernVersion": "PDV",
      "modernText": "Allez donc, faites de toutes les nations des disciples. Baptisez-les au nom du Père, du Fils et du Saint-Esprit.",
      "meditation": "Va et fais de toutes les nations des disciples. Quand tu lis ces paroles, peut-être que le doute apparaît. Mais écoute ce que Jésus a dit avant: \"Toute autorité m'a été donnée.\" Cela ne dit pas que tu dois avoir toutes les réponses. Cela dit: j'ai toute l'autorité, et je vais avec toi. Partager la foi n'exige pas un doctorat en théologie. Cela exige une vraie histoire. Peut-être que ton amie lutte au travail, et tu lui racontes comment la prière t'a aidée.\n\nPeut-être que quelqu'un est en deuil, et ton honnêteté sur ta propre douleur ouvre une conversation sur l'espoir. Peut-être que tu vis simplement différemment—avec plus de paix, plus de pardon, plus de joie—et quelqu'un demande pourquoi. Ta voix compte. Ton petit témoignage, ta foi authentique, ta volonté de partager ce que Jésus a fait pour toi—cela change des vies.",
      "actionStep": "Pense à une personne dans ta vie qui semble ouverte ou en recherche. Cette semaine, commence une conversation naturelle avec elle. Ne force pas une discussion religieuse; partage simplement une manière concrète dont ta foi t’a aidée, et écoute bien.",
      "prayer": "Cher Père céleste, je reçois cette grâce : Jésus a confié à ses disciples la mission de faire de toutes les nations des disciples. Donne-nous le courage de témoigner fidèlement et l’humilité de conduire les autres vers Christ. Là où je cherche encore à contrôler les résultats, détends mes mains et apaise mon cœur. Je reconnais que je désire souvent la certitude plus que l’abandon. Ramène-moi vers toi jusqu’à ce que l’obéissance ressemble moins à une perte de moi-même qu’à un retour à la maison auprès de Celui qui m’aime le mieux. Au nom de Jésus, amen."
    },
    {
      "day": 3,
      "segment": "evening",
      "reference": {
        "book": "Genesis",
        "chapter": 1,
        "verse": "2",
        "full_reference": "Genesis 1:2"
      },
      "modernVersion": "PDV",
      "modernText": "La terre était en désordre total, les ténèbres couvraient l'abîme, et l'Esprit de Dieu se mouvait sur les eaux.",
      "meditation": "Certaines saisons ne ressemblent pas à une vie en construction; elles semblent sans forme. Les projets se défont, les repères disparaissent, et l'avenir n'a plus de contours clairs. L'obscurité peut te faire croire que rien de bon ne se passe. Pourtant, le commencement de la création nous rappelle ceci: même le vide et le chaos ne sont pas hors de l'action de Dieu.\n\nAvant que l'ordre, la beauté et le fruit apparaissent, l'Esprit de Dieu était déjà présent. Il ne regardait pas de loin, Il n'arrivait pas en retard, et Il n'était pas dépassé par le désordre. Sa présence commence souvent avant que nous voyions le changement. Quand tu ne vois pas encore la forme, Dieu sait ce qu'Il façonne; quand tu ne vois pas le résultat, Il continue d'agir.\n\nSon œuvre est à la fois puissante et douce. Dieu entre dans ton obscurité sans t'écraser. Même le commencement qui te semble désordonné peut devenir, entre Ses mains, le début d'une vie nouvelle.",
      "actionStep": "Nomme un domaine de ta vie qui semble inachevé, confus ou sans forme claire. Invite l’Esprit de Dieu à y venir, non avec un plan forcé, mais avec confiance. Demande-Lui un petit pas vers l’ordre, la lumière ou une foi patiente aujourd’hui.",
      "prayer": "Cher Père céleste, je reçois cette grâce : ton Esprit est présent même quand ma vie paraît informe et inachevée. Approche-toi des lieux confus, sombres et vides en moi. Souffle ordre, patience et espérance dans ce que je ne comprends pas encore, et apprends-moi à faire confiance à ton œuvre. Là où je cherche encore à contrôler les résultats, détends mes mains et apaise mon cœur. Je reconnais que je désire souvent la certitude plus que l’abandon. Ramène-moi vers toi jusqu’à ce que l’obéissance ressemble moins à une perte de moi-même qu’à un retour à la maison auprès de Celui qui m’aime le mieux. Au nom de Jésus, amen."
    }
  ],
  "es": [
    {
      "day": 1,
      "segment": "morning",
      "reference": {
        "book": "John",
        "chapter": 1,
        "verse": "9",
        "full_reference": "John 1:9"
      },
      "modernVersion": "NVI",
      "modernText": "Esa luz verdadera que ilumina a todos viene al mundo.",
      "meditation": "Si hoy despertaste sintiendo que la luz está lejos, este versículo se acerca con una promesa tierna. La oscuridad no siempre es dramática. A veces es un peso silencioso, una búsqueda confusa de la verdad, o el dolor de una pérdida o un fracaso. Juan no nos dice que escapemos de esa oscuridad siendo más fuertes o más dignos. Nos señala a Jesús, la Luz verdadera que ya vino al mundo.\n\nEsta Luz no está reservada para quienes tienen la vida en orden. Ilumina a todos, también a ti cuando tu fe se siente pequeña, tu corazón está cansado o no ves el siguiente paso. Jesús no espera lejos hasta que logres alcanzarlo. Él entra en tu oscuridad con su presencia.\n\nHoy, volverte hacia Cristo significa dejar que su verdad sea la primera luz en tu corazón. No tienes que producir la luz ni ganártela. Solo necesitas abrirte a Aquel que se ha acercado.",
      "actionStep": "Nombra un área de tu vida que se sienta oscura o confusa. Invita a Jesús, la Luz verdadera, a encontrarte allí hoy.",
      "prayer": "Querido Padre celestial, te doy gracias por enviar a Jesús, la luz verdadera que ilumina a todos. Te alabo porque su luz entra en nuestra oscuridad y nos conduce a tu verdad y a tu gracia. No quiero estar de acuerdo con esto solo de palabra y luego seguir igual. Encuéntrame en los lugares escondidos donde el miedo, la costumbre o la autoprotección todavía me gobiernan. Enséñame a abrir esos lugares a tu amor, y que mi respuesta a ti sea sincera, firme e íntegra. En el nombre de Jesús, amén."
    },
    {
      "day": 1,
      "segment": "evening",
      "reference": {
        "book": "John",
        "chapter": 14,
        "verse": "1",
        "full_reference": "John 14:1"
      },
      "modernVersion": "NVI",
      "modernText": "No dejen que se turbe su corazón. Crean en Dios, y crean también en mí.",
      "meditation": "Cuando la ansiedad se instala, rara vez pide permiso. Puede llegar por una ruptura, la pérdida de un trabajo, una noticia médica difícil o esas horas de la noche en que cada temor parece crecer. Tal vez ni siquiera sabes nombrar lo que sientes; solo sabes que tu corazón está inquieto, cansado y asustado.\n\nJesús habló palabras de consuelo a sus discípulos en un momento nada tranquilo. Sabía que pronto lo verían arrestado y que la cruz sacudiría todo lo que entendían. Su situación no se volvería fácil de inmediato, pero Jesús los llamó a confiar: creer en Dios y creer también en Él. No los consoló diciendo que todo saldría como esperaban, sino llevándolos de nuevo a Él mismo.\n\nEsa fe no niega la dificultad. Vuelve el corazón hacia el Señor que sigue siendo bueno, fiel y poderoso cuando todo tiembla. Él no te deja sola en la ansiedad de hoy. Por eso, aun cuando tu emoción no cambia de inmediato, puedes respirar delante de Él y dejar que su presencia sostenga lo que tu fuerza no puede cargar.",
      "actionStep": "Escribe el temor o la preocupación que hoy habla más fuerte en tu corazón. Llévalo a Jesús sin arreglarlo ni suavizarlo, y escribe al lado una frase de confianza: «Señor, pongo esto en tus manos». Vuelve a esa frase cada vez que el miedo se levante.",
      "prayer": "Querido Padre celestial, te doy gracias porque en Cristo mi corazón no tiene que vivir gobernado por el miedo. Cuando las preocupaciones suenen más fuerte que tu promesa, enséñame a traerlas con honestidad delante de ti. Afírmame con tu presencia y ayúdame a dar hoy el siguiente paso confiando en ti. No quiero estar de acuerdo con esto solo de palabra y luego seguir igual. Encuéntrame en los lugares escondidos donde el miedo, la costumbre o la autoprotección todavía me gobiernan. Enséñame a abrir esos lugares a tu amor, y que mi respuesta a ti sea sincera, firme e íntegra. En el nombre de Jesús, amén."
    },
    {
      "day": 2,
      "segment": "morning",
      "reference": {
        "book": "Jeremiah",
        "chapter": 29,
        "verse": "11",
        "full_reference": "Jeremiah 29:11"
      },
      "modernVersion": "NVI",
      "modernText": "\"Porque sé los planes que tengo para ustedes —afirma el Señor—, planes de bienestar y no de calamidad, a fin de darles un futuro y una esperanza.\"",
      "meditation": "Jeremías escribió estas palabras a personas en el exilio, no a personas cuya vida se sentía fácil u ordenada. Habían perdido hogar, seguridad y un futuro claro. En medio de esa incertidumbre, Dios dice: 'Yo sé los planes que tengo para ustedes.' Él no solo observa su dolor; todavía sostiene un propósito para ellos. Esta promesa no niega la dificultad. Revela el corazón de Dios dentro de ella. Sus planes no son para destruir a su pueblo, sino para conducirlo hacia paz, restauración y esperanza.\n\nCuando tu futuro parece interrumpido, o cuando tus errores pasados parecen tener la última palabra, este versículo te recuerda que Dios no ha dejado de pensar en ti con misericordia. Tus circunstancias quizá sigan inconclusas, pero su intención permanece fiel. Así que no te apresures a llamar final al capítulo que estás viviendo. Para Judá, el exilio parecía un final, pero Dios ya estaba hablando de futuro. Tu espera, dolor o incertidumbre pueden ser reales, pero no son más fuertes que la fidelidad del pacto de Dios.",
      "actionStep": "Escribe en tu diario o en las notas del teléfono: “Dios tiene planes de paz para mí, no de desastre.” Cuando aparezca la duda, vuelve a leerlo. Si puedes, léelo por la mañana y por la noche, dejando que esta verdad cambie poco a poco tu manera de mirar el futuro.",
      "prayer": "Querido Padre celestial, te alabo por tu promesa de que tus planes para nosotros son para bien — llenos de esperanza y un futuro próspero. Sostienes nuestros días en tus manos. Tus propósitos no son para dañarnos sino para establecernos en esperanza. Tus planes nunca fallan. Escribes la historia con esperanza. Qué buen Padre eres. Te traigo las partes cansadas de mi corazón que conocen las palabras correctas, pero luchan por creerlas. Quédate conmigo allí, Padre, y haz que tu verdad sea más cálida que mi vergüenza y más fuerte que mi miedo. Ayúdame a orar no desde la distancia, sino desde la confianza de que ya estoy sostenida por ti. En el nombre de Jesús, amén."
    },
    {
      "day": 2,
      "segment": "evening",
      "reference": {
        "book": "John",
        "chapter": 14,
        "verse": "16",
        "full_reference": "John 14:16"
      },
      "modernVersion": "NVI",
      "modernText": "Y yo le pediré al Padre, y él les dará otro Consolador para que los acompañe siempre.",
      "meditation": "Cuando alguien importante se va, la ausencia puede llenar toda la habitación. Una mudanza, una ruptura, una muerte o una despedida repentina puede hacer que tu sentido de seguridad se derrumbe. Los discípulos conocieron ese miedo. Cuando Jesús les dijo que se iba, no reaccionaron con valentía tranquila, sino con confusión, tristeza y temor.\n\nEn esa hora oscura, Jesús prometió enviar a otro Consolador para estar con ellos para siempre. No era un reemplazo menor de su presencia, sino una cercanía más profunda. Jesús no solo caminaría junto a ellos; por el Espíritu Santo, Dios viviría en ellos. Lo que al principio parecía pérdida se convertiría en consuelo, guía, valentía y fuerza interior.\n\nEl Espíritu Santo no es un visitante ocasional. Está contigo en las noches solitarias, en decisiones confusas, en tristezas que no sabes explicar y cuando no tienes palabras para orar. Él conoce tu corazón y entiende tus suspiros. No vives sostenida solo por recuerdos. Dios está contigo ahora y no te abandonará. Por eso tu soledad de hoy también puede ser nombrada delante de Dios. No tienes que sostenerte solo con recuerdos; puedes pedir una ayuda viva y presente.",
      "actionStep": "Detente y pregúntate: ¿Dónde me siento más sola hoy, y qué necesito de Dios en ese lugar? Ora con sencillez: «Espíritu Santo, recuérdame que no estoy abandonada». Quédate en silencio un momento y observa si Él trae consuelo, sabiduría o fuerza.",
      "prayer": "Querido Padre celestial, te alabo por darnos tu Espíritu para permanecer con nosotros. Cuando la ausencia, el cambio o la soledad me hagan sentir desprotegida, recuérdame que no enfrento la vida a solas. Ayúdame a recibir el consuelo del Espíritu y a seguir hoy su guía suave. Te traigo las partes cansadas de mi corazón que conocen las palabras correctas, pero luchan por creerlas. Quédate conmigo allí, Padre, y haz que tu verdad sea más cálida que mi vergüenza y más fuerte que mi miedo. Ayúdame a orar no desde la distancia, sino desde la confianza de que ya estoy sostenida por ti. En el nombre de Jesús, amén."
    },
    {
      "day": 3,
      "segment": "morning",
      "reference": {
        "book": "Matthew",
        "chapter": 28,
        "verse": "19",
        "full_reference": "Matthew 28:19"
      },
      "modernVersion": "NVI",
      "modernText": "Por lo tanto, vayan y hagan discípulos de todas las naciones, bautizándolos en el nombre del Padre y del Hijo y del Espíritu Santo,",
      "meditation": "La Gran Comisión comienza con la autoridad de Jesús, no con nuestra capacidad. Antes de decir 'vayan', Él declara que toda autoridad en el cielo y en la tierra le pertenece. Eso significa que nuestro testimonio no descansa en palabras perfectas, confianza completa o tener todas las respuestas. Descansa en el Cristo resucitado que nos envía y va con nosotros. Muchos dudamos porque nos sentimos poco preparados.\n\nPero Jesús no te pide que desempeñes un papel religioso; te invita a dar testimonio de lo que has recibido. Tu vida transformada, tu historia sincera y tu fidelidad silenciosa en lugares ordinarios pueden abrir una puerta para que alguien más lo encuentre. Dios suele usar más a personas disponibles que a personas impresionantes. Esto da dignidad a la obediencia pequeña.",
      "actionStep": "Piensa en una persona de tu vida que parezca abierta o en búsqueda. Esta semana, empieza una conversación natural con ella. No fuerces una charla religiosa; comparte simplemente una forma práctica en que tu fe te ha ayudado, y escucha con atención.",
      "prayer": "Querido Padre celestial, recibo esta gracia: Jesús confió a sus discípulos la misión de hacer discípulos de todas las naciones. Danos valor para dar testimonio fielmente y humildad para dirigir a otros hacia Cristo. Donde sigo intentando controlar los resultados, afloja mis manos y aquieta mi corazón. Confieso que muchas veces deseo más la certeza que la entrega. Atráeme de nuevo a ti hasta que la obediencia se sienta menos como perderme y más como volver a casa con Aquel que más me ama. En el nombre de Jesús, amén."
    },
    {
      "day": 3,
      "segment": "evening",
      "reference": {
        "book": "Genesis",
        "chapter": 1,
        "verse": "2",
        "full_reference": "Genesis 1:2"
      },
      "modernVersion": "NVI",
      "modernText": "La tierra era un caos total, las tinieblas cubrían el abismo, y el Espíritu de Dios se movía sobre la superficie de las aguas.",
      "meditation": "Hay temporadas que no se sienten como una vida en construcción, sino como algo sin forma. Los planes se disuelven, el suelo conocido desaparece y el futuro no tiene contorno claro. La oscuridad puede hacerte pensar que nada bueno está sucediendo, pero el comienzo de la historia de Dios muestra otra cosa: el vacío no es demasiado vacío para Él.\n\nAntes de que hubiera orden, belleza o fruto visible, el Espíritu de Dios ya estaba presente. No estaba lejos ni confundido por el caos. Su presencia llegó antes de que la transformación pudiera verse. Esa es una promesa silenciosa para los tiempos en que tu vida se siente incompleta.\n\nEl Espíritu que se mueve sobre lo informe revela poder y ternura. Dios no necesita irrumpir con violencia en tu oscuridad; ya está cerca, guardando lo frágil y preparando lo que aún no tiene forma. Tu espera no está desperdiciada. Bajo Su mano, puede volver la luz, el orden y la vida.",
      "actionStep": "Nombra un área de tu vida que se siente incompleta, confusa o sin forma clara. Invita allí al Espíritu de Dios, no con un plan forzado, sino con confianza. Pídele un paso pequeño hacia orden, luz o una fe paciente hoy.",
      "prayer": "Querido Padre celestial, recibo esta gracia: tu Espíritu está presente aun cuando mi vida parece desordenada e incompleta. Acércate a los lugares confundidos, oscuros y vacíos dentro de mí. Sopla orden, paciencia y esperanza en lo que todavía no entiendo, y enséñame a confiar en tu obra. Donde sigo intentando controlar los resultados, afloja mis manos y aquieta mi corazón. Confieso que muchas veces deseo más la certeza que la entrega. Atráeme de nuevo a ti hasta que la obediencia se sienta menos como perderme y más como volver a casa con Aquel que más me ama. En el nombre de Jesús, amén."
    }
  ],
  "pt": [
    {
      "day": 1,
      "segment": "morning",
      "reference": {
        "book": "John",
        "chapter": 1,
        "verse": "9",
        "full_reference": "John 1:9"
      },
      "modernVersion": "NVI-PT",
      "modernText": "A verdadeira luz que ilumina todos vinha chegando ao mundo.",
      "meditation": "Se hoje você acordou sentindo que a luz está longe, este versículo se aproxima com uma promessa terna. A escuridão nem sempre parece dramática. Às vezes, é um peso silencioso, uma busca confusa pela verdade, ou a dor de uma perda ou de um fracasso. João não nos diz que saímos dessa escuridão sendo mais fortes ou mais dignos. Ele aponta para Jesus, a verdadeira Luz que já veio ao mundo.\n\nEssa Luz não é reservada para quem tem a vida em ordem. Ela ilumina todos, inclusive tu, quando tua fé parece pequena, teu coração está cansado ou o próximo passo não está claro. Jesus não espera de longe até que consigas alcançá-lo. Ele entra na tua escuridão com sua presença.\n\nHoje, voltar-te para Cristo significa deixar que sua verdade seja a primeira luz no teu coração. Tu não precisas produzir essa luz nem merecê-la. Só precisas abrir-te Àquele que se aproximou.",
      "actionStep": "Dá nome a uma área da tua vida que parece escura ou confusa. Convida Jesus, a verdadeira Luz, a encontrar-te ali hoje.",
      "prayer": "Querido Pai celestial, eu te agradeço por enviares Jesus, a verdadeira Luz que ilumina todos. Eu te louvo porque a sua luz entra em nossa escuridão e nos conduz à tua verdade e graça. Não quero concordar com isso apenas em palavras e depois continuar igual. Encontra-me nos lugares escondidos onde o medo, o hábito ou a autoproteção ainda me governam. Ensina-me a abrir esses lugares ao teu amor, e que minha resposta a ti se torne sincera, firme e inteira. Em nome de Jesus, amém."
    },
    {
      "day": 1,
      "segment": "evening",
      "reference": {
        "book": "John",
        "chapter": 14,
        "verse": "1",
        "full_reference": "John 14:1"
      },
      "modernVersion": "NVI-PT",
      "modernText": "Não deixem que seus corações se perturbem. Creiam em Deus; creiam também em mim.",
      "meditation": "Quando a ansiedade se instala, raramente pede permissão. Ela pode vir por uma separação, a perda de um emprego, uma notícia difícil sobre saúde ou as horas silenciosas da noite, quando todo medo parece crescer. Talvez você nem saiba nomear o que sente; só sabe que seu coração está inquieto, cansado e assustado.\n\nJesus falou palavras de consolo aos discípulos em um momento nada tranquilo. Ele sabia que logo o veriam ser preso e que a cruz abalaria tudo o que entendiam. A situação deles não ficaria fácil de imediato, mas Jesus os chamou a confiar: crer em Deus e crer também nele. Ele não os consolou dizendo que tudo sairia como esperavam; levou o coração deles de volta para si mesmo.\n\nEssa fé não nega a dificuldade. Ela volta o coração para o Senhor que continua bom, fiel e poderoso quando tudo treme. Por isso, mesmo quando a emoção não muda de imediato, você pode respirar diante dele e permitir que sua presença sustente o que sua força já não consegue carregar.",
      "actionStep": "Escreva o medo ou a preocupação que fala mais alto em seu coração hoje. Leve isso a Jesus sem tentar arrumar as palavras e escreva ao lado uma frase de confiança: “Senhor, coloco isto em tuas mãos.” Volte a essa frase sempre que o medo surgir.",
      "prayer": "Querido Pai celestial, eu te agradeço porque em Cristo meu coração não precisa ser governado pelo medo. Quando as preocupações falarem mais alto que a tua promessa, ensina-me a trazê-las com honestidade diante de ti. Firma-me com a tua presença e ajuda-me a dar hoje o próximo passo confiando em ti. Não quero concordar com isso apenas em palavras e depois continuar igual. Encontra-me nos lugares escondidos onde o medo, o hábito ou a autoproteção ainda me governam. Ensina-me a abrir esses lugares ao teu amor, e que minha resposta a ti se torne sincera, firme e inteira. Em nome de Jesus, amém."
    },
    {
      "day": 2,
      "segment": "morning",
      "reference": {
        "book": "Jeremiah",
        "chapter": 29,
        "verse": "11",
        "full_reference": "Jeremiah 29:11"
      },
      "modernVersion": "NVI-PT",
      "modernText": "\"Porque eu bem sei os planos que tenho para vocês\", declara o Senhor, \"planos de bem-estar e não de calamidade, para lhes dar um futuro cheio de esperança.\"",
      "meditation": "Jeremias escreveu estas palavras a pessoas no exílio, não a pessoas cuja vida parecia fácil ou organizada. Elas haviam perdido casa, segurança e uma visão clara do futuro. No meio dessa incerteza, Deus diz: 'Eu sei os planos que tenho para vocês.' Ele não apenas observa a dor delas; ainda sustenta um propósito para elas. Essa promessa não nega a dificuldade. Ela revela o coração de Deus dentro dela. Seus planos não são para destruir seu povo, mas para conduzi-lo à paz, à restauração e à esperança.\n\nQuando teu futuro parece interrompido, ou quando teus erros passados parecem ter a última palavra, este versículo lembra que Deus não deixou de pensar em ti com misericórdia. Tuas circunstâncias talvez ainda estejam inacabadas, mas a intenção dele permanece fiel. Por isso, não te apresses em chamar o capítulo presente de fim da história. Para Judá, o exílio parecia um fim, mas Deus já falava de futuro. Tua espera, dor ou incerteza podem ser reais, mas não são mais fortes que a fidelidade da aliança de Deus.",
      "actionStep": "Escreva no diário ou nas notas do celular: “Deus tem planos de paz para mim, não de desastre.” Quando a dúvida aparecer, leia de novo. Se puder, leia de manhã e à noite, deixando essa verdade mudar pouco a pouco a forma como você olha para o futuro.",
      "prayer": "Querido Pai celestial, eu te louvo por tua promessa de que teus planos para nós são para bem — cheios de esperança e um futuro próspero. Tu sustentas nossos dias em tuas mãos. Teus propósitos não são para nos prejudicar mas para nos estabelecer em esperança. Os teus planos nunca falham. Escreves a história com esperança. Que bom Pai és. Trago-te as partes cansadas do meu coração que conhecem as palavras certas, mas lutam para crer nelas. Fica comigo ali, Pai, e torna tua verdade mais quente que minha vergonha e mais forte que meu medo. Ajuda-me a orar não de longe, mas a partir da confiança de que já sou sustentada por ti. Em nome de Jesus, amém."
    },
    {
      "day": 2,
      "segment": "evening",
      "reference": {
        "book": "John",
        "chapter": 14,
        "verse": "16",
        "full_reference": "John 14:16"
      },
      "modernVersion": "NVI-PT",
      "modernText": "Vou pedir ao Pai, e ele lhes dará outro Consolador para estar com vocês para sempre—",
      "meditation": "Quando alguém importante vai embora, a ausência pode parecer maior que o próprio quarto. Uma mudança, uma separação, uma morte ou uma despedida repentina pode derrubar todo senso de segurança. Os discípulos conheceram esse medo. Quando Jesus disse que partiria, eles não reagiram com coragem tranquila, mas com confusão, tristeza e temor.\n\nNessa hora escura, Jesus prometeu enviar outro Consolador para estar com eles para sempre. Não era uma presença menor, mas uma intimidade mais profunda. Jesus não apenas caminharia ao lado deles; pelo Espírito Santo, Deus habitaria neles.\n\nO Espírito Santo não é um visitante ocasional. Ele está com você nas noites solitárias, nas decisões confusas, nas tristezas que você não consegue explicar e quando faltam palavras para orar. Ele conhece seu coração e entende seus suspiros. Você não vive sustentada apenas por lembranças. Deus está com você agora e não vai abandoná-la.",
      "actionStep": "Pare e pergunte a si mesma: onde me sinto mais sozinha hoje, e do que preciso de Deus nesse lugar? Ore com simplicidade: “Espírito Santo, lembra-me de que não estou abandonada.” Fique em silêncio por um momento e perceba se Ele traz consolo, sabedoria ou força.",
      "prayer": "Querido Pai celestial, eu te louvo por nos dares o teu Espírito para permanecer conosco. Quando a ausência, a mudança ou a solidão me fizerem sentir desprotegida, lembra-me de que não enfrento a vida sozinha. Ajuda-me a receber o consolo do Espírito e a seguir hoje a sua direção suave. Trago-te as partes cansadas do meu coração que conhecem as palavras certas, mas lutam para crer nelas. Fica comigo ali, Pai, e torna tua verdade mais quente que minha vergonha e mais forte que meu medo. Ajuda-me a orar não de longe, mas a partir da confiança de que já sou sustentada por ti. Em nome de Jesus, amém."
    },
    {
      "day": 3,
      "segment": "morning",
      "reference": {
        "book": "Matthew",
        "chapter": 28,
        "verse": "19",
        "full_reference": "Matthew 28:19"
      },
      "modernVersion": "NVI-PT",
      "modernText": "Portanto, vão e façam discípulos de todas as nações, batizando-os em nome do Pai e do Filho e do Espírito Santo,",
      "meditation": "A Grande Comissão começa com a autoridade de Jesus, não com nossa capacidade. Antes de dizer 'ide', ele declara que toda autoridade no céu e na terra pertence a ele. Isso significa que nosso testemunho não repousa em palavras perfeitas, confiança completa ou em ter todas as respostas. Repousa no Cristo ressuscitado que nos envia e vai conosco. Muitos de nós hesitamos porque nos sentimos despreparados.\n\nMas Jesus não te pede para desempenhar um papel religioso; ele te convida a testemunhar o que recebeste. Tua vida transformada, tua história sincera e tua fidelidade silenciosa em lugares comuns podem se tornar uma porta para que outra pessoa o encontre. Deus costuma usar pessoas disponíveis mais do que pessoas impressionantes. Isso dá dignidade à pequena obediência.",
      "actionStep": "Pense em uma pessoa da sua vida que pareça aberta ou em busca. Esta semana, comece uma conversa natural com ela. Não force uma conversa religiosa; compartilhe simplesmente uma forma prática como sua fé ajudou você, e escute bem.",
      "prayer": "Querido Pai celestial, recebo esta graça: Jesus confiou aos seus discípulos a missão de fazer discípulos de todas as nações. Dá-nos coragem para testemunhar fielmente e humildade para apontar outros para Cristo. Onde continuo tentando controlar os resultados, afrouxa minhas mãos e aquieta meu coração. Confesso que muitas vezes desejo mais a certeza do que a entrega. Atrai-me de volta a ti até que a obediência pareça menos perder a mim mesma e mais voltar para casa junto daquele que mais me ama. Em nome de Jesus, amém."
    },
    {
      "day": 3,
      "segment": "evening",
      "reference": {
        "book": "Genesis",
        "chapter": 1,
        "verse": "2",
        "full_reference": "Genesis 1:2"
      },
      "modernVersion": "NVI-PT",
      "modernText": "A terra era um caos total, as trevas cobriam o abismo, e o Espírito de Deus se movia sobre as águas.",
      "meditation": "Algumas fases não parecem uma vida sendo construída, mas algo sem forma. Planos se desfazem, o chão conhecido desaparece, e o futuro não tem contorno claro. A escuridão pode fazer você pensar que nada bom está acontecendo, mas o começo da história da criação lembra: até o vazio e o caos estão dentro do alcance de Deus.\n\nAntes que ordem, beleza e fruto aparecessem, o Espírito de Deus já estava presente. Ele não observava de longe, não chegava atrasado e não estava confuso diante da desordem. Sua presença muitas vezes vem antes da mudança visível. Quando você não vê forma, Deus ainda sabe o que está moldando; quando não vê resultado, Ele continua trabalhando.\n\nSeu agir é poderoso e também gentil. Deus entra na sua escuridão sem esmagar você. Até o começo que parece desordenado pode se tornar, nas mãos dele, o início de uma vida nova. A sua espera não é invisível para Deus.",
      "actionStep": "Dê nome a uma área da vida que parece inacabada, confusa ou sem forma clara. Convide o Espírito de Deus para esse lugar, não com um plano forçado, mas com confiança. Peça a Ele um pequeno passo rumo à ordem, luz ou fé paciente hoje.",
      "prayer": "Querido Pai celestial, recebo esta graça: o teu Espírito está presente mesmo quando minha vida parece sem forma e inacabada. Aproxima-te dos lugares confusos, escuros e vazios dentro de mim. Sopra ordem, paciência e esperança naquilo que ainda não entendo, e ensina-me a confiar na tua obra. Onde continuo tentando controlar os resultados, afrouxa minhas mãos e aquieta meu coração. Confesso que muitas vezes desejo mais a certeza do que a entrega. Atrai-me de volta a ti até que a obediência pareça menos perder a mim mesma e mais voltar para casa junto daquele que mais me ama. Em nome de Jesus, amém."
    }
  ]
};
