// AUTO-GENERATED by scripts/gen_bundled_verses.mjs — do not edit by hand.
// Slim, offline-first daily-verse bundle shipped inside the APK/IPA.
// Only the first 3 day(s) are bundled; the full 60-day set lives on
// the CDN (pd-text-corpus) and supersedes this the moment the first
// DailyVersesContext fetch completes. Regenerate with:
//   node scripts/gen_bundled_verses.mjs ./_incoming_verses 3
import type { LanguageCode } from '../state/TranslationsContext';

export interface DailyVerse {
  day: number;
  segment: 'morning' | 'evening';
  reference: {
    book: string;
    chapter: number;
    verse: string;
    full_reference: string;
  };
  /** Local verse numbering where Segond/Luther shift psalm titles into v1
   *  (fr/de only, 5 psalm entries) — display this over full_reference when
   *  the active Bible matches the verse's language. */
  verseLocal?: string;
  /** Which edition modernText actually holds. Batch 2+: the licensed modern
   *  text ships empty, so this is usually the public-domain traditional
   *  edition until a licensed backfill lands. */
  modernVersion: string;
  modernText: string;
  /** Per-language background note (schema 3.2) — the ⓘ icon on the verse page. */
  contextNote?: string;
  meditation: string;
  actionStep: string;
  prayer: string;
}

// Bundled coverage in days. The CDN file covers 60; this fallback covers
// only the first 3 so the prayer card is never blank before the pull.
export const BUNDLED_COVERAGE_DAYS = 3;

export const BUNDLED_DAILY_VERSES: Record<LanguageCode, DailyVerse[]> =
{
  "en": [
    {
      "day": 1,
      "segment": "morning",
      "reference": {
        "book": "Psalms",
        "chapter": 143,
        "verse": "8",
        "full_reference": "Psalms 143:8"
      },
      "modernVersion": "NIV",
      "modernText": "Let the morning bring me word of your unfailing love, for I have put my trust in you. Show me the way I should go, for to you I entrust my life.",
      "contextNote": "Psalm 143 is a lament — David is being hunted, and says so plainly a few verses earlier. This is not a serene morning prayer; it was written by someone in trouble. The Hebrew behind 'lovingkindness' is chesed: covenant loyalty, love that committed itself in advance and cannot be talked back out of it.",
      "meditation": "David is not describing a good morning. He is asking for one, and the order he asks in is worth borrowing.\n\nFirst to hear that he is loved. Then to know where to go. As Christians we usually reverse it — we come for the direction, the decision, what to do about the thing. But direction without love turns into pressure, and most of us have tried living that way for a stretch. Let's ask for the first one this morning. The second will keep.",
      "actionStep": "Before you plan anything today, say one sentence out loud: I am loved before I am useful. Then ask God about the first decision on your list.",
      "prayer": "Dear Heavenly Father, before I ask You where to go, let me hear that I am loved. I confess how easily I skip that part and go straight to the planning. Speak first to the part of me that needs reassuring, and then show me the next step. I am lifting my whole day up to You. In Jesus' name, amen."
    },
    {
      "day": 1,
      "segment": "evening",
      "reference": {
        "book": "Hebrews",
        "chapter": 4,
        "verse": "16",
        "full_reference": "Hebrews 4:16"
      },
      "modernVersion": "NIV",
      "modernText": "Let us then approach God's throne of grace with confidence, so that we may receive mercy and find grace to help us in our time of need.",
      "contextNote": "Hebrews was written to Jewish Christians who knew the holy of holies could be entered once a year, by one man, carrying blood. Against that background, 'come boldly' is startling. The Greek is parrhesia — the freedom of a citizen to speak plainly in public, not the nerve of an intruder.",
      "meditation": "As Christians we tend to approach God the way we approach an appraisal — with the case for ourselves already half drafted. Hebrews uses a different word for it: boldly. Not carefully, not once we have tidied ourselves up first.\n\nAnd notice what the throne is named for. Grace, not review. So let's come as we actually are tonight, and stop rehearsing the explanation on the way in.",
      "actionStep": "Bring God the one thing you were planning to handle by yourself. Say it out loud before you sleep.",
      "prayer": "Dear Heavenly Father, I come to You tonight without tidying myself up first, because You said I could. Thank You that this is a throne of grace and not a review. Here is what I need help with, and here is where I fell short. In Jesus' name, amen."
    },
    {
      "day": 2,
      "segment": "morning",
      "reference": {
        "book": "Romans",
        "chapter": 8,
        "verse": "6",
        "full_reference": "Romans 8:6"
      },
      "modernVersion": "NIV",
      "modernText": "The mind governed by the flesh is death, but the mind governed by the Spirit is life and peace.",
      "contextNote": "Romans 8 opens with 'no condemnation', and this verse sits inside that promise rather than against it. Paul's word for a flesh-governed mind is phronema — not a single thought but a settled leaning, the direction a mind drifts when it is left alone. He is describing a current, not passing a verdict.",
      "meditation": "Paul is not moralising about your behaviour here. He is talking about where your mind goes when you stop steering it — the channel it returns to on its own.\n\nAnd here is the promise, aimed at you: the other channel opens into life and peace. Not tidier thinking. Life. You are not stuck with the default, and you were never expected to fight your way out of it on your own!",
      "actionStep": "Notice the first place your mind goes when it goes idle today. Don't judge it — just tell God what it was.",
      "prayer": "Dear Heavenly Father, You know where my mind goes when I stop steering it, and some of that is not doing me any good. Would You turn my thinking toward what actually gives life this morning — not by force, but by drawing me. In Jesus' name, amen."
    },
    {
      "day": 2,
      "segment": "evening",
      "reference": {
        "book": "2 Kings",
        "chapter": 20,
        "verse": "5",
        "full_reference": "2 Kings 20:5"
      },
      "modernVersion": "NIV",
      "modernText": "Go back and tell Hezekiah, the ruler of my people, 'This is what the LORD, the God of your father David, says: I have heard your prayer and seen your tears; I will heal you.'",
      "contextNote": "Hezekiah was terminally ill and had just been told to set his house in order. Isaiah was already leaving the palace when God turned him around. In Hebrew, 'I have seen thy tears' uses the ordinary verb for looking at a thing — no poetic flourish. The point is that God attends to the part of prayer that has no words.",
      "meditation": "Hezekiah had already been told the answer was no; the prophet had walked out. Then God sent him back. And read the order of what God says. Before the promise, before anything changes, there is this: I have heard your prayer, I have seen your tears. The tears get their own clause. God does not fold them into the prayer as though weeping were an inefficient way of asking. He counts them separately.\n\nWhatever you have been crying about — the thing you stopped explaining to people because you got tired of explaining it — it has been seen. Not overlooked, not endured. Seen!",
      "actionStep": "Say out loud the thing you have stopped explaining to anyone. You don't have to make a case for it. Just say it.",
      "prayer": "Dear Heavenly Father, thank You that You count tears separately from words, and that You have not grown tired of mine. I stopped explaining this to people a while ago. I am not going to stop explaining it to You. Thank You that being seen by You is not the same as being pitied. Hold what I have brought You tonight. In Jesus' name, amen."
    },
    {
      "day": 3,
      "segment": "morning",
      "reference": {
        "book": "2 Corinthians",
        "chapter": 3,
        "verse": "17",
        "full_reference": "2 Corinthians 3:17"
      },
      "modernVersion": "NIV",
      "modernText": "Now the Lord is the Spirit, and where the Spirit of the Lord is, there is freedom.",
      "contextNote": "Paul has just described Moses veiling his face after being with God. The contrast he draws is between a covenant kept at a distance behind a veil and one lived with the face uncovered. The Greek eleutheria means the legal standing of a freed person — a status, not a mood.",
      "meditation": "As Christians we can quietly turn faith into one more place we are being measured. Another list, another performance, one more room where we might not be enough.\n\nPaul says the opposite thing about the room. Where the Spirit is, there is freedom — not licence to do anything, but the release of not having to prove anything. Let's carry that into today. You are not auditioning.",
      "actionStep": "Name one thing you were going to do today mainly to prove something. Do it, or drop it — but as a free woman, not an applicant.",
      "prayer": "Dear Heavenly Father, thank You that Your Spirit brings freedom and not another test. I confess how often I turn my faith into something I could fail. Loosen that in me today. Let me work and speak as someone who is already accepted. In Jesus' name, amen."
    },
    {
      "day": 3,
      "segment": "evening",
      "reference": {
        "book": "Acts",
        "chapter": 16,
        "verse": "25",
        "full_reference": "Acts 16:25"
      },
      "modernVersion": "NIV",
      "modernText": "About midnight Paul and Silas were praying and singing hymns to God, and the other prisoners were listening to them.",
      "contextNote": "Paul and Silas had been stripped, beaten with rods and thrown into the innermost cell — Luke is specific about all three. The Greek for their singing, hymneo, is the same verb used of the hymn Jesus sang with his disciples before Gethsemane. That the prisoners 'heard them' is Luke's own detail, and he includes it deliberately.",
      "meditation": "Two men, beaten and locked in the inner cell, feet in the stocks. It is midnight. And Luke records what they did with that particular hour: they prayed, and then they sang.\n\nNotice the last clause, because it is the one usually skipped. The other prisoners heard them. Nobody was singing for an audience — there was no audience, only people in the same dark lying awake. But faith in a bad night is never entirely private. The woman in the next room hears. The child down the hall hears. Your midnight is louder than you think, and not always in a bad way.",
      "actionStep": "If you are awake tonight when you would rather be asleep, stop fighting it for ten minutes. Pray in that time instead — out loud, if you can.",
      "prayer": "Dear Heavenly Father, I would rather not be awake right now, and I would rather this were over. Thank You that You are not absent from the middle of the night. If I cannot sleep, let me pray. And if anyone near me is listening, let what they hear from me be trust and not despair. In Jesus' name, amen."
    }
  ],
  "zh-Hans": [
    {
      "day": 1,
      "segment": "morning",
      "reference": {
        "book": "Psalms",
        "chapter": 143,
        "verse": "8",
        "full_reference": "Psalms 143:8"
      },
      "modernVersion": "和合本",
      "modernText": "求你使我清晨得听你慈爱之言，因我倚靠你；求你使我知道当行的路，因我的心仰望你。",
      "contextNote": "诗篇一百四十三篇是一首哀歌。前面几节里，大卫直说自己正被人追杀。这不是从安稳处发出的清晨祷告，是一个身处险境的人写下的。「慈爱」的希伯来原文是 chesed，指立约的忠诚——一种事先就把自己许出去、事后反悔不了的爱。",
      "meditation": "大卫不是在描述一个美好的清晨，他是在求一个。他求的顺序值得我们借来用。\n\n先听见自己被爱，然后才知道该往哪里走。我们大多数人是反着来的——一睁眼就来要方向、要答案、要那件事到底该怎么办。可是没有爱托着的方向，很快就变成压力，这样的日子我们多半都过过一阵。今天早晨，我们先求第一样。第二样跑不掉，它会等着我们。",
      "actionStep": "今天安排任何事之前，先出声说一句：我先是被爱的，才是有用的。然后把清单上第一件事交给神。",
      "prayer": "亲爱的天父，在我开口问你我该往哪里去之前，求你先让我听见我是被爱的。我承认自己常常跳过这一步，一醒来就直奔计划和安排。今天早晨，求你先对我里面那个需要被安慰的地方说话，然后再指给我下一步。我把这一整天都举到你面前。奉主耶稣的名祷告，阿们。"
    },
    {
      "day": 1,
      "segment": "evening",
      "reference": {
        "book": "Hebrews",
        "chapter": 4,
        "verse": "16",
        "full_reference": "Hebrews 4:16"
      },
      "modernVersion": "和合本",
      "modernText": "所以，我们只管坦然无惧地来到施恩的宝座前，为要得怜恤，蒙恩惠，作随时的帮助。",
      "contextNote": "希伯来书写给的是犹太基督徒。他们知道至圣所一年只能进一次，只能由一个人进去，还要带着血。在这样的背景下，「坦然无惧地来」是件让人吃惊的事。这里的希腊文是 parrhesia，指公民在众人面前坦白讲话的自由，不是闯入者的胆量。",
      "meditation": "我们来到神面前，常常像去见考核——话还没说，心里已经把自我辩护打了半份草稿。希伯来书用的却是另一个词：坦然无惧。不是小心翼翼，也不是先把自己收拾干净再来。\n\n再留意这宝座叫什么名字。是施恩，不是审查。今晚就照着我们真实的样子来吧，别再在路上背台词了。",
      "actionStep": "把你本来打算自己扛下来的那一件事带到神面前。睡前出声说出来。",
      "prayer": "亲爱的天父，今晚我不先把自己收拾整齐才来，因为这是你允许的。谢谢你，这是施恩的宝座，不是审查台。我需要帮助的在这里，我做得不好的也在这里。奉主耶稣的名祷告，阿们。"
    },
    {
      "day": 2,
      "segment": "morning",
      "reference": {
        "book": "Romans",
        "chapter": 8,
        "verse": "6",
        "full_reference": "Romans 8:6"
      },
      "modernVersion": "和合本",
      "modernText": "体贴肉体的，就是死；体贴圣灵的，乃是生命、平安。",
      "contextNote": "罗马书第八章一开头就说「不定罪」，这节经文是落在那个应许里面的，不是站在它对面。保罗用来形容体贴肉体的那个词是 phronema，指的不是某一个念头，而是一种固定的倾向——心思没人管的时候会往哪边偏。他在描述一股水流，不是在下判决。",
      "meditation": "保罗在这里不是在评判你的行为。他说的是：当你不再刻意去管的时候，你的心思会自己滑到哪里去——那个它总要回去的频道。\n\n而应许是对你说的：另一个频道通向生命和平安。不是让你想得更整齐，是生命。你不必被那个默认设定困住，神也从来没有指望你靠自己一个人挣脱出来！",
      "actionStep": "今天留意一下，心思一空下来，第一个跑去的地方是哪里。不要评判它，只把它告诉神。",
      "prayer": "亲爱的天父，你知道我不看着它的时候，心思会往哪里去，其中有些对我并没有好处。求你今天早晨把我的思想转向真正带来生命的事——不是用强的，是用你的吸引。奉主耶稣的名祷告，阿们。"
    },
    {
      "day": 2,
      "segment": "evening",
      "reference": {
        "book": "2 Kings",
        "chapter": 20,
        "verse": "5",
        "full_reference": "2 Kings 20:5"
      },
      "modernVersion": "和合本",
      "modernText": "「你回去告诉我民的君希西家说：耶和华─你祖大卫的神如此说：『我听见了你的祷告，看见了你的眼泪，我必医治你；到第三日，你必上到耶和华的殿。",
      "contextNote": "希西家当时已经病危，先知刚刚告诉他要交代后事。以赛亚人还没走出王宫，神就叫他回头。希伯来原文里「看见你的眼泪」用的是最普通的那个「看」，没有一点修辞。要说的正是这个：祷告里说不出话的那一部分，神也在留心。",
      "meditation": "希西家已经听见了答案：不行。先知说完就走出去了。然后神把他叫了回来。留意神说话的次序：在应许之前，在任何事情有转机之前，先有这一句——我听见了你的祷告，我看见了你的眼泪。眼泪单独占了一句。神没有把它并进祷告里，好像哭只是一种效率低的求告。他是分开数的。\n\n你一直在为之落泪的那件事——那件你已经不想再跟人解释的事——已经被看见了。神并不需要你先把它说得有条有理。不是被忽略，不是被勉强忍受。是被看见！",
      "actionStep": "把那件你已经不再向任何人解释的事，出声说出来。不必替它辩护，说出来就好。",
      "prayer": "亲爱的天父，谢谢你把眼泪和言语分开来数，也谢谢你从没有听厌我的眼泪。这件事我很久以前就不再向人解释了，但我不会停止向你说。谢谢你，被你看见，和被人可怜完全不是一回事。今晚我把它交在你手里，求你替我拿着。奉主耶稣的名祷告，阿们。"
    },
    {
      "day": 3,
      "segment": "morning",
      "reference": {
        "book": "2 Corinthians",
        "chapter": 3,
        "verse": "17",
        "full_reference": "2 Corinthians 3:17"
      },
      "modernVersion": "和合本",
      "modernText": "主就是那灵；主的灵在哪里，那里就得以自由。",
      "contextNote": "保罗刚讲完摩西见过神之后用帕子蒙脸。他要对比的，是一份隔着帕子、保持距离守住的约，和一份可以坦然露着脸活出来的约。希腊文 eleutheria 指的是一个获释之人的法律身份——是一种地位，不是一种心情。",
      "meditation": "我们做基督徒，很容易不知不觉把信仰也变成又一个被打分的地方。又一张清单，又一场表现，又一个可能显得自己不够格的房间。\n\n保罗说这个房间不是那样的。主的灵在哪里，那里就有自由——不是想做什么就做什么，是不必再证明什么的松开。今天就带着这个走。你不是在试镜。",
      "actionStep": "想一件你今天主要是为了证明什么才做的事。去做，或者放下——但要像一个自由人，不是应聘者。",
      "prayer": "亲爱的天父，谢谢你，你的灵带来的是自由，不是又一场考试。我承认自己常把信仰变成一件可能考砸的事。求你今天松开我里面这一处，让我做事说话的时候，像一个已经被接纳的人。奉主耶稣的名祷告，阿们。"
    },
    {
      "day": 3,
      "segment": "evening",
      "reference": {
        "book": "Acts",
        "chapter": 16,
        "verse": "25",
        "full_reference": "Acts 16:25"
      },
      "modernVersion": "和合本",
      "modernText": "约在半夜，保罗和西拉祷告，唱诗赞美神，众囚犯也侧耳而听。",
      "contextNote": "保罗和西拉被剥了衣服、用棍打过，又下在最里面的监牢里——这三样路加都写得很清楚。他们唱诗，希腊文用的是 hymneo，与耶稣在客西马尼之前和门徒同唱的那个词相同。「别的囚犯听见了」是路加自己加的一笔，他是有意写下的。",
      "meditation": "两个人，被打过，锁在最里面的一间牢房，两脚上了木狗。时间是半夜。路加特意记下他们在那个钟点做了什么：祷告，然后唱诗。\n\n留意最后那一句，因为它常常被读过去——别的囚犯都听见了。没有人是唱给听众听的，那里根本没有听众，只有同在黑暗里睡不着的人。但一个人在难熬的夜里守住的信心，从来不会完全是私事。隔壁房间的女人听得见。走廊那头的孩子听得见。你的半夜比你以为的响，而且不一定是坏事。而半夜里唱得出来的，多半是白天存下的。",
      "actionStep": "今晚若你在该睡的时候醒着，别再跟它较劲十分钟。用那十分钟祷告，能出声就出声。",
      "prayer": "亲爱的天父，此刻我并不想醒着，也很想这一切快点过去。谢谢你，深夜的中间你并没有缺席。如果我睡不着，就让我祷告。若身边有人听见，愿他们从我这里听见的是信靠，不是绝望。求你也把睡眠还给我；若还不能，就陪我坐到天亮。奉主耶稣的名祷告，阿们。"
    }
  ],
  "zh-Hant": [
    {
      "day": 1,
      "segment": "morning",
      "reference": {
        "book": "Psalms",
        "chapter": 143,
        "verse": "8",
        "full_reference": "Psalms 143:8"
      },
      "modernVersion": "和合本",
      "modernText": "求你使我清晨得聽你慈愛之言，因我倚靠你；求你使我知道當行的路，因我的心仰望你。",
      "contextNote": "詩篇一百四十三篇是一首哀歌。前面幾節裡，大衛直說自己正被人追殺。這不是從安穩處發出的清晨禱告，是一個身處險境的人寫下的。「慈愛」的希伯來原文是 chesed，指立約的忠誠——一種事先就把自己許出去、事後反悔不了的愛。",
      "meditation": "大衛不是在描述一個美好的清晨，他是在求一個。他求的順序值得我們借來用。\n\n先聽見自己被愛，然後才知道該往哪裡走。我們大多數人是反著來的——一睜眼就來要方向、要答案、要那件事到底該怎麼辦。可是沒有愛託著的方向，很快就變成壓力，這樣的日子我們多半都過過一陣。今天早晨，我們先求第一樣。第二樣跑不掉，它會等著我們。",
      "actionStep": "今天安排任何事之前，先出聲說一句：我先是被愛的，才是有用的。然後把清單上第一件事交給神。",
      "prayer": "親愛的天父，在我開口問你我該往哪裡去之前，求你先讓我聽見我是被愛的。我承認自己常常跳過這一步，一醒來就直奔計劃和安排。今天早晨，求你先對我裡面那個需要被安慰的地方說話，然後再指給我下一步。我把這一整天都舉到你面前。奉主耶穌的名禱告，阿們。"
    },
    {
      "day": 1,
      "segment": "evening",
      "reference": {
        "book": "Hebrews",
        "chapter": 4,
        "verse": "16",
        "full_reference": "Hebrews 4:16"
      },
      "modernVersion": "和合本",
      "modernText": "所以，我們只管坦然無懼地來到施恩的寶座前，為要得憐恤，蒙恩惠，作隨時的幫助。",
      "contextNote": "希伯來書寫給的是猶太基督徒。他們知道至聖所一年只能進一次，只能由一個人進去，還要帶著血。在這樣的背景下，「坦然無懼地來」是件讓人喫驚的事。這裡的希臘文是 parrhesia，指公民在衆人面前坦白講話的自由，不是闖入者的膽量。",
      "meditation": "我們來到神面前，常常像去見考覈——話還沒說，心裡已經把自我辯護打了半份草稿。希伯來書用的卻是另一個詞：坦然無懼。不是小心翼翼，也不是先把自己收拾乾淨再來。\n\n再留意這寶座叫什麼名字。是施恩，不是審查。今晚就照著我們真實的樣子來吧，別再在路上背臺詞了。",
      "actionStep": "把你本來打算自己扛下來的那一件事帶到神面前。睡前出聲說出來。",
      "prayer": "親愛的天父，今晚我不先把自己收拾整齊才來，因為這是你允許的。謝謝你，這是施恩的寶座，不是審查臺。我需要幫助的在這裡，我做得不好的也在這裡。奉主耶穌的名禱告，阿們。"
    },
    {
      "day": 2,
      "segment": "morning",
      "reference": {
        "book": "Romans",
        "chapter": 8,
        "verse": "6",
        "full_reference": "Romans 8:6"
      },
      "modernVersion": "和合本",
      "modernText": "體貼肉體的，就是死；體貼聖靈的，乃是生命、平安。",
      "contextNote": "羅馬書第八章一開頭就說「不定罪」，這節經文是落在那個應許裡面的，不是站在它對面。保羅用來形容體貼肉體的那個詞是 phronema，指的不是某一個念頭，而是一種固定的傾向——心思沒人管的時候會往哪邊偏。他在描述一股水流，不是在下判決。",
      "meditation": "保羅在這裡不是在評判你的行為。他說的是：當你不再刻意去管的時候，你的心思會自己滑到哪裡去——那個它總要回去的頻道。\n\n而應許是對你說的：另一個頻道通向生命和平安。不是讓你想得更整齊，是生命。你不必被那個默認設定困住，神也從來沒有指望你靠自己一個人掙脫出來！",
      "actionStep": "今天留意一下，心思一空下來，第一個跑去的地方是哪裡。不要評判它，只把它告訴神。",
      "prayer": "親愛的天父，你知道我不看著它的時候，心思會往哪裡去，其中有些對我並沒有好處。求你今天早晨把我的思想轉向真正帶來生命的事——不是用強的，是用你的吸引。奉主耶穌的名禱告，阿們。"
    },
    {
      "day": 2,
      "segment": "evening",
      "reference": {
        "book": "2 Kings",
        "chapter": 20,
        "verse": "5",
        "full_reference": "2 Kings 20:5"
      },
      "modernVersion": "和合本",
      "modernText": "「你回去告訴我民的君希西家說：耶和華─你祖大衛的神如此說：『我聽見了你的禱告，看見了你的眼淚，我必醫治你；到第三日，你必上到耶和華的殿。",
      "contextNote": "希西家當時已經病危，先知剛剛告訴他要交代後事。以賽亞人還沒走出王宮，神就叫他回頭。希伯來原文裡「看見你的眼淚」用的是最普通的那個「看」，沒有一點修辭。要說的正是這個：禱告裡說不出話的那一部分，神也在留心。",
      "meditation": "希西家已經聽見了答案：不行。先知說完就走出去了。然後神把他叫了回來。留意神說話的次序：在應許之前，在任何事情有轉機之前，先有這一句——我聽見了你的禱告，我看見了你的眼淚。眼淚單獨佔了一句。神沒有把它並進禱告裡，好像哭只是一種效率低的求告。他是分開數的。\n\n你一直在為之落淚的那件事——那件你已經不想再跟人解釋的事——已經被看見了。神並不需要你先把它說得有條有理。不是被忽略，不是被勉強忍受。是被看見！",
      "actionStep": "把那件你已經不再向任何人解釋的事，出聲說出來。不必替它辯護，說出來就好。",
      "prayer": "親愛的天父，謝謝你把眼淚和言語分開來數，也謝謝你從沒有聽厭我的眼淚。這件事我很久以前就不再向人解釋了，但我不會停止向你說。謝謝你，被你看見，和被人可憐完全不是一回事。今晚我把它交在你手裡，求你替我拿著。奉主耶穌的名禱告，阿們。"
    },
    {
      "day": 3,
      "segment": "morning",
      "reference": {
        "book": "2 Corinthians",
        "chapter": 3,
        "verse": "17",
        "full_reference": "2 Corinthians 3:17"
      },
      "modernVersion": "和合本",
      "modernText": "主就是那靈；主的靈在哪裡，那裡就得以自由。",
      "contextNote": "保羅剛講完摩西見過神之後用帕子蒙臉。他要對比的，是一份隔著帕子、保持距離守住的約，和一份可以坦然露著臉活出來的約。希臘文 eleutheria 指的是一個獲釋之人的法律身份——是一種地位，不是一種心情。",
      "meditation": "我們做基督徒，很容易不知不覺把信仰也變成又一個被打分的地方。又一張清單，又一場表現，又一個可能顯得自己不夠格的房間。\n\n保羅說這個房間不是那樣的。主的靈在哪裡，那裡就有自由——不是想做什麼就做什麼，是不必再證明什麼的鬆開。今天就帶著這個走。你不是在試鏡。",
      "actionStep": "想一件你今天主要是為了證明什麼才做的事。去做，或者放下——但要像一個自由人，不是應聘者。",
      "prayer": "親愛的天父，謝謝你，你的靈帶來的是自由，不是又一場考試。我承認自己常把信仰變成一件可能考砸的事。求你今天鬆開我裡面這一處，讓我做事說話的時候，像一個已經被接納的人。奉主耶穌的名禱告，阿們。"
    },
    {
      "day": 3,
      "segment": "evening",
      "reference": {
        "book": "Acts",
        "chapter": 16,
        "verse": "25",
        "full_reference": "Acts 16:25"
      },
      "modernVersion": "和合本",
      "modernText": "約在半夜，保羅和西拉禱告，唱詩讚美神，衆囚犯也側耳而聽。",
      "contextNote": "保羅和西拉被剝了衣服、用棍打過，又下在最裡面的監牢裡——這三樣路加都寫得很清楚。他們唱詩，希臘文用的是 hymneo，與耶穌在客西馬尼之前和門徒同唱的那個詞相同。「別的囚犯聽見了」是路加自己加的一筆，他是有意寫下的。",
      "meditation": "兩個人，被打過，鎖在最裡面的一間牢房，兩腳上了木狗。時間是半夜。路加特意記下他們在那個鐘點做了什麼：禱告，然後唱詩。\n\n留意最後那一句，因為它常常被讀過去——別的囚犯都聽見了。沒有人是唱給聽衆聽的，那裡根本沒有聽衆，只有同在黑暗裡睡不著的人。但一個人在難熬的夜裡守住的信心，從來不會完全是私事。隔壁房間的女人聽得見。走廊那頭的孩子聽得見。你的半夜比你以為的響，而且不一定是壞事。而半夜裡唱得出來的，多半是白天存下的。",
      "actionStep": "今晚若你在該睡的時候醒著，別再跟它較勁十分鐘。用那十分鐘禱告，能出聲就出聲。",
      "prayer": "親愛的天父，此刻我並不想醒著，也很想這一切快點過去。謝謝你，深夜的中間你並沒有缺席。如果我睡不著，就讓我禱告。若身邊有人聽見，願他們從我這裡聽見的是信靠，不是絕望。求你也把睡眠還給我；若還不能，就陪我坐到天亮。奉主耶穌的名禱告，阿們。"
    }
  ],
  "de": [
    {
      "day": 1,
      "segment": "morning",
      "reference": {
        "book": "Psalms",
        "chapter": 143,
        "verse": "8",
        "full_reference": "Psalms 143:8"
      },
      "modernVersion": "Lutherbibel 1912",
      "modernText": "Laß mich frühe hören deine Gnade; denn ich hoffe auf dich. Tue mir kund den Weg, darauf ich gehen soll; denn mich verlangt nach dir.",
      "contextNote": "Psalm 143 ist ein Klagelied. David wird verfolgt, und wenige Verse vorher sagt er das ganz ungeschützt. Das hier ist kein ruhiges Morgengebet, sondern das Gebet eines Bedrängten. Hinter dem Wort „Gnade“ steht im Hebräischen chesed: Bundestreue, eine Liebe, die sich vorher festgelegt hat und sich nicht mehr herausredet.",
      "meditation": "David beschreibt keinen guten Morgen. Er bittet um einen. Er sagt nicht: Ich höre deine Gnade. Er sagt: Lass mich hören. Das Hören stellt sich also nicht von allein ein, und er weiß das.\n\nDann bittet er um zweierlei, und die Reihenfolge steht fest: erst die Gnade, dann der Weg. Die meisten von uns drehen das um. Wir wollen morgens zuerst wissen, wo es langgeht, und hoffen, dass die Zusage sich unterwegs schon einstellt. Aber ein Weg ohne diese Zusage wird schnell zu Druck. Bitten wir heute um das Erste. Das Zweite läuft uns nicht weg.",
      "actionStep": "Sag heute Morgen einen Satz laut, bevor du irgendetwas planst: Ich bin geliebt, bevor ich nützlich bin. Und frag Gott danach nach der ersten Entscheidung auf deiner Liste.",
      "prayer": "Lieber himmlischer Vater, bevor ich dich frage, wohin ich gehen soll, lass mich hören, dass du mich liebst. Ich gebe zu, wie schnell ich diesen Teil überspringe und gleich beim Planen lande. Rede zuerst zu dem Teil in mir, der Zuspruch braucht, und zeig mir danach den nächsten Schritt. Diesen ganzen Tag lege ich dir hin. In Jesu Namen, Amen."
    },
    {
      "day": 1,
      "segment": "evening",
      "reference": {
        "book": "Hebrews",
        "chapter": 4,
        "verse": "16",
        "full_reference": "Hebrews 4:16"
      },
      "modernVersion": "Lutherbibel 1912",
      "modernText": "Darum laßt uns hinzutreten mit Freudigkeit zu dem Gnadenstuhl, auf daß wir Barmherzigkeit empfangen und Gnade finden auf die Zeit, wenn uns Hilfe not sein wird.",
      "contextNote": "Der Hebräerbrief richtet sich an Menschen aus dem Judentum, die wussten: In das Allerheiligste ging einmal im Jahr ein einziger Mann, mit Blut. „Gnadenstuhl“ ist Luthers Wort für genau diesen Ort. Das griechische parrhesia hinter „Freudigkeit“ meint die Freiheit einer Bürgerin, öffentlich offen zu reden — nicht die Dreistigkeit einer Eindringlingin.",
      "meditation": "„Freudigkeit“ — das ist das Wort, das hier steht, und am Ende eines Tages wie diesem klingt es fast unpassend. Nicht vorsichtig. Nicht erst, wenn wir uns vorzeigbar gemacht haben. Und der Ort, zu dem wir treten dürfen, heißt Gnadenstuhl: die Stelle, an der Versöhnung geschah, keine Prüfungsstelle.\n\nDie meisten von uns bringen abends zuerst die Bilanz mit und dann erst das Anliegen. Drehen wir das heute um. Wir dürfen freudig kommen, weil dort Barmherzigkeit ausgeteilt wird und niemand Punkte vergibt.",
      "actionStep": "Bring Gott heute Abend die eine Sache, die du eigentlich allein regeln wolltest. Sprich sie laut aus, bevor du schlafen gehst.",
      "prayer": "Lieber himmlischer Vater, ich komme heute Abend zu dir, ohne mich vorher zurechtzumachen, weil du es mir erlaubt hast. Danke, dass hier Barmherzigkeit wartet und keine Abrechnung. Hier ist, wobei ich Hilfe brauche, und hier ist, wo ich heute daneben lag. In Jesu Namen, Amen."
    },
    {
      "day": 2,
      "segment": "morning",
      "reference": {
        "book": "Romans",
        "chapter": 8,
        "verse": "6",
        "full_reference": "Romans 8:6"
      },
      "modernVersion": "Lutherbibel 1912",
      "modernText": "Aber fleischlich gesinnt sein ist der Tod, und geistlich gesinnt sein ist Leben und Friede.",
      "contextNote": "Römer 8 beginnt mit „keine Verdammnis“, und dieser Vers steht innerhalb dieser Zusage, nicht dagegen. Das Wort des Paulus für den fleischlichen Sinn ist phronema — kein einzelner Gedanke, sondern eine eingefahrene Neigung, die Richtung, in die ein Denken driftet, wenn man es sich selbst überlässt. Er beschreibt eine Strömung, kein Urteil.",
      "meditation": "Paulus hält hier keine Moralpredigt über dein Verhalten. Er spricht davon, wohin deine Gedanken laufen, wenn du sie nicht mehr lenkst — die Spur, in die sie von allein zurückfallen, sobald nichts sie hält.\n\nDie eine Richtung endet in einer Art Erstarrung. Die andere öffnet sich zu Leben und Frieden. Und das Gute daran: Es geht nicht darum, dass du dich heute besser zusammenreißt. Es geht darum, worauf dein Sinn gerichtet ist — und der darf heute Morgen neu gedreht werden!",
      "actionStep": "Achte heute darauf, wohin deine Gedanken gehen, sobald du sie loslässt. Bewerte es nicht — sag Gott einfach, was es war.",
      "prayer": "Lieber himmlischer Vater, du weißt, wohin meine Gedanken laufen, wenn ich sie nicht mehr lenke, und manches davon tut mir nicht gut. Dreh mein Denken heute Morgen dorthin, wo Leben und Friede sind — nicht mit Gewalt, sondern indem du mich ziehst. In Jesu Namen, Amen."
    },
    {
      "day": 2,
      "segment": "evening",
      "reference": {
        "book": "2 Kings",
        "chapter": 20,
        "verse": "5",
        "full_reference": "2 Kings 20:5"
      },
      "modernVersion": "Lutherbibel 1912",
      "modernText": "Kehre um und sage Hiskia, dem Fürsten meines Volkes: So spricht der HERR, der Gott deines Vaters David: Ich habe dein Gebet gehört und deine Tränen gesehen. Siehe, ich will dich gesund machen, am dritten Tage wirst du hinauf in das Haus des HERRN gehen,",
      "contextNote": "Hiskia war todkrank, und man hatte ihm gerade gesagt, er solle sein Haus bestellen. Jesaja verließ bereits den Palast, als Gott ihn umkehren ließ. Für das Sehen der Tränen steht im Hebräischen das ganz gewöhnliche Verb für Anschauen, ohne jedes poetische Schmuckwerk. Gott wendet sich dem Teil des Gebets zu, der keine Worte hat.",
      "meditation": "Hiskia hatte die Antwort längst bekommen, und sie hieß Nein; der Prophet war schon aus dem Zimmer. Dann schickte Gott ihn zurück. Achte auf die Reihenfolge dessen, was Gott ihm mitgibt. Vor jeder Zusage, bevor sich irgendetwas ändert, steht zweierlei: Das Gebet ist gehört. Die Tränen sind gesehen. Die Tränen bekommen einen eigenen Halbsatz. Gott verrechnet sie nicht stillschweigend mit dem Gebet, als wäre Weinen nur eine unbeholfene Art zu bitten. Er zählt sie einzeln.\n\nUnd worüber du auch weinst — das eine Thema, das du irgendwann aufgehört hast, Menschen zu erklären, weil dich das Erklären müde gemacht hat: Es ist gesehen. Nicht übersehen, nicht bloß geduldet. Gesehen!",
      "actionStep": "Sprich heute Abend laut aus, was du längst niemandem mehr erklärst. Du musst dafür nichts begründen. Sag es einfach.",
      "prayer": "Lieber himmlischer Vater, danke, dass du Tränen gesondert zählst und meiner nicht müde geworden bist. Vor Menschen habe ich vor einer Weile aufgehört, das zu erklären. Vor dir höre ich damit nicht auf. Danke, dass von dir gesehen zu werden etwas anderes ist als bemitleidet zu werden. Halt fest, was ich dir heute Abend hinlege. In Jesu Namen, Amen."
    },
    {
      "day": 3,
      "segment": "morning",
      "reference": {
        "book": "2 Corinthians",
        "chapter": 3,
        "verse": "17",
        "full_reference": "2 Corinthians 3:17"
      },
      "modernVersion": "Lutherbibel 1912",
      "modernText": "Denn der HERR ist der Geist; wo aber der Geist des HERRN ist, da ist Freiheit.",
      "contextNote": "Kurz vorher beschreibt Paulus, wie Mose sein Gesicht verhüllte, nachdem er bei Gott gewesen war. Der Gegensatz ist ein Bund, den man hinter einer Decke auf Abstand hält, und einer, der mit unbedecktem Gesicht gelebt wird. Das griechische eleutheria meint den Rechtsstand einer Freigelassenen — ein Status, keine Stimmung.",
      "meditation": "Als Christinnen machen wir aus dem Glauben still und leise noch einen Ort, an dem wir gemessen werden. Noch eine Liste, noch eine Leistung, noch ein Raum, in dem wir vielleicht nicht genügen.\n\nPaulus sagt etwas anderes über diesen Raum. Wo Gottes Geist wirkt, entsteht Freiheit — keine Erlaubnis, alles zu tun, sondern die Entlastung, nichts mehr beweisen zu müssen. Nehmen wir das heute mit in den Tag. Du stehst nicht auf dem Prüfstand.",
      "actionStep": "Nenn eine Sache, die du heute vor allem tun wolltest, um etwas zu beweisen. Tu sie oder lass sie — aber als freie Frau, nicht als Bewerberin.",
      "prayer": "Lieber himmlischer Vater, danke, dass dein Geist Freiheit bringt und nicht die nächste Prüfung. Ich gebe zu, wie oft ich meinen Glauben in etwas verwandle, woran ich scheitern könnte. Lockere das heute in mir. Lass mich arbeiten und reden als eine, die längst angenommen ist. In Jesu Namen, Amen."
    },
    {
      "day": 3,
      "segment": "evening",
      "reference": {
        "book": "Acts",
        "chapter": 16,
        "verse": "25",
        "full_reference": "Acts 16:25"
      },
      "modernVersion": "Lutherbibel 1912",
      "modernText": "Um Mitternacht aber beteten Paulus und Silas und lobten Gott. Und es hörten sie die Gefangenen.",
      "contextNote": "Paulus und Silas waren ausgezogen, mit Ruten geschlagen und in den innersten Kerker geworfen worden — Lukas nennt alle drei Punkte. Ihr Tun in dieser Nacht heißt bei Luther beten und Gott loben. Dass die Gefangenen ihnen zuhörten, ist eine Beobachtung, die Lukas eigens hinzufügt; er hätte sie auch weglassen können.",
      "meditation": "Zwei Männer, geschlagen, im innersten Kerker, die Füße im Block. Es ist Mitternacht — die Stunde, in der niemand mehr zusieht und nichts mehr zu machen ist. Und in dieser Stunde beten Paulus und Silas, und sie loben Gott. Nicht erst, als die Türen aufspringen. Vorher, als sich noch gar nichts geändert hatte.\n\nDer letzte Halbsatz wird meistens überlesen: Die anderen Gefangenen hörten mit. Niemand betete für ein Publikum, es gab keins — nur Menschen im selben Dunkel, die wach lagen. Aber Vertrauen in einer schlechten Nacht bleibt nie ganz privat. Die Frau im Nebenzimmer hört es. Das Kind auf dem Flur hört es. Wenn du heute Nacht wach liegst, bete so laut, dass du dich selbst hörst — deine Mitternacht trägt weiter, als du denkst.",
      "actionStep": "Wenn du heute Nacht wach liegst, obwohl du schlafen willst, hör für zehn Minuten auf, dagegen anzukämpfen. Bete in dieser Zeit — laut, wenn es geht.",
      "prayer": "Lieber himmlischer Vater, ich wäre jetzt lieber nicht wach, und ich wäre lieber schon durch damit. Danke, dass du der Mitte der Nacht nicht fernbleibst. Wenn ich nicht schlafen kann, dann lass mich beten. Und wenn jemand neben mir zuhört, dann lass ihn Vertrauen hören und nicht Verzweiflung. In Jesu Namen, Amen."
    }
  ],
  "fr": [
    {
      "day": 1,
      "segment": "morning",
      "reference": {
        "book": "Psalms",
        "chapter": 143,
        "verse": "8",
        "full_reference": "Psalms 143:8"
      },
      "modernVersion": "Louis Segond 1910",
      "modernText": "Fais-moi dès le matin entendre ta bonté! Car je me confie en toi. Fais-moi connaître le chemin où je dois marcher! Car j'élève à toi mon âme.",
      "contextNote": "Le Psaume 143 est une plainte : quelques versets plus haut, David dit sans détour qu'on le poursuit. Ce n'est pas une prière matinale sereine, elle vient de quelqu'un en danger. Le mot hébreu derrière « bonté » est chesed — une loyauté d'alliance, un attachement engagé d'avance, dont on ne se dédit pas.",
      "meditation": "David ne décrit pas une belle matinée : il en demande une. Le verbe est une requête — fais-moi entendre — ce qui suppose que la chose ne va pas de soi, et il le sait très bien.\n\nPuis il demande deux choses, dans cet ordre : d'abord entendre la bonté de Dieu, ensuite connaître le chemin. La plupart d'entre nous inversons : la direction tout de suite, la bonté plus tard, s'il reste du temps. Mais une direction reçue sans bonté se transforme très vite en pression, et nous avons presque toutes essayé de vivre ainsi. Demandons donc la première ce matin, en élevant notre âme vers lui. La seconde tiendra bien jusque-là.",
      "actionStep": "Avant d'organiser quoi que ce soit aujourd'hui, dis une phrase à voix haute : je suis aimée avant d'être utile. Puis parle à Dieu de la première décision de ta liste.",
      "prayer": "Cher Père céleste, avant de te demander où aller, laisse-moi entendre ta bonté. Je reconnais que je saute presque toujours cette étape pour passer directement aux plans de la journée. Parle d'abord à la part de moi qui a besoin d'être rassurée, puis montre-moi le pas suivant. J'élève vers toi cette journée entière, telle qu'elle est. Au nom de Jésus, amen."
    },
    {
      "day": 1,
      "segment": "evening",
      "reference": {
        "book": "Hebrews",
        "chapter": 4,
        "verse": "16",
        "full_reference": "Hebrews 4:16"
      },
      "modernVersion": "Louis Segond 1910",
      "modernText": "Approchons-nous donc avec assurance du trône de la grâce, afin d'obtenir miséricorde et de trouver grâce, pour être secourus dans nos besoins.",
      "contextNote": "L'épître aux Hébreux s'adresse à des chrétiens d'origine juive : ils savaient qu'on entrait dans le lieu très saint une fois l'an, un seul homme, avec du sang. Sur ce fond, s'approcher avec assurance est stupéfiant. Le grec parrhesia désigne la liberté du citoyen de parler ouvertement en public, pas l'audace d'un intrus.",
      "meditation": "Avec assurance : voilà le mot choisi, au bout d'une journée pareille. Pas prudemment. Pas une fois que nous nous serons remises en ordre. Et remarquons de quoi ce trône porte le nom — la grâce, et non l'examen.\n\nEn tant que chrétiennes, nous trions souvent avant d'entrer, et nous ne présentons que le présentable. Qu'apporterais-tu vraiment ce soir, si tu croyais cela de la pièce où tu entres ?",
      "actionStep": "Apporte à Dieu la seule chose que tu comptais gérer toute seule. Dis-la à voix haute avant de dormir.",
      "prayer": "Cher Père céleste, je viens à toi ce soir sans m'être d'abord remise en ordre, parce que tu me l'as permis. Merci : c'est un trône de grâce, et non un tribunal. Voici ce pour quoi j'ai besoin d'aide, et voici où j'ai manqué. Au nom de Jésus, amen."
    },
    {
      "day": 2,
      "segment": "morning",
      "reference": {
        "book": "Romans",
        "chapter": 8,
        "verse": "6",
        "full_reference": "Romans 8:6"
      },
      "modernVersion": "Louis Segond 1910",
      "modernText": "Et l'affection de la chair, c'est la mort, tandis que l'affection de l'esprit, c'est la vie et la paix;",
      "contextNote": "Romains 8 s'ouvre sur « aucune condamnation », et ce verset se tient à l'intérieur de cette promesse, non pas contre elle. Le mot grec de Paul, phronema, ne désigne pas une pensée isolée mais un penchant installé, la direction où l'on se laisse aller quand personne ne regarde. Il décrit un courant, il ne prononce pas un verdict.",
      "meditation": "Paul ne fait pas ici la morale sur les comportements. Il parle de ce vers quoi ton affection penche quand tu cesses de la tenir : l'attachement où tout revient tout seul, dès que rien ne te retient.\n\nUn penchant aboutit à une forme de mort. L'autre s'ouvre sur la vie et la paix. La vraie question de ce matin n'est donc pas ce que tu vas faire, mais vers quoi ton cœur s'incline depuis quelque temps, sans que tu l'aies décidé. Et cette inclination-là n'est pas ta condamnation : elle peut être déplacée !",
      "actionStep": "Remarque aujourd'hui vers quoi ton cœur revient dès qu'il n'a plus rien à faire. Ne le juge pas : dis simplement à Dieu ce que c'était.",
      "prayer": "Cher Père céleste, tu sais vers quoi mon cœur penche quand je cesse de le tenir, et une partie de cela ne me fait aucun bien. Tourne ce matin mon affection vers ce qui donne vraiment la vie et la paix — non par contrainte, mais en m'attirant. Au nom de Jésus, amen."
    },
    {
      "day": 2,
      "segment": "evening",
      "reference": {
        "book": "2 Kings",
        "chapter": 20,
        "verse": "5",
        "full_reference": "2 Kings 20:5"
      },
      "modernVersion": "Louis Segond 1910",
      "modernText": "Retourne, et dis à Ézéchias, chef de mon peuple: Ainsi parle l'Éternel, le Dieu de David, ton père: J'ai entendu ta prière, j'ai vu tes larmes. Voici, je te guérirai; le troisième jour, tu monteras à la maison de l'Éternel.",
      "contextNote": "Ézéchias est mourant et vient de recevoir l'ordre de mettre sa maison en ordre. Ésaïe quittait déjà le palais quand Dieu l'a retourné. En hébreu, la phrase sur les larmes emploie le verbe ordinaire pour regarder une chose, sans aucun effet poétique. Dieu prête attention à la part de la prière qui n'a pas de mots.",
      "meditation": "On avait déjà dit à Ézéchias que la réponse était non ; le prophète était sorti du palais. Et Dieu l'a fait revenir sur ses pas. Regarde l'ordre des mots. Avant la promesse, avant que quoi que ce soit change, il y a ceci : ta prière, il l'a entendue ; tes larmes, il les a vues. Les larmes reçoivent leur propre proposition. Dieu ne les range pas à l'intérieur de la prière, comme si pleurer n'était qu'une façon maladroite de demander. Il les compte à part.\n\nCe sur quoi tu pleures depuis des mois — ce que tu as cessé d'expliquer aux autres, à force de l'expliquer — a été vu. Ni négligé, ni seulement toléré. Vu !",
      "actionStep": "Dis à voix haute la chose que tu n'expliques plus à personne. Tu n'as ni à la plaider ni à la justifier. Dis-la, simplement, et laisse-la là.",
      "prayer": "Cher Père céleste, merci de compter les larmes à part des mots, et de ne pas t'être lassé des miennes. J'ai arrêté depuis longtemps d'expliquer cela autour de moi. Je n'arrêterai pas de te l'expliquer à toi. Merci : être vue par toi n'est pas la même chose qu'être plainte. Garde cette nuit ce que je viens de déposer devant toi. Au nom de Jésus, amen."
    },
    {
      "day": 3,
      "segment": "morning",
      "reference": {
        "book": "2 Corinthians",
        "chapter": 3,
        "verse": "17",
        "full_reference": "2 Corinthians 3:17"
      },
      "modernVersion": "Louis Segond 1910",
      "modernText": "Or, le Seigneur c'est l'Esprit; et là où est l'Esprit du Seigneur, là est la liberté.",
      "contextNote": "Paul vient de rappeler Moïse se voilant le visage après avoir été avec Dieu. Le contraste porte sur deux alliances : l'une tenue à distance derrière un voile, l'autre vécue à visage découvert. Le grec eleutheria désigne le statut juridique d'une personne affranchie — une position acquise, pas une humeur passagère.",
      "meditation": "En tant que chrétiennes, nous transformons parfois la foi en un endroit de plus où l'on nous mesure. Une liste supplémentaire, une performance de plus, encore une pièce où nous risquons de ne pas suffire.\n\nPaul dit exactement le contraire de cette pièce-là : là où est l'Esprit, il y a la liberté. Non pas la permission de tout faire, mais le soulagement de n'avoir plus rien à prouver. Emportons cela dans la journée. Tu ne passes pas une audition.",
      "actionStep": "Nomme une chose que tu allais faire aujourd'hui surtout pour prouver quelque chose. Fais-la, ou renonces-y — mais en femme libre, pas en candidate.",
      "prayer": "Cher Père céleste, merci : ton Esprit apporte la liberté, et non un examen de plus. Je reconnais combien souvent je transforme ma foi en quelque chose que je pourrais rater. Desserre cela en moi aujourd'hui. Que je travaille et que je parle en femme déjà accueillie. Au nom de Jésus, amen."
    },
    {
      "day": 3,
      "segment": "evening",
      "reference": {
        "book": "Acts",
        "chapter": 16,
        "verse": "25",
        "full_reference": "Acts 16:25"
      },
      "modernVersion": "Louis Segond 1910",
      "modernText": "Vers le milieu de la nuit, Paul et Silas priaient et chantaient les louanges de Dieu, et les prisonniers les entendaient.",
      "contextNote": "Paul et Silas avaient été dévêtus, battus de verges et jetés dans le cachot le plus intérieur — Luc précise les trois. Le verbe grec de leur chant, hymneo, est celui de l'hymne que Jésus a chanté avec ses disciples avant Gethsémané. Que les détenus les aient entendus est un détail propre à Luc, ajouté à dessein.",
      "meditation": "Deux hommes battus, enfermés dans le cachot le plus intérieur, les pieds pris dans des entraves. Il est minuit. Et voilà ce qu'ils font de cette heure-là : ils prient, puis ils chantent.\n\nRemarque la dernière proposition, celle qu'on saute d'habitude : les autres détenus les entendaient. Personne ne chantait pour un public — il n'y avait pas de public, seulement des gens couchés dans la même obscurité, éveillés eux aussi. Mais la foi, dans une mauvaise nuit, n'est jamais tout à fait privée. La femme de la chambre d'à côté entend. L'enfant au bout du couloir entend. Ton minuit porte plus loin que tu ne crois, et pas toujours en mal. Ce soir, choisis ce qu'on entendra de toi.",
      "actionStep": "Si tu es réveillée cette nuit alors que tu voudrais dormir, cesse de lutter pendant dix minutes. Prie pendant ce temps-là — à voix haute, si tu peux.",
      "prayer": "Cher Père céleste, je préférerais ne pas être éveillée maintenant, et je préférerais que tout cela soit fini. Merci de n'être pas absent du milieu de la nuit. Si je ne peux pas dormir, que je prie. Et si quelqu'un près de moi écoute, que ce qu'il entend de moi soit la confiance et non le désespoir. Au nom de Jésus, amen."
    }
  ],
  "es": [
    {
      "day": 1,
      "segment": "morning",
      "reference": {
        "book": "Psalms",
        "chapter": 143,
        "verse": "8",
        "full_reference": "Psalms 143:8"
      },
      "modernVersion": "Reina-Valera 1909",
      "modernText": "Hazme oir por la mañana tu misericordia, porque en ti he confiado: hazme saber el camino por donde ande, porque á ti he alzado mi alma.",
      "contextNote": "El Salmo 143 es un lamento: unos versículos antes, David dice sin rodeos que lo persiguen. No es una oración serena de la mañana; la escribió alguien en peligro. La palabra hebrea detrás de misericordia es chesed: lealtad de pacto, un amor que ya se comprometió de antemano y no se echa atrás.",
      "meditation": "David no está describiendo una buena mañana. Está pidiendo una, y vale la pena copiarle el orden en que pide.\n\nPrimero, oír que es amado. Después, saber por dónde caminar. Nosotras casi siempre lo hacemos al revés: llegamos por la dirección, por la decisión, por qué hacer con el asunto que nos quita el sueño. Pero la dirección sin amor se vuelve presión, y casi todas hemos vivido así por temporadas largas. Pidamos hoy lo primero. Lo segundo puede esperar. Dios no se cansa de empezar por ahí.",
      "actionStep": "Antes de planear nada hoy, di una frase en voz alta: soy amada antes de ser útil. Después pregúntale a Dios por la primera decisión de tu lista.",
      "prayer": "Amado Padre celestial, antes de preguntarte hacia dónde ir, déjame oír que me amas. Reconozco que salto esa parte con demasiada facilidad y me voy directo a organizar el día. Habla primero a la parte de mí que necesita ser tranquilizada, y después muéstrame el siguiente paso. Levanto hacia ti todo este día, tal como viene. En el nombre de Jesús, amén."
    },
    {
      "day": 1,
      "segment": "evening",
      "reference": {
        "book": "Hebrews",
        "chapter": 4,
        "verse": "16",
        "full_reference": "Hebrews 4:16"
      },
      "modernVersion": "Reina-Valera 1909",
      "modernText": "Lleguémonos pues confiadamente al trono de la gracia, para alcanzar misericordia, y hallar gracia para el oportuno socorro.",
      "contextNote": "Hebreos se escribió a cristianos judíos que sabían que al lugar santísimo se entraba una vez al año, un solo hombre, con sangre. Con ese trasfondo, 'lleguémonos confiadamente' sorprende. La palabra griega es parrhesia: la libertad de un ciudadano para hablar sin rodeos en público, no el atrevimiento de quien se cuela.",
      "meditation": "Como cristianas solemos acercarnos a Dios igual que a una evaluación: con nuestra defensa medio redactada antes de entrar. Hebreos usa otra palabra: confiadamente. No con cautela, no después de arreglarnos un poco.\n\nY fíjate en el nombre de ese trono. Gracia, no revisión. Vengamos esta noche tal como estamos, sin ir ensayando la explicación por el camino.",
      "actionStep": "Lleva a Dios esa única cosa que pensabas resolver tú sola. Dila en voz alta antes de dormir, aunque te salga torpe y entrecortada.",
      "prayer": "Amado Padre celestial, vengo a ti esta noche sin arreglarme primero, porque tú me dijiste que podía. Gracias porque este es un trono de gracia y no una revisión. Aquí está lo que necesito y aquí está donde fallé. En el nombre de Jesús, amén."
    },
    {
      "day": 2,
      "segment": "morning",
      "reference": {
        "book": "Romans",
        "chapter": 8,
        "verse": "6",
        "full_reference": "Romans 8:6"
      },
      "modernVersion": "Reina-Valera 1909",
      "modernText": "Porque la intención de la carne es muerte; mas la intención del espíritu, vida y paz:",
      "contextNote": "Romanos 8 empieza con la palabra ninguna condenación, y este versículo vive dentro de esa promesa, no en contra de ella. El término de Pablo para la mente gobernada por la carne es phronema: no un pensamiento suelto, sino una inclinación asentada, la dirección hacia la que la mente se va sola. Describe una corriente, no dicta una sentencia.",
      "meditation": "Pablo no está aquí dando una lección de moral sobre tu conducta. Habla de adónde va tu mente cuando dejas de dirigirla, del canal al que vuelve sola.\n\nY esta es la promesa, dirigida a ti: el otro canal se abre en vida y paz. No en pensamientos más ordenados. Vida. ¡No estás atrapada en lo de siempre, y nunca se esperó que salieras de ahí peleando sola!",
      "actionStep": "Fíjate hoy en el primer lugar al que va tu mente cuando queda libre. No lo juzgues: solo cuéntale a Dios lo que encontraste.",
      "prayer": "Amado Padre celestial, tú sabes adónde va mi mente cuando dejo de dirigirla, y parte de eso no me hace ningún bien. Vuelve hoy mi pensamiento hacia lo que de verdad da vida, no a la fuerza, sino atrayéndome. En el nombre de Jesús, amén."
    },
    {
      "day": 2,
      "segment": "evening",
      "reference": {
        "book": "2 Kings",
        "chapter": 20,
        "verse": "5",
        "full_reference": "2 Kings 20:5"
      },
      "modernVersion": "Reina-Valera 1909",
      "modernText": "Vuelve, y di á Ezechîas, príncipe de mi pueblo: Así dice Jehová, el Dios de David tu padre: Yo he oído tu oración, y he visto tus lágrimas: he aquí yo te sano; al tercer día subirás á la casa de Jehová.",
      "contextNote": "Ezequías estaba enfermo de muerte y acababan de decirle que pusiera su casa en orden. Isaías ya salía del palacio cuando Dios lo hizo volver. En hebreo, el verbo para ver las lágrimas es el común de mirar algo, sin adorno poético. La idea es que Dios atiende la parte de la oración que no tiene palabras.",
      "meditation": "A Ezequías ya le habían dado la respuesta: no. El profeta ya se había ido. Y entonces Dios lo mandó de vuelta. Fíjate en el orden de lo que Dios dice. Antes de la promesa, antes de que nada cambie, Dios menciona dos cosas: la oración que escuchó y las lágrimas que vio. Las lágrimas tienen su propia frase. Dios no las mete dentro de la oración como si llorar fuera una manera torpe de pedir. Las cuenta aparte.\n\nEso por lo que has estado llorando, aquello que dejaste de explicarle a la gente porque te cansaste de explicarlo, ya fue visto. No pasado por alto, no tolerado. ¡Visto!",
      "actionStep": "Di en voz alta aquello que ya dejaste de explicarle a nadie. No tienes que defenderlo ni justificarlo delante de Dios. Solo dilo, con las palabras que te salgan.",
      "prayer": "Amado Padre celestial, gracias porque cuentas mis lágrimas aparte de mis palabras, y porque no te has cansado de ellas. Hace tiempo dejé de explicarle esto a la gente. A ti no voy a dejar de explicártelo. Gracias porque ser vista por ti no es lo mismo que dar lástima. Sostén esta noche lo que he traído delante de ti. En el nombre de Jesús, amén."
    },
    {
      "day": 3,
      "segment": "morning",
      "reference": {
        "book": "2 Corinthians",
        "chapter": 3,
        "verse": "17",
        "full_reference": "2 Corinthians 3:17"
      },
      "modernVersion": "Reina-Valera 1909",
      "modernText": "Porque el Señor es el Espíritu; y donde hay el Espíritu del Señor, allí hay libertad.",
      "contextNote": "Pablo acaba de describir a Moisés cubriéndose el rostro con un velo después de estar con Dios. El contraste es entre un pacto vivido a distancia, detrás de un velo, y otro vivido a cara descubierta. El griego eleutheria era el estatus legal de una persona liberada: una condición, no un estado de ánimo.",
      "meditation": "Como cristianas podemos convertir la fe, sin darnos cuenta, en un lugar más donde nos miden. Otra lista, otro desempeño, otro cuarto donde quizá no seamos suficientes.\n\nPablo describe ese cuarto al revés. Donde el Espíritu está presente hay aire para respirar: no es permiso para hacer cualquier cosa, sino el alivio de no tener que demostrar nada. Llevemos eso al día de hoy. No estás en una audición.",
      "actionStep": "Nombra una cosa que ibas a hacer hoy sobre todo para demostrar algo. Hazla o déjala, pero como mujer libre, no como candidata.",
      "prayer": "Amado Padre celestial, gracias porque tu Espíritu trae libertad y no otra prueba. Reconozco cuántas veces convierto mi fe en algo que podría reprobar. Aflójame eso hoy. Que trabaje y hable como alguien que ya fue aceptada. En el nombre de Jesús, amén."
    },
    {
      "day": 3,
      "segment": "evening",
      "reference": {
        "book": "Acts",
        "chapter": 16,
        "verse": "25",
        "full_reference": "Acts 16:25"
      },
      "modernVersion": "Reina-Valera 1909",
      "modernText": "Mas á media noche, orando Pablo y Silas, cantaban himnos á Dios: y los que estaban presos los oían.",
      "contextNote": "A Pablo y Silas los habían desnudado, azotado con varas y echado en el calabozo más interior; Lucas es preciso en los tres detalles. El verbo griego de su canto, hymneo, es el mismo del himno que Jesús cantó con sus discípulos antes de Getsemaní. Que los presos 'los oían' es un detalle propio de Lucas, y lo incluye a propósito.",
      "meditation": "Dos hombres golpeados y encerrados en el calabozo de más adentro, con los pies en el cepo. Es medianoche. Y Lucas anota qué hicieron con esa hora en particular: oraron, y después cantaron.\n\nFíjate en la última frase, que es la que solemos saltarnos. Los demás presos los oían. Nadie estaba cantando para un público, porque público no había: solo gente en la misma oscuridad, despierta. Pero la fe en una noche mala nunca es del todo privada. La mujer del cuarto de al lado escucha. El hijo que duerme en el pasillo escucha. Tu medianoche suena más fuerte de lo que crees, y no siempre para mal.",
      "actionStep": "Si esta noche estás despierta cuando preferirías dormir, deja de pelear con el insomnio diez minutos. Ora en ese rato, en voz alta si puedes.",
      "prayer": "Amado Padre celestial, preferiría no estar despierta ahora, y preferiría que todo esto ya hubiera pasado. Gracias porque tú no estás ausente de la mitad de la noche. Si no puedo dormir, déjame orar. Y si alguien cerca de mí está escuchando, que lo que oiga de mí sea confianza y no desesperación. En el nombre de Jesús, amén."
    }
  ],
  "pt": [
    {
      "day": 1,
      "segment": "morning",
      "reference": {
        "book": "Psalms",
        "chapter": 143,
        "verse": "8",
        "full_reference": "Psalms 143:8"
      },
      "modernVersion": "João Ferreira de Almeida",
      "modernText": "Faze-me ouvir da tua benignidade pela manhã, pois em ti confio; faze-me saber o caminho que devo seguir, porque a ti elevo a minha alma.",
      "contextNote": "O Salmo 143 é um lamento: poucos versículos antes, Davi diz que está sendo perseguido. Não é uma oração serena de manhã; foi escrita por alguém em apuros. A palavra hebraica traduzida por benignidade é chesed — lealdade de aliança, um amor que já se comprometeu antes e não volta atrás.",
      "meditation": "Davi não está descrevendo uma manhã boa. Ele está pedindo por uma, e a ordem do pedido vale a pena copiar.\n\nPrimeiro ele quer ouvir que é amado. Depois, saber para onde ir. Como cristãs, nós costumamos inverter a ordem: chegamos atrás da direção, da decisão, do que fazer com aquele assunto. Mas direção sem amor vira pressão, e quase todas nós já vivemos assim por um tempo. Hoje de manhã, vamos pedir a primeira coisa: a bondade que nos alcança antes de qualquer resposta. A segunda pode esperar.",
      "actionStep": "Antes de planejar qualquer coisa hoje, diga uma frase em voz alta: sou amada antes de ser útil. Depois pergunte a Deus sobre a primeira decisão da sua lista.",
      "prayer": "Amado Pai celestial, antes de eu te perguntar para onde ir, deixa-me ouvir que sou amada. Confesso como pulo essa parte com facilidade e corro direto para o planejamento. Fala primeiro com a parte de mim que precisa de segurança, e depois mostra-me o próximo passo. Eu te entrego o meu dia inteiro. Em nome de Jesus, amém."
    },
    {
      "day": 1,
      "segment": "evening",
      "reference": {
        "book": "Hebrews",
        "chapter": 4,
        "verse": "16",
        "full_reference": "Hebrews 4:16"
      },
      "modernVersion": "João Ferreira de Almeida",
      "modernText": "Cheguemo-nos, pois, confiadamente ao trono da graça, para que recebamos misericórdia e achemos graça, a fim de sermos socorridos no momento oportuno.",
      "contextNote": "Hebreus foi escrito a cristãos judeus que sabiam: no Santo dos Santos se entrava uma vez por ano, por um só homem, levando sangue. Diante disso, chegar confiadamente é surpreendente. O grego é parrhesia — a liberdade que um cidadão tinha de falar abertamente em público, não a ousadia de quem invade.",
      "meditation": "Como cristãs, muitas vezes chegamos diante de Deus como quem chega a uma avaliação: com a defesa já meio pronta na cabeça. Hebreus usa outra palavra: confiadamente. Não com cuidado, não depois de nos ajeitarmos.\n\nE repare no nome daquele trono. Graça, não julgamento. Então vamos chegar esta noite como realmente estamos, sem ensaiar a explicação no caminho.",
      "actionStep": "Leve a Deus aquela única coisa que você estava planejando resolver sozinha. Diga em voz alta, antes de dormir, sem preparar argumento nenhum.",
      "prayer": "Amado Pai celestial, chego a ti esta noite sem me ajeitar primeiro, porque tu mesmo disseste que eu podia. Obrigada porque este é um trono de graça, e não um tribunal. Aqui está o que preciso, e aqui está onde eu falhei. Em nome de Jesus, amém."
    },
    {
      "day": 2,
      "segment": "morning",
      "reference": {
        "book": "Romans",
        "chapter": 8,
        "verse": "6",
        "full_reference": "Romans 8:6"
      },
      "modernVersion": "João Ferreira de Almeida",
      "modernText": "Porque a inclinação da carne é morte; mas a inclinação do Espírito é vida e paz.",
      "contextNote": "Romanos 8 começa com 'nenhuma condenação', e este versículo está dentro dessa promessa, não contra ela. A palavra de Paulo para a mente dominada pela carne é phronema: não um pensamento isolado, mas uma inclinação firme, a direção para onde a mente escorrega quando é deixada em paz. Ele descreve uma correnteza, não profere uma sentença.",
      "meditation": "Paulo não está aqui dando lição de moral sobre o seu comportamento. Ele está falando do lugar para onde a sua mente vai quando você para de conduzi-la — o canal em que ela sintoniza sozinha.\n\nE aqui está a promessa, endereçada a você: o outro canal abre para vida e paz. Não para pensamentos mais organizados. Vida. Você não está presa ao automático, e nunca se esperou que você saísse dele lutando sozinha!",
      "actionStep": "Repare hoje no primeiro lugar para onde a sua mente vai quando ela fica à toa. Não julgue o que encontrar; apenas conte a Deus o que era.",
      "prayer": "Amado Pai celestial, tu sabes para onde a minha mente vai quando eu paro de conduzi-la, e parte disso não me faz bem nenhum. Volta o meu pensamento hoje para aquilo que dá vida de verdade — não à força, mas me atraindo. Em nome de Jesus, amém."
    },
    {
      "day": 2,
      "segment": "evening",
      "reference": {
        "book": "2 Kings",
        "chapter": 20,
        "verse": "5",
        "full_reference": "2 Kings 20:5"
      },
      "modernVersion": "João Ferreira de Almeida",
      "modernText": "Volta, e dize a Ezequias, príncipe do meu povo: Assim diz o Senhor Deus de teu pai Davi: Ouvi a tua oração, e vi as tuas lágrimas. Eis que eu te sararei; ao terceiro dia subirás à casa do Senhor.",
      "contextNote": "Ezequias estava doente, sem cura à vista, e acabara de ouvir que devia pôr a casa em ordem. Isaías já saía do palácio quando Deus o fez voltar. Em hebraico, vi as tuas lágrimas usa o verbo comum de olhar para alguma coisa, sem nenhum enfeite poético. É a parte da oração que não tem palavras, e Deus repara nela.",
      "meditation": "A Ezequias já tinha sido dito que a resposta era não. O profeta já estava saindo. E então Deus o mandou voltar. Repare na ordem do que Deus diz. Antes da promessa, antes de qualquer coisa mudar, vem isto: ele ouviu a oração, e viu as lágrimas. As lágrimas ganham uma frase só delas. Deus não as dissolve dentro da oração, como se chorar fosse um jeito ineficiente de pedir. Ele conta as duas coisas separadamente.\n\nAquilo que você tem chorado — aquilo que você parou de explicar para as pessoas porque cansou de explicar — isso foi visto. Não passou despercebido, não foi apenas tolerado. Foi visto!",
      "actionStep": "Diga em voz alta aquilo que você já parou de explicar para todo mundo. Você não precisa justificar nem construir argumento. Só diga.",
      "prayer": "Amado Pai celestial, obrigada porque tu contas as lágrimas à parte das palavras, e porque não te cansaste das minhas. Faz um tempo que parei de explicar isso para as pessoas. Contigo eu não vou parar. Obrigada porque ser vista por ti não é o mesmo que ser motivo de pena. Guarda esta noite aquilo que eu trouxe. Em nome de Jesus, amém."
    },
    {
      "day": 3,
      "segment": "morning",
      "reference": {
        "book": "2 Corinthians",
        "chapter": 3,
        "verse": "17",
        "full_reference": "2 Corinthians 3:17"
      },
      "modernVersion": "João Ferreira de Almeida",
      "modernText": "Ora, o Senhor é o Espírito; e onde está o Espírito do Senhor aí há liberdade.",
      "contextNote": "Pouco antes, Paulo lembra Moisés cobrindo o rosto com um véu depois de estar com Deus. O contraste é entre uma aliança vivida a distância, atrás do véu, e outra vivida de rosto descoberto. O grego eleutheria descreve a condição legal de quem foi libertado: um status conquistado por outro, não um estado de espírito.",
      "meditation": "Como cristãs, nós conseguimos transformar a fé em mais um lugar onde estamos sendo medidas. Outra lista, outro desempenho, mais uma sala em que talvez não sejamos suficientes.\n\nPaulo diz outra coisa sobre essa sala: onde o Espírito habita, a marca é liberdade — não permissão para qualquer coisa, mas o alívio de não ter nada a provar. Vamos levar isso para hoje. Você não está em uma seleção.",
      "actionStep": "Escolha uma coisa que você faria hoje só para provar algo. Faça ou deixe de lado, mas decida como mulher livre, e não como candidata a uma vaga.",
      "prayer": "Amado Pai celestial, obrigada porque o teu Espírito traz liberdade e não mais uma prova. Confesso quantas vezes transformo a minha fé em algo que eu poderia reprovar. Afrouxa isso em mim hoje. Que eu trabalhe e fale como quem já foi aceita. Em nome de Jesus, amém."
    },
    {
      "day": 3,
      "segment": "evening",
      "reference": {
        "book": "Acts",
        "chapter": 16,
        "verse": "25",
        "full_reference": "Acts 16:25"
      },
      "modernVersion": "João Ferreira de Almeida",
      "modernText": "Pela meia-noite Paulo e Silas oravam e cantavam hinos a Deus, enquanto os presos os escutavam.",
      "contextNote": "Paulo e Silas tinham sido despidos, açoitados com varas e jogados na cela mais interna — Lucas faz questão de citar as três coisas. O verbo grego do canto deles, hymneo, é o mesmo usado do hino que Jesus cantou com os discípulos antes do Getsêmani. E o detalhe de que os presos os escutavam é de Lucas, colocado ali de propósito.",
      "meditation": "Dois homens, açoitados e trancados na cela mais interna, com os pés presos no tronco de madeira. É meia-noite. E Lucas registra o que eles fizeram com aquela hora exata: oraram e depois cantaram.\n\nRepare na última frase, que é a que costuma passar batido na leitura. E os outros presos estavam ali, escutando. Ninguém estava cantando para uma plateia — não havia plateia nenhuma, só gente no mesmo escuro, deitada e acordada. Mas a fé numa noite ruim nunca é totalmente particular. A mulher do quarto ao lado escuta. A filha no corredor escuta. A sua meia-noite faz mais barulho do que você imagina, e nem sempre para o mal.",
      "actionStep": "Se você estiver acordada hoje quando queria estar dormindo, pare de brigar com isso por dez minutos. Use esse tempo para orar — em voz alta, se der.",
      "prayer": "Amado Pai celestial, eu preferia não estar acordada agora, e preferia que isto já tivesse passado. Obrigada porque tu não estás ausente do meio da noite. Se eu não conseguir dormir, que eu ore. E se alguém perto de mim estiver escutando, que o que essa pessoa ouvir de mim seja confiança, e não desespero. Em nome de Jesus, amém."
    }
  ]
};
