// Daily-verse "listen / 导读" narration audio. Google-TTS reads of the
// four prayer-flow steps (scripture → reflection → simple-step → prayer)
// for each of the 120 verses. Served PUBLICLY from the same R2 bucket as
// the Bible audio (audio.everlandapps.com → herbible-audio-7languages),
// under `dailyverse_4steps_audio/`. No gating — it's free narration of
// already-free content, same posture as the bg music + Bible audio.
//
// **en / es / pt today.** The listen button is hidden for other UI languages
// until their audio is uploaded (see AVAILABLE_DAILY_VERSE_AUDIO_LANGS below,
// and the per-verse MISSING holes for partial uploads).
//
// Filenames carry an unpredictable middle slug, so the app can't build
// them directly — it reads a bundled manifest (constants/
// dailyVerseAudioManifest.ts) that maps each verseId to its four exact
// filenames. That manifest is generated by
// scripts/gen_dailyverse_audio_manifest.mjs from the local audio folder.

// Bucket prefix (without the language segment). Files live under
// <BASE>/<lang>/<filename>, e.g.
//   …/dailyverse_4steps_audio_7languages/en/e_001_evening_john-14-1_01_scripture.mp3
export const DAILY_VERSE_AUDIO_BASE =
  'https://audio.everlandapps.com/dailyverse_4steps_audio_7languages';

// Default language-folder segment. English is the baseline that always
// exists; the URL builders below accept an explicit `lang` so the path is
// already multilingual-ready — only the SET below gates which languages we
// actually point at.
export const DAILY_VERSE_AUDIO_LANG = 'en';

// Languages that have narration mp3s + timestamp .json uploaded to the CDN
// under <BASE>/<lang>/…. es/pt mirror the ENGLISH filenames 1:1 (same slugs),
// so the single bundled manifest serves all three — only this set (plus the
// per-verse holes below) gates what we offer. When another language lands on
// Cloudflare, add its code here after a full-coverage probe.
export const AVAILABLE_DAILY_VERSE_AUDIO_LANGS = new Set<string>(['en', 'es', 'pt']);

// Per-language upload HOLES at VERSE granularity — any missing step mp3 hides
// that verse's Listen for that language (a shown button that 404s mid-flow is
// worse than no button). ADD a verseId here if a language's upload is partial.
//
// 2026-07-09: a FULL .mp3 HEAD sweep (check_daily_verse_audio.sh) found es
// m_026–m_050 return 404 for ALL FOUR steps — the timing .json siblings were
// uploaded but the audio .mp3s were NOT (an earlier spot-check only hit the
// .json and wrongly cleared these). es e_025 + pt are complete. DELETE the es
// entries once the m_026–m_050 mp3s are actually uploaded (re-run the sweep to
// confirm) — nothing else needs to change.
const MISSING_DAILY_VERSE_AUDIO: Record<string, ReadonlySet<string>> = {
  es: new Set([
    'm_026', 'm_027', 'm_028', 'm_029', 'm_030', 'm_031', 'm_032', 'm_033',
    'm_034', 'm_035', 'm_036', 'm_037', 'm_038', 'm_039', 'm_040', 'm_041',
    'm_042', 'm_043', 'm_044', 'm_045', 'm_046', 'm_047', 'm_048', 'm_049',
    'm_050',
  ]),
};

// Resolve a UI language to the narration language we should fetch: the UI
// language itself when its audio exists, otherwise null (caller skips the
// listen control / prefetch — we never silently serve English audio to a
// non-English reader, and we never waste bandwidth pre-warming clips that
// won't be offered).
export function resolveDailyVerseAudioLang(uiLang: string): string | null {
  return AVAILABLE_DAILY_VERSE_AUDIO_LANGS.has(uiLang) ? uiLang : null;
}

// Verse-level availability: the language is recorded AND this specific verse
// has no upload hole. Callers gate the Listen button + prefetch on this.
export function isDailyVerseAudioAvailable(lang: string, verseId: string): boolean {
  if (!AVAILABLE_DAILY_VERSE_AUDIO_LANGS.has(lang)) return false;
  return !MISSING_DAILY_VERSE_AUDIO[lang]?.has(verseId);
}

// Step keys in PRAYER-FLOW PAGE ORDER (page 0..3). Mirrors PrayerFlow's
// SECTIONS = ['verse','meditation','action','prayer'] one-to-one:
//   page 0 verse      → scripture
//   page 1 meditation → reflection
//   page 2 action     → simple-step
//   page 3 prayer     → prayer
export const DAILY_VERSE_AUDIO_STEPS = ['scripture', 'reflection', 'simple-step', 'prayer'] as const;
export type DailyVerseAudioStep = typeof DAILY_VERSE_AUDIO_STEPS[number];

export interface DailyVerseAudioManifest {
  version: number;
  base_url: string;
  step_order: string[];
  // verseId (m_001 / e_001) → { scripture, reflection, simple-step, prayer }
  verses: Record<string, Partial<Record<DailyVerseAudioStep, string>>>;
}

export function dailyVerseAudioUrl(filename: string, lang: string = DAILY_VERSE_AUDIO_LANG): string {
  return `${DAILY_VERSE_AUDIO_BASE}/${lang}/${filename}`;
}

// Holiday-verse narration. Separate bucket prefix from the regular daily-verse
// audio because the holiday verseIds (m_001…e_010 = holiday day index) COLLIDE
// with the regular ones — same id, different audio — so they need a distinct
// folder + manifest + on-device cache. Now EN/ES/PT, mirroring the regular set:
// es/pt reuse the ENGLISH filenames 1:1, so the single bundled manifest serves
// all three. NOTE the language folder is UPPERCASE here (EN/ES/PT) — that's how
// the files are actually laid out under this prefix, unlike the lowercase
// regular-audio folders.
//   <BASE>/<LANG>/<filename>, e.g.
//   …/dailyverse_4steps_audio_7languages_holidays/EN/e_001_new-years-day_evening_01_scripture.mp3
export const HOLIDAY_VERSE_AUDIO_BASE =
  'https://audio.everlandapps.com/dailyverse_4steps_audio_7languages_holidays';

// Holiday audio ships in the same three languages as the regular narration.
export function isHolidayVerseAudioAvailable(lang: string): boolean {
  return AVAILABLE_DAILY_VERSE_AUDIO_LANGS.has(lang);
}

export function holidayVerseAudioUrl(filename: string, lang: string = DAILY_VERSE_AUDIO_LANG): string {
  // Language folder is UPPERCASE on the CDN (EN/ES/PT).
  return `${HOLIDAY_VERSE_AUDIO_BASE}/${lang.toUpperCase()}/${filename}`;
}
