// AUTO-GENERATED 89-day Gospels & Psalms reading plan (see GOSPELS_PSALMS_PLAN.md).
// Morning = one Gospel chapter + a Psalm; Evening = a Psalm. Verse text is
// fetched at read time from the corpus CDN (services/bibleService.fetchChapter);
// this table only carries the references. Psalm specs may be a whole chapter
// or a verse range (long psalms like 119 are split across days).

export interface PsalmRef { chapter: number; vStart?: number; vEnd?: number; }
export interface GospelRef { bookSlug: string; bookName: string; chapter: number; }
export interface GPlanDay {
  day: number;
  gospel: GospelRef;        // morning core reading
  morningPsalm: PsalmRef;   // morning 'response' psalm
  eveningPsalm: PsalmRef;   // evening meditation psalm
  note?: string;            // optional cross-reference hint (Jesus quoting the psalm)
}

export const GOSPELS_PSALMS_PLAN: GPlanDay[] = [
  { day: 1, gospel: { bookSlug: 'matthew', bookName: 'Matthew', chapter: 1 }, morningPsalm: { chapter: 89 }, eveningPsalm: { chapter: 75 } },
  { day: 2, gospel: { bookSlug: 'matthew', bookName: 'Matthew', chapter: 2 }, morningPsalm: { chapter: 72 }, eveningPsalm: { chapter: 76 } },
  { day: 3, gospel: { bookSlug: 'matthew', bookName: 'Matthew', chapter: 3 }, morningPsalm: { chapter: 2 }, eveningPsalm: { chapter: 77 }, note: 'Ps 2:7 "Thou art my Son"' },
  { day: 4, gospel: { bookSlug: 'matthew', bookName: 'Matthew', chapter: 4 }, morningPsalm: { chapter: 91 }, eveningPsalm: { chapter: 79 }, note: 'Satan quotes Ps 91 (Mt 4:6)' },
  { day: 5, gospel: { bookSlug: 'matthew', bookName: 'Matthew', chapter: 5 }, morningPsalm: { chapter: 37 }, eveningPsalm: { chapter: 80 }, note: 'Ps 37:11 = "the meek shall inherit"' },
  { day: 6, gospel: { bookSlug: 'matthew', bookName: 'Matthew', chapter: 6 }, morningPsalm: { chapter: 103 }, eveningPsalm: { chapter: 81 } },
  { day: 7, gospel: { bookSlug: 'matthew', bookName: 'Matthew', chapter: 7 }, morningPsalm: { chapter: 1 }, eveningPsalm: { chapter: 82 } },
  { day: 8, gospel: { bookSlug: 'matthew', bookName: 'Matthew', chapter: 8 }, morningPsalm: { chapter: 107 }, eveningPsalm: { chapter: 83 } },
  { day: 9, gospel: { bookSlug: 'matthew', bookName: 'Matthew', chapter: 9 }, morningPsalm: { chapter: 3 }, eveningPsalm: { chapter: 84 } },
  { day: 10, gospel: { bookSlug: 'matthew', bookName: 'Matthew', chapter: 10 }, morningPsalm: { chapter: 4 }, eveningPsalm: { chapter: 85 } },
  { day: 11, gospel: { bookSlug: 'matthew', bookName: 'Matthew', chapter: 11 }, morningPsalm: { chapter: 5 }, eveningPsalm: { chapter: 86 } },
  { day: 12, gospel: { bookSlug: 'matthew', bookName: 'Matthew', chapter: 12 }, morningPsalm: { chapter: 6 }, eveningPsalm: { chapter: 87 } },
  { day: 13, gospel: { bookSlug: 'matthew', bookName: 'Matthew', chapter: 13 }, morningPsalm: { chapter: 49 }, eveningPsalm: { chapter: 90 } },
  { day: 14, gospel: { bookSlug: 'matthew', bookName: 'Matthew', chapter: 14 }, morningPsalm: { chapter: 7 }, eveningPsalm: { chapter: 92 } },
  { day: 15, gospel: { bookSlug: 'matthew', bookName: 'Matthew', chapter: 15 }, morningPsalm: { chapter: 8 }, eveningPsalm: { chapter: 93 } },
  { day: 16, gospel: { bookSlug: 'matthew', bookName: 'Matthew', chapter: 16 }, morningPsalm: { chapter: 9 }, eveningPsalm: { chapter: 94 } },
  { day: 17, gospel: { bookSlug: 'matthew', bookName: 'Matthew', chapter: 17 }, morningPsalm: { chapter: 10 }, eveningPsalm: { chapter: 95 } },
  { day: 18, gospel: { bookSlug: 'matthew', bookName: 'Matthew', chapter: 18 }, morningPsalm: { chapter: 11 }, eveningPsalm: { chapter: 96 } },
  { day: 19, gospel: { bookSlug: 'matthew', bookName: 'Matthew', chapter: 19 }, morningPsalm: { chapter: 12 }, eveningPsalm: { chapter: 97 } },
  { day: 20, gospel: { bookSlug: 'matthew', bookName: 'Matthew', chapter: 20 }, morningPsalm: { chapter: 13 }, eveningPsalm: { chapter: 99 } },
  { day: 21, gospel: { bookSlug: 'matthew', bookName: 'Matthew', chapter: 21 }, morningPsalm: { chapter: 118 }, eveningPsalm: { chapter: 101 }, note: 'Mt 21 quotes Ps 118:22' },
  { day: 22, gospel: { bookSlug: 'matthew', bookName: 'Matthew', chapter: 22 }, morningPsalm: { chapter: 110 }, eveningPsalm: { chapter: 102 }, note: 'Mt 22:44 quotes Ps 110:1' },
  { day: 23, gospel: { bookSlug: 'matthew', bookName: 'Matthew', chapter: 23 }, morningPsalm: { chapter: 14 }, eveningPsalm: { chapter: 104 } },
  { day: 24, gospel: { bookSlug: 'matthew', bookName: 'Matthew', chapter: 24 }, morningPsalm: { chapter: 15 }, eveningPsalm: { chapter: 105, vStart: 1, vEnd: 22 } },
  { day: 25, gospel: { bookSlug: 'matthew', bookName: 'Matthew', chapter: 25 }, morningPsalm: { chapter: 17 }, eveningPsalm: { chapter: 105, vStart: 23, vEnd: 45 } },
  { day: 26, gospel: { bookSlug: 'matthew', bookName: 'Matthew', chapter: 26 }, morningPsalm: { chapter: 116 }, eveningPsalm: { chapter: 22 } },
  { day: 27, gospel: { bookSlug: 'matthew', bookName: 'Matthew', chapter: 27 }, morningPsalm: { chapter: 22 }, eveningPsalm: { chapter: 31 }, note: 'Mt 27:46 quotes Ps 22:1' },
  { day: 28, gospel: { bookSlug: 'matthew', bookName: 'Matthew', chapter: 28 }, morningPsalm: { chapter: 16 }, eveningPsalm: { chapter: 118 } },
  { day: 29, gospel: { bookSlug: 'mark', bookName: 'Mark', chapter: 1 }, morningPsalm: { chapter: 18, vStart: 1, vEnd: 25 }, eveningPsalm: { chapter: 106, vStart: 1, vEnd: 23 } },
  { day: 30, gospel: { bookSlug: 'mark', bookName: 'Mark', chapter: 2 }, morningPsalm: { chapter: 18, vStart: 26, vEnd: 50 }, eveningPsalm: { chapter: 106, vStart: 24, vEnd: 48 } },
  { day: 31, gospel: { bookSlug: 'mark', bookName: 'Mark', chapter: 3 }, morningPsalm: { chapter: 19 }, eveningPsalm: { chapter: 108 } },
  { day: 32, gospel: { bookSlug: 'mark', bookName: 'Mark', chapter: 4 }, morningPsalm: { chapter: 65 }, eveningPsalm: { chapter: 109 } },
  { day: 33, gospel: { bookSlug: 'mark', bookName: 'Mark', chapter: 5 }, morningPsalm: { chapter: 20 }, eveningPsalm: { chapter: 111 } },
  { day: 34, gospel: { bookSlug: 'mark', bookName: 'Mark', chapter: 6 }, morningPsalm: { chapter: 21 }, eveningPsalm: { chapter: 112 } },
  { day: 35, gospel: { bookSlug: 'mark', bookName: 'Mark', chapter: 7 }, morningPsalm: { chapter: 24 }, eveningPsalm: { chapter: 114 } },
  { day: 36, gospel: { bookSlug: 'mark', bookName: 'Mark', chapter: 8 }, morningPsalm: { chapter: 25 }, eveningPsalm: { chapter: 115 } },
  { day: 37, gospel: { bookSlug: 'mark', bookName: 'Mark', chapter: 9 }, morningPsalm: { chapter: 26 }, eveningPsalm: { chapter: 117 } },
  { day: 38, gospel: { bookSlug: 'mark', bookName: 'Mark', chapter: 10 }, morningPsalm: { chapter: 27 }, eveningPsalm: { chapter: 119, vStart: 1, vEnd: 48 } },
  { day: 39, gospel: { bookSlug: 'mark', bookName: 'Mark', chapter: 11 }, morningPsalm: { chapter: 28 }, eveningPsalm: { chapter: 119, vStart: 49, vEnd: 96 } },
  { day: 40, gospel: { bookSlug: 'mark', bookName: 'Mark', chapter: 12 }, morningPsalm: { chapter: 29 }, eveningPsalm: { chapter: 119, vStart: 97, vEnd: 144 } },
  { day: 41, gospel: { bookSlug: 'mark', bookName: 'Mark', chapter: 13 }, morningPsalm: { chapter: 36 }, eveningPsalm: { chapter: 119, vStart: 145, vEnd: 176 } },
  { day: 42, gospel: { bookSlug: 'mark', bookName: 'Mark', chapter: 14 }, morningPsalm: { chapter: 42 }, eveningPsalm: { chapter: 116 } },
  { day: 43, gospel: { bookSlug: 'mark', bookName: 'Mark', chapter: 15 }, morningPsalm: { chapter: 88 }, eveningPsalm: { chapter: 22 } },
  { day: 44, gospel: { bookSlug: 'mark', bookName: 'Mark', chapter: 16 }, morningPsalm: { chapter: 30 }, eveningPsalm: { chapter: 16 } },
  { day: 45, gospel: { bookSlug: 'luke', bookName: 'Luke', chapter: 1 }, morningPsalm: { chapter: 113 }, eveningPsalm: { chapter: 120 } },
  { day: 46, gospel: { bookSlug: 'luke', bookName: 'Luke', chapter: 2 }, morningPsalm: { chapter: 98 }, eveningPsalm: { chapter: 121 } },
  { day: 47, gospel: { bookSlug: 'luke', bookName: 'Luke', chapter: 3 }, morningPsalm: { chapter: 38 }, eveningPsalm: { chapter: 122 } },
  { day: 48, gospel: { bookSlug: 'luke', bookName: 'Luke', chapter: 4 }, morningPsalm: { chapter: 146 }, eveningPsalm: { chapter: 123 } },
  { day: 49, gospel: { bookSlug: 'luke', bookName: 'Luke', chapter: 5 }, morningPsalm: { chapter: 39 }, eveningPsalm: { chapter: 124 } },
  { day: 50, gospel: { bookSlug: 'luke', bookName: 'Luke', chapter: 6 }, morningPsalm: { chapter: 40 }, eveningPsalm: { chapter: 125 } },
  { day: 51, gospel: { bookSlug: 'luke', bookName: 'Luke', chapter: 7 }, morningPsalm: { chapter: 43 }, eveningPsalm: { chapter: 127 } },
  { day: 52, gospel: { bookSlug: 'luke', bookName: 'Luke', chapter: 8 }, morningPsalm: { chapter: 44 }, eveningPsalm: { chapter: 128 } },
  { day: 53, gospel: { bookSlug: 'luke', bookName: 'Luke', chapter: 9 }, morningPsalm: { chapter: 45 }, eveningPsalm: { chapter: 129 } },
  { day: 54, gospel: { bookSlug: 'luke', bookName: 'Luke', chapter: 10 }, morningPsalm: { chapter: 46 }, eveningPsalm: { chapter: 130 } },
  { day: 55, gospel: { bookSlug: 'luke', bookName: 'Luke', chapter: 11 }, morningPsalm: { chapter: 47 }, eveningPsalm: { chapter: 131 } },
  { day: 56, gospel: { bookSlug: 'luke', bookName: 'Luke', chapter: 12 }, morningPsalm: { chapter: 48 }, eveningPsalm: { chapter: 132 } },
  { day: 57, gospel: { bookSlug: 'luke', bookName: 'Luke', chapter: 13 }, morningPsalm: { chapter: 50 }, eveningPsalm: { chapter: 133 } },
  { day: 58, gospel: { bookSlug: 'luke', bookName: 'Luke', chapter: 14 }, morningPsalm: { chapter: 52 }, eveningPsalm: { chapter: 134 } },
  { day: 59, gospel: { bookSlug: 'luke', bookName: 'Luke', chapter: 15 }, morningPsalm: { chapter: 32 }, eveningPsalm: { chapter: 135 } },
  { day: 60, gospel: { bookSlug: 'luke', bookName: 'Luke', chapter: 16 }, morningPsalm: { chapter: 53 }, eveningPsalm: { chapter: 136 } },
  { day: 61, gospel: { bookSlug: 'luke', bookName: 'Luke', chapter: 17 }, morningPsalm: { chapter: 54 }, eveningPsalm: { chapter: 137 } },
  { day: 62, gospel: { bookSlug: 'luke', bookName: 'Luke', chapter: 18 }, morningPsalm: { chapter: 51 }, eveningPsalm: { chapter: 138 } },
  { day: 63, gospel: { bookSlug: 'luke', bookName: 'Luke', chapter: 19 }, morningPsalm: { chapter: 55 }, eveningPsalm: { chapter: 139 } },
  { day: 64, gospel: { bookSlug: 'luke', bookName: 'Luke', chapter: 20 }, morningPsalm: { chapter: 56 }, eveningPsalm: { chapter: 140 } },
  { day: 65, gospel: { bookSlug: 'luke', bookName: 'Luke', chapter: 21 }, morningPsalm: { chapter: 57 }, eveningPsalm: { chapter: 141 } },
  { day: 66, gospel: { bookSlug: 'luke', bookName: 'Luke', chapter: 22 }, morningPsalm: { chapter: 58 }, eveningPsalm: { chapter: 42 } },
  { day: 67, gospel: { bookSlug: 'luke', bookName: 'Luke', chapter: 23 }, morningPsalm: { chapter: 31 }, eveningPsalm: { chapter: 88 }, note: 'Lk 23:46 quotes Ps 31:5' },
  { day: 68, gospel: { bookSlug: 'luke', bookName: 'Luke', chapter: 24 }, morningPsalm: { chapter: 59 }, eveningPsalm: { chapter: 30 } },
  { day: 69, gospel: { bookSlug: 'john', bookName: 'John', chapter: 1 }, morningPsalm: { chapter: 33 }, eveningPsalm: { chapter: 142 } },
  { day: 70, gospel: { bookSlug: 'john', bookName: 'John', chapter: 2 }, morningPsalm: { chapter: 69 }, eveningPsalm: { chapter: 143 }, note: 'Jn 2:17 quotes Ps 69:9' },
  { day: 71, gospel: { bookSlug: 'john', bookName: 'John', chapter: 3 }, morningPsalm: { chapter: 60 }, eveningPsalm: { chapter: 144 } },
  { day: 72, gospel: { bookSlug: 'john', bookName: 'John', chapter: 4 }, morningPsalm: { chapter: 61 }, eveningPsalm: { chapter: 145 } },
  { day: 73, gospel: { bookSlug: 'john', bookName: 'John', chapter: 5 }, morningPsalm: { chapter: 62 }, eveningPsalm: { chapter: 147 } },
  { day: 74, gospel: { bookSlug: 'john', bookName: 'John', chapter: 6 }, morningPsalm: { chapter: 78 }, eveningPsalm: { chapter: 148 }, note: 'Jn 6:31 quotes Ps 78:24' },
  { day: 75, gospel: { bookSlug: 'john', bookName: 'John', chapter: 7 }, morningPsalm: { chapter: 63 }, eveningPsalm: { chapter: 149 } },
  { day: 76, gospel: { bookSlug: 'john', bookName: 'John', chapter: 8 }, morningPsalm: { chapter: 64 }, eveningPsalm: { chapter: 2 } },
  { day: 77, gospel: { bookSlug: 'john', bookName: 'John', chapter: 9 }, morningPsalm: { chapter: 66 }, eveningPsalm: { chapter: 3 } },
  { day: 78, gospel: { bookSlug: 'john', bookName: 'John', chapter: 10 }, morningPsalm: { chapter: 23 }, eveningPsalm: { chapter: 4 }, note: 'Ps 23 = the Good Shepherd (Jn 10)' },
  { day: 79, gospel: { bookSlug: 'john', bookName: 'John', chapter: 11 }, morningPsalm: { chapter: 67 }, eveningPsalm: { chapter: 5 } },
  { day: 80, gospel: { bookSlug: 'john', bookName: 'John', chapter: 12 }, morningPsalm: { chapter: 68 }, eveningPsalm: { chapter: 6 } },
  { day: 81, gospel: { bookSlug: 'john', bookName: 'John', chapter: 13 }, morningPsalm: { chapter: 41 }, eveningPsalm: { chapter: 7 }, note: 'Jn 13:18 quotes Ps 41:9' },
  { day: 82, gospel: { bookSlug: 'john', bookName: 'John', chapter: 14 }, morningPsalm: { chapter: 70 }, eveningPsalm: { chapter: 8 } },
  { day: 83, gospel: { bookSlug: 'john', bookName: 'John', chapter: 15 }, morningPsalm: { chapter: 35 }, eveningPsalm: { chapter: 9 } },
  { day: 84, gospel: { bookSlug: 'john', bookName: 'John', chapter: 16 }, morningPsalm: { chapter: 71 }, eveningPsalm: { chapter: 10 } },
  { day: 85, gospel: { bookSlug: 'john', bookName: 'John', chapter: 17 }, morningPsalm: { chapter: 73 }, eveningPsalm: { chapter: 11 } },
  { day: 86, gospel: { bookSlug: 'john', bookName: 'John', chapter: 18 }, morningPsalm: { chapter: 74 }, eveningPsalm: { chapter: 31 } },
  { day: 87, gospel: { bookSlug: 'john', bookName: 'John', chapter: 19 }, morningPsalm: { chapter: 34 }, eveningPsalm: { chapter: 22 }, note: 'Jn 19:36 quotes Ps 34:20' },
  { day: 88, gospel: { bookSlug: 'john', bookName: 'John', chapter: 20 }, morningPsalm: { chapter: 126 }, eveningPsalm: { chapter: 118 } },
  { day: 89, gospel: { bookSlug: 'john', bookName: 'John', chapter: 21 }, morningPsalm: { chapter: 100 }, eveningPsalm: { chapter: 150 } },
];

export const GOSPELS_PSALMS_TOTAL_DAYS = GOSPELS_PSALMS_PLAN.length; // 89