import type { LanguageCode } from '../state/TranslationsContext';

// Decorative, ANONYMOUS social-proof comments for the verse-card comment sheet.
// NOT real user data — purely encouraging reactions. The sheet shows a random
// 5–25 of these (for the active UI language) with random virtual names each open.

export const VERSE_COMMENTS: Record<LanguageCode, string[]> = {
  "en": ["Amen 🙏", "Amen!", "Praise God 🙌", "Thank you Jesus", "Thank you God 🙏", "So needed this today", "This blessed me", "Glory to God", "Hallelujah!", "God is good 🙌", "God is good all the time", "Praying 🙏", "Praying for you all", "Speak Lord", "Yes and amen", "Receiving this", "Blessed 🙏", "Such a blessing", "Thank you for this word", "Right on time", "I needed to hear this", "My heart needed this", "He is faithful", "He is so faithful", "Trusting Him today", "Holding onto this", "Saving this verse", "Sharing this 🙏", "Beautiful 🕊️", "So beautiful", "🙏❤️", "🙏🙏🙏", "🕊️", "❤️🙏", "This touched my heart", "Tears 🥹", "God knew I needed this", "On my knees this morning", "Starting my day with this", "Goodnight, resting in Him", "Peace be with you all", "Grace upon grace", "His mercy is new every morning", "Faith over fear", "Let go and let God", "He's working it out", "God's got you", "Stay strong sis 💪", "Keep the faith", "We're praying with you", "Standing in agreement 🙏", "So encouraging", "Needed this reminder", "Truth 🙌", "Powerful word", "Wow 🙏", "Believing God", "In Jesus' name 🙏", "To God be the glory", "Forever grateful", "Grateful heart", "My God is able", "Nothing is impossible with God", "He will make a way", "Sending love and prayers", "Stay blessed 🙏", "Have a blessed day", "Goodnight everyone 🙏", "Reading this with my coffee ☕🙏", "First thing every morning", "Love this community 🙏"],
  "zh-Hans": ["阿们 🙏", "阿们!", "感谢主 🙏", "感谢耶稣", "赞美主 🙌", "哈利路亚!", "荣耀归神", "神是信实的", "神真好", "今天太需要这句了", "正是我需要的", "这句话击中我心", "为大家祷告 🙏", "在为你们祷告", "求主帮助", "愿神与你同在", "蒙福了 🙏", "收下了,感谢", "保存这节经文了", "分享给更多人 🙏", "主的话语真奇妙", "刚好在这个时候", "我的心需要这句", "祂的慈爱每早晨都是新的", "凭信心不凭眼见", "交托给神", "今天单单信靠祂", "祂必开路", "神必看顾你", "姐妹加油 💪", "持守信心", "我们一起为你祷告", "同心合意 🙏", "太鼓励人了", "正需要这个提醒", "句句是真理 🙌", "有能力的话语", "哇 🙏", "深受触动", "眼泪都下来了 🥹", "神知道我需要这句", "清早跪下祷告", "用这句开启新的一天", "晚安,在主里安息", "愿平安与你们同在", "恩上加恩", "信心胜过恐惧", "交给神吧", "祂在为你成就", "靠主刚强", "为这里每个人祷告 🙏", "送上爱与祷告", "愿你常蒙福 🙏", "祝你有蒙福的一天", "大家晚安 🙏", "配着咖啡读经 ☕🙏", "每天第一件事", "爱这个群体 🙏", "主啊我相信", "奉耶稣的名 🙏", "愿一切荣耀归神", "永远感恩", "感恩的心", "我的神大有能力", "在神没有难成的事", "🙏❤️", "🙏🙏🙏", "🕊️", "❤️🙏"],
  "zh-Hant": ["阿們 🙏", "阿們!", "感謝主 🙏", "感謝耶穌", "讚美主 🙌", "哈利路亞!", "榮耀歸神", "神是信實的", "神真好", "今天太需要這句了", "正是我需要的", "這句話擊中我心", "為大家禱告 🙏", "在為你們禱告", "求主幫助", "願神與你同在", "蒙福了 🙏", "收下了,感謝", "保存這節經文了", "分享給更多人 🙏", "主的話語真奇妙", "剛好在這個時候", "我的心需要這句", "祂的慈愛每早晨都是新的", "憑信心不憑眼見", "交託給神", "今天單單信靠祂", "祂必開路", "神必看顧你", "姐妹加油 💪", "持守信心", "我們一起為你禱告", "同心合意 🙏", "太鼓勵人了", "正需要這個提醒", "句句是真理 🙌", "有能力的話語", "哇 🙏", "深受觸動", "眼淚都下來了 🥹", "神知道我需要這句", "清早跪下禱告", "用這句開啟新的一天", "晚安,在主裡安息", "願平安與你們同在", "恩上加恩", "信心勝過恐懼", "交給神吧", "祂在為你成就", "靠主剛強", "為這裡每個人禱告 🙏", "送上愛與禱告", "願你常蒙福 🙏", "祝你有蒙福的一天", "大家晚安 🙏", "配著咖啡讀經 ☕🙏", "每天第一件事", "愛這個群體 🙏", "主啊我相信", "奉耶穌的名 🙏", "願一切榮耀歸神", "永遠感恩", "感恩的心", "我的神大有能力", "在神沒有難成的事", "🙏❤️", "🙏🙏🙏", "🕊️", "❤️🙏"],
  "de": ["Amen 🙏", "Amen!", "Gott sei Dank 🙏", "Danke Jesus", "Gelobt sei der Herr 🙌", "Halleluja!", "Ehre sei Gott", "Gott ist treu", "Gott ist gut 🙌", "Das brauchte ich heute", "Genau zur rechten Zeit", "Das hat mein Herz berührt", "Ich bete für euch 🙏", "Bete für dich", "Rede, Herr", "Der Herr sei mit dir", "Gesegnet 🙏", "Ich nehme das an", "Diesen Vers speichere ich", "Das teile ich 🙏", "Sein Wort ist wunderbar", "Mein Herz brauchte das", "Seine Gnade ist jeden Morgen neu", "Glaube statt Furcht", "Ich vertraue Gott heute", "Er wird einen Weg bahnen", "Gott sorgt für dich", "Bleib stark, Schwester 💪", "Halte am Glauben fest", "Wir beten mit dir 🙏", "So ermutigend", "Diese Erinnerung brauchte ich", "Reine Wahrheit 🙌", "Kraftvolles Wort", "Wow 🙏", "Tief berührt", "Tränen 🥹", "Gott wusste, dass ich das brauche", "Am Morgen auf den Knien", "So beginne ich meinen Tag", "Gute Nacht, ich ruhe in ihm", "Friede sei mit euch", "Gnade über Gnade", "Lass los und vertrau Gott", "Er hat alles im Griff", "Im Namen Jesu 🙏", "Gott allein die Ehre", "Für immer dankbar", "Dankbares Herz", "Mein Gott ist mächtig", "Bei Gott ist nichts unmöglich", "Ich bete für alle hier 🙏", "Liebe und Gebete für euch", "Bleibt gesegnet 🙏", "Einen gesegneten Tag", "Gute Nacht zusammen 🙏", "Ich lese das bei meinem Kaffee ☕🙏", "Das Erste am Morgen", "🙏❤️", "🕊️", "❤️🙏"],
  "fr": ["Amen 🙏", "Amen !", "Merci Seigneur 🙏", "Merci Jésus", "Loué soit le Seigneur 🙌", "Alléluia !", "Gloire à Dieu", "Dieu est fidèle", "Dieu est bon 🙌", "J'avais besoin de ça aujourd'hui", "Juste au bon moment", "Ça a touché mon cœur", "Je prie pour vous 🙏", "Je prie pour toi", "Parle Seigneur", "Que le Seigneur soit avec toi", "Bénie 🙏", "Je reçois cette parole", "Je garde ce verset", "Je partage 🙏", "Sa Parole est merveilleuse", "Mon cœur en avait besoin", "Ses compassions se renouvellent chaque matin", "La foi plutôt que la peur", "Je fais confiance à Dieu aujourd'hui", "Il ouvrira un chemin", "Dieu veille sur toi", "Reste forte, ma sœur 💪", "Garde la foi", "Nous prions avec toi 🙏", "Tellement encourageant", "J'avais besoin de ce rappel", "Pure vérité 🙌", "Parole puissante", "Waouh 🙏", "Profondément touchée", "Les larmes 🥹", "Dieu savait que j'en avais besoin", "À genoux ce matin", "Je commence ma journée avec ça", "Bonne nuit, je me repose en lui", "Que la paix soit avec vous", "Grâce sur grâce", "Lâche prise et fais confiance à Dieu", "Il s'occupe de tout", "Au nom de Jésus 🙏", "À Dieu seul la gloire", "Reconnaissante pour toujours", "Un cœur reconnaissant", "Mon Dieu est puissant", "Rien n'est impossible à Dieu", "Je prie pour tout le monde ici 🙏", "Amour et prières pour vous", "Restez bénis 🙏", "Belle journée bénie", "Bonne nuit à tous 🙏", "Je lis ça avec mon café ☕🙏", "La première chose le matin", "🙏❤️", "🕊️", "❤️🙏"],
  "es": ["Amén 🙏", "¡Amén!", "Gracias Señor 🙏", "Gracias Jesús", "Alabado sea el Señor 🙌", "¡Aleluya!", "Gloria a Dios", "Dios es fiel", "Dios es bueno 🙌", "Necesitaba esto hoy", "Justo a tiempo", "Tocó mi corazón", "Orando por ustedes 🙏", "Oro por ti", "Habla Señor", "El Señor esté contigo", "Bendecida 🙏", "Recibo esta palabra", "Guardo este versículo", "Lo comparto 🙏", "Su Palabra es maravillosa", "Mi corazón lo necesitaba", "Sus misericordias son nuevas cada mañana", "Fe en vez de miedo", "Confío en Dios hoy", "Él abrirá camino", "Dios cuida de ti", "Mantente fuerte, hermana 💪", "Guarda la fe", "Oramos contigo 🙏", "Muy alentador", "Necesitaba este recordatorio", "Pura verdad 🙌", "Palabra poderosa", "Guau 🙏", "Profundamente conmovida", "Lágrimas 🥹", "Dios sabía que lo necesitaba", "De rodillas esta mañana", "Empiezo mi día con esto", "Buenas noches, descanso en Él", "La paz sea con ustedes", "Gracia sobre gracia", "Suelta y confía en Dios", "Él tiene todo bajo control", "En el nombre de Jesús 🙏", "A Dios sea la gloria", "Agradecida por siempre", "Corazón agradecido", "Mi Dios es poderoso", "Nada es imposible para Dios", "Oro por todos aquí 🙏", "Amor y oraciones para ustedes", "Sigan benditos 🙏", "Un día bendecido", "Buenas noches a todos 🙏", "Leo esto con mi café ☕🙏", "Lo primero en la mañana", "🙏❤️", "🕊️", "❤️🙏"],
  "pt": ["Amém 🙏", "Amém!", "Obrigada Senhor 🙏", "Obrigada Jesus", "Louvado seja o Senhor 🙌", "Aleluia!", "Glória a Deus", "Deus é fiel", "Deus é bom 🙌", "Eu precisava disso hoje", "Bem na hora certa", "Tocou meu coração", "Orando por vocês 🙏", "Oro por você", "Fala Senhor", "O Senhor esteja com você", "Abençoada 🙏", "Recebo essa palavra", "Vou guardar esse versículo", "Compartilhando 🙏", "A Palavra Dele é maravilhosa", "Meu coração precisava disso", "As misericórdias Dele se renovam a cada manhã", "Fé no lugar do medo", "Confio em Deus hoje", "Ele vai abrir um caminho", "Deus cuida de você", "Seja forte, irmã 💪", "Guarde a fé", "Estamos orando com você 🙏", "Muito encorajador", "Eu precisava desse lembrete", "Pura verdade 🙌", "Palavra poderosa", "Uau 🙏", "Profundamente tocada", "Lágrimas 🥹", "Deus sabia que eu precisava", "De joelhos esta manhã", "Começo meu dia com isso", "Boa noite, descansando Nele", "A paz esteja convosco", "Graça sobre graça", "Entregue e confie em Deus", "Ele está no controle", "Em nome de Jesus 🙏", "A Deus seja a glória", "Grata para sempre", "Coração grato", "Meu Deus é poderoso", "Para Deus nada é impossível", "Oro por todos aqui 🙏", "Amor e orações para vocês", "Permaneçam abençoados 🙏", "Um dia abençoado", "Boa noite a todos 🙏", "Leio isso com meu café ☕🙏", "A primeira coisa de manhã", "🙏❤️", "🕊️", "❤️🙏"],
};

// Virtual commenter names. Names don't translate, so one shared pool reads
// naturally across a multilingual feed.
// Virtual commenter names — a deliberately MIXED pool so the feed feels global:
// some single first names, many first+last, a few with middle names, and a
// spread of cultures (English, Italian, Portuguese/Brazilian, Spanish, French,
// German, East-Asian, African). The sheet shuffles + samples these each open.
export const COMMENT_NAMES: string[] = [
  // First-name only (kept for natural variety)
  "Grace", "Hope", "Joy", "Naomi", "Esther", "Ruth", "Faith", "Abigail",
  // English first + last (+ a few middle names)
  "Hannah Brooks", "Sarah Mitchell", "Olivia Hayes", "Emma Coleman", "Charlotte Reeves",
  "Bethany Cole", "Naomi Carter", "Abigail Reed", "Ruth Whitfield", "Hope Sullivan",
  "Lydia Grace Turner", "Mary Ellen Foster", "Hannah Joy Parker", "Sarah Anne Bennett",
  // Italian
  "Giulia Romano", "Francesca Bianchi", "Chiara Esposito", "Alessia Ferrari",
  "Martina Conti", "Sofia Greco", "Valentina Ricci", "Giorgia De Luca", "Elena Marino",
  // Portuguese / Brazilian
  "Mariana Oliveira", "Beatriz Santos", "Ana Carolina Lima", "Camila Ribeiro",
  "Maria Clara Souza", "Letícia Almeida", "Gabriela da Costa", "Inês Fernandes",
  "Joana Pereira", "Mariana de Sousa", "Rafaela Gomes",
  // Spanish
  "Lucía Fernández", "Valentina García", "Sofía Martínez", "Isabela Torres",
  "Camila Rodríguez", "María José Herrera", "Daniela Ramírez",
  // French
  "Marie Laurent", "Camille Moreau", "Léa Dubois", "Chloé Bernard", "Manon Petit",
  // German
  "Lena Schmidt", "Greta Müller", "Hannah Wagner", "Sophie Becker",
  // East-Asian
  "Mei Lin", "Hui Chen", "Grace Wong", "Sarah Tan", "Hannah Kim", "Joy Park",
  // African
  "Amara Okafor", "Naomi Mwangi", "Grace Adeyemi", "Esther Abara",
];
