const { withAppDelegate } = require('@expo/config-plugins');

// Meta Audience Network — FBAdSettings.setAdvertiserTrackingEnabled(<ATT>) on iOS.
//
// WHY
// ───
// Meta requires this flag on iOS 14+, set BEFORE the Google Mobile Ads SDK
// initialises, whether or not you use mediation. It tells Meta whether it may
// use the data for personalised ads. Without it Meta still serves — just limited
// / non-personalised, at a materially lower eCPM. So skipping it is not a crash,
// it is quiet revenue loss, which is exactly the kind of thing nobody notices.
//
// WHY IT LOOKS LIKE THIS
// ──────────────────────
// The obvious implementation — `import FBAudienceNetwork` and call the class
// directly — creates a COMPILE-TIME dependency on a pod that is only present
// when `meta` is enabled in withAdMobMediation. Ship that while Meta is off and
// the entire iOS build fails on a missing module.
//
// So the call goes through the Objective-C runtime instead: look the class up by
// name, look the selector up by name, bail out if either is absent. When the
// Meta pod isn't linked this compiles fine and does nothing at runtime. The only
// imports are system frameworks (ObjectiveC, AppTrackingTransparency), which are
// always available.
//
// `unsafeBitCast` to a @convention(c) function pointer rather than `perform(_:)`
// is deliberate: the selector takes a BOOL primitive, and `perform` passes an
// object pointer, which would push garbage into that argument.
//
// TIMING
// ──────
// It runs twice on purpose. At didFinishLaunching the ATT status is almost
// always `.notDetermined` on a first run — the app hasn't asked yet (the prompt
// is fired from JS at app root). Re-applying on didBecomeActive picks up the
// user's answer as soon as the system alert is dismissed, which lands before the
// ad stack has done much. Later launches get the right value immediately.
//
// ⚠️ NOT BUILD-TESTED. This was written without a macOS toolchain to compile it.
// The runtime-lookup design means a mistake here degrades to "Meta gets no flag"
// rather than "iOS build is broken", and the mod no-ops instead of throwing if
// it can't find its anchor — but the first iOS build after this lands should be
// checked, not assumed.

const HELPER = `
// ─── Meta Audience Network advertiser tracking (generated by
//     plugins/withMetaAdvertiserTracking.js — do not edit here) ───────────────
@objc final class HerBibleMetaAdvertiserTracking: NSObject {
  @objc static func apply() {
    var enabled = true
    if #available(iOS 14, *) {
      enabled = ATTrackingManager.trackingAuthorizationStatus == .authorized
    }
    // Runtime lookup: no compile-time dependency on the Meta pod.
    guard let cls: AnyClass = NSClassFromString("FBAdSettings") else { return }
    let sel = NSSelectorFromString("setAdvertiserTrackingEnabled:")
    guard let method = class_getClassMethod(cls, sel) else { return }
    typealias Setter = @convention(c) (AnyObject, Selector, Bool) -> Void
    let fn = unsafeBitCast(method_getImplementation(method), to: Setter.self)
    fn(cls, sel, enabled)
  }

  @objc static func observe() {
    apply()
    NotificationCenter.default.addObserver(
      forName: UIApplication.didBecomeActiveNotification,
      object: nil,
      queue: .main
    ) { _ in apply() }
  }
}
`;

const IMPORTS = ['import ObjectiveC', 'import AppTrackingTransparency'];
const CALL = '    HerBibleMetaAdvertiserTracking.observe()';

module.exports = function withMetaAdvertiserTracking(config) {
  return withAppDelegate(config, (cfg) => {
    const { modResults } = cfg;

    // Objective-C AppDelegates are pre-SDK-53 and this project is Swift. Rather
    // than emit code for a shape we can't see, leave it alone and say so.
    if (modResults.language !== 'swift') {
      console.warn(
        '[withMetaAdvertiserTracking] AppDelegate is not Swift — skipped. ' +
        'Meta will serve non-personalised ads on iOS.',
      );
      return cfg;
    }

    let contents = modResults.contents;

    // Idempotent: prebuild runs repeatedly, and a second copy of the helper
    // would be a duplicate-symbol error.
    if (contents.includes('HerBibleMetaAdvertiserTracking')) return cfg;

    for (const imp of IMPORTS) {
      if (!contents.includes(imp)) {
        contents = contents.replace(/^(import .+)$/m, `$1\n${imp}`);
      }
    }

    contents += `\n${HELPER}`;

    // Anchor on the didFinishLaunchingWithOptions body. If Expo changes the
    // template signature this misses — which is why it warns loudly instead of
    // throwing: a missing Meta flag must never block a release build.
    const anchor = /(func application\([\s\S]*?didFinishLaunchingWithOptions[\s\S]*?\)\s*->\s*Bool\s*\{)/;
    if (!anchor.test(contents)) {
      console.warn(
        '[withMetaAdvertiserTracking] could not find didFinishLaunchingWithOptions ' +
        'in AppDelegate.swift — the advertiser-tracking flag was NOT wired. ' +
        'Meta will serve non-personalised ads on iOS.',
      );
      return cfg;
    }
    contents = contents.replace(anchor, `$1\n${CALL}`);

    modResults.contents = contents;
    return cfg;
  });
};
