// Rich "big-picture" morning/evening prayer reminders via Notifee.
//
// WHY Notifee (not expo-notifications): expo-notifications on Android supports
// text only — no embedded big image. Notifee renders an AndroidStyle.BIGPICTURE
// notification (a prayer photo + title + expanded copy + a "PRAY" action button),
// matching the large-notification look the user wants.
//
// COEXISTENCE: Notifee owns ONLY the morning + night daily reminders (and the
// background re-engagement one-off). Everything else (plan slot, always-on
// extras, win-back, complete-streak, the enable-confirmation) stays on
// expo-notifications. To guarantee morning/evening never DOUBLE-fire, the expo
// scheduler always cancels its own morning/night ids and no longer schedules
// them (see NotificationsContext.syncScheduledNotifications) — Notifee is the
// sole writer for those two slots, using its OWN id namespace below.
//
// PERMISSION: Notifee never prompts here — all permission prompting stays on the
// existing expo paths. On Android 13+/iOS the OS grant is shared, so Notifee
// simply reads it (via expo's getPermissionsAsync) and schedules when granted.

import { Image, Platform } from 'react-native';
import notifee, {
  AndroidImportance,
  AndroidStyle,
  AndroidVisibility,
  TriggerType,
  RepeatFrequency,
  type Notification,
  type TimestampTrigger,
} from '@notifee/react-native';
import { lookupString } from '../i18n/lookup';
import type { UILanguageCode } from './UILanguageContext';
import { pickDailyVariant, nextOccurrence } from './reminderContent';

export type RichSlot = 'morning' | 'night';

// Notifee's OWN channel + ids — deliberately DISTINCT from the expo channel
// (`her-bible.daily`) and expo ids so the two libraries' registries never race
// or collide on a shared id.
export const NOTIFEE_CHANNEL = 'her-bible.daily.rich';
const NOTIFEE_IDS: Record<RichSlot, string> = {
  morning: 'her-bible.notifee.morning',
  night:   'her-bible.notifee.night',
};
const BG_NUDGE_IDS: Record<RichSlot, string> = {
  morning: 'her-bible.notifee.bgnudge.morning',
  night:   'her-bible.notifee.bgnudge.night',
};
const IOS_CATEGORY = 'her-bible.prayer.rich';
const BRAND_ROSE = '#E8619A';

// Bundled photos — offline-safe (resolvable even when the app is killed and a
// scheduled trigger fires with no network), unlike a CDN URL. Reuses the
// already-bundled Follow-Him day/night frames (woman in a field).
const PICTURES: Record<RichSlot, number> = {
  morning: require('../../assets/follow_him_day.webp'),
  night:   require('../../assets/follow_him_night.webp'),
};

// iOS attachments need a file/url string, not a require() handle. Resolve the
// bundled asset to a uri; if it can't resolve, we omit the attachment (iOS then
// shows a normal text notification with the PRAY action — never a crash).
function pictureUri(slot: RichSlot): string | undefined {
  try { return Image.resolveAssetSource(PICTURES[slot])?.uri || undefined; } catch { return undefined; }
}

// ── Channel / category setup (idempotent) ─────────────────────────────────────
export async function ensureNotifeeChannel(lang: UILanguageCode): Promise<void> {
  if (Platform.OS !== 'android') return;
  try {
    await notifee.createChannel({
      id: NOTIFEE_CHANNEL,
      name: lookupString('notif.channel.name', lang),
      importance: AndroidImportance.HIGH,   // heads-up banner + sound
      lights: true,
      lightColor: BRAND_ROSE,
      vibration: true,
      vibrationPattern: [0, 250, 250, 250],
      visibility: AndroidVisibility.PUBLIC,
    });
  } catch { /* never crash on channel setup */ }
}

export async function ensureNotifeeIosCategory(lang: UILanguageCode): Promise<void> {
  if (Platform.OS !== 'ios') return;
  try {
    await notifee.setNotificationCategories([
      { id: IOS_CATEGORY, actions: [{ id: 'pray', title: lookupString('notif.push.prayAction', lang), foreground: true }] },
    ]);
  } catch { /* ignore — action button just won't show on iOS */ }
}

// ── Notification builder ──────────────────────────────────────────────────────
function buildNotification(slot: RichSlot, lang: UILanguageCode, id: string): Notification {
  const variant = pickDailyVariant(slot);
  const title = lookupString(`notif.push.${slot}.title.${variant}`, lang);
  const body  = lookupString(`notif.push.${slot}.body.${variant}`, lang);
  const pray  = lookupString('notif.push.prayAction', lang);
  const iosUri = pictureUri(slot);

  return {
    id,
    title,
    body,
    // Slot vocabulary ('morning'/'night') matches DeepLinkHandler.routeForSlot,
    // which maps night → PrayerFlow {kind:'evening'} (PrayerFlow crashes without
    // a kind param). Notifee data values are strings.
    data: { slot },
    android: {
      channelId: NOTIFEE_CHANNEL,
      // Generated by the expo-notifications config plugin (app.json icon).
      smallIcon: 'notification_icon',
      largeIcon: PICTURES[slot],
      color: BRAND_ROSE,
      // BIGPICTURE = the large expanded photo; if the asset can't be found
      // Notifee just shows a blank space, so this never throws.
      style: { type: AndroidStyle.BIGPICTURE, picture: PICTURES[slot] },
      pressAction: { id: 'default', launchActivity: 'default' },
      actions: [
        { title: pray, pressAction: { id: 'pray', launchActivity: 'default' } },
      ],
      visibility: AndroidVisibility.PUBLIC,
      // Wake the screen / show as heads-up.
      importance: AndroidImportance.HIGH,
    },
    ios: {
      categoryId: IOS_CATEGORY,
      sound: 'default',
      ...(iosUri ? { attachments: [{ url: iosUri }] } : {}),
    },
  };
}

function timestampTrigger(when: number, repeat: boolean): TimestampTrigger {
  return {
    type: TriggerType.TIMESTAMP,
    timestamp: when,
    ...(repeat ? { repeatFrequency: RepeatFrequency.DAILY } : {}),
    alarmManager: { allowWhileIdle: true },   // fire even in Doze
  };
}

// ── Daily reminder scheduling ─────────────────────────────────────────────────
// Serialize so an overlapping foreground/settings sync can't interleave a slow
// schedule after a fast cancel (mirrors the expo completeStreakChain pattern).
let chain: Promise<void> = Promise.resolve();

async function scheduleOne(slot: RichSlot, hour: number, minute: number, enabled: boolean, granted: boolean, lang: UILanguageCode): Promise<void> {
  try { await notifee.cancelTriggerNotification(NOTIFEE_IDS[slot]); } catch { /* none pending */ }
  if (!enabled || !granted) return;
  const when = nextOccurrence(hour, minute).getTime();
  try {
    await notifee.createTriggerNotification(
      buildNotification(slot, lang, NOTIFEE_IDS[slot]),
      timestampTrigger(when, true),
    );
  } catch { /* swallow — a failed schedule just means no rich reminder this cycle */ }
}

export interface RichSlotConfig { hour: number; minute: number; enabled: boolean }

/** Reconcile the Notifee morning/night triggers with current settings +
 *  permission. Called on mount, settings change, lang change, and foreground
 *  (the foreground re-run also refreshes the baked daily-variant content). */
export function syncNotifeeReminders(
  cfg: Record<RichSlot, RichSlotConfig>,
  granted: boolean,
  lang: UILanguageCode,
): void {
  chain = chain.then(async () => {
    await ensureNotifeeChannel(lang);
    await ensureNotifeeIosCategory(lang);
    await scheduleOne('morning', cfg.morning.hour, cfg.morning.minute, cfg.morning.enabled, granted, lang);
    await scheduleOne('night', cfg.night.hour, cfg.night.minute, cfg.night.enabled, granted, lang);
  }).catch(() => {});
}

// ── Background re-engagement one-off ──────────────────────────────────────────
/** Schedule a single big reminder ~`delayMs` out for a slot (default 60s). Uses
 *  a distinct id so it never collides with the daily trigger; non-repeating, so
 *  it self-clears after firing. Caller owns the once/day gate + eligibility. */
export async function scheduleBackgroundNudge(slot: RichSlot, lang: UILanguageCode, delayMs = 60_000): Promise<void> {
  try {
    await ensureNotifeeChannel(lang);
    await ensureNotifeeIosCategory(lang);
    await notifee.createTriggerNotification(
      buildNotification(slot, lang, BG_NUDGE_IDS[slot]),
      timestampTrigger(Date.now() + delayMs, false),
    );
  } catch { /* never crash on a nudge */ }
}

/** Cancel a slot's background nudge — both a still-pending trigger AND an
 *  already-displayed one (`cancelNotification` covers both). Called the instant
 *  the user prays that slot, so a "time to pray" reminder never fires ~60s after
 *  they've already prayed. */
export async function cancelBackgroundNudge(slot: RichSlot): Promise<void> {
  try { await notifee.cancelNotification(BG_NUDGE_IDS[slot]); } catch { /* nothing to cancel */ }
}
