#!/usr/bin/env node
// Walks ~/claude_herbible_plan/featured_plans/<lang>/*.json and emits a
// slim TS module with just the fields PlanScreen + FeaturedPlanDetail
// need (title, subtitle, goal, duration, gradient colors, categories).
//
// Full per-day content (sections, paragraphs, prayer, verses) stays out
// of the bundle and is lazy-fetched from the corpus CDN by
// `featuredPlansService.fetchPlan()` only when the user opens a Day.
//
// Run after every plan-source edit:
//   node scripts/build_plans_summary.mjs

import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const SRC = '/Users/liwencao/claude_herbible_plan/featured_plans';
const OUT = '/Users/liwencao/HerBibleApp/src/constants/featuredPlansSummary.ts';
const LANGS = ['en', 'zh-Hans', 'zh-Hant', 'de', 'fr', 'es', 'pt'];

// IMPORTANT: the canonical slug is the FILENAME (without .json), not the
// `plan.slug` field inside the JSON. The two diverge — files are named
// like `anxiety-fear-thoughts-keep-me-up-5day.json` (category + topic +
// duration), while `plan.slug` is just `thoughts-keep-me-up`. The CDN
// resolves files by their filename, so the app must navigate using the
// filename slug or it'll 404. We expose `slug` = filename and tuck the
// short topic ID under `topicSlug` for any future copy-link use.
function slim(plan, fileSlug) {
  const p = plan.plan;
  return {
    id: p.id,
    slug: fileSlug,
    topicSlug: p.slug,
    title: p.title,
    subtitle: p.subtitle || '',
    goal: p.goal || '',
    primary: p.category.primary,
    primaryLabel: p.category.primary_label,
    secondary: p.category.secondary,
    secondaryLabel: p.category.secondary_label,
    duration: p.duration_days,
    minutes: p.estimated_minutes_per_day,
    colorPrimary: p.cover?.color_primary || '#E8619A',
    colorSecondary: p.cover?.color_secondary || '#9D7FE0',
  };
}

const out = {};
for (const lang of LANGS) {
  const dir = join(SRC, lang);
  let files;
  try { files = readdirSync(dir).filter(f => f.endsWith('.json')); }
  catch { console.warn(`[skip] ${lang} — directory missing`); out[lang] = []; continue; }
  const summaries = files
    .map(f => ({ raw: JSON.parse(readFileSync(join(dir, f), 'utf8')), fileSlug: f.replace(/\.json$/, '') }))
    .filter(({ raw }) => raw.plan?.status === 'published')
    .map(({ raw, fileSlug }) => slim(raw, fileSlug))
    // Stable sort: primary, then secondary, then duration ascending so
    // "anxiety 3-day" → "anxiety 5-day" → "anxiety 7-day" naturally.
    .sort((a, b) =>
      a.primary.localeCompare(b.primary) ||
      a.secondary.localeCompare(b.secondary) ||
      a.duration - b.duration);
  out[lang] = summaries;
  console.log(`  ${lang.padEnd(8)} ${summaries.length} plans`);
}

const banner = `// AUTO-GENERATED by scripts/build_plans_summary.mjs.
// Source: ~/claude_herbible_plan/featured_plans/<lang>/*.json.
// Re-run the script after editing any plan source. Do NOT hand-edit.
`;

const ts = `${banner}
import type { LanguageCode } from '../state/TranslationsContext';

export interface PlanSummary {
  id: string;
  slug: string;             // canonical (= filename on CDN, also nav route param)
  topicSlug: string;        // shorter identifier from plan.slug — kept for copy-link affordance
  title: string;
  subtitle: string;
  goal: string;
  primary: string;          // emotion-garden | life-seasons | roles-identity
  primaryLabel: string;     // localized
  secondary: string;        // sub-category id (e.g. "anxiety-fear")
  secondaryLabel: string;   // localized
  duration: number;         // duration_days
  minutes: number;          // estimated_minutes_per_day
  colorPrimary: string;     // hex
  colorSecondary: string;   // hex
}

export const FEATURED_PLANS_SUMMARY: Record<LanguageCode, PlanSummary[]> =
  ${JSON.stringify(out, null, 2)} as const;
`;

writeFileSync(OUT, ts);
const sizeKb = (ts.length / 1024).toFixed(1);
console.log(`\nWrote ${OUT}`);
console.log(`Bundle size: ${sizeKb} KB`);
