// Build the daily-verse audio manifest from the local TTS audio folder.
//
// Filenames look like:
//   e_002_evening_promises-and-comfort_02_reflection.mp3
//   m_001_morning_john-1-9_01_scripture.mp3
//   <verseId>_<segment>_<slug>_<NN>_<stepname>.mp3
//
// The middle <slug> is unpredictable (sometimes a category, sometimes a
// verse-ref), so the app can't construct filenames itself — it reads this
// manifest instead, which maps each verseId to its four exact filenames.
//
// Usage:
//   node scripts/gen_dailyverse_audio_manifest.mjs <local-audio-en-dir>
// e.g.
//   node scripts/gen_dailyverse_audio_manifest.mjs ~/Desktop/dailyverse_4steps_audio_7languages/en
//
// Writes src/constants/dailyVerseAudioManifest.ts — the BUNDLED filename map
// the app reads. (No CDN upload needed; the manifest ships in the app, only
// the audio bytes are pulled from R2 on demand.)

import fs from 'node:fs';
import path from 'node:path';

const STEP_KEYS = ['scripture', 'reflection', 'simple-step', 'prayer']; // page 0..3
const BASE_URL = 'https://audio.everlandapps.com/dailyverse_4steps_audio_7languages/en';

const srcDir = process.argv[2];
const outPath = process.argv[3]
  || path.join(process.cwd(), 'src', 'constants', 'dailyVerseAudioManifest.ts');
if (!srcDir) {
  console.error('Usage: node scripts/gen_dailyverse_audio_manifest.mjs <local-audio-en-dir>');
  process.exit(1);
}

// Parse "<verseId>_<segment>_<slug>_<NN>_<stepname>.mp3" → { verseId, step }.
// verseId = first two underscore segments (e_002 / m_001); step = last segment
// (scripture / reflection / simple-step / prayer). The slug in the middle is
// ignored — we just record the full filename per (verseId, step).
function parse(name) {
  if (!/\.mp3$/i.test(name)) return null;
  const parts = name.split('_');
  if (parts.length < 5) return null;
  const verseId = `${parts[0]}_${parts[1]}`;
  if (!/^[me]_\d{3}$/.test(verseId)) return null;
  const step = parts[parts.length - 1].replace(/\.mp3$/i, '');
  if (!STEP_KEYS.includes(step)) return null;
  return { verseId, step };
}

const files = fs.readdirSync(srcDir).filter((f) => /\.mp3$/i.test(f));
const manifest = {};
let parsed = 0, skipped = 0;
for (const name of files) {
  const p = parse(name);
  if (!p) { skipped++; continue; }
  (manifest[p.verseId] ||= {})[p.step] = name;
  parsed++;
}

// Coverage report: which verseIds are missing any of the 4 steps.
const ids = Object.keys(manifest).sort();
const incomplete = ids.filter((id) => STEP_KEYS.some((k) => !manifest[id][k]));
const complete = ids.length - incomplete.length;

const out = {
  version: 1,
  base_url: BASE_URL,
  step_order: STEP_KEYS,
  verses: manifest,
};

// Emit a .ts module (not JSON) so the app bundles it with no tsconfig /
// resolveJsonModule dependency.
const ts = `// AUTO-GENERATED by scripts/gen_dailyverse_audio_manifest.mjs — do not edit by hand.
//
// Maps each verseId (m_001 / e_001) to the four exact mp3 filenames of its
// narration steps. Bundled (not CDN-fetched) — tiny + static; only the
// audio bytes are pulled on demand.
//
// Regenerate after re-recording / re-uploading audio:
//   node scripts/gen_dailyverse_audio_manifest.mjs <local-audio-en-folder>
import type { DailyVerseAudioManifest } from './dailyVerseAudioCdn';

export const DAILY_VERSE_AUDIO_MANIFEST: DailyVerseAudioManifest = ${JSON.stringify(out, null, 2)};
`;

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, ts, 'utf8');

console.log(`Parsed ${parsed} files, skipped ${skipped} non-matching.`);
console.log(`Verses: ${ids.length} total, ${complete} complete (all 4 steps), ${incomplete.length} incomplete.`);
if (incomplete.length) {
  console.log('Incomplete verseIds (missing a step):');
  for (const id of incomplete) {
    const have = STEP_KEYS.filter((k) => manifest[id][k]);
    console.log(`  ${id}: has [${have.join(', ')}]`);
  }
}
console.log(`\nWrote ${outPath}`);
console.log('Next: Claude commits this; reload the app — the listen button goes live.');
